import type { PrayerTranslationSeed } from "./types";

/**
 * Spanish (es) translations of PrayerType content.
 *
 * Authoring conventions:
 *  - **Source tier**: USCCB Spanish (usccb.org/es), Vatican.va
 *    Spanish, Editorial Verbo Divino / Ediciones Paulinas for
 *    published prayer collections.
 *  - **Variant**: macro-tag "es" — neutral Latin American Spanish.
 *    Avoid Spain-specific "vosotros"; prefer "ustedes." Catholic
 *    register: "rezar por" (not "para") for prayer intentions.
 *  - **Brand names stay English**: "PrayerTrain," "Surrender Novena."
 *  - **Prayer texts (prayerText) intentionally left null** for now —
 *    the helper falls back field-by-field to the canonical English
 *    text. A future round will populate Spanish prayer texts from
 *    USCCB / Vatican.va canonical sources rather than rendering
 *    from translation memory.
 */
export const esTranslations: PrayerTranslationSeed[] = [
  {
    prayerSlug: "novena-sacred-heart",
    name: "Novena al Sagrado Corazón de Jesús",
    description:
      "La Novena al Sagrado Corazón de Jesús es una de las devociones más queridas de la Iglesia Católica, nacida de las apariciones de Jesús a Santa Margarita María Alacoque en Paray-le-Monial, Francia, entre 1673 y 1675. En estas visiones, Cristo reveló la profundidad de su amor por la humanidad, simbolizado por su Corazón traspasado y coronado de espinas, y pidió que ese amor fuera honrado mediante la devoción a su Sagrado Corazón. La novena abarca nueve días consecutivos de oración (el número nueve recuerda los nueve días que los apóstoles y María pasaron en oración entre la Ascensión y Pentecostés) y se ofrece tradicionalmente con confianza en la compasión de Cristo hacia los que sufren. Es especialmente apropiada en tiempos de enfermedad, dificultad familiar, desolación espiritual o intenciones persistentes que aún no han encontrado respuesta. El Sagrado Corazón no es un mero símbolo; es el corazón histórico y físico de Cristo, plenamente humano y plenamente divino, fuente de su caridad infinita. La encíclica Haurietis Aquas de Pío XII (1956) describe el Sagrado Corazón como «el trono de la misericordia» y confirma el lugar central de esta devoción en la vida de la Iglesia. Los guerreros de oración que ofrecen esta novena se unen a siglos de católicos que han depositado su confianza en el Corazón herido del Salvador.",
    instructions:
      "Reza una vez al día durante nueve días consecutivos, aproximadamente a la misma hora cada día. Elige un lugar tranquilo y comienza con la Señal de la Cruz. La estructura tradicional es: (1) una invocación inicial, a menudo «Oh Sagradísimo Corazón de Jesús, en Ti pongo toda mi confianza»; (2) el texto mismo de la novena; (3) un Padrenuestro, un Avemaría y un Gloria; (4) una intención personal dicha en voz alta o en silencio. Muchos añaden las Letanías del Sagrado Corazón el último día o rezan la novena junto con la devoción de los Primeros Viernes, recibiendo la Sagrada Comunión nueve primeros viernes consecutivos como el mismo Cristo le pidió a Santa Margarita María. La novena puede rezarse en cualquier época del año, pero es especialmente apropiada durante el mes de junio (mes del Sagrado Corazón), en los días previos a la Solemnidad del Sagrado Corazón (viernes después del Corpus Christi), o cuando alguien atraviesa un momento particularmente difícil. Si se omite un día, el consejo tradicional es comenzar de nuevo desde el día uno en lugar de saltárselo; la disciplina de la oración consecutiva es parte de la gracia de la devoción. Algunos rezan por una persona específica cada día de la novena; otros ofrecen los nueve días por una sola intención.",
    patronSaint: "Santa Margarita María Alacoque",
    feastDay: "Viernes después del Corpus Christi",
    source:
      "USCCB materials in Spanish (usccb.org/es) + traditional Catholic devotional sources for the Sacred Heart novena. Historical claims verified against the 1956 encyclical Haurietis Aquas and the published account of the apparitions at Paray-le-Monial. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-st-joseph",
    name: "Novena a San José",
    description:
      "San José, padre adoptivo de Jesús y casto esposo de la Santísima Virgen María, es uno de los intercesores más amados en la tradición católica. Aunque la Escritura no recoge palabra alguna pronunciada por él, su fidelidad es inconfundible: protegió a la Sagrada Familia en la huida a Egipto, los sostuvo con el trabajo de sus manos y enseñó a Jesús el oficio de la carpintería y los caminos de la masculinidad fiel. El Papa Pío IX lo nombró Patrono de la Iglesia Universal en 1870, y el Papa Francisco declaró el período 2020-2021 como Año de San José mediante la carta apostólica Patris Corde («Con Corazón de Padre»). Esta novena se nutre de una larga tradición católica que reconoce a San José como patrono de los padres, los trabajadores, las familias, los asuntos inmobiliarios y la buena muerte: los cuatro pilares de su ministerio terrenal. Se le invoca especialmente en momentos de dificultad económica, discordia familiar, dificultades laborales y en el discernimiento vocacional. Muchos católicos se comprometen con la novena en los días previos a alguna de sus fiestas: el 19 de marzo (Solemnidad de San José, Esposo de la Bienaventurada Virgen María) o el 1 de mayo (San José Obrero, instituida por el Papa Pío XII en 1955 para santificar el trabajo humano). Santa Teresa de Ávila escribió célebremente: «A otros santos parece que les dio el Señor gracia para socorrer en una necesidad; a este glorioso Santo tengo experiencia que socorre en todas».",
    instructions:
      "Reza una vez al día durante nueve días consecutivos. La estructura tradicional es: comenzar con la Señal de la Cruz; rezar el texto de la novena; concluir con un Padrenuestro, un Avemaría y un Gloria; y nombrar tu intención específica. Algunas familias católicas añaden las Letanías de San José o siete Padrenuestros, Avemarías y Glorias en honor a los Siete Dolores y los Siete Gozos de San José — una devoción tradicional vinculada a sus experiencias de dolor y alegría en la vida de la Sagrada Familia. Para familias que están discerniendo una decisión importante (un cambio de trabajo, una mudanza, un matrimonio), es costumbre comenzar la novena nueve días antes de que deba tomarse la decisión, pidiendo la intercesión de San José para obtener claridad y la gracia de aceptar la voluntad de Dios. La novena también se reza tradicionalmente durante el mes de marzo (mes de San José) o junto con la práctica popular de enterrar una estatua de San José en relación con la venta de una casa: una tradición popular que subraya la confianza pacífica, no la superstición. Ya sea que se rece por discernimiento vocacional, provisión económica, sanación familiar o una buena muerte (uno de los cuatro fines tradicionales de esta devoción), el espíritu debe ser de confianza tranquila y trabajadora, la misma disposición que San José modeló en la Escritura.",
    patronSaint: "San José",
    feastDay: "19 de marzo / 1 de mayo",
    source:
      "Patris Corde (Francisco, 2020) + USCCB materials in Spanish + traditional Catholic devotional sources for the St. Joseph novena. The St. Teresa of Ávila quotation is from her Autobiografía (chapter 6, on her devotion to San José). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "holy-rosary",
    name: "El Santo Rosario",
    description:
      "El Santo Rosario es la devoción mariana central de la Iglesia Católica: una oración contemplativa en la que el creyente medita los grandes misterios de la vida, muerte y resurrección de Cristo mientras reza decenas repetidas de Avemarías. El Rosario, tal como lo conocemos hoy, tomó forma a lo largo de los siglos; la tradición sostiene que la Santísima Virgen María entregó el Rosario a Santo Domingo en 1208 como arma espiritual contra la herejía albigense, y la estructura de quince misterios fue codificada por el Papa San Pío V en 1569. En 2002, el Papa San Juan Pablo II añadió los Misterios Luminosos (Misterios de la Luz) en su carta apostólica Rosarium Virginis Mariae, llevando el total a veinte misterios agrupados en cuatro conjuntos. Cada decena es una meditación: mientras los dedos se mueven por las cuentas y los labios recitan el Avemaría, la mente se detiene en un momento de los Evangelios — la Anunciación, la Crucifixión, la Resurrección, la Transfiguración. El Rosario no es vana repetición (Mateo 6:7) sino una escuela de contemplación, que permite que el ritmo de las oraciones libere la mente para reflexionar sobre los misterios de la salvación. Los Papas, desde León XIII (cuyas once encíclicas sobre el Rosario siguen siendo referencias magisteriales) hasta Francisco, han exhortado a los fieles a rezar el Rosario diariamente. Es la oración que se ofreció en Lourdes, Fátima y muchas otras apariciones marianas, y la oración que con más frecuencia rezan las familias católicas reunidas junto a un lecho de enfermo o ante una tumba.",
    instructions:
      "Un Rosario completo consta de cinco decenas, generalmente rezado en unos veinte minutos. Comienza con la Señal de la Cruz y el Credo de los Apóstoles sobre el crucifijo. En la primera cuenta grande reza el Padrenuestro; en cada una de las tres cuentas pequeñas que siguen reza un Avemaría (por el aumento de las tres virtudes teologales: fe, esperanza y caridad); en la siguiente cuenta grande reza el Gloria. Luego anuncia el primer misterio en voz alta y medita brevemente en su significado; reza un Padrenuestro en la cuenta grande, diez Avemarías en las diez cuentas pequeñas (una por cuenta) mientras continúas meditando el misterio, luego un Gloria y la Oración de Fátima («Oh Jesús mío, perdónanos nuestros pecados, líbranos del fuego del infierno…»). Repite con cuatro decenas más, nombrando cada misterio. Concluye con la Salve y la oración del Rosario. Los cuatro conjuntos de misterios se rezan tradicionalmente así: Misterios Gozosos los lunes y sábados (la Anunciación, la Visitación, el Nacimiento, la Presentación, el Niño Perdido y Hallado en el Templo); Dolorosos los martes y viernes (la Oración en el Huerto, la Flagelación, la Coronación de Espinas, la Cruz a Cuestas, la Crucifixión); Gloriosos los miércoles y domingos (la Resurrección, la Ascensión, Pentecostés, la Asunción, la Coronación de la Virgen); Luminosos los jueves (el Bautismo del Señor, las Bodas de Caná, el Anuncio del Reino, la Transfiguración, la Institución de la Eucaristía). Para la cobertura de un PrayerTrain, una sola decena — o incluso una sola Avemaría ofrecida con intención — también es una ofrenda válida del Rosario.",
    patronSaint: "Nuestra Señora del Rosario",
    feastDay: "7 de octubre",
    source:
      "Rosarium Virginis Mariae (San Juan Pablo II, 2002) + León XIII's eleven rosary encyclicals + Catechism of the Catholic Church paragraphs 971, 2678, and 2708 on the Marian dimension of prayer. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "chaplet-divine-mercy",
    name: "Coronilla de la Divina Misericordia",
    description:
      "La Coronilla de la Divina Misericordia fue entregada por Jesús a Santa María Faustina Kowalska, religiosa polaca, en una serie de revelaciones que tuvieron lugar entre 1931 y 1938 y que ella misma recogió en su Diario: La Divina Misericordia en mi alma. La coronilla es una poderosa oración de intercesión ofrecida por la conversión de los pecadores, el consuelo de los moribundos y la misericordia de Dios sobre el mundo entero. Jesús le dijo a Faustina que quien rezara esta coronilla recibiría «gran misericordia en la hora de la muerte», y que se complacía especialmente en esta oración cuando se rezaba a las 3:00 de la tarde, la Hora de la Misericordia (la hora de su muerte en el Calvario). La coronilla se reza con un rosario común, lo que la hace accesible a cualquiera que tenga un rosario, y dura aproximadamente diez minutos. La devoción a la Divina Misericordia estuvo suprimida durante muchos años, pero el Papa San Juan Pablo II — él mismo polaco y compatriota de Santa Faustina — la canonizó el 30 de abril del año 2000 y estableció el Domingo de la Divina Misericordia (segundo domingo de Pascua) como fiesta para toda la Iglesia universal. La Coronilla de la Divina Misericordia se ha convertido en una de las devociones más rezadas en la Iglesia contemporánea, especialmente apreciada por capellanes de hospital, voluntarios de cuidados paliativos y quienes rezan por la conversión de seres queridos. Es la oración diaria en el Santuario Nacional de la Divina Misericordia de Stockbridge, Massachusetts, y en el Santuario de la Divina Misericordia de Łagiewniki, Cracovia — el lugar donde Faustina vivió, murió y hoy reposa.",
    prayerText:
      "Padre Eterno, te ofrezco el Cuerpo y la Sangre, el Alma y la Divinidad de tu amadísimo Hijo, nuestro Señor Jesucristo, en propiciación por nuestros pecados y los del mundo entero. Por su dolorosa Pasión, ten misericordia de nosotros y del mundo entero.",
    instructions:
      "Con un rosario común de cinco decenas, comienza con la Señal de la Cruz, un Padrenuestro, un Avemaría y el Credo de los Apóstoles sobre el crucifijo y las cuentas iniciales. En cada una de las cinco cuentas grandes (donde normalmente se reza el Padrenuestro) reza: «Padre Eterno, te ofrezco el Cuerpo y la Sangre, el Alma y la Divinidad de tu amadísimo Hijo, nuestro Señor Jesucristo, como propiciación por nuestros pecados y los del mundo entero». En cada una de las diez cuentas pequeñas de cada decena reza: «Por su dolorosa Pasión, ten misericordia de nosotros y del mundo entero». Al terminar las cinco decenas, concluye rezando tres veces: «Santo Dios, Santo Fuerte, Santo Inmortal, ten piedad de nosotros y del mundo entero». La coronilla es especialmente poderosa cuando se reza a las 3:00 de la tarde (la Hora de la Misericordia), junto al lecho de los moribundos, en los nueve días previos al Domingo de la Divina Misericordia (la Novena a la Divina Misericordia, que comienza el Viernes Santo), y en momentos de angustia o temor personal. Puede rezarse en silencio, en voz alta, a solas o en grupo. Muchas parroquias rezan la coronilla semanalmente, a menudo los viernes en memoria de la Pasión de Cristo. Los católicos que rezan por la conversión o la muerte serena de un ser querido suelen comprometerse a rezar la coronilla diariamente durante un período sostenido — un mes, la duración de una enfermedad, el tiempo previo a una decisión importante. La coronilla se asocia naturalmente con la asistencia a la Novena a la Divina Misericordia, desde el Viernes Santo hasta el Domingo de la Divina Misericordia.",
    patronSaint: "Santa Faustina Kowalska",
    feastDay: "Domingo de la Divina Misericordia",
    source:
      "Diary: Divine Mercy in My Soul (St. Faustina Kowalska) + the canonical chaplet text as approved by the Holy See following St. John Paul II's canonization of Faustina on April 30, 2000 and the establishment of Divine Mercy Sunday. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "memorare",
    name: "El Acordaos (Memorare)",
    description:
      "El Memorare es una oración breve pero extraordinariamente poderosa de confianza en la intercesión de la Santísima Virgen María. Toma su nombre de la primera palabra latina del texto, Memorare («Acordaos»), y en su forma moderna se atribuye al P. Claude Bernard, sacerdote francés del siglo XVII conocido como «el Sacerdote Pobre» por su apostolado entre los prisioneros y los moribundos. La oración se popularizó gracias a la distribución por parte del P. Bernard de más de 200,000 folletos en el París previo a la Revolución, aunque sus raíces devocionales se remontan más atrás — probablemente a una oración más extensa atribuida a San Bernardo de Claraval (1090-1153), el gran abad cisterciense y Doctor de la Iglesia cuya devoción mariana dio forma a la piedad occidental. La estructura de la oración es una apelación confiada: reconoce la maternidad universal de María («Oh Virgen de las vírgenes, mi Madre»), hace referencia a la tradición ininterrumpida de su intercesión («jamás se ha oído decir que ninguno de los que han acudido a tu protección… haya sido desamparado»), y concluye con una petición humilde («en tu misericordia escúchame y respóndeme»). Los santos a lo largo de los siglos han testimoniado su poder: la Madre Teresa de Calcuta rezaba nueve Memorares consecutivos cada día — lo que ella llamaba su «novena al vuelo» — cuando necesitaba algo con urgencia. El Memorare es la oración católica de último recurso, rezada en momentos de necesidad aguda, junto al lecho de los moribundos, en la capilla antes de una conversación difícil, o susurrada mientras un padre o una madre espera noticias desde una habitación de hospital.",
    prayerText:
      "Acordaos, oh piadosísima Virgen María, que jamás se ha oído decir que ninguno de los que han acudido a vuestra protección, implorado vuestro auxilio o reclamado vuestro socorro, haya sido desamparado. Animado por esta confianza, a Vos también acudo, oh Madre, Virgen de las vírgenes, y aunque gimiendo bajo el peso de mis pecados, me atrevo a comparecer ante vuestra presencia soberana. No desechéis mis humildes súplicas, oh Madre del Verbo divino, antes bien, escuchadlas y acogedlas benignamente. Amén.",
    instructions:
      "Reza una vez con plena atención y devoción, trayendo a la mente a la persona y la intención que estás presentando ante María. El Memorare es lo suficientemente breve como para memorizarlo y rezarlo en cualquier parte — en el auto, durante una caminata, antes de dormir, en los momentos previos a cualquier tarea difícil. Para una intercesión más sostenida, reza nueve Memorares consecutivos seguidos (esta es la «novena al vuelo» que la Madre Teresa prefería para intenciones urgentes). Algunas tradiciones añaden un breve momento de silencio antes de rezar, nombrando la intención en voz alta o en el corazón. La oración también puede incorporarse como oración final al término de un Rosario más extenso o de una novena, sellando la petición con la confianza serena en el amor maternal de María. Las familias católicas suelen rezar el Memorare junto al lecho de alguien gravemente enfermo, al recibir un diagnóstico difícil, o durante el trabajo de parto. Por ser una oración breve cuyas palabras son antiguas y queridas, se ha convertido en una especie de respuesta espiritual de emergencia: una oración que acude espontáneamente a los labios cuando faltan otras palabras. Los niños pueden aprenderla desde muy pequeños, en cuanto puedan recitarla; es una de las oraciones más apropiadas para enseñar a un niño como «primera oración en momentos de dificultad». La versión latina original todavía es rezada por algunos atraídos a las formas tradicionales: «Memorare, O piissima Virgo Maria, non esse auditum a saeculo…»",
    patronSaint: "San Bernardo de Claraval",
    feastDay: null,
    source:
      "Traditional Spanish Catholic devotional text of the Memorare (Acordaos), as published in the Latin American breviary and major Spanish-language prayer books. Historical attribution to Fr. Claude Bernard verified against the Catholic Encyclopedia entry and the 19th-century printed editions of his prayer leaflets. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── Round 2: 6 more prayers from PR #71 ────────────────────
  {
    prayerSlug: "novena-st-jude",
    name: "Novena a San Judas Tadeo",
    description:
      "San Judas Tadeo, llamado el Apóstol de la Esperanza, fue uno de los Doce y pariente del Señor, tradicionalmente considerado hermano de Santiago el Menor y primo de Jesús. Es nombrado en los Evangelios como uno de los apóstoles (Lucas 6:16) y es el autor de la breve Epístola de Judas que cierra la sección de cartas católicas del Nuevo Testamento. Durante siglos, la devoción popular católica ha invocado a San Judas como patrono de las causas desesperadas y de los casos imposibles. Las razones que ofrece la tradición son prácticas: porque su nombre (Judas) se confundía fácilmente con Judas Iscariote, el traidor, su intercesión fue evitada por los cristianos ordinarios durante siglos — y así, dice el dicho, anhela ayudar a quien acude a él en verdadera necesidad. La devoción moderna a San Judas Tadeo fue popularizada en los Estados Unidos por los padres claretianos, quienes construyeron el Santuario Nacional de San Judas en Chicago en 1929 — en plena Gran Depresión — y el santuario sigue siendo uno de los sitios de peregrinación católica más visitados de Norteamérica. La devoción está fuertemente asociada con la práctica de publicar agradecimientos («Gracias, San Judas, por las oraciones respondidas») en los avisos clasificados de los periódicos, una costumbre que comenzó en la cultura católica estadounidense de mediados del siglo XX. Esta novena es apropiada para enfermedad con pronóstico difícil, colapso económico, alejamiento familiar que parece sin remedio, infertilidad y cualquier situación que una persona experimenta como «más allá de toda esperanza».",
    instructions:
      "Reza una vez al día durante nueve días consecutivos. La estructura tradicional: comienza con la Señal de la Cruz; reza el texto de la novena a San Judas; concluye con un Padrenuestro, un Avemaría y un Gloria; nombra tu intención específica en silencio o en voz alta. Muchos católicos añaden tres Padrenuestros, Avemarías y Glorias adicionales en honor a la Santísima Trinidad al cierre de la oración de cada día. La novena puede rezarse en cualquier época del año, pero es especialmente apropiada en los nueve días previos a la fiesta de San Judas (28 de octubre, compartida con San Simón el Zelote) o cuando alguien enfrenta una situación que se siente «imposible». Una práctica complementaria tradicional es comprometerse, cuando la oración es escuchada, a agradecer públicamente a San Judas. Si se omite un día de la novena, el consejo tradicional es comenzar de nuevo desde el día uno. La disposición de la oración importa: San Judas no es una máquina expendedora. La novena se reza en fe y abandono.",
    patronSaint: "San Judas Tadeo",
    feastDay: "28 de octubre",
    source: "USCCB Spanish + Claretian National Shrine of St. Jude (Chicago, 1929). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-divine-mercy",
    name: "Novena a la Divina Misericordia",
    description:
      "La Novena a la Divina Misericordia fue entregada por Jesús a Santa María Faustina Kowalska, religiosa polaca, en una serie de revelaciones recogidas en su Diario: La Divina Misericordia en mi alma. Los escritos místicos de Faustina, suprimidos por un tiempo después de su muerte en 1938, fueron reivindicados por el Papa San Juan Pablo II — él mismo polaco y compatriota — quien la canonizó el 30 de abril de 2000 y estableció el Domingo de la Divina Misericordia (segundo domingo de Pascua) como fiesta para toda la Iglesia universal. La novena comienza el Viernes Santo y concluye en la vigilia del Domingo de la Divina Misericordia. Cada uno de los nueve días, Jesús instruyó a Faustina, trae una categoría diferente de almas ante el trono de la misericordia: Día 1, toda la humanidad; Día 2, sacerdotes y religiosos; Día 3, almas devotas y fieles; Día 4, los que no creen; Día 5, las almas de los hermanos separados; Día 6, los humildes, sencillos y los niños; Día 7, las almas que veneran la Divina Misericordia; Día 8, las almas del purgatorio; Día 9, las almas tibias. El hogar espiritual de la novena es el Santuario de la Divina Misericordia en Łagiewniki, Cracovia.",
    instructions:
      "Reza una vez al día durante nueve días consecutivos, tradicionalmente comenzando el Viernes Santo. Cada día tiene una intención única y una invocación inicial única que Jesús dictó a Santa Faustina; después de la apertura del día, la oración concluye con la Coronilla de la Divina Misericordia. La estructura tradicional de cada día: (1) Lee la intención específica del día; (2) Reza la oración inicial que Jesús dio a Faustina; (3) Reza la Coronilla entera; (4) Concluye con una intención personal. La novena completa toma aproximadamente quince minutos por día. También puede rezarse en cualquier época del año para una intención privada.",
    patronSaint: "Santa Faustina Kowalska",
    feastDay: "Domingo de la Divina Misericordia",
    source: "Diary: Divine Mercy in My Soul (St. Faustina) + Marian Fathers (Stockbridge, MA) Spanish texts. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-our-lady-perpetual-help",
    name: "Novena a Nuestra Señora del Perpetuo Socorro",
    description:
      "Nuestra Señora del Perpetuo Socorro es uno de los títulos marianos más queridos en la Iglesia Católica. La devoción se centra en un icono bizantino del siglo XV — escrito, en la tradición iconográfica, sobre madera de ciprés y mostrando al Niño Jesús sostenido en los brazos de María mientras los arcángeles Miguel y Gabriel se acercan, cada uno portando instrumentos de la Pasión (la cruz, la lanza, la esponja). El Niño Jesús vuelve su rostro hacia su Madre con aparente temor; una sandalia cuelga suelta de su pie, un detalle tradicionalmente leído como el Niño recoiling ante la Pasión anunciada. El icono llegó a Roma en 1499 y fue venerado durante siglos antes de desaparecer durante las supresiones napoleónicas; fue redescubierto en 1862 y entregado por el Papa Pío IX a los padres redentoristas en 1866 con el encargo: «Hacedla conocida en todo el mundo». La novena a Nuestra Señora del Perpetuo Socorro — compuesta y popularizada por los redentoristas — es una de las devociones marianas más rezadas en la Iglesia moderna.",
    instructions:
      "Reza una vez al día durante nueve días consecutivos. La novena redentorista tradicionalmente acompaña la oración de cada día con el canto del himno «Oh Madre del Perpetuo Socorro» — muchas parroquias todavía celebran servicios semanales de novena al Perpetuo Socorro los miércoles. La estructura tradicional: (1) Señal de la Cruz; (2) Reza la oración de la novena; (3) Concluye con tres Avemarías y una Salve; (4) Nombra tu intención. La novena es apropiada en los días previos a la Fiesta (27 de junio), pero puede rezarse en cualquier momento. Especialmente recomendada para madres que rezan por sus hijos y para quienes cuidan a los enfermos.",
    patronSaint: "Nuestra Señora del Perpetuo Socorro",
    feastDay: "27 de junio",
    source: "Redemptorist Spanish-language tradition + Pius IX's 1866 entrustment. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "litany-sacred-heart",
    name: "Letanías del Sagrado Corazón",
    description:
      "Las Letanías del Sagrado Corazón de Jesús son una de las seis letanías aprobadas por la Santa Sede para el uso litúrgico público en el Rito Latino. Compuestas en 1718 por sor Juana Magdalena Joly de la Orden de la Visitación en Dijon, las letanías fueron refinadas y amplificadas durante el siglo siguiente. El Papa León XIII dio a las letanías la aprobación formal para uso litúrgico público el 2 de abril de 1899 — el mismo año en que consagró toda la raza humana al Sagrado Corazón en su encíclica Annum Sacrum. Las letanías están estructuradas como treinta y tres invocaciones al Corazón de Cristo bajo distintos títulos — correspondientes a los treinta y tres años de la vida terrena de Cristo. A cada invocación se le da la respuesta «Ten piedad de nosotros». Las letanías son una de las devociones principales del Primer Viernes y se rezan tradicionalmente durante el mes de junio.",
    instructions:
      "Las letanías se rezan responsorialmente. Un líder pronuncia cada invocación y la compañía reunida responde «Ten piedad de nosotros». Las invocaciones iniciales utilizan el patrón del Kyrie y la invocación trinitaria. Siguen las treinta y tres invocaciones al Corazón de Jesús. Las letanías concluyen con el Cordero de Dios y una oración colecta al Sagrado Corazón. La duración total es de aproximadamente diez a quince minutos. Apropiadamente rezadas: en los Primeros Viernes; durante el mes de junio; durante la Novena al Sagrado Corazón; al final de una Hora Santa.",
    patronSaint: "Sagrado Corazón de Jesús",
    feastDay: "Viernes después del Corpus Christi",
    source: "Annum Sacrum (Leo XIII, 1899) + USCCB Spanish. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "litany-blessed-virgin",
    name: "Letanías de la Santísima Virgen María (Letanías Lauretanas)",
    description:
      "Las Letanías de la Santísima Virgen María — conocidas tradicionalmente como Letanías Lauretanas — son las letanías marianas más antiguas y queridas de la Iglesia Latina. Las letanías toman su nombre común de la Santa Casa de Loreto en las Marcas italianas. El Papa Sixto V aprobó formalmente las letanías para uso litúrgico y devocional en 1587. A lo largo de los siglos, los papas sucesivos han añadido invocaciones: Pío VII añadió «Auxilio de los Cristianos» en 1815; Pío IX añadió «Reina concebida sin pecado original» después de 1854; Pío XII añadió «Reina asunta al cielo» después de 1950; San Juan Pablo II añadió «Madre de la Iglesia» en 1980 y «Reina de las Familias» en 1995. Más recientemente, el Papa Francisco añadió «Madre de la Misericordia», «Madre de la Esperanza» y «Consuelo de los Migrantes» en 2020. Los títulos acumulados forman un retrato del lugar de María en la economía de la salvación.",
    instructions:
      "Las letanías se rezan responsorialmente. Un líder pronuncia cada título de María y la compañía reunida responde «Ruega por nosotros». Las letanías comienzan con el patrón del Kyrie y la invocación trinitaria; el cuerpo de las letanías es la larga secuencia de títulos marianos; las letanías se cierran con tres invocaciones al Cordero de Dios y una oración colecta a la Santísima Virgen. Las Letanías Lauretanas se rezan tradicionalmente después del Santo Rosario; durante los meses marianos de mayo y octubre; al final de la novena mariana previa a las solemnidades marianas; en momentos de consagración familiar a María.",
    patronSaint: "Santísima Virgen María",
    feastDay: null,
    source: "Sixtus V's 1587 approval + papal additions through Francis 2020 + USCCB Spanish. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "prayer-conversion",
    name: "Oración por la Conversión de un Ser Querido",
    description:
      "La oración católica por la conversión de un ser querido está arraigada en uno de los grandes testimonios pastorales de la historia cristiana: la larga y fiel oración de Santa Mónica por su hijo San Agustín. Mónica rezó por la conversión de su hijo a través de años de su persecución de la filosofía maniquea, a través de sus propias lágrimas y el consejo que recibió de San Ambrosio de Milán («No es posible que perezca el hijo de tantas lágrimas»). Agustín fue bautizado en 387 a la edad de treinta y tres años; Mónica murió poco después en Ostia, habiendo vivido para ver lo que había pedido. Agustín registró su perseverancia en sus Confesiones (Libro IX). El testimonio pastoral que Mónica encarna no es una garantía de resultado — la conversión de Agustín ocurrió en el tiempo de Dios, no en el de Mónica — sino una postura de fidelidad inquebrantable: que la oración del creyente por un ser querido es en sí misma una gracia, una participación en el propio deseo de Dios por esa alma.",
    instructions:
      "Reza diariamente, idealmente a la misma hora y en la misma postura (de rodillas, ante un crucifijo o una imagen del Sagrado Corazón). Nombra a la persona en voz alta en la oración donde el texto dice «(nombre)». Después de la oración, dedica un minuto de silencio a sostenerla ante el Sagrado Corazón. Muchos católicos combinan esta oración con: (1) el ofrecimiento diario de pequeños sacrificios por la intención; (2) una intención regular de Misa por la persona, especialmente el día de la fiesta de Santa Mónica (27 de agosto) o el día de la fiesta de San Agustín (28 de agosto); (3) la Coronilla de la Divina Misericordia a las 3:00 PM.",
    patronSaint: "Santa Mónica",
    feastDay: "27 de agosto",
    source: "Augustine's Confessions Book IX + USCCB Spanish pastoral resources. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── Locale-anchored devotion (Spanish) ────────────────────
  {
    prayerSlug: "novena-guadalupe",
    name: "Novena a Nuestra Señora de Guadalupe",
    description:
      "Nuestra Señora de Guadalupe es la devoción mariana central del mundo católico de habla hispana y una de las apariciones marianas más poderosas en la historia de la Iglesia. El 9 de diciembre de 1531 — diez años después de la conquista española de México, en un momento de profundo trastorno cultural y espiritual — la Santísima Virgen María se apareció en el cerro del Tepeyac a San Juan Diego Cuauhtlatoatzin, un campesino nahua recién convertido. Hablando en su náhuatl nativo, María se identificó como «la perfecta siempre Virgen Santa María, Madre del verdaderísimo Dios» y pidió que se construyera una iglesia en el cerro. Después de que el obispo local, Juan de Zumárraga, solicitara una señal, María instruyó a Juan Diego el 12 de diciembre a recoger rosas del cerro helado y llevarlas en su tilma al obispo. Cuando Juan Diego abrió la tilma ante el obispo, las rosas cayeron y apareció milagrosamente una imagen de María impresa en la tela — una joven mujer embarazada con vestimenta indígena, vistiendo el cinturón de maternidad de costumbre nahua, rodeada de rayos solares y de pie sobre una luna creciente. Esta es la imagen preservada hasta el día de hoy en la Basílica de Nuestra Señora de Guadalupe en la Ciudad de México, uno de los santuarios católicos más visitados del mundo. La narrativa — conocida como el Nican Mopohua, registrada en náhuatl poco después de los eventos — ha sido estudiada por historiadores, científicos y peregrinos durante casi cinco siglos. El Papa San Juan Pablo II canonizó a Juan Diego en 2002 en la propia Basílica, convirtiéndolo en la primera canonización de un indígena americano. María es honrada como Emperatriz de las Américas, Patrona de los no nacidos, y la Estrella de la Nueva Evangelización.",
    instructions:
      "Reza una vez al día durante nueve días consecutivos. La novena se reza tradicionalmente en los nueve días previos a la Fiesta de Nuestra Señora de Guadalupe (12 de diciembre), comenzando el 3 de diciembre. Las Mañanitas — la tradicional serenata pre-amanecer con canto y oración — se cantan en parroquias de toda Latinoamérica y de la comunidad católica hispana de los EE. UU. la noche del 11 de diciembre hasta la mañana del 12 de diciembre. La estructura de la novena: (1) Señal de la Cruz; (2) Lee la reflexión breve del día del Nican Mopohua; (3) Reza el texto de la novena; (4) Reza tres Avemarías; (5) Nombra tu intención. Muchas familias se reúnen alrededor de una imagen doméstica de Nuestra Señora de Guadalupe (a menudo colocada en un pequeño altar doméstico). La novena es apropiada para el embarazo y la protección de los niños no nacidos (María se muestra embarazada en la tilma); la conversión de miembros de la familia; protección de inmigrantes y desplazados; sanación de heridas culturales o familiares; y cualquier momento de crisis personal o comunitaria. La Peregrinación a la Basílica de Guadalupe en la Ciudad de México, especialmente el 12 de diciembre, atrae a millones de peregrinos anualmente.",
    patronSaint: "Nuestra Señora de Guadalupe, Emperatriz de las Américas",
    feastDay: "12 de diciembre",
    source: "Nican Mopohua + USCCB Spanish + Basílica de Guadalupe Ciudad de México devotional sources. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── ROUND 3 (es) ──────────────────────────────────────────
  {
    prayerSlug: "litany-st-joseph",
    name: "Letanías de San José",
    description:
      "Las Letanías de San José son una de las seis letanías aprobadas por la Santa Sede para uso litúrgico público en el Rito Latino. Compuestas gradualmente durante los siglos XVII y XVIII a medida que la devoción a San José se profundizó por todo el mundo católico, las letanías recibieron su aprobación magisterial formal del Papa San Pío X el 18 de marzo de 1909 — víspera de la Fiesta de San José — para el Esposo de María, padre adoptivo de Jesús y Patrono de la Iglesia Universal. La estructura sigue el patrón de otras letanías católicas aprobadas: una apertura de Kyrie, una invocación trinitaria, y luego una larga secuencia de invocaciones dirigidas a San José bajo títulos distintos, cada uno con la respuesta «Ruega por nosotros»: «Ilustre hijo de David», «Luz de los patriarcas», «Esposo de la Madre de Dios», «Casto custodio de la Virgen», «Padre adoptivo del Hijo de Dios», «Solícito defensor de Cristo», «Cabeza de la Sagrada Familia», «José justísimo», «José castísimo», «José prudentísimo», «Espejo de paciencia», «Amante de la pobreza», «Modelo de los trabajadores», «Gloria de la vida doméstica», «Custodio de las vírgenes», «Sostén de las familias», «Consuelo de los afligidos», «Esperanza de los enfermos», «Patrono de los moribundos», «Terror de los demonios», «Protector de la Santa Iglesia». En mayo de 2021, en conexión con el Año de San José (diciembre 2020 - diciembre 2021) y su carta apostólica Patris Corde, el Papa Francisco añadió formalmente siete nuevas invocaciones a las letanías, tomadas directamente del lenguaje de Patris Corde: «Custodio del Redentor», «Servidor de Cristo», «Ministro de la salvación», «Sostén en las dificultades», «Patrono de los exiliados», «Patrono de los afligidos» y «Patrono de los pobres». Estas adiciones reflejan el encuadre pastoral específico de Francisco de San José como modelo para los padres, los trabajadores y los marginados del mundo contemporáneo.",
    instructions:
      "Las letanías se rezan responsorialmente. Un guía pronuncia cada invocación («José justísimo…») y la asamblea responde «Ruega por nosotros» a cada una. El patrón inicial del Kyrie y la invocación trinitaria usan «Ten piedad de nosotros» como respuesta; el cuerpo de las letanías — la larga secuencia de títulos — usa «Ruega por nosotros». Las letanías concluyen con tres invocaciones al Cordero de Dios (Agnus Dei), un par de versículo-respuesta tomado del Génesis («Lo constituyó señor de su casa, y administrador de todos sus bienes»), y una colecta a San José. La duración total es aproximadamente diez minutos cuando se reza a paso devocional sin prisa. Las Letanías de San José se rezan tradicionalmente: durante el mes de marzo, Mes de San José; en los días previos a la Solemnidad de San José (19 de marzo) o a la Fiesta de San José Obrero (1 de mayo); al final de una Hora Santa o adoración eucarística; en contextos familiares pidiendo la protección de San José sobre el hogar. Las adiciones de 2021 pueden incorporarse a cualquier texto impreso tradicional insertando las siete nuevas invocaciones en sus lugares correspondientes en la secuencia de las letanías (la mayoría de las versiones actuales publicadas las incluyen); tanto la Conferencia Episcopal Mexicana (CEM) como el sitio web de la Santa Sede publican el texto oficial completo actualizado en español. Muchas familias católicas rezan las letanías juntas los miércoles por la noche (el día tradicionalmente dedicado a San José en el calendario devocional católico antiguo). Cuando se reza a solas, simplemente lee tanto la invocación como la respuesta en voz alta o en silencio.",
    patronSaint: "San José",
    feastDay: "19 de marzo",
    source: "USCCB Spanish + Patris Corde (Pope Francis, December 8, 2020) + Pope Pius X 1909 approval. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-holy-spirit",
    name: "Novena al Espíritu Santo",
    description:
      "La Novena al Espíritu Santo es la novena original — el patrón de oración del cual desciende cada otra novena católica de nueve días. Su fundamento bíblico es el libro de los Hechos de los Apóstoles: «Todos perseveraban unánimes en la oración, junto con algunas mujeres, y María la madre de Jesús, y sus hermanos» (Hechos 1,14). Durante nueve días después de la Ascensión de Cristo, los discípulos y la Santísima Virgen María permanecieron en el cenáculo de Jerusalén en oración; al décimo día, la Fiesta de Pentecostés (Hechos 2,1-4), el Espíritu Santo descendió sobre ellos con el sonido de un viento impetuoso y lenguas de fuego. Cada novena católica posterior toma su patrón de nueve días de este único precedente dado por el Espíritu. La novena invoca los siete dones del Espíritu Santo enumerados en Isaías 11,2-3: sabiduría, entendimiento, consejo, fortaleza, ciencia, piedad y temor de Dios. A estos la tradición católica añade los doce frutos del Espíritu Santo nombrados en la Carta a los Gálatas (5,22-23 en la enumeración de la Vulgata): caridad, gozo, paz, paciencia, benignidad, bondad, longanimidad, mansedumbre, fe, modestia, continencia y castidad. El tono de la novena es petitorio pero confiado — el Espíritu es el don que Jesús prometió enviar (Juan 14,16-17; 16,7-15), y la Iglesia reza con confianza en que el mismo Espíritu que descendió sobre los apóstoles continúa descendiendo sobre los fieles. La novena es especialmente apropiada para el discernimiento de la vocación, la unción de los enfermos, la preparación de quienes reciben sacramentos (Confirmación, matrimonio, ordenación), y cualquier momento en que un alma sienta que no puede encontrar claridad por su sola razón y necesita la inspiración del Espíritu.",
    prayerText:
      "Ven, Espíritu Santo, llena los corazones de tus fieles y enciende en ellos el fuego de tu amor. Envía tu Espíritu y serán creados, y renovarás la faz de la tierra. Oh Dios, que iluminaste los corazones de tus hijos con la luz del Espíritu Santo, concédenos, por el mismo Espíritu, sentir rectamente y gozar siempre de su consuelo. Por Cristo nuestro Señor. Amén.",
    instructions:
      "Reza una vez al día durante nueve días consecutivos. Tradicionalmente, la novena se reza entre la Ascensión y el domingo de Pentecostés — los nueve días originales que la Iglesia ha rezado continuamente desde los apóstoles. (En diócesis donde la Ascensión se traslada al domingo siguiente al jueves tradicional, la novena comienza el viernes después de ese domingo; consulta el calendario litúrgico local.) La novena también puede rezarse en cualquier otro momento del año por una intención privada. La estructura tradicional para cada día: (1) Comenzar con la Señal de la Cruz; (2) Recitar o cantar el Veni Creator Spiritus («Ven, Espíritu Creador») o el Veni Sancte Spiritus («Ven, Espíritu Santo») — las dos grandes secuencias latinas de Pentecostés; (3) Rezar la oración de la novena; (4) Meditar brevemente sobre uno de los siete dones del Espíritu (uno por día durante los primeros siete días; en los días ocho y nueve, sobre los doce frutos y sobre una intención personal); (5) Concluir con un Padrenuestro, un Avemaría y un Gloria. La duración total es aproximadamente diez minutos por día. Las familias con niños pequeños a menudo rezan una versión más corta usando solo la invocación Ven, Espíritu Santo y una explicación apta para niños de un don por día — los dones y frutos son lo suficientemente tangibles como para que un niño de cinco años pueda comenzar a reconocerlos en su propia vida a lo largo de nueve atardeceres. La novena también es apropiada antes de una decisión importante, antes de una conversación difícil, o antes de cualquier tarea en la que una persona necesite consejo, fortaleza o sabiduría más allá de su capacidad natural.",
    patronSaint: null,
    feastDay: "Pentecostés",
    source: "USCCB Spanish + Acts 1:14, 2:1-4 + Vatican.va Spanish liturgical sources. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-st-therese",
    name: "Novena a Santa Teresita del Niño Jesús",
    description:
      "Santa Teresita del Niño Jesús y de la Santa Faz — mejor conocida como Teresa de Lisieux o «la Florecita» — fue una monja carmelita descalza que ingresó al claustro de Lisieux, en Normandía, a los quince años y murió de tuberculosis a los veinticuatro (1873-1897). Su autobiografía espiritual, Historia de un Alma, fue publicada poco después de su muerte y rápidamente se convirtió en uno de los libros católicos más leídos de la era moderna. Desde la oscuridad de un claustro provincial enseñó lo que llamó el Caminito: confianza en el amor misericordioso de Dios expresado en los más pequeños actos de fidelidad diaria, en lugar de hazañas externas heroicas. «Pasaré mi cielo haciendo el bien sobre la tierra», prometió célebremente; «haré caer una lluvia de rosas». La tradición de la «lluvia de rosas» — la creencia de que las intercesiones respondidas a través de Santa Teresita son a menudo acompañadas por una rosa inesperada, literal o simbólica — ha moldeado la devoción católica hacia ella desde entonces. Fue canonizada por el Papa Pío XI en 1925, nombrada Patrona de las Misiones en 1927 (a pesar de no haber salido nunca del claustro), y proclamada Doctora de la Iglesia por el Papa San Juan Pablo II en 1997 — una de solo cuatro mujeres así nombradas, junto con las Santas Teresa de Ávila, Catalina de Siena e Hildegarda de Bingen. Su contribución doctrinal es la teología de la infancia: la enseñanza evangélica de que uno debe hacerse como un niño pequeño para entrar en el Reino (Mateo 18,3) dada una articulación contemplativa sostenida. La novena a Santa Teresita es apropiada para: discernimiento de la vocación religiosa o laical, recuperación de enfermedad (su propia tuberculosis fue soportada con gran sufrimiento), aridez espiritual, la conversión de seres queridos lejanos (rezó continuamente por Pranzini, un asesino condenado, como su «primer hijo»), y cualquier momento en que un alma siente su propia pequeñez ante una gran necesidad.",
    instructions:
      "Reza una vez al día durante nueve días consecutivos. La estructura tradicional: (1) Comienza con la Señal de la Cruz; (2) Reza la oración de la novena a Santa Teresita (pidiendo su intercesión y su famosa rosa); (3) Nombra tu intención en silencio o en voz alta; (4) Concluye con un Padrenuestro, un Avemaría y un Gloria. La novena se reza apropiadamente en los nueve días previos a su fiesta (1 de octubre) o en cualquier momento del año por una intención privada. Muchos católicos conservan una pequeña imagen o reliquia de Santa Teresita en el hogar o llevan una estampa con tema de rosas durante la novena. La tradición de la «lluvia de rosas» es exactamente eso — una tradición, no una garantía mágica. Una rosa recibida durante o después de la novena se lee como una señal personal de que la santa ha escuchado la oración y está intercediendo ante Cristo; la ausencia de una rosa no se lee como la ausencia de intercesión. El punto es la disposición: el Caminito de Teresita invita al peticionario a la misma confianza infantil que ella modeló, que es en sí misma la gracia que se pide. La novena también es un acompañamiento apropiado a actos específicos de pequeña fidelidad durante los nueve días — paciencia con un familiar difícil, aceptar una pequeña incomodidad sin quejarse, contener una palabra cortante, realizar un acto oculto de bondad diariamente. Estos «pequeños caminos» encarnan lo que la novena pide: no transformación heroica, sino el camino de las pequeñas cosas hechas con gran amor que Teresita enseñó y vivió.",
    patronSaint: "Santa Teresita del Niño Jesús",
    feastDay: "1 de octubre",
    source: "USCCB Spanish + Historia de un Alma + Pope St. John Paul II Divini Amoris Scientia (1997, declaration as Doctor of the Church). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-miraculous-medal",
    name: "Novena de la Medalla Milagrosa",
    description:
      "En la noche del 18 al 19 de julio de 1830, en la capilla de las Hijas de la Caridad en la Rue du Bac de París, una joven novicia llamada Catalina Labouré fue despertada por su ángel custodio y conducida a la capilla para una aparición privada de la Santísima Virgen María. María habló con ella durante más de dos horas sobre el estado turbado de Francia y de la Iglesia en general. En una segunda aparición en noviembre, Catalina vio a María de pie sobre un globo con rayos de luz que brotaban de sus manos, rodeada de un marco inscrito con las palabras: «¡Oh María, sin pecado concebida, ruega por nosotros que recurrimos a ti!» En el reverso de esta visión había una M cruciforme con doce estrellas, un corazón de Cristo coronado de espinas, y un corazón de María traspasado por una espada. María instruyó a Catalina: «Manda acuñar una medalla según este modelo. Quienes la lleven con devoción recibirán grandes gracias, especialmente si la llevan al cuello». La medalla fue acuñada en 1832 con la aprobación del Arzobispo de París. En cinco años se había distribuido en tales cantidades y había acompañado tantas intercesiones reportadas que la imaginación católica popular la renombró «la Medalla Milagrosa», nombre que la Iglesia finalmente adoptó. Las apariciones de 1830 son notables como uno de los principales eventos marianos de la era moderna, anteriores a Lourdes (1858) por veintiocho años y a Fátima (1917) por ochenta y siete. La doctrina de la Inmaculada Concepción — en el corazón de la inscripción central de la medalla — fue definida formalmente por el Papa Pío IX en 1854, veinticuatro años después de las visiones de Catalina. Catalina Labouré permaneció en su convento de Reuilly, trabajando con los ancianos pobres, durante los cuarenta y seis años restantes de su vida. Fue canonizada en 1947 por el Papa Pío XII. La novena a la Medalla Milagrosa es apropiada para: enfermedad (especialmente con mal pronóstico — la reputación de la medalla comenzó con curaciones), conversión de familiares, protección durante el embarazo (una larga tradición católica de prender la medalla al vestido de la madre o llevarla durante el parto), y cualquier momento difícil en que un alma busca la intercesión maternal específica de María a través de este signo particular.",
    instructions:
      "Reza una vez al día durante nueve días consecutivos. La estructura tradicional: (1) Comenzar con la Señal de la Cruz; (2) Rezar el Memorare o tres Avemarías como invocación mariana inicial; (3) Rezar la oración de la novena a la Inmaculada Virgen por la Medalla Milagrosa; (4) Concluir con la inscripción central de la medalla como jaculatoria: «¡Oh María, sin pecado concebida, ruega por nosotros que recurrimos a ti!»; (5) Nombrar la intención específica. Si es posible, lleva la Medalla Milagrosa — físicamente — durante la novena. La medalla no es un amuleto; la tradición es que llevarla expresa la confianza en la intercesión de María y la apertura del portador a la gracia. Capillas y santuarios católicos distribuyen Medallas Milagrosas gratuitamente. La novena puede rezarse en cualquier momento pero es especialmente apropiada en los días previos a la Fiesta de Nuestra Señora de la Medalla Milagrosa (27 de noviembre) o la Solemnidad de la Inmaculada Concepción (8 de diciembre). Muchos católicos también usan la Medalla Milagrosa como signo de consagración al Inmaculado Corazón de María — emparejando la novena con la oración de Consagración Total de San Maximiliano Kolbe o la preparación más larga de 33 días para la consagración mariana (la tradición de Montfort). Para familias rezando por un ser querido ausente o que lucha, una práctica tradicional es deslizar una Medalla Milagrosa entre las pertenencias del ser querido — una billetera, el bolsillo de un abrigo, una mochila — como un pequeño signo de acompañamiento maternal constante.",
    patronSaint: "Santa Catalina Labouré",
    feastDay: "27 de noviembre",
    source: "USCCB Spanish + Rue du Bac apparition narrative (1830) + Pope Pius XII 1947 canonization. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "st-michael-prayer",
    name: "Oración a San Miguel Arcángel",
    description:
      "La Oración a San Miguel Arcángel fue compuesta por el Papa León XIII en 1886 después de que, según la tradición largamente atestiguada, el Papa tuviera una súbita experiencia mística mientras celebraba la Misa — una especie de visión despierta en la que escuchó un coloquio entre Cristo y Satanás en el que Satanás se jactaba de poder destruir la Iglesia si se le concedía suficiente tiempo y poder. Conmocionado por lo que había visto, León XIII compuso la oración a San Miguel ese mismo día y ordenó que se añadiera a las oraciones rezadas por el sacerdote y los fieles al final de cada Misa rezada en toda la Iglesia universal. Esta práctica — las «Oraciones Leoninas» después de la Misa — continuó durante casi ochenta años hasta las reformas litúrgicas de los años sesenta. La oración a San Miguel no fue abolida pero su lugar formal en las oraciones post-Misa caducó. El Papa San Juan Pablo II revivió la prominencia de la oración en una alocución del Ángelus dominical de 1994, en la que urgió a los fieles a «no olvidar recitar» la oración a San Miguel «para obtener ayuda en la batalla contra las fuerzas de las tinieblas y contra el espíritu de este mundo». El texto de la oración se basa en Judas 1,9 (Miguel disputando con el diablo por el cuerpo de Moisés), Apocalipsis 12,7-9 (Miguel derribando al dragón), y la tradición católica más amplia de San Miguel como el caudillo de la milicia celestial contra las potencias del mal. La oración es apropiada para: guerra espiritual en cualquier forma, ansiedad por el mal en el mundo o en la vida personal, protección durante un viaje o antes de un encuentro difícil, la conversión de quienes han caído en pecado grave, y como oración diaria de consagración a la protección de San Miguel. Es la oración que más comúnmente se enseña a los niños católicos como primera «oración de protección» junto con la oración del Ángel de la Guarda.",
    instructions:
      "Reza una vez con plena atención y devoción. La Oración a San Miguel es lo suficientemente corta como para memorizarla y rezarla en cualquier parte — en el coche antes de una reunión difícil, a la puerta de un hospital, caminando junto a un lugar donde se percibe discordia espiritual, antes de dormir al final del día. La práctica católica tradicional — y la que León XIII instituyó originalmente — es rezarla inmediatamente después de la conclusión de la Santa Misa, ya sea en el silencio que sigue a la despedida o como parte de una secuencia pública de Oraciones Leoninas. Muchas parroquias han revivido la oración a San Miguel post-Misa tras la llamada de JPII en 1994; si tu parroquia no lo hace, es completamente apropiado permanecer en tu banco durante treinta segundos después de la despedida y rezarla en privado. La oración también se incluye frecuentemente: al cierre del Rosario o de una Hora Santa; al concluir las oraciones nocturnas familiares; antes de cualquier tarea en la que un católico perciba una oposición espiritual real. Algunos hogares católicos colocan la oración sobre la puerta principal de la casa como signo de consagración a la protección de San Miguel sobre el hogar, en continuidad con la tradición más antigua de inscribir «Christus vincit, Christus regnat, Christus imperat» («Cristo vence, Cristo reina, Cristo impera») sobre los umbrales. La oración se empareja naturalmente con la oración del Ángel de la Guarda para los niños: San Miguel como príncipe de la hueste angélica, y el ángel custodio como el espíritu ministrante particular asignado a cada persona en el bautismo.",
    patronSaint: "San Miguel Arcángel",
    feastDay: "29 de septiembre",
    source: "USCCB Spanish + Leo XIII 1886 composition + Pope St. John Paul II Sunday Angelus, April 24, 1994. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "anima-christi",
    name: "Alma de Cristo (Anima Christi)",
    description:
      "El Anima Christi («Alma de Cristo») es una de las oraciones eucarísticas más amadas y antiguas de la tradición católica. Su origen es medieval — probablemente del siglo XIV — y durante muchos años fue atribuida a San Ignacio de Loyola porque la colocó al comienzo mismo de sus Ejercicios Espirituales (1522-1524) y la recomendó como oración diaria para los retirantes. La erudición moderna ha datado la oración al menos un siglo antes del nacimiento de Ignacio; aparece en manuscritos ya en 1314, posiblemente compuesta por Juan XXII o por un monje anónimo de la tradición cartuja o franciscana. Ignacio no la escribió, pero la amaba, y sus Ejercicios Espirituales le dieron la amplia circulación que disfruta hoy por todo el mundo católico. La oración es una meditación sostenida sobre el Cristo Eucarístico — Su alma, Su cuerpo, Su sangre, el agua y la sangre que fluyeron de Su costado traspasado en la Crucifixión (Juan 19,34), Su Pasión. Cada línea es a la vez una confesión de fe y una petición: «Alma de Cristo, santifícame» es la oración de quien pide ser interiormente santificado por la santidad misma de Cristo; «Cuerpo de Cristo, sálvame» es la confesión de que la salvación viene a través del mismo cuerpo ahora recibido bajo la apariencia de pan; «Dentro de tus llagas, escóndeme» es el anhelo místico medieval de encontrar refugio en las mismas llagas del Señor crucificado. El cierre de la oración — «En la hora de mi muerte, llámame» — la ha hecho una oración católica tradicional para los moribundos, rezada al lado de la cama en las horas finales por capellanes de hospicio, familiares y enfermeros católicos. El Anima Christi es apropiado para: acción de gracias inmediatamente después de recibir la Sagrada Comunión (su uso tradicional principal), una Hora Santa o visita al Santísimo Sacramento, el cierre de la oración personal, el lecho de los moribundos, y como devoción diaria que expresa intimidad eucarística.",
    instructions:
      "Reza con devoción, idealmente en una postura de quietud atenta — de rodillas, sentado erguido con las manos abiertas, o de pie ante el Santísimo Sacramento. La oración está pensada para ser sin prisa; cada línea es una petición distinta y el ritmo natural permite una breve pausa entre frases para que cada línea se asiente en el corazón. Los momentos tradicionales para el Anima Christi: (1) Inmediatamente después de recibir la Sagrada Comunión en la Misa, en el silencio del agradecimiento personal — este es el uso devocional principal de la oración, y la recomendación de San Ignacio; (2) Durante una Hora Santa o adoración eucarística ante el Santísimo Sacramento expuesto; (3) Al cierre de la oración personal matutina o vespertina, especialmente como parte de una espiritualidad eucarística; (4) Al lado del lecho de alguien gravemente enfermo o moribundo — la línea final, «En la hora de mi muerte, llámame, y mándame ir a Ti», hace la oración particularmente apropiada como devoción de lecho de muerte, rezada por la persona moribunda si está consciente o por familiares junto a ella; (5) Versión cantada en latín («Anima Christi, sanctifica me…») en entornos monásticos y litúrgicos tradicionales. Muchas estampas católicas llevan el Anima Christi en el reverso junto con una oración de recepción de la Comunión; algunos libros devocionales católicos abren con ella (siguiendo el patrón de los Ejercicios Espirituales). La oración puede memorizarse en una sola tarde y rezarse en cualquier parte; su brevedad y densidad de contenido eucarístico la hacen una de las oraciones breves de mayor alcance en el repertorio devocional católico.",
    patronSaint: "San Ignacio de Loyola",
    feastDay: null,
    source: "Vatican.va Spanish + Spiritual Exercises of St. Ignatius (1522-1524) + 14th-century manuscript tradition. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── ROUND 4 (es) ──────────────────────────────────────────
  {
    prayerSlug: "litany-saints",
    name: "Letanías de los Santos",
    description:
      "Las Letanías de los Santos son la letanía más antigua y solemne de la Iglesia Católica. Sus raíces se remontan a los primeros siglos — fragmentos de la forma aparecen en libros litúrgicos occidentales del siglo VII, y el Papa Gregorio Magno instituyó las grandes procesiones letánicas de Roma en el año 590, pidiendo a los fieles que invocaran a los santos por nombre en súplica durante una pestilencia. Las letanías se convirtieron en parte de la liturgia bautismal de la Vigilia Pascual al menos para el siglo VIII. Su texto actual en el rito romano fue fijado formalmente por el Papa Pío V en 1568 y revisado en la reforma litúrgica post-Vaticano II (1969). La estructura se despliega en cinco movimientos principales: (1) Invocaciones del Kyrie eleison y peticiones trinitarias; (2) la gran lista de santos por nombre — primero la Santísima Virgen María, luego los arcángeles (Miguel, Gabriel, Rafael), patriarcas y profetas (Abraham, Moisés, Elías, Juan el Bautista), apóstoles y evangelistas (Pedro, Pablo, Andrés, Juan, Santiago, etc.), mártires (Esteban, Lorenzo, Policarpo, Ignacio de Antioquía, Cipriano, Sebastián, Águeda, Inés), obispos confesores y doctores (Atanasio, Basilio, Gregorio, Agustín, Jerónimo, Ambrosio), fundadores y vírgenes (Antonio del Desierto, Benito, Francisco, Domingo, Catalina de Siena, Teresa de Ávila); (3) peticiones de liberación («De todo mal, líbranos, Señor»); (4) peticiones de súplica («Para que gobiernes y conserves tu santa Iglesia, te rogamos óyenos»); (5) Agnus Dei final y colecta. Las letanías son una de las principales oraciones de la liturgia católica y se usan en: la Vigilia Pascual (durante la Liturgia del Bautismo), bautismos del Sábado Santo, ordenaciones sacerdotales y episcopales (los candidatos yacen postrados mientras la Iglesia reunida canta las letanías sobre ellos), el Rito de Iniciación Cristiana de Adultos (RICA) en el Rito de Elección, la dedicación de una iglesia, la consagración de altares, y la profesión de votos religiosos. También es habitual en muchas parroquias en la Solemnidad de Todos los Santos (1 de noviembre), en funerales de sacerdotes y religiosos, en momentos de grave necesidad pública (guerra, pandemia, desastre natural), y como oración final de procesiones de peregrinación. La diócesis o comunidad local también es libre de añadir a los santos patronos de la iglesia local.",
    instructions:
      "Las Letanías de los Santos se rezan responsorialmente, generalmente cantadas en entornos litúrgicos. Un guía (sacerdote, diácono o cantor entrenado) entona la invocación; la asamblea responde con la fórmula apropiada. Las respuestas siguen la estructura: «Ruega por nosotros» después de cada santo nombrado o grupo de santos; «Líbranos, Señor» después de cada invocación de liberación («De todo mal…»); «Te rogamos óyenos» después de cada petición de súplica («Para que…»). Las letanías toman aproximadamente quince a veinte minutos cuando se cantan a paso solemne en un entorno litúrgico; algo menos cuando se rezan en casa de forma hablada. Para la devoción privada, las letanías pueden rezarse desde cualquier texto impreso aprobado (el Misal Romano, un libro de oraciones parroquial, o el sitio web de la USCCB o de la Conferencia Episcopal Mexicana llevan los textos oficiales en latín y español). Cuando se reza en casa, siéntate, ponte de pie o de rodillas como desees; el ritmo de las letanías es contemplativo en lugar de apurado. Las letanías se usan apropiadamente: (1) en Todos los Santos (1 de noviembre) y Todos los Fieles Difuntos (2 de noviembre) como oración familiar de esos días; (2) junto al lecho de alguien gravemente enfermo o moribundo — muchos capellanes católicos de hospital rezan las letanías mientras se aproximan los últimos sacramentos; (3) al comienzo de una peregrinación importante o de una empresa familiar, pidiendo a la gran nube de testigos (Hebreos 12,1) que rodeen a los peticionarios; (4) en tiempo de pestilencia, desastre o emergencia pública, en continuidad con la institución de las procesiones letánicas por Gregorio Magno durante la peste romana del año 590. El don espiritual particular de las letanías es la presencia sentida de la comunión de los santos — la verdad de que los fieles que oran en la tierra y aquellos triunfantes en el cielo son un solo cuerpo en Cristo.",
    patronSaint: null,
    feastDay: "1 de noviembre (Todos los Santos)",
    source: "USCCB Spanish + Pope Pius V 1568 codification + post-Vatican II 1969 revision + Gregorio Magno 590 institución. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "prayer-expectant-mothers",
    name: "Oración por las Madres Encinta",
    description:
      "La oración católica por las madres encinta se nutre de la tradición secular de la Iglesia de acompañar a las mujeres durante el embarazo bajo el patrocinio de la Santísima Virgen María, quien llevó a Cristo en su propio vientre durante nueve meses. El fundamento bíblico principal es la Visitación (Lucas 1,39-56): María, ella misma en los primeros meses de embarazo con Jesús, se apresura hacia las montañas de Judá para estar con su prima Isabel, quien está en su sexto mes con Juan el Bautista. El Magníficat («Mi alma engrandece al Señor…») es la oración de dos mujeres encinta regocijándose juntas. La tradición devocional católica ha confiado durante mucho tiempo las madres encinta a María bajo varios títulos específicos: Nuestra Señora de la Expectación o de la O (la Solemnidad del 18 de diciembre, una fiesta de tradición española nueve días antes de la Navidad, que marca el inminente parto de María); Nuestra Señora de Guadalupe (cuya imagen la muestra embarazada, vistiendo el cinturón de maternidad de costumbre indígena mexicana); y San Gerardo Mayela (1726-1755), un hermano laico redentorista italiano cuyo nombre se ha asociado tanto al parto seguro que sus estatuas se colocan en las salas de maternidad de los hospitales católicos de todo el mundo. La oración por las madres encinta es apropiada en cada etapa del embarazo: al primer test positivo, durante la ansiedad del primer trimestre que muchas madres sienten, durante los largos meses centrales de espera, en las semanas de preparación previas al parto, durante el mismo parto (cuando los familiares a menudo la rezan junto a la cama), e inmediatamente después del parto en acción de gracias. También la rezan las comunidades — parroquias, grupos de oración, el círculo de amigas de la mujer — como una forma de rodearla con intercesión durante los nueve meses de espera que reflejan los de María.",
    instructions:
      "Reza una vez al día por la madre encinta, idealmente a la misma hora cada día para que la práctica se vuelva parte de su ritmo ordinario. La oración es lo suficientemente corta como para memorizarla; muchas madres encinta la llevan en una pequeña tarjeta guardada en una Biblia, libro de oraciones o cartera, y la rezan mientras hacen una pausa en el trabajo cotidiano de preparación para el bebé. Prácticas comunes que se emparejan con la oración: (1) Encender una vela en un santuario mariano de la parroquia por cada mes del embarazo — muchas parroquias mantienen un soporte de velas designado para «madres encinta» y publican los nombres de las mujeres por las que se reza; (2) Rezar una decena diaria del Rosario, meditando en los Misterios Gozosos (la Anunciación, la Visitación, la Natividad, la Presentación, el Niño Perdido y Hallado en el Templo — cinco misterios que recorren el arco espiritual desde la concepción hasta la maternidad joven); (3) Pedir la intercesión de San Gerardo Mayela — la oración por las madres encinta puede emparejarse con la novena a San Gerardo, especialmente en los nueve días finales antes del parto; (4) Oración familiar o comunitaria junto al lecho durante el parto, en la que el esposo de la madre encinta u otro familiar reza el Memorare (la breve oración mariana de confianza) o esta oración en voz alta a medida que progresa el parto. La tradición católica es clara que el embarazo es en sí mismo una forma de oración. Después del parto, la oración continúa en acción de gracias y se vuelve naturalmente hacia las oraciones de maternidad por el recién nacido.",
    patronSaint: "Nuestra Señora",
    feastDay: null,
    source: "USCCB Spanish + Lucas 1,39-56 + tradición de San Gerardo Mayela. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "adoration-hour",
    name: "Hora Santa de Adoración",
    description:
      "La Hora Santa de Adoración Eucarística es una de las formas más antiguas y centrales de oración católica — oración sostenida y silenciosa en la real presencia de Jesucristo en el Santísimo Sacramento, expuesto en una custodia sobre el altar. La práctica se nutre directamente de la escena evangélica en Getsemaní: Cristo pregunta a sus apóstoles, «¿No pudisteis velar una hora conmigo?» (Mateo 26,40). La «una hora» no es una duración arbitraria — es la petición explícita del Señor en la noche de su pasión, y la Hora Santa católica responde directamente a esa petición. La práctica devocional de la adoración eucarística sostenida cristalizó en la Contrarreforma y recibió un impulso particular de las apariciones del Sagrado Corazón a Santa Margarita María Alacoque en Paray-le-Monial (1673-1675); Cristo pidió específicamente a Margarita María una hora de reparación en su presencia cada noche del jueves, en recuerdo de la Agonía en el Huerto. La Hora Santa se volvió central en el «Apostolado de la Oración» (fundado en 1844) y fue predicada ampliamente en el siglo XX por el Venerable Fulton Sheen (1895-1979), quien célebremente se comprometió a una Hora Santa cada día de su vida sacerdotal — más de 60 años — y atribuyó cada gracia de su ministerio a esa hora. Hoy capillas de adoración eucarística perpetua operan en miles de parroquias en todo el mundo, atendidas por voluntarios laicos que se comprometen a horas específicas a través de la noche y el día para que Cristo nunca quede solo en su Sacramento expuesto. La Hora Santa es apropiada para: cualquier intercesión sostenida, especialmente por sanación, conversión o discernimiento vocacional; reparación por el pecado (el propio o el del mundo); aridez espiritual (cuando la oración se siente seca, la presencia de la Eucaristía sostiene al alma incluso cuando los sentimientos están ausentes); preparación para decisiones importantes de la vida; acción de gracias después de recibir una gracia. Es la oración que Sheen llamaba «el secreto de cada sacerdote que se hizo santo».",
    instructions:
      "Visita tu parroquia durante las horas de Adoración — consulta el sitio web o el boletín de tu parroquia para conocer el horario. Muchas parroquias ofrecen adoración eucarística los jueves (la petición de Cristo a Margarita María), los viernes (el día tradicional de reparación), o como una Hora Santa extendida después de la Misa entre semana. Algunas mantienen adoración perpetua con el Santísimo Sacramento expuesto 24/7. Al llegar: (1) Genuflexiona con ambas rodillas (el signo tradicional de reverencia para la Eucaristía expuesta, distinto de la genuflexión con una rodilla para el Sacramento reservado en el tabernáculo); (2) Encuentra un lugar para sentarte o arrodillarte; (3) Inclínate en silencioso reconocimiento de que estás en la presencia literal de Dios encarnado. La hora misma es desestructurada por diseño — la presencia sostenida es la oración. Algunos patrones que usan los católicos para llenar la hora: (a) Rezar el Rosario, meditando en los Misterios Dolorosos; (b) Leer la Sagrada Escritura (las narraciones de la Pasión, el Evangelio de Juan, los Salmos — Salmos 23 y 91 son escrituras comunes de adoración eucarística); (c) Rezar la Coronilla de la Divina Misericordia, especialmente durante la hora de las 3:00 PM; (d) Leer de un clásico espiritual (los escritos de Fulton Sheen, la Imitación de Cristo de Tomás de Kempis, el diario de Santa Faustina); (e) Sentarse en presencia silenciosa — la forma más alta de oración contemplativa; (f) Llevar un diario de conversación con Jesús sobre la persona por la que ofreces la hora. A lo largo de la hora, nombra a la persona y la intención frecuentemente. La hora termina con otra genuflexión y una breve oración de acción de gracias por el don de su presencia.",
    patronSaint: null,
    feastDay: null,
    source: "USCCB Spanish + Mateo 26,40 + apariciones del Sagrado Corazón en Paray-le-Monial (1673-1675) + tradición de Fulton Sheen. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "stations-of-the-cross",
    name: "Vía Crucis (Estaciones de la Cruz)",
    description:
      "El Vía Crucis (también llamado Camino de la Cruz, Via Crucis en latín, o Vía Dolorosa) es una devoción meditativa en la que el creyente sigue la Pasión de Cristo a través de catorce estaciones distintas — momentos a lo largo de su recorrido desde el pretorio de Pilato hasta el sepulcro. La práctica se originó en los primeros siglos cristianos como una peregrinación literal a los lugares santos de Jerusalén; los peregrinos caminaban el sendero real que Cristo caminó, deteniéndose en cada estación significativa para orar. Cuando Jerusalén cayó bajo control musulmán en el siglo VII y la peregrinación se volvió peligrosa y rara, los franciscanos — a quienes el Papa Clemente VI dio la custodia de Tierra Santa en 1342 — comenzaron a reconstruir la Vía Dolorosa en forma de estaciones devocionales en sus iglesias por toda Europa, para que cualquier católico pudiera «caminar» el Camino de la Cruz espiritualmente sin viajar a Jerusalén. El Papa Inocencio XI concedió a los franciscanos indulgencias por rezar las estaciones en 1686, y el Papa Clemente XII extendió esto a todos los fieles en 1731. Las catorce estaciones estándar se fijaron en el siglo XVIII: (1) Jesús es condenado a muerte; (2) Jesús carga la cruz; (3) Jesús cae por primera vez; (4) Jesús encuentra a su Madre María; (5) Simón el Cireneo ayuda a Jesús a cargar la cruz; (6) Verónica enjuga el rostro de Jesús; (7) Jesús cae por segunda vez; (8) Jesús encuentra a las mujeres de Jerusalén; (9) Jesús cae por tercera vez; (10) Jesús es despojado de sus vestiduras; (11) Jesús es clavado en la cruz; (12) Jesús muere en la cruz; (13) Jesús es bajado de la cruz; (14) Jesús es depositado en el sepulcro. Algunas comunidades católicas añaden una decimoquinta estación para la Resurrección. El Vía Crucis se reza tradicionalmente los viernes durante la Cuaresma y es la devoción pública central del Viernes Santo en la mayoría de las parroquias católicas del mundo. El Papa preside el Vía Crucis en el Coliseo de Roma cada Viernes Santo — una tradición revivida por el Papa Pablo VI y continuada por cada papa desde entonces, transmitida globalmente.",
    instructions:
      "Visita una iglesia católica — la mayoría tiene las catorce estaciones montadas a lo largo de las paredes laterales de la nave, generalmente como pequeñas pinturas, placas, o bajorrelieves. La práctica tradicional: (1) Comenzar en la primera estación; genuflexionar; (2) Anunciar la estación en voz alta («Primera Estación: Jesús es condenado a muerte»); (3) Rezar la respuesta «Te adoramos, oh Cristo, y te bendecimos, porque por tu santa Cruz redimiste al mundo»; (4) Meditar brevemente sobre la escena de la Pasión de Cristo correspondiente a la estación; (5) Rezar un Padrenuestro, un Avemaría y un Gloria (u otras oraciones de un librito del Vía Crucis); (6) Ofrecer la estación por tu intención. Pasa a la siguiente estación — caminar físicamente de una a la siguiente es parte de la oración; el Vía Crucis está pensado para ser caminado, aunque sea brevemente. Duración total: aproximadamente treinta a cuarenta y cinco minutos cuando se reza a paso sin prisa en una iglesia. En casa, un librito impreso del Vía Crucis funciona bien — no hay un requisito de presencia física. La devoción se reza apropiadamente: (a) Los viernes durante la Cuaresma, la disciplina católica tradicional; (b) En el mismo Viernes Santo, el día que Cristo caminó la Vía Dolorosa; (c) En cualquier viernes a lo largo del año (como el día tradicional de recuerdo de la Pasión); (d) Cuando se carga una pesada cruz personal — enfermedad, dolor, adicción, persecución — uniendo tu sufrimiento al de Cristo; (e) Cuando se reza por alguien que sufre o muere; (f) Cuando se busca la gracia de la paciencia bajo la aflicción.",
    patronSaint: null,
    feastDay: "Viernes Santo",
    source: "USCCB Spanish + Franciscan custody of Holy Land (1342) + Pope Innocent XI 1686 + Clement XII 1731. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "morning-offering",
    name: "Ofrecimiento de la Mañana",
    description:
      "El Ofrecimiento de la Mañana es la oración diaria fundacional del Apostolado de la Oración — un movimiento espiritual católico fundado en 1844 por el sacerdote jesuita François-Xavier Gautrelet en Vals, Francia, y renombrado en 2015 por el Papa Francisco como la Red Mundial de Oración del Papa. La intuición central del movimiento es simple pero transformadora: cada acción ordinaria del día de un católico — el trabajo, el estudio, la conversación, las comidas, el cansancio, el gozo, el sufrimiento, incluso el sueño — puede ofrecerse a Dios como un acto intencional de amor, transformando todo el día en un acto sostenido de oración. El Ofrecimiento de la Mañana es el acto que realiza este ofrecimiento, rezado lo primero al despertar, antes de que el día tome el control. El texto tradicional — compuesto a finales del siglo XIX en los folletos devocionales del Apostolado y refinado a través de varias versiones aprobadas por los papas — coloca el ofrecimiento del día «a través del Inmaculado Corazón de María» (la mediación mariana que enmarca la vida católica como filial) y lo une «con el Santo Sacrificio de la Misa en todo el mundo» (de modo que el ofrecimiento del día se reúne en el sacrificio eucarístico que se celebra en alguna parroquia católica en alguna parte de la tierra en cada minuto de cada hora). Cada mes, el Papa publica intenciones específicas de oración universal a través de la Red Mundial de Oración del Papa — por ejemplo, «por la protección de los niños» o «por el fin de la trata de personas» — y los católicos que rezan el Ofrecimiento de la Mañana unen las pequeñas acciones de su día a esas intenciones más amplias. El Ofrecimiento de la Mañana es también una poderosa oración de intercesión por una persona en particular: un familiar enfermo, un hijo adulto que ha abandonado la fe, un padre luchando con la adicción, cualquiera cuya situación el peticionario experimenta como constantemente presente.",
    prayerText:
      "Oh Jesús, por el Inmaculado Corazón de María, te ofrezco mis oraciones, trabajos, gozos y sufrimientos de este día, por todas las intenciones de tu Sagrado Corazón, en unión con el Santo Sacrificio de la Misa en todo el mundo, en acción de gracias por tus favores, en reparación por mis pecados, por las intenciones de todos mis asociados y, en particular, por (mencionar el nombre y la intención de la persona). Amén.",
    instructions:
      "Reza inmediatamente al despertar, antes de que la ocupación del día pueda tomar el control. La disciplina tradicional es rezarlo antes de levantarse de la cama, mientras la mente está aún suave y el día todavía se siente como un regalo; algunos católicos lo rezan durante el primer momento tranquilo de la rutina matutina (con la primera taza de café, en el fregadero de la cocina, mientras alimentan al bebé). La oración es lo suficientemente corta como para memorizarla en un solo día. Para hacerla parte de la vida: (1) Coloca la oración en un lugar donde la verás lo primero — pegada al espejo del baño, dentro de la puerta del dormitorio, en una tarjeta junto a la cafetera; (2) Nombra a la persona específica y la intención en el lugar apropiado de la oración (la línea «y en particular por…»), haciendo el ofrecimiento concreto y no abstracto; (3) A lo largo del día, cuando el trabajo se vuelve difícil o una interrupción rompe tus planes, renueva brevemente el ofrecimiento: «Te di este día por (nombre); este momento es parte de eso». Muchos hogares católicos rezan el Ofrecimiento de la Mañana en voz alta juntos al levantarse la familia — padres e hijos rezándolo juntos antes del desayuno. La Red Mundial de Oración del Papa publica las intenciones universales mensuales del Papa; alinear tu ofrecimiento diario con la intención del Papa cada mes añade una dimensión de solidaridad católica universal a tu oración. Para una intercesión sostenida (una novena de días por un ser querido enfermo, la duración de un discernimiento difícil, los meses de quimioterapia de un familiar), el Ofrecimiento de la Mañana se convierte en la columna vertebral de la oración.",
    patronSaint: null,
    feastDay: null,
    source: "USCCB Spanish + Apostolado de la Oración / Red Mundial de Oración del Papa (1844, renombrado 2015). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "three-oclock-prayer",
    name: "Oración de las Tres de la Tarde (Hora de la Misericordia)",
    description:
      "La Oración de las Tres de la Tarde — también llamada la Hora de la Misericordia o la Hora de la Gran Misericordia — fue dada por Jesús a Santa María Faustina Kowalska en las revelaciones de la Divina Misericordia registradas en su Diario: La Divina Misericordia en mi Alma. Jesús instruyó a Faustina que las 3:00 PM de cada día — la hora de su muerte en el Calvario — sea honrada como la Hora de la Gran Misericordia, en la cual un breve acto de oración obtiene gracias extraordinarias. La promesa exacta, registrada en el Diario de Faustina (entrada 1320): «A las tres de la tarde, implora mi misericordia, especialmente por los pecadores; y, aunque sea por un breve momento, sumérgete en mi Pasión, particularmente en mi abandono en el momento de la agonía. Esta es la hora de la gran misericordia para todo el mundo… En esta hora no rechazaré nada al alma que me hace una petición en virtud de mi Pasión». La hora corresponde a la hora novena del día judío en la cronología evangélica (Marcos 15,34) — la hora a la que «Jesús lanzó un fuerte grito… y expiró» (Marcos 15,37). La Oración de las Tres de la Tarde es la forma más simple y más accesible de devoción a la Divina Misericordia — mucho más corta que la coronilla, accesible a cualquiera que pueda detenerse treinta segundos a la hora de la muerte de Cristo. Es la oración que la tradición católica coloca en el corazón del día para aquellos que no pueden hacer una Hora Santa completa, que no pueden rezar la coronilla, que están en el trabajo o en la escuela o junto al lecho de un hospital — el breve momento ofrecido que toma a Cristo en su palabra y pide la misericordia que prometió. La devoción fue suprimida durante muchos años (el mismo período en que los escritos de Faustina estaban bajo restricción provisional), pero el Papa San Juan Pablo II canonizó a Faustina el 30 de abril de 2000, y estableció el Domingo de la Divina Misericordia como fiesta para la Iglesia universal.",
    prayerText:
      "Expiraste, Jesús, pero la fuente de la vida brotó para las almas y se abrió el océano de misericordia para todo el mundo. Oh Fuente de Vida, insondable Divina Misericordia, envuelve al mundo entero y derrámate sobre nosotros. Oh Sangre y Agua que brotaste del Corazón de Jesús como fuente de misericordia para nosotros, en Ti confío. Santo Dios, Santo Fuerte, Santo Inmortal, ten piedad de nosotros y del mundo entero. (3 veces)",
    instructions:
      "A las 3:00 PM cada día, haz una breve pausa — sea lo que sea que estés haciendo — y reza. La oración es lo suficientemente corta como para memorizarla en una sola tarde y para rezarla en cualquier parte: en un escritorio, en un coche, en un aula, junto al lecho de un hospital, caminando por una acera. La tradición católica es clara que «incluso un momento de oración a esta hora es poderoso» — si una vida ocupada solo puede dedicar veinte segundos para un único «Jesús, en ti confío» a las 3:00 PM, ese breve momento es en sí mismo la práctica. Para aquellos con más tiempo en la hora: (1) Rezar la Coronilla completa de la Divina Misericordia (aproximadamente diez minutos); (2) Hacer una breve «visita» a una iglesia católica cercana o capilla de adoración eucarística; (3) Detenerse a leer un párrafo del Diario de Santa Faustina; (4) Rezar por los pecadores — Faustina registró que Jesús le dijo que esta es la intercesión más poderosa a esta hora. Las disciplinas católicas tradicionales que se emparejan con la Oración de las Tres de la Tarde: (a) Establecer una alarma diaria a las 3:00 PM como recordatorio hasta que la disciplina se convierta en hábito; (b) Llevar una pequeña estampa o imagen de la Divina Misericordia como recordatorio táctil a lo largo del día; (c) Rezar al pie de un crucifijo (la postura literal de Cristo en su muerte); (d) Añadir un momento de quietud física — pausando cualquier movimiento en curso, aunque sea brevemente. La hora es un ancla diaria para la vida devocional de la Divina Misericordia.",
    patronSaint: "Santa María Faustina Kowalska",
    feastDay: null,
    source: "USCCB Spanish + Diario de Santa Faustina (1320) + JPII canonización 30 de abril 2000 + Marcos 15,34-37. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
];
