import type { PrayerTranslationSeed } from "./types";

/**
 * Spanish (es) translations of PrayerType content.
 *
 * Authoring conventions:
 *  - **Source tier**: USCCB Spanish (usccb.org/es), Vatican.va Spanish,
 *    Editorial Verbo Divino / Ediciones Paulinas for published prayer
 *    collections.
 *  - **Variant**: macro-tag "es" — neutral Latin American Spanish.
 *    Avoid Spain-specific "vosotros"; prefer "ustedes." Catholic
 *    register: "rezar por" (not "para") for prayer intentions.
 *  - **Brand names stay English**: "PrayerTrain," "Surrender Novena."
 *  - **`prayerText` left null for the description+instructions wave** —
 *    canonical Spanish prayer wording should be drawn from USCCB es /
 *    Vatican.va sources in a separate focused pass. Helper falls back
 *    to canonical English prayer text under the Spanish description +
 *    instructions.
 */
export const esTranslations: PrayerTranslationSeed[] = [
  // ─── Round 1: 5 anchor prayers from PR #69 ──────────────────
  {
    prayerSlug: "novena-sacred-heart",
    name: "Novena al Sagrado Corazón de Jesús",
    description:
      "La Novena al Sagrado Corazón de Jesús es una de las devociones más queridas de la Iglesia Católica, nacida de las apariciones de Jesús a Santa Margarita María Alacoque en Paray-le-Monial, Francia, entre 1673 y 1675. En estas visiones, Cristo reveló la profundidad de su amor por la humanidad, simbolizado por su Corazón traspasado y coronado de espinas, y pidió que ese amor fuera honrado mediante la devoción a su Sagrado Corazón. La novena abarca nueve días consecutivos de oración (el número nueve recuerda los nueve días que los apóstoles y María pasaron en oración entre la Ascensión y Pentecostés) y se ofrece tradicionalmente con confianza en la compasión de Cristo hacia los que sufren. Es especialmente apropiada en tiempos de enfermedad, dificultad familiar, desolación espiritual o intenciones persistentes que aún no han encontrado respuesta. El Sagrado Corazón no es un mero símbolo; es el corazón histórico y físico de Cristo, plenamente humano y plenamente divino, fuente de su caridad infinita. La encíclica Haurietis Aquas de Pío XII (1956) describe el Sagrado Corazón como «el trono de la misericordia» y confirma el lugar central de esta devoción en la vida de la Iglesia. Los guerreros de oración que ofrecen esta novena se unen a siglos de católicos que han depositado su confianza en el Corazón herido del Salvador.",
    instructions:
      "Reza una vez al día durante nueve días consecutivos, aproximadamente a la misma hora cada día. Elige un lugar tranquilo y comienza con la Señal de la Cruz. La estructura tradicional es: (1) una invocación inicial, a menudo «Oh Sagradísimo Corazón de Jesús, en Ti pongo toda mi confianza»; (2) el texto mismo de la novena; (3) un Padrenuestro, un Avemaría y un Gloria; (4) una intención personal dicha en voz alta o en silencio. Muchos añaden las Letanías del Sagrado Corazón el último día o rezan la novena junto con la devoción de los Primeros Viernes, recibiendo la Sagrada Comunión nueve primeros viernes consecutivos como el mismo Cristo le pidió a Santa Margarita María. La novena puede rezarse en cualquier época del año, pero es especialmente apropiada durante el mes de junio (mes del Sagrado Corazón), en los días previos a la Solemnidad del Sagrado Corazón (viernes después del Corpus Christi), o cuando alguien atraviesa un momento particularmente difícil. Si se omite un día, el consejo tradicional es comenzar de nuevo desde el día uno en lugar de saltárselo; la disciplina de la oración consecutiva es parte de la gracia de la devoción. Algunos rezan por una persona específica cada día de la novena; otros ofrecen los nueve días por una sola intención.",
    patronSaint: "Santa Margarita María Alacoque",
    feastDay: "Viernes después del Corpus Christi",
    source: "USCCB Spanish materials + Haurietis Aquas (Pius XII, 1956). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-st-joseph",
    name: "Novena a San José",
    description:
      "San José, padre adoptivo de Jesús y casto esposo de la Santísima Virgen María, es uno de los intercesores más amados en la tradición católica. Aunque la Escritura no recoge palabra alguna pronunciada por él, su fidelidad es inconfundible: protegió a la Sagrada Familia en la huida a Egipto, los sostuvo con el trabajo de sus manos y enseñó a Jesús el oficio de la carpintería y los caminos de la masculinidad fiel. El Papa Pío IX lo nombró Patrono de la Iglesia Universal en 1870, y el Papa Francisco declaró el período 2020-2021 como Año de San José mediante la carta apostólica Patris Corde («Con Corazón de Padre»). Esta novena se nutre de una larga tradición católica que reconoce a San José como patrono de los padres, los trabajadores, las familias, los asuntos inmobiliarios y la buena muerte: los cuatro pilares de su ministerio terrenal. Se le invoca especialmente en momentos de dificultad económica, discordia familiar, dificultades laborales y en el discernimiento vocacional. Muchos católicos se comprometen con la novena en los días previos a alguna de sus fiestas: el 19 de marzo (Solemnidad de San José, Esposo de la Bienaventurada Virgen María) o el 1 de mayo (San José Obrero, instituida por el Papa Pío XII en 1955 para santificar el trabajo humano). Santa Teresa de Ávila escribió célebremente: «A otros santos parece que les dio el Señor gracia para socorrer en una necesidad; a este glorioso Santo tengo experiencia que socorre en todas».",
    instructions:
      "Reza una vez al día durante nueve días consecutivos. La estructura tradicional es: comenzar con la Señal de la Cruz; rezar el texto de la novena; concluir con un Padrenuestro, un Avemaría y un Gloria; y nombrar tu intención específica. Algunas familias católicas añaden las Letanías de San José o siete Padrenuestros, Avemarías y Glorias en honor a los Siete Dolores y los Siete Gozos de San José — una devoción tradicional vinculada a sus experiencias de dolor y alegría en la vida de la Sagrada Familia. Para familias que están discerniendo una decisión importante (un cambio de trabajo, una mudanza, un matrimonio), es costumbre comenzar la novena nueve días antes de que deba tomarse la decisión, pidiendo la intercesión de San José para obtener claridad y la gracia de aceptar la voluntad de Dios. La novena también se reza tradicionalmente durante el mes de marzo (mes de San José) o junto con la práctica popular de enterrar una estatua de San José en relación con la venta de una casa: una tradición popular que subraya la confianza pacífica, no la superstición. Ya sea que se rece por discernimiento vocacional, provisión económica, sanación familiar o una buena muerte (uno de los cuatro fines tradicionales de esta devoción), el espíritu debe ser de confianza tranquila y trabajadora, la misma disposición que San José modeló en la Escritura.",
    patronSaint: "San José",
    feastDay: "19 de marzo / 1 de mayo",
    source: "Patris Corde (Francis, 2020) + USCCB Spanish + St. Teresa of Ávila, Vida (ch. 6). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "holy-rosary",
    name: "El Santo Rosario",
    description:
      "El Santo Rosario es la devoción mariana central de la Iglesia Católica: una oración contemplativa en la que el creyente medita los grandes misterios de la vida, muerte y resurrección de Cristo mientras reza decenas repetidas de Avemarías. El Rosario, tal como lo conocemos hoy, tomó forma a lo largo de los siglos; la tradición sostiene que la Santísima Virgen María entregó el Rosario a Santo Domingo en 1208 como arma espiritual contra la herejía albigense, y la estructura de quince misterios fue codificada por el Papa San Pío V en 1569. En 2002, el Papa San Juan Pablo II añadió los Misterios Luminosos (Misterios de la Luz) en su carta apostólica Rosarium Virginis Mariae, llevando el total a veinte misterios agrupados en cuatro conjuntos. Cada decena es una meditación: mientras los dedos se mueven por las cuentas y los labios recitan el Avemaría, la mente se detiene en un momento de los Evangelios — la Anunciación, la Crucifixión, la Resurrección, la Transfiguración. El Rosario no es vana repetición (Mateo 6:7) sino una escuela de contemplación, que permite que el ritmo de las oraciones libere la mente para reflexionar sobre los misterios de la salvación. Los Papas, desde León XIII (cuyas once encíclicas sobre el Rosario siguen siendo referencias magisteriales) hasta Francisco, han exhortado a los fieles a rezar el Rosario diariamente. Es la oración que se ofreció en Lourdes, Fátima y muchas otras apariciones marianas, y la oración que con más frecuencia rezan las familias católicas reunidas junto a un lecho de enfermo o ante una tumba.",
    instructions:
      "Un Rosario completo consta de cinco decenas, generalmente rezado en unos veinte minutos. Comienza con la Señal de la Cruz y el Credo de los Apóstoles sobre el crucifijo. En la primera cuenta grande reza el Padrenuestro; en cada una de las tres cuentas pequeñas que siguen reza un Avemaría (por el aumento de las tres virtudes teologales: fe, esperanza y caridad); en la siguiente cuenta grande reza el Gloria. Luego anuncia el primer misterio en voz alta y medita brevemente en su significado; reza un Padrenuestro en la cuenta grande, diez Avemarías en las diez cuentas pequeñas (una por cuenta) mientras continúas meditando el misterio, luego un Gloria y la Oración de Fátima («Oh Jesús mío, perdónanos nuestros pecados, líbranos del fuego del infierno…»). Repite con cuatro decenas más, nombrando cada misterio. Concluye con la Salve y la oración del Rosario. Los cuatro conjuntos de misterios se rezan tradicionalmente así: Misterios Gozosos los lunes y sábados (la Anunciación, la Visitación, el Nacimiento, la Presentación, el Niño Perdido y Hallado en el Templo); Dolorosos los martes y viernes (la Oración en el Huerto, la Flagelación, la Coronación de Espinas, la Cruz a Cuestas, la Crucifixión); Gloriosos los miércoles y domingos (la Resurrección, la Ascensión, Pentecostés, la Asunción, la Coronación de la Virgen); Luminosos los jueves (el Bautismo del Señor, las Bodas de Caná, el Anuncio del Reino, la Transfiguración, la Institución de la Eucaristía). Para la cobertura de un PrayerTrain, una sola decena — o incluso una sola Avemaría ofrecida con intención — también es una ofrenda válida del Rosario.",
    patronSaint: "Nuestra Señora del Rosario",
    feastDay: "7 de octubre",
    source: "Rosarium Virginis Mariae (St. John Paul II, 2002) + Leo XIII rosary encyclicals + CCC 971, 2678, 2708. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "chaplet-divine-mercy",
    name: "Coronilla de la Divina Misericordia",
    description:
      "La Coronilla de la Divina Misericordia fue entregada por Jesús a Santa María Faustina Kowalska, religiosa polaca, en una serie de revelaciones que tuvieron lugar entre 1931 y 1938 y que ella misma recogió en su Diario: La Divina Misericordia en mi alma. La coronilla es una poderosa oración de intercesión ofrecida por la conversión de los pecadores, el consuelo de los moribundos y la misericordia de Dios sobre el mundo entero. Jesús le dijo a Faustina que quien rezara esta coronilla recibiría «gran misericordia en la hora de la muerte», y que se complacía especialmente en esta oración cuando se rezaba a las 3:00 de la tarde, la Hora de la Misericordia (la hora de su muerte en el Calvario). La coronilla se reza con un rosario común, lo que la hace accesible a cualquiera que tenga un rosario, y dura aproximadamente diez minutos. La devoción a la Divina Misericordia estuvo suprimida durante muchos años, pero el Papa San Juan Pablo II — él mismo polaco y compatriota de Santa Faustina — la canonizó el 30 de abril del año 2000 y estableció el Domingo de la Divina Misericordia (segundo domingo de Pascua) como fiesta para toda la Iglesia universal. La Coronilla de la Divina Misericordia se ha convertido en una de las devociones más rezadas en la Iglesia contemporánea, especialmente apreciada por capellanes de hospital, voluntarios de cuidados paliativos y quienes rezan por la conversión de seres queridos. Es la oración diaria en el Santuario Nacional de la Divina Misericordia de Stockbridge, Massachusetts, y en el Santuario de la Divina Misericordia de Łagiewniki, Cracovia — el lugar donde Faustina vivió, murió y hoy reposa.",
    instructions:
      "Con un rosario común de cinco decenas, comienza con la Señal de la Cruz, un Padrenuestro, un Avemaría y el Credo de los Apóstoles sobre el crucifijo y las cuentas iniciales. En cada una de las cinco cuentas grandes (donde normalmente se reza el Padrenuestro) reza: «Padre Eterno, te ofrezco el Cuerpo y la Sangre, el Alma y la Divinidad de tu amadísimo Hijo, nuestro Señor Jesucristo, como propiciación por nuestros pecados y los del mundo entero». En cada una de las diez cuentas pequeñas de cada decena reza: «Por su dolorosa Pasión, ten misericordia de nosotros y del mundo entero». Al terminar las cinco decenas, concluye rezando tres veces: «Santo Dios, Santo Fuerte, Santo Inmortal, ten piedad de nosotros y del mundo entero». La coronilla es especialmente poderosa cuando se reza a las 3:00 de la tarde (la Hora de la Misericordia), junto al lecho de los moribundos, en los nueve días previos al Domingo de la Divina Misericordia (la Novena a la Divina Misericordia, que comienza el Viernes Santo), y en momentos de angustia o temor personal. Puede rezarse en silencio, en voz alta, a solas o en grupo. Muchas parroquias rezan la coronilla semanalmente, a menudo los viernes en memoria de la Pasión de Cristo. Los católicos que rezan por la conversión o la muerte serena de un ser querido suelen comprometerse a rezar la coronilla diariamente durante un período sostenido — un mes, la duración de una enfermedad, el tiempo previo a una decisión importante. La coronilla se asocia naturalmente con la asistencia a la Novena a la Divina Misericordia, desde el Viernes Santo hasta el Domingo de la Divina Misericordia.",
    patronSaint: "Santa Faustina Kowalska",
    feastDay: "Domingo de la Divina Misericordia",
    source: "Diary: Divine Mercy in My Soul (St. Faustina) + canonical chaplet text per Holy See post-2000 canonization. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "memorare",
    name: "El Acordaos (Memorare)",
    description:
      "El Memorare es una oración breve pero extraordinariamente poderosa de confianza en la intercesión de la Santísima Virgen María. Toma su nombre de la primera palabra latina del texto, Memorare («Acordaos»), y en su forma moderna se atribuye al P. Claude Bernard, sacerdote francés del siglo XVII conocido como «el Sacerdote Pobre» por su apostolado entre los prisioneros y los moribundos. La oración se popularizó gracias a la distribución por parte del P. Bernard de más de 200,000 folletos en el París previo a la Revolución, aunque sus raíces devocionales se remontan más atrás — probablemente a una oración más extensa atribuida a San Bernardo de Claraval (1090-1153), el gran abad cisterciense y Doctor de la Iglesia cuya devoción mariana dio forma a la piedad occidental. La estructura de la oración es una apelación confiada: reconoce la maternidad universal de María («Oh Virgen de las vírgenes, mi Madre»), hace referencia a la tradición ininterrumpida de su intercesión («jamás se ha oído decir que ninguno de los que han acudido a tu protección… haya sido desamparado»), y concluye con una petición humilde («en tu misericordia escúchame y respóndeme»). Los santos a lo largo de los siglos han testimoniado su poder: la Madre Teresa de Calcuta rezaba nueve Memorares consecutivos cada día — lo que ella llamaba su «novena al vuelo» — cuando necesitaba algo con urgencia. El Memorare es la oración católica de último recurso, rezada en momentos de necesidad aguda, junto al lecho de los moribundos, en la capilla antes de una conversación difícil, o susurrada mientras un padre o una madre espera noticias desde una habitación de hospital.",
    instructions:
      "Reza una vez con plena atención y devoción, trayendo a la mente a la persona y la intención que estás presentando ante María. El Memorare es lo suficientemente breve como para memorizarlo y rezarlo en cualquier parte — en el auto, durante una caminata, antes de dormir, en los momentos previos a cualquier tarea difícil. Para una intercesión más sostenida, reza nueve Memorares consecutivos seguidos (esta es la «novena al vuelo» que la Madre Teresa prefería para intenciones urgentes). Algunas tradiciones añaden un breve momento de silencio antes de rezar, nombrando la intención en voz alta o en el corazón. La oración también puede incorporarse como oración final al término de un Rosario más extenso o de una novena, sellando la petición con la confianza serena en el amor maternal de María. Las familias católicas suelen rezar el Memorare junto al lecho de alguien gravemente enfermo, al recibir un diagnóstico difícil, o durante el trabajo de parto. Por ser una oración breve cuyas palabras son antiguas y queridas, se ha convertido en una especie de respuesta espiritual de emergencia: una oración que acude espontáneamente a los labios cuando faltan otras palabras. Los niños pueden aprenderla desde muy pequeños, en cuanto puedan recitarla; es una de las oraciones más apropiadas para enseñar a un niño como «primera oración en momentos de dificultad». La versión latina original todavía es rezada por algunos atraídos a las formas tradicionales: «Memorare, O piissima Virgo Maria, non esse auditum a saeculo…»",
    patronSaint: "San Bernardo de Claraval",
    feastDay: null,
    source: "Traditional Spanish Catholic Memorare (Acordaos) text + Fr. Claude Bernard attribution per Catholic Encyclopedia. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── Round 2: 6 more prayers from PR #71 ────────────────────
  {
    prayerSlug: "novena-st-jude",
    name: "Novena a San Judas Tadeo",
    description:
      "San Judas Tadeo, llamado el Apóstol de la Esperanza, fue uno de los Doce y pariente del Señor, tradicionalmente considerado hermano de Santiago el Menor y primo de Jesús. Es nombrado en los Evangelios como uno de los apóstoles (Lucas 6:16) y es el autor de la breve Epístola de Judas que cierra la sección de cartas católicas del Nuevo Testamento — una carta que famosamente exhorta a los creyentes a «luchar fervientemente por la fe». Durante siglos, la devoción popular católica ha invocado a San Judas como patrono de las causas desesperadas y de los casos imposibles. Las razones que ofrece la tradición son prácticas: porque su nombre (Judas) se confundía fácilmente con Judas Iscariote, el traidor, su intercesión fue evitada por los cristianos ordinarios durante siglos — y así, dice el dicho, anhela ayudar a quien acude a él en verdadera necesidad. La devoción moderna a San Judas Tadeo fue popularizada en los Estados Unidos por los padres claretianos, quienes construyeron el Santuario Nacional de San Judas en Chicago en 1929 — en plena Gran Depresión — y el santuario sigue siendo uno de los sitios de peregrinación católica más visitados de Norteamérica. La devoción está fuertemente asociada con la práctica de publicar agradecimientos («Gracias, San Judas, por las oraciones respondidas») en los avisos clasificados de los periódicos, una costumbre que comenzó en la cultura católica estadounidense de mediados del siglo XX y que continúa en silencio hasta nuestros días. Esta novena es apropiada para enfermedad con pronóstico difícil, colapso económico, alejamiento familiar que parece sin remedio, infertilidad y cualquier situación que una persona experimenta como «más allá de toda esperanza».",
    instructions:
      "Reza una vez al día durante nueve días consecutivos. La estructura tradicional: comienza con la Señal de la Cruz; reza el texto de la novena a San Judas; concluye con un Padrenuestro, un Avemaría y un Gloria; nombra tu intención específica en silencio o en voz alta. Muchos católicos añaden tres Padrenuestros, Avemarías y Glorias adicionales en honor a la Santísima Trinidad al cierre de la oración de cada día. La novena puede rezarse en cualquier época del año, pero es especialmente apropiada en los nueve días previos a la fiesta de San Judas (28 de octubre, compartida con San Simón el Zelote) o cuando alguien enfrenta una situación que se siente «imposible». Una práctica complementaria tradicional es comprometerse, cuando la oración es escuchada, a agradecer públicamente a San Judas — ya sea mediante un agradecimiento publicado (la tradición de los avisos clasificados), una donación a un apostolado de San Judas, o simplemente fomentando la devoción a él dentro de la familia y la parroquia. El Santuario Nacional de San Judas de los Claretianos en Chicago acepta peticiones de intercesión por correo y en línea y mantiene una novena perpetua a San Judas que se ha rezado diariamente desde 1929. Si se omite un día de la novena, el consejo tradicional es comenzar de nuevo desde el día uno. La disposición de la oración importa: San Judas no es una máquina expendedora. La novena se reza con fe y abandono, confiando en que el Espíritu Santo conoce lo que el orante verdaderamente necesita y que los santos interceden por lo que es bueno, no siempre por lo que se quiere.",
    patronSaint: "San Judas Tadeo",
    feastDay: "28 de octubre",
    source: "USCCB Spanish + traditional Claretian National Shrine of St. Jude devotional sources (Chicago, founded 1929). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-divine-mercy",
    name: "Novena a la Divina Misericordia",
    description:
      "La Novena a la Divina Misericordia fue entregada por Jesús a Santa María Faustina Kowalska, religiosa polaca de la Congregación de las Hermanas de Nuestra Señora de la Misericordia, en una serie de revelaciones recogidas en su Diario: La Divina Misericordia en mi alma. Los escritos místicos de Faustina, suprimidos por un tiempo después de su muerte en 1938, fueron reivindicados por el Papa San Juan Pablo II — él mismo polaco y compatriota — quien la canonizó el 30 de abril de 2000 y estableció el Domingo de la Divina Misericordia (segundo domingo de Pascua) como fiesta para toda la Iglesia universal. La novena comienza el Viernes Santo y concluye en la vigilia del Domingo de la Divina Misericordia, reuniendo los ocho días de la Octava de Pascua en una sola intercesión sostenida. Cada uno de los nueve días, Jesús instruyó a Faustina, trae una categoría diferente de almas ante el trono de la misericordia: Día 1, toda la humanidad; Día 2, sacerdotes y religiosos; Día 3, almas devotas y fieles; Día 4, los que no creen; Día 5, las almas de los hermanos separados; Día 6, los humildes, sencillos y los niños; Día 7, las almas que veneran la Divina Misericordia; Día 8, las almas del purgatorio; Día 9, las almas tibias. Este patrón — comenzando con toda la humanidad, estrechándose a través de la familia de la Iglesia y cerrando con aquellos cuyos corazones son más fríos — encarna la amplitud de la misericordia que esta devoción proclama. El hogar espiritual de la novena es el Santuario de la Divina Misericordia en Łagiewniki, Cracovia, donde Faustina vivió, murió y reposa hoy, y donde una transmisión diaria en vivo de la coronilla a la Hora de la Misericordia (3:00 de la tarde) llega a millones en todo el mundo.",
    instructions:
      "Reza una vez al día durante nueve días consecutivos, tradicionalmente comenzando el Viernes Santo y terminando el sábado anterior al Domingo de la Divina Misericordia. Cada día tiene una intención única (especificada arriba) y una invocación inicial única que Jesús dictó a Santa Faustina; después de la apertura del día, la oración concluye con la Coronilla de la Divina Misericordia (consulta la entrada separada de la Coronilla para las instrucciones completas). La estructura tradicional de cada día: (1) Lee o recuerda la intención específica del día; (2) Reza la oración inicial que Jesús dio a Faustina para ese día; (3) Reza la Coronilla de la Divina Misericordia entera; (4) Concluye con una intención personal. La novena completa toma aproximadamente quince minutos por día. Aunque la novena está tradicionalmente vinculada a la ventana del Viernes Santo al Domingo de la Divina Misericordia de la Pascua, también puede rezarse en cualquier época del año por una intención privada, especialmente en momentos de crisis o por la conversión de un ser querido. El Santuario de la Divina Misericordia en Łagiewniki y el Santuario Nacional de la Divina Misericordia en Stockbridge, Massachusetts, ofrecen la recitación pública diaria de la coronilla a la Hora de la Misericordia (3:00 PM) y aceptan peticiones de intercesión por escrito. La coronilla puede rezarse a solas, en familia o en grupo; también es la oración que con más frecuencia ofrecen junto al lecho de los moribundos los capellanes de hospital católicos y los voluntarios de cuidados paliativos.",
    patronSaint: "Santa Faustina Kowalska",
    feastDay: "Domingo de la Divina Misericordia",
    source: "Diary: Divine Mercy in My Soul (St. Faustina) + canonical Spanish-language novena text published by the Marian Fathers (Stockbridge, MA). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-our-lady-perpetual-help",
    name: "Novena a Nuestra Señora del Perpetuo Socorro",
    description:
      "Nuestra Señora del Perpetuo Socorro es uno de los títulos marianos más queridos en la Iglesia Católica. La devoción se centra en un icono bizantino del siglo XV — escrito, en la tradición iconográfica, sobre madera de ciprés y mostrando al Niño Jesús sostenido en los brazos de María mientras los arcángeles Miguel y Gabriel se acercan, cada uno portando instrumentos de la Pasión (la cruz, la lanza, la esponja). El Niño Jesús vuelve su rostro hacia su Madre con aparente temor; una sandalia cuelga suelta de su pie, un detalle tradicionalmente leído como el Niño retrocediendo ante la Pasión anunciada y encontrando refugio contra el corazón de su Madre. El icono llegó a Roma en 1499 y fue venerado durante siglos antes de desaparecer durante las supresiones napoleónicas; fue redescubierto en 1862 y entregado por el Papa Pío IX a los padres redentoristas en 1866 con el encargo: «Hacedla conocer en todo el mundo». Los redentoristas lo han hecho. El icono cuelga ahora sobre el altar de la iglesia de San Alfonso en Roma y se veneran reproducciones en decenas de miles de parroquias en todo el mundo. La novena a Nuestra Señora del Perpetuo Socorro — compuesta y popularizada por los redentoristas — es una de las devociones marianas más rezadas en la Iglesia moderna. Su tono es el de la confianza infantil: el creyente, como el Niño Jesús en el icono, se vuelve al abrazo de María cuando tiene miedo. La novena es particularmente apropiada durante la enfermedad, dificultad en el embarazo, duelo, crisis familiar, y cualquier momento en que un alma busca el refugio silencioso de la intercesión maternal.",
    instructions:
      "Reza una vez al día durante nueve días consecutivos. La novena redentorista tradicionalmente acompaña la oración de cada día con el canto del himno «Madre de Cristo, Madre de Dios» o «Oh Madre del Perpetuo Socorro» — muchas parroquias todavía celebran servicios semanales de novena al Perpetuo Socorro los miércoles, en los que se cantan estos himnos. La estructura tradicional para la oración de cada día en casa: (1) Comienza con la Señal de la Cruz; (2) Reza la oración de la novena a Nuestra Señora del Perpetuo Socorro; (3) Concluye con tres Avemarías y una Salve; (4) Nombra tu intención específica. Algunas familias añaden un acto de consagración a María al final del noveno día, especialmente si la novena se rezó por una intención seria. La novena se reza apropiadamente en los días previos a la Fiesta de Nuestra Señora del Perpetuo Socorro (27 de junio), pero puede rezarse en cualquier momento. Muchos hogares católicos mantienen una copia del icono en una pared o en un pequeño altar en el hogar; venerar el icono mientras se reza la novena — encontrarse con los ojos de Cristo y su Madre mientras ellos se miran — es parte del patrón pastoral de la devoción. La novena es especialmente recomendada para madres que rezan por sus hijos, para quienes cuidan a los enfermos, y para cualquier persona abrumada por circunstancias que se sienten más allá de sus fuerzas.",
    patronSaint: "Nuestra Señora del Perpetuo Socorro",
    feastDay: "27 de junio",
    source: "Redemptorist tradition + Vatican.va Spanish + Pius IX's 1866 entrustment of the icon. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "litany-sacred-heart",
    name: "Letanías del Sagrado Corazón",
    description:
      "Las Letanías del Sagrado Corazón de Jesús son una de las seis letanías aprobadas por la Santa Sede para el uso litúrgico público en el Rito Latino. Compuestas en 1718 por sor Juana Magdalena Joly de la Orden de la Visitación en Dijon (miembro de la misma comunidad religiosa que dio a la Iglesia a Santa Margarita María Alacoque, la vidente de las apariciones del Sagrado Corazón en Paray-le-Monial), las letanías fueron refinadas y amplificadas durante el siglo siguiente a través del uso devocional entre las visitandinas, los jesuitas y la tradición devocional católica más amplia. El Papa León XIII dio a las letanías la aprobación formal para uso litúrgico público el 2 de abril de 1899 — el mismo año en que consagró toda la raza humana al Sagrado Corazón en su encíclica Annum Sacrum. Las letanías están estructuradas como treinta y tres invocaciones al Corazón de Cristo bajo distintos títulos — «Corazón de Jesús, formado por el Espíritu Santo en el seno de la Virgen Madre», «Corazón de Jesús, horno ardiente de caridad», «Corazón de Jesús, paciente y rico en misericordia», y así sucesivamente — correspondientes a los treinta y tres años de la vida terrena de Cristo. A cada invocación se le da la respuesta «Ten piedad de nosotros». El patrón de treinta y tres veces es contemplativo: el corazón del creyente, mediante la repetición sostenida, es atraído a las disposiciones del Corazón de Cristo — humildad, paciencia, misericordia, caridad. Las letanías son una de las devociones principales del Primer Viernes y se rezan tradicionalmente durante el mes de junio (mes del Sagrado Corazón), en la Novena al Sagrado Corazón, y en la Hora Santa de reparación que Cristo pidió a Santa Margarita María.",
    instructions:
      "Las letanías se rezan responsorialmente. Un líder pronuncia cada invocación («Corazón de Jesús, Hijo del Eterno Padre…») y la compañía reunida — familia, grupo pequeño, congregación parroquial — responde con la fórmula señalada. Las invocaciones iniciales utilizan el patrón del Kyrie («Señor, ten piedad / Cristo, ten piedad / Señor, ten piedad») y la invocación trinitaria al Dios Padre, Hijo y Espíritu Santo, cada una con la respuesta «Ten piedad de nosotros». Siguen las treinta y tres invocaciones al Corazón de Jesús, cada una con la misma respuesta «Ten piedad de nosotros». Las letanías concluyen con el Cordero de Dios (Agnus Dei) y un versículo-respuesta más una oración colecta al Sagrado Corazón. La duración total es de aproximadamente diez a quince minutos cuando se reza a un ritmo devocional sin prisa. Las letanías se rezan apropiadamente: en los Primeros Viernes (el día devocional tradicional del Sagrado Corazón, observado especialmente en asociación con la promesa de los «nueve primeros viernes» que Cristo hizo a Santa Margarita María); durante el mes de junio, mes del Sagrado Corazón; durante la Novena al Sagrado Corazón (los nueve días previos a la Solemnidad del Sagrado Corazón, viernes después del Corpus Christi); al final de una Hora Santa de adoración eucarística; en momentos de consagración familiar al Sagrado Corazón. Cuando se reza a solas, simplemente lee tanto la invocación como la respuesta en voz alta o en silencio. Muchas familias católicas guardan una copia impresa de las letanías cerca de una imagen de entronización del Sagrado Corazón en el hogar.",
    patronSaint: "Sagrado Corazón de Jesús",
    feastDay: "Viernes después del Corpus Christi",
    source: "Annum Sacrum (Leo XIII, 1899) + USCCB Spanish + Visitation Order devotional tradition. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "litany-blessed-virgin",
    name: "Letanías de la Santísima Virgen María (Letanías Lauretanas)",
    description:
      "Las Letanías de la Santísima Virgen María — conocidas tradicionalmente como Letanías Lauretanas — son las letanías marianas más antiguas y queridas de la Iglesia Latina. Las letanías toman su nombre común de la Santa Casa de Loreto en las Marcas italianas, donde los peregrinos las han rezado de manera continua desde finales de la Edad Media; la tradición sostiene que la pequeña casa de piedra en la que María recibió la Anunciación fue trasladada por los ángeles desde Nazaret hasta Loreto en el siglo XIII, y las letanías se convirtieron en la oración formal de esa peregrinación. El Papa Sixto V aprobó formalmente las letanías para uso litúrgico y devocional en 1587, otorgando indulgencias por su recitación pública. A lo largo de los siglos, los papas sucesivos han añadido invocaciones a medida que la comprensión de la Iglesia de la doctrina mariana ha madurado: el Papa Pío VII añadió «Auxilio de los Cristianos» en 1815 después de su liberación de la cautividad napoleónica; el Papa Pío IX añadió «Reina concebida sin pecado original» después de la definición de la Inmaculada Concepción en 1854; el Papa Pío XII añadió «Reina asunta al cielo» después de la definición de la Asunción en 1950; el Papa San Juan Pablo II añadió «Madre de la Iglesia» en 1980 y «Reina de las Familias» en 1995. Más recientemente, el Papa Francisco añadió «Madre de la Misericordia», «Madre de la Esperanza» y «Consuelo de los Migrantes» en 2020. La estructura de las letanías se mueve a través de tres categorías de invocaciones: títulos extraídos de la relación de María con la Trinidad («Santa Madre de Dios», «Madre de Cristo», «Madre de la Iglesia»), títulos extraídos de las virtudes y tipos marianos («Virgen prudentísima», «Espejo de justicia», «Rosa mística», «Torre de David»), y títulos extraídos de la realeza e intercesión de María («Reina de los Ángeles», «Reina de todos los Santos», «Reina de la Paz»). Los títulos acumulados forman juntos un retrato del lugar de María en la economía de la salvación tal como la Iglesia ha llegado a conocerla.",
    instructions:
      "Las letanías se rezan responsorialmente. Un líder pronuncia cada título de María («Santa María…», «Santa Madre de Dios…», «Santa Virgen de las vírgenes…») y la compañía reunida responde «Ruega por nosotros» a cada uno. Las letanías comienzan con el patrón del Kyrie y la invocación trinitaria; el cuerpo de las letanías es la larga secuencia de títulos marianos; las letanías se cierran con tres invocaciones al Cordero de Dios («Cordero de Dios que quitas el pecado del mundo, perdónanos / escúchanos / ten piedad de nosotros»), un versículo-respuesta, y una oración colecta a la Santísima Virgen. La duración total es de aproximadamente diez minutos cuando se reza a un ritmo devocional sin prisa. Las Letanías Lauretanas se rezan tradicionalmente: después del Santo Rosario (en muchas familias católicas este es el cierre del rosario diario); durante los meses marianos de mayo y octubre; al final de la novena mariana previa a las solemnidades marianas (la Inmaculada Concepción, la Asunción, Nuestra Señora del Rosario); en momentos de consagración familiar a María. Cuando se reza a solas, simplemente lee tanto el título como la respuesta en voz alta o en silencio. Las ceremonias de coronación de María en el mes de mayo — la práctica tradicional de las escuelas católicas de coronar una estatua de María con flores durante mayo — a menudo incorporan las Letanías Lauretanas como oración central. La versión latina original («Sancta Maria, ora pro nobis…») todavía se reza en muchas parroquias que mantienen un sólido repertorio devocional en latín junto al vernáculo.",
    patronSaint: "Santísima Virgen María",
    feastDay: null,
    source: "Sixtus V's 1587 approval + papal additions through Francis 2020 + USCCB Spanish-language Marian devotional texts. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "prayer-conversion",
    name: "Oración por la Conversión de un Ser Querido",
    description:
      "La oración católica por la conversión de un ser querido está arraigada en uno de los grandes testimonios pastorales de la historia cristiana: la larga y fiel oración de Santa Mónica por su hijo San Agustín. Mónica rezó por la conversión de su hijo a través de años de su persecución de la filosofía maniquea, a través de su deambular moral en Cartago y Roma, a través de sus propias lágrimas y el consejo que recibió de San Ambrosio de Milán («No es posible que perezca el hijo de tantas lágrimas»). Agustín fue bautizado en 387 a la edad de treinta y tres años; Mónica murió poco después en Ostia, habiendo vivido para ver lo que había pedido. Agustín registró su perseverancia en sus Confesiones (Libro IX), una de las autobiografías espirituales más leídas de la tradición occidental. El testimonio pastoral que Mónica encarna no es una garantía de resultado — la conversión de Agustín ocurrió en el tiempo de Dios, no en el de Mónica — sino una postura de fidelidad inquebrantable: que la oración del creyente por un ser querido es en sí misma una gracia, una participación en el propio deseo de Dios por esa alma, independientemente de cuándo o si la oración es visiblemente respondida. Esta oración es apropiada para: un cónyuge que ha dejado de practicar la fe; un hijo adulto que ha abandonado la Iglesia; un padre o madre que nunca ha sido bautizado; un amigo cuyo viaje interior hacia Cristo parece estancado o retrocediendo; cualquiera cuya conversión el orante experimenta como una herida abierta. También es apropiada como oración diaria para el largo arco — los diecisiete años de oración de Mónica por Agustín no son un mandato literal, sino un recordatorio de que este tipo de intercesión debe ser sostenida, no apresurada.",
    instructions:
      "Reza diariamente, idealmente a la misma hora y en la misma postura (de rodillas, ante un crucifijo o una imagen del Sagrado Corazón, en un altar doméstico) para que la disciplina de la oración se convierta en parte de la vida diaria en lugar de una reacción a un momento difícil. Nombra a la persona en voz alta en la oración donde el texto dice «(nombre)» — esto no es un encantamiento mágico sino un rechazo a abstraerla; la persona que amas tiene un nombre y traes ese nombre ante Dios. Después de la oración, dedica un minuto de silencio a sostenerla ante el Sagrado Corazón. Muchos católicos combinan esta oración con: (1) el ofrecimiento diario de pequeños sacrificios por la intención de la conversión del ser querido — ayunar de un alimento particular, abstenerse de un placer particular, aceptar una inconveniencia particular con paciencia; (2) una intención regular de Misa por la persona, especialmente el día de la fiesta de Santa Mónica (27 de agosto) o el día de la fiesta de San Agustín (28 de agosto); (3) la Novena a Santa Mónica o a San Agustín en esos días de fiesta; (4) la Coronilla de la Divina Misericordia a las 3:00 PM. La disposición de la oración importa: se ofrece en confianza, no en transacción. Dios conoce al ser querido mejor que el orante; la oración es una participación en el amor de Dios por esa persona, no un apalancamiento de Dios para producir un resultado. Cuando llega el desánimo — y llega, especialmente cuando pasan los años sin cambios visibles — el consejo tradicional es apoyarse con más fuerza en la intercesión de Santa Mónica y en el Sagrado Corazón, y recordar que la oración misma es parte de la misericordia de Dios para el ser querido, independientemente de cuándo o cómo sea escuchada.",
    patronSaint: "Santa Mónica",
    feastDay: "27 de agosto",
    source: "Augustine's Confessions Book IX + traditional Catholic devotion to St. Monica + USCCB Spanish-language pastoral resources. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
];
