import type { PrayerTranslationSeed } from "./types";

/**
 * Filipino / Tagalog (fil) translations of PrayerType content.
 *
 * Authoring conventions:
 *  - **Source tier**: CBCP (Catholic Bishops' Conference of the
 *    Philippines), Vatican.va Tagalog, Pauline Books & Media,
 *    SVD / Salesian publications.
 *  - **Variant**: macro-tag `fil` — Filipino, the standardized
 *    national language based on Tagalog. "tl" (ethnic Tagalog)
 *    macro-falls to `fil` via the Accept-Language negotiator.
 *    Bisaya / Cebuano / Ilocano are NOT covered here.
 *  - **Catholic register**: Filipino Catholic devotional speech
 *    code-switches naturally with English — "novena", "rosary",
 *    "PrayerTrain", "chaplet" stay English. Over-translation reads
 *    stiff. "Ipanalangin natin para kay [name]" is the natural
 *    devotional formula.
 *  - **Brand names stay English**: `PrayerTrain`, `Surrender Novena`.
 *  - **`prayerText` left null** — canonical Tagalog prayer wording
 *    should be drawn from CBCP / Vatican.va sources in a separate
 *    focused pass. Helper falls back to English prayer text under
 *    the Tagalog description + instructions.
 */
export const filTranslations: PrayerTranslationSeed[] = [
  {
    prayerSlug: "novena-sacred-heart",
    name: "Nobena sa Banal na Puso ni Hesus",
    description:
      "Ang Nobena sa Banal na Puso ni Hesus ay isa sa pinakamamahal na debosyon sa Simbahang Katoliko, ipinanganak mula sa mga pagpapakita ni Hesus kay Santa Margarita Maria Alacoque sa Paray-le-Monial, France, noong 1673-1675. Sa mga pangitain na ito, ipinakita ni Kristo ang lalim ng Kanyang pag-ibig sa sangkatauhan, sinisimbolo ng Kanyang Pusong dinaluyan ng espada at nakoronahan ng mga tinik, at hiniling Niya na ang pag-ibig na ito ay parangalan sa pamamagitan ng debosyon sa Kanyang Banal na Puso. Ang nobena ay tumatakbo sa siyam na magkakasunod na araw ng panalangin (ang bilang na siyam ay nagpapaalala sa siyam na araw na ginugol ng mga apostol at ni Maria sa panalangin sa pagitan ng Pag-akyat at Pentekostes), at karaniwang inialay nang may pagtitiwala sa habag ni Kristo sa mga nagdurusa. Lalo itong angkop sa mga panahon ng karamdaman, paghihirap sa pamilya, espirituwal na pagkalumbay, o mga patuloy na intensyon na hindi pa nakatatanggap ng kasagutan. Ang Banal na Puso ay hindi lamang sagisag; ito ang totoong pisikal na puso ni Kristo, ganap na tao at ganap na Diyos, ang bukal ng Kanyang walang-hanggang pag-ibig. Inilarawan ng encyclical na Haurietis Aquas ni Papa Pio XII (1956) ang Banal na Puso bilang «trono ng habag» at pinagtibay ang sentral na lugar ng debosyong ito sa buhay ng Simbahan. Ang mga prayer warrior na nag-aalay ng nobenang ito ay sumasama sa mga siglo ng mga Katoliko na nagtiwala sa Sugatang Puso ng Tagapagligtas.",
    prayerText:
      "O Banalang-banal na Puso ni Hesus, bukal ng bawat biyaya, sinasamba Kita, iniibig Kita, at sa malalim na pagsisisi sa aking mga kasalanan ay inihahandog ko sa Iyo itong aking abang puso. Gawin Mo akong mapagpakumbaba, matiyaga, malinis, at lubos na masunurin sa Iyong kalooban. Ipagkaloob Mo, Mabuting Hesus, na ako ay mabuhay sa Iyo at para sa Iyo. Pangalagaan Mo ako sa gitna ng panganib. Aliwin Mo ako sa aking mga paghihirap. Bigyan Mo ako ng kalusugan ng katawan, tulong sa aking mga pang-temporal na pangangailangan, ng Iyong basbas sa lahat ng aking ginagawa, at ng biyaya ng banal na kamatayan. Amen.",
    instructions:
      "Manalangin minsan sa isang araw sa loob ng siyam na magkakasunod na araw, halos sa parehong oras araw-araw. Pumili ng isang tahimik na lugar at simulan sa Tanda ng Krus. Ang tradisyonal na istraktura ay: (1) isang panimulang panalangin, kadalasang «O Sakratisimong Puso ni Hesus, sa Iyo ko ipinagkakatiwala ang lahat»; (2) ang teksto mismo ng nobena; (3) isang Ama Namin, Aba Ginoong Maria, at Luwalhati; (4) isang personal na intensyon na binabanggit nang malakas o sa katahimikan. Maraming nagdaragdag ng Litanya sa Banal na Puso sa huling araw, o nagdadasal ng nobena kasama ng debosyon sa Unang Biyernes — tumatanggap ng Banal na Komunyon sa siyam na sunud-sunod na Unang Biyernes gaya ng hiniling mismo ni Kristo kay Santa Margarita Maria. Ang nobena ay maaaring idasal sa anumang panahon ng taon, ngunit lalo itong angkop sa buwan ng Hunyo (ang Buwan ng Banal na Puso), sa mga araw na nauuna sa Kapistahan ng Banal na Puso (Biyernes pagkatapos ng Corpus Christi), o sa tuwing hinaharap ng isang tao ang mahirap na sandali. Kung makaligtaan ang isang araw, ang tradisyonal na payo ay magsimulang muli mula sa unang araw kaysa lumaktaw; ang disiplina ng sunud-sunod na panalangin ay bahagi mismo ng grasya ng debosyon. Ang ilan ay nagdarasal para sa isang partikular na tao bawat araw ng nobena; ang iba ay nag-aalay ng lahat ng siyam na araw para sa isang intensyon.",
    patronSaint: "Santa Margarita Maria Alacoque",
    feastDay: "Biyernes pagkatapos ng Corpus Christi",
    source:
      "CBCP-approved Tagalog prayer collections + Vatican.va Tagalog materials + traditional Filipino Catholic devotional sources for the Sacred Heart novena. Historical claims verified against Haurietis Aquas (Pius XII, 1956) and the published account of the apparitions at Paray-le-Monial. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-st-joseph",
    name: "Nobena kay San Jose",
    description:
      "Si San Jose, ang inaampong ama ni Hesus at malinis na asawa ng Mahal na Birheng Maria, ay isa sa pinakamamahal na tagapamagitan sa tradisyong Katoliko. Bagama't walang naitatala ang Banal na Kasulatan na salita mula sa kanya, ang kanyang katapatan ay walang pag-aalinlangan: pinangalagaan niya ang Banal na Pamilya sa pagtakas sa Egipto, sinuportahan sila sa pamamagitan ng paggawa ng kanyang mga kamay, at itinuro kay Hesus ang trabaho ng karpintero at ang paraan ng tapat na pagkalalaki. Hinirang siya ni Papa Pio IX bilang Patron ng Simbahang Pansandaigdigan noong 1870, at idineklara ni Papa Francisco ang panahong 2020-2021 bilang Taon ni San Jose sa pamamagitan ng apostolikong sulat na Patris Corde («Sa Pusong Pang-ama»). Ang nobenang ito ay umiinom mula sa mahabang tradisyong Katoliko ng pagkilala kay San Jose bilang patron ng mga ama, mga manggagawa, mga pamilya, mga usapin sa real estate, at ng mabuting kamatayan — ang apat na haligi ng kanyang ministeryo sa lupa. Tinatawagan siya lalo na sa mga sandali ng paghihirap sa pera, hindi pagkakaunawaan sa pamilya, mga problema sa trabaho, at sa pagdidiskimini ng bokasyon. Maraming Katoliko ang nakikipagsapi sa nobena sa mga araw na nauuna sa alinman sa kanyang mga kapistahan: ika-19 ng Marso (Dakilang Kapistahan ni San Jose, Asawa ng Mahal na Birhen) o ika-1 ng Mayo (San Jose Manggagawa, itinatag ni Papa Pio XII noong 1955 upang banalin ang gawaing pantao). Sumulat si Santa Teresa ng Avila: «Sa iba pang mga santo ay tila pinagkalooban ng Panginoon ng biyaya na tulungan tayo sa ilang partikular na pangangailangan; ngunit sa maluwalhating santong ito, alam ko sa karanasan, pinagkalooban Niya ng biyaya upang tulungan tayo sa lahat».",
    prayerText:
      "O San Jose, na ang proteksyon ay napakadakila, napakalakas, napakabilis sa harap ng trono ng Diyos, sa Iyo inilalagay ko ang lahat ng aking interes at mithiin. O San Jose, tulungan Mo ako sa pamamagitan ng Iyong makapangyarihang pamamagitan at ipagkaloob sa akin mula sa Iyong banal na Anak ang lahat ng espirituwal na biyaya sa pamamagitan ni Hesukristong aming Panginoon; upang sa pagkakaroon dito sa lupa ng Iyong makalangit na kapangyarihan, ako'y makapag-alay ng aking pasasalamat at parangal sa pinakamapagmahal sa mga Ama. Amen.",
    instructions:
      "Manalangin minsan sa isang araw sa loob ng siyam na magkakasunod na araw. Ang tradisyonal na istraktura: simulan sa Tanda ng Krus; idasal ang teksto ng nobena; tapusin sa isang Ama Namin, Aba Ginoong Maria, at Luwalhati; at banggitin ang iyong tiyak na intensyon. Ang ilang Katolikong pamilya ay nagdaragdag ng Litanya kay San Jose o pitong Ama Namin, Aba Ginoong Maria, at Luwalhati bilang pagpaparangal sa Pitong Hapis at Pitong Galak ni San Jose — isang tradisyonal na debosyon na nakakawing sa kanyang masaya at malungkot na mga karanasan sa buhay ng Banal na Pamilya. Para sa mga pamilyang nagdidiskimini ng malaking desisyon sa buhay (pagpapalit ng trabaho, paglilipat, pag-aasawa), kaugalian ang magsimula ng nobena siyam na araw bago kailangang gawin ang desisyon, hinihiling ang pagitan ni San Jose para sa kalinawan at sa biyaya na tanggapin ang kalooban ng Diyos. Ang nobena ay tradisyonal ding idinadasal sa buwan ng Marso (Buwan ni San Jose) o kasabay ng popular na praktika ng paglilibing ng estatwa ni San Jose kaugnay sa pagbebenta ng bahay — isang katutubong tradisyon na nagbibigay-diin sa tahimik na pagtitiwala sa halip na pamahiin. Manalangin man para sa pagdidiskimini ng bokasyon, pang-ekonomyang probisyon, paghilom ng pamilya, o mabuting kamatayan (isa sa apat na tradisyonal na hangarin ng debosyong ito), ang espiritu ay dapat ng tahimik at masipag na pagtitiwala — ang mismong disposisyon na ipinakita ni San Jose sa Banal na Kasulatan.",
    patronSaint: "San Jose",
    feastDay: "Marso 19 / Mayo 1",
    source:
      "Patris Corde (Francis, 2020) + CBCP materials in Tagalog + traditional Filipino Catholic devotional sources for the St. Joseph novena. The St. Teresa of Ávila quotation is from her autobiography (chapter 6). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "holy-rosary",
    name: "Ang Banal na Rosaryo",
    description:
      "Ang Banal na Rosaryo ay ang sentral na debosyong Marian ng Simbahang Katoliko — isang panalanging kontemplatibo kung saan ang naniniwala ay nagninilay sa mga dakilang misteryo ng buhay, kamatayan, at muling pagkabuhay ni Kristo habang nagdarasal ng paulit-ulit na dekada ng Aba Ginoong Maria. Ang Rosaryo, ayon sa kanyang anyo ngayon, ay nahubog sa loob ng mga siglo; pinaniniwalaang ibinigay ng Mahal na Birheng Maria ang Rosaryo kay Santo Domingo noong 1208 bilang isang espirituwal na sandata laban sa heresyang Albigensian, at ang istraktura ng labinlimang misteryo ay kinodipika ni Papa San Pio V noong 1569. Noong 2002, idinagdag ni Papa San Juan Pablo II ang mga Maluwalhating Misteryo (Mga Misteryo ng Liwanag) sa kanyang apostolikong sulat na Rosarium Virginis Mariae, dinala ang kabuuan sa dalawampung misteryo na nakapangkat sa apat na hanay. Bawat dekada ay isang pagninilay: habang gumagalaw ang mga daliri sa mga butil at sinasambit ng mga labi ang Aba Ginoong Maria, nagtatambay ang isip sa isang sandali mula sa mga Ebanghelyo — ang Pagbabalita, ang Pagpapako sa Krus, ang Muling Pagkabuhay, ang Pagbabagong-anyo. Ang Rosaryo ay hindi walang-kabuluhang pag-uulit (Mateo 6:7) kundi isang paaralan ng pagninilay, na nagpapahintulot sa ritmo ng mga panalangin na palayain ang isip upang magnilay sa mga misteryo ng kaligtasan. Mula kay Papa Leon XIII (na ang labing-isang encyclical sa Rosaryo ay nananatiling mga magisterial reference) hanggang kay Francisco, hinikayat ng mga Papa ang mga tapat na magdasal ng Rosaryo araw-araw. Ito ang panalangin na inialay sa Lourdes, Fatima, at sa hindi mabilang na iba pang pagpapakita ng Birhen, at ang panalanging pinaka-karaniwang idinadasal ng mga Katolikong pamilya na nagtitipon sa tabi ng kama ng maysakit o ng libingan.",
    instructions:
      "Ang buong Rosaryo ay binubuo ng limang dekada, karaniwang idinadasal sa loob ng halos dalawampung minuto. Simulan sa Tanda ng Krus at ang Sumasampalataya sa krusipiho. Sa unang malaking butil, idasal ang Ama Namin; sa bawat isa sa tatlong maliliit na butil na sumusunod, idasal ang isang Aba Ginoong Maria (para sa pagdagdag ng tatlong teologikong birtud — pananampalataya, pag-asa, at pag-ibig); sa kasunod na malaking butil, idasal ang Luwalhati. Pagkatapos ay ipahayag ang unang misteryo nang malakas at magnilay sa kahulugan nito; idasal ang Ama Namin sa malaking butil, sampung Aba Ginoong Maria sa sampung maliliit na butil (isa kada butil) habang patuloy na nagninilay sa misteryo, pagkatapos ay Luwalhati at ang Panalangin sa Fatima («O Hesus ko, patawarin Mo kami sa aming mga kasalanan, ilayo Mo kami sa apoy ng impyerno…»). Ulitin nang apat pang dekada, na binabanggit ang bawat misteryo. Tapusin sa Aba Po, Santa Mariang Hari at ang panalangin ng Rosaryo. Ang apat na hanay ng mga misteryo ay tradisyonal na idinadasal: Misteryo ng Tuwa tuwing Lunes at Sabado (ang Pagbabalita, ang Pagdalaw, ang Pagsilang, ang Pag-aalay sa Templo, ang Pagkahanap sa Templo); Misteryo ng Hapis tuwing Martes at Biyernes (ang Paghihirap sa Hardin, ang Paghagupit, ang Pagkokorona ng mga Tinik, ang Pagpasan ng Krus, ang Pagpako sa Krus); Misteryo ng Luwalhati tuwing Miyerkules at Linggo (ang Muling Pagkabuhay, ang Pag-akyat sa Langit, ang Pentekostes, ang Pag-akyat ng Birhen, ang Pagkokorona kay Maria); Misteryo ng Liwanag tuwing Huwebes (ang Pagbibinyag, ang Kasalan sa Cana, ang Pagpapahayag ng Kaharian, ang Pagbabagong-anyo, ang Pag-tatatag ng Eukaristiya). Para sa pagsakop ng isang PrayerTrain, ang isang dekada — o kahit isang Aba Ginoong Maria na inialay nang may intensyon — ay isa ring tunay na alay ng Rosaryo.",
    patronSaint: "Mahal na Birhen ng Rosaryo",
    feastDay: "Oktubre 7",
    source:
      "Rosarium Virginis Mariae (St. John Paul II, 2002) + Leo XIII's eleven rosary encyclicals + CBCP-approved Tagalog Rosary prayer texts. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "chaplet-divine-mercy",
    name: "Koronilya ng Banal na Awa",
    description:
      "Ang Koronilya ng Banal na Awa ay ibinigay ni Hesus kay Santa Maria Faustina Kowalska, isang Polish na madre, sa isang serye ng mga pagpapahayag sa pagitan ng 1931 at 1938 na naitala sa kanyang Diary: Divine Mercy in My Soul. Ang koronilya ay isang makapangyarihang panalangin ng pamamagitan na inialay para sa pagbabalik-loob ng mga makasalanan, sa kaginhawaan ng mga naghihingalo, at sa habag ng Diyos sa buong mundo. Sinabi ni Hesus kay Faustina na sinumang magdarasal ng koronilyang ito ay tatanggap ng «malaking habag sa oras ng kamatayan» — at na siya'y lalo na nasisiyahan sa panalanging ito kapag idinasal sa 3:00 ng hapon, ang Oras ng Habag (ang oras ng Kanyang kamatayan sa Kalbaryo). Ang koronilya ay idinadasal gamit ang isang ordinaryong rosaryo, na ginagawang madaling makuha sa sinumang may rosaryo, at tumatagal ng halos sampung minuto. Ang debosyon sa Banal na Awa ay pinigil sa loob ng maraming taon, ngunit ang Papa San Juan Pablo II — na isang Polish at kapwa-bayan ni Santa Faustina — ay nakanonisa siya noong Abril 30, 2000, at itinatag ang Linggo ng Banal na Awa (ikalawang Linggo ng Pasko ng Pagkabuhay) bilang isang kapistahan para sa buong Simbahan. Ang Koronilya ng Banal na Awa ay naging isa sa pinaka-malawak na ipinagdarasal na debosyon sa modernong Simbahan, lalo na pinahahalagahan ng mga hospital chaplain, mga boluntaryo sa hospice, at ng mga nagdarasal para sa pagbabalik-loob ng mga mahal sa buhay. Ito ang pang-araw-araw na panalangin sa National Shrine of the Divine Mercy sa Stockbridge, Massachusetts, at sa Sanctuary of Divine Mercy sa Łagiewniki, Kraków — ang lugar kung saan namuhay, namatay, at ngayon ay nakahimlay si Faustina.",
    prayerText:
      "Walang-hanggang Ama, iniaalay ko sa Iyo ang Katawan at Dugo, Kaluluwa at Pagka-Diyos ng Iyong kasintang Anak, ang aming Panginoong Hesukristo, bilang pagbabayad-puri sa aming mga kasalanan at sa kasalanan ng buong mundo. Alang-alang sa Kanyang mapighating Pagpapakasakit, kaawaan Mo kami at ang buong mundo.",
    instructions:
      "Gamit ang isang ordinaryong limang-dekadang rosaryo, simulan sa Tanda ng Krus, isang Ama Namin, isang Aba Ginoong Maria, at ang Sumasampalataya sa krusipiho at panimulang butil. Sa bawat isa sa limang malalaking butil (kung saan kadalasang idinadasal ang Ama Namin), idasal: «Walang-hanggang Ama, inialay ko sa Iyo ang Katawan at Dugo, Kaluluwa at Pagka-Diyos ng Iyong pinakamamahal na Anak, ang aming Panginoong Hesukristo, bilang katubusan ng aming mga kasalanan at ng buong mundo». Sa bawat isa sa sampung maliliit na butil ng bawat dekada, idasal: «Alang-alang sa Kanyang mahapdi na Paghihirap, kaawaan Mo kami at ang buong mundo». Pagkatapos ng limang dekada, tapusin sa pamamagitan ng paulit-ulit na pagdarasal ng tatlong beses: «Banal na Diyos, Banal na Makapangyarihan, Banal na Walang-kamatayan, kaawaan Mo kami at ang buong mundo». Lalong makapangyarihan ang koronilya kapag idinasal sa 3:00 ng hapon (ang Oras ng Habag), sa tabi ng kama ng mga naghihingalo, sa siyam na araw bago ang Linggo ng Banal na Awa (ang Nobena ng Banal na Awa, nagsisimula sa Biyernes Santo), at sa mga sandali ng personal na pighati o takot. Maaari itong idasal nang tahimik, malakas, mag-isa, o nang kasama ng grupo. Maraming parokya ang lingguhang nagdadasal ng koronilya, kadalasan tuwing Biyernes bilang pag-alala sa Paghihirap ni Kristo. Ang mga Katoliko na nagdarasal para sa pagbabalik-loob o tahimik na kamatayan ng isang mahal sa buhay ay madalas nakikipag-sapi na magdasal ng koronilya araw-araw sa loob ng isang pangmatagalang panahon — isang buwan, ang tagal ng isang karamdaman, ang panahon bago ang isang malaking desisyon. Ang koronilya ay natural na umaalinsunod sa pagdalo sa Nobena ng Banal na Awa mula sa Biyernes Santo hanggang sa Linggo ng Banal na Awa.",
    patronSaint: "Santa Faustina Kowalska",
    feastDay: "Linggo ng Banal na Awa",
    source:
      "Diary: Divine Mercy in My Soul (St. Faustina Kowalska) + canonical chaplet text as approved by the Holy See after St. John Paul II's canonization of Faustina (April 30, 2000). CBCP-approved Tagalog renderings of the chaplet text. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "memorare",
    name: "Ang Memorare (Alalahanin)",
    description:
      "Ang Memorare ay isang maikli ngunit pambihirang makapangyarihang panalangin ng pagtitiwala sa pamamagitan ng Mahal na Birheng Maria. Kinukuha nito ang pangalan mula sa unang Latin na salita ng teksto, Memorare («Alalahanin»), at sa kasalukuyang anyo nito ay iniuugnay kay Pe. Claude Bernard, isang Pranses na pari noong ika-17 siglo na kilala bilang «ang Mahirap na Pari» dahil sa kanyang apostolado sa mga bilanggo at sa mga naghihingalo. Naging popular ang panalangin sa pamamagitan ng pamamahagi ni Pe. Bernard ng mahigit 200,000 leaflet sa Paris bago ang Rebolusyon, bagaman ang mga ugat ng debosyon ay mas matanda — malamang na sa isang mas mahabang panalangin na iniuugnay kay San Bernardo ng Clairvaux (1090-1153), ang dakilang abad Cistercian at Doktor ng Simbahan na ang debosyong Marian ay nag-hubog sa kabanalan ng Kanluran. Ang istraktura ng panalangin ay isang matiwasay na pagsamo: kinikilala nito ang pandaigdigang pagiging ina ni Maria («O Birhen ng mga birhen, aking Ina»), tumutukoy sa hindi nasisirang tradisyon ng kanyang pamamagitan («hindi pa naririnig kailanman na ang sinumang tumakbo sa iyong proteksiyon… ay iniwan na walang tulong»), at nagtatapos sa isang mapagkumbabang panalangin («sa iyong habag pakinggan at sagutin mo ako»). Pinatotohanan ng mga santo sa buong mga siglo ang kapangyarihan nito: si Mother Teresa ng Calcutta ay nagdarasal ng siyam na sunud-sunod na Memorare araw-araw — ang tinatawag niyang «flying novena» — kapag may kailangan siyang mabilisan. Ang Memorare ay ang Katolikong panalangin ng huling pag-asa, idinadasal sa mga sandali ng matinding pangangailangan, sa tabi ng kama ng mga naghihingalo, sa kapilya bago ang isang mahirap na pag-uusap, o ibinubulong habang ang magulang ay naghihintay ng balita mula sa silid ng ospital.",
    prayerText:
      "Alalahanin Mo, O kaibig-ibig na Birheng Maria, na kailanman ay hindi pa narinig na ang sinumang sumalig sa Iyong proteksyon, humingi ng Iyong tulong, o nagpasakop sa Iyong pamamagitan ay napabayaan. Sa pagtitiwalang ito, ako'y lumalapit sa Iyo, O Birhen ng mga Birhen, aking Ina; sa Iyo ako'y pumupunta, sa harap Mo ako'y tumatayo, makasalanan at malungkot. O Ina ng Salitang Nagkatawang-tao, huwag Mong hamakin ang aking mga panalangin, kundi sa Iyong awa ay dinggin at sagutin Mo ako. Amen.",
    instructions:
      "Manalangin minsan nang may buong atensyon at debosyon, tinatawag sa isip ang tao at intensyon na inihaharap mo kay Maria. Sapat ang ikli ng Memorare upang maisaulo at maidasal kahit saan — sa kotse, sa paglalakad, bago matulog, sa mga sandali bago ang anumang mahirap na gawain. Para sa isang mas sustained na pamamagitan, magdasal ng siyam na sunud-sunod na Memorare (ito ang «flying novena» na pinaboran ni Mother Teresa para sa mga mabilisang intensyon). Ang ilang tradisyon ay nagdaragdag ng maikling sandali ng katahimikan bago magdasal, binabanggit ang intensyon nang malakas o sa puso. Maaari ring isama ang panalangin bilang panghuling panalangin sa pagtatapos ng mas mahabang Rosaryo o nobena, sinusuhulan ang pagsamo ng matiwasay na pagtitiwala sa pag-ibig ng ina ni Maria. Madalas idinadasal ng mga Katolikong pamilya ang Memorare sa tabi ng kama ng isang malubhang maysakit, sa balita ng isang mahirap na diagnosis, o sa panahon ng panganganak. Dahil maikli ang panalangin at ang mga salita ay mga sinaunang at minamahal, naging isang uri ng espirituwal na tugon sa emergency — isang panalangin na natural na lumalapit sa mga labi kapag wala nang ibang salita. Maaaring turuan ang mga bata ng panalangin sa abot ng kanilang makakaya na maisaulo ito; isa ito sa mga pinaka-angkop na panalangin upang ituro sa isang bata bilang isang «unang panalangin ng kaguluhan». Ang orihinal na Latin ay paminsan-minsan pa rin idinadasal ng mga nais sa mga tradisyonal na anyo: «Memorare, O piissima Virgo Maria, non esse auditum a saeculo…»",
    patronSaint: "San Bernardo ng Clairvaux",
    feastDay: null,
    source:
      "CBCP-approved Tagalog devotional text of the Memorare + traditional Filipino Catholic prayer books. Historical attribution to Fr. Claude Bernard verified against the Catholic Encyclopedia. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── Round 2: 6 more prayers from PR #71 ────────────────────
  {
    prayerSlug: "novena-st-jude",
    name: "Nobena kay San Judas Tadeo",
    description:
      "Si San Judas Tadeo, tinatawag na Apostol ng Pag-asa, ay isa sa Labindalawang Apostol at kamag-anak ng Panginoon. Siya'y binanggit sa mga Ebanghelyo bilang isa sa mga apostol (Lucas 6:16) at siya ang may-akda ng maikling Liham ni Judas. Sa mga siglo, hinanap ng popular na debosyong Katoliko si San Judas bilang patron ng mga desperadong sitwasyon at imposibleng kalagayan. Ang mga dahilang ibinigay ng tradisyon ay praktikal: dahil ang kanyang pangalan ay madaling maipagkamali kay Judas Iscariote, ang taksil, ang kanyang pamamagitan ay iniwasan ng karaniwang mga Kristiyano sa loob ng mga siglo — at kaya, sabi ng kasabihan, siya'y naghahangad tulungan ang sinumang lumalapit sa kanya sa tunay na pangangailangan. Ang modernong debosyon kay San Judas Tadeo ay pinasikat sa Estados Unidos ng mga padre Claretian, na nagtayo ng National Shrine of St. Jude sa Chicago noong 1929 sa kasagsagan ng Great Depression. Sa mga Filipinong-Amerikano, ang debosyon kay San Judas ay malakas. Ang nobenang ito ay angkop para sa karamdaman na may mahirap na prognosis, paghirap sa pananalapi, paghihiwalay sa pamilya na tila walang solusyon, kawalang-anak at anumang sitwasyon na nararamdaman ng isang tao na «lampas sa pag-asa».",
    prayerText:
      "Banalang-banal na apostol, San Hudas Tadeo, tapat na lingkod at kaibigan ni Hesus, pandaigdigang pinararangalan at tinatawagan ka ng Simbahan bilang patron ng pag-asa. Maaari ba'y mamagitan ka para sa akin. Gamitin Mo ang partikular na pribilehiyong ibinigay sa Iyo upang magdala ng pag-asa, kaaliwan, at tulong sa mga lugar na pinakakailangan. Tulungan Mo ako sa aking malaking pangangailangang ito upang aking matanggap ang aliw at tulong ng langit habang nakikipagbuno ako sa aking mga pagsubok, partikular sa (banggitin ang intensyon). Pinupuri ko ang Diyos kasama Mo at sa lahat ng mga santo magpakailanman. Nangangako ako, mapalad na San Hudas, na laging maaalala ang malaking pabor na ito, laging parangalan Ka bilang aking natatangi at makapangyarihang patron, at masuyong hikayatin ang debosyon sa Iyo. Amen.",
    instructions:
      "Manalangin minsan sa isang araw sa loob ng siyam na magkakasunod na araw. Ang tradisyonal na istraktura: simulan sa Tanda ng Krus; idasal ang teksto ng nobena kay San Judas; tapusin sa isang Ama Namin, Aba Ginoong Maria, at Luwalhati; banggitin ang iyong tiyak na intensyon. Ang nobena ay maaaring idasal sa anumang panahon ng taon, ngunit lalo itong angkop sa siyam na araw na nauuna sa kapistahan ni San Judas (Oktubre 28). Isang tradisyonal na karagdagang gawain ay magpasya, kapag pinakinggan ang panalangin, na pasalamatan sa publiko si San Judas.",
    patronSaint: "San Judas Tadeo",
    feastDay: "Oktubre 28",
    source: "CBCP Tagalog + Claretian National Shrine (Chicago, 1929). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-divine-mercy",
    name: "Nobena sa Banal na Awa",
    description:
      "Ang Nobena sa Banal na Awa ay ibinigay ni Hesus kay Santa Maria Faustina Kowalska, Polish na madre, sa isang serye ng mga paghahayag na naitala sa kanyang Diary: Divine Mercy in My Soul. Ang Papa San Juan Pablo II ay nakanonisa siya noong Abril 30, 2000 at nagtatag ng Linggo ng Banal na Awa bilang kapistahan para sa buong Simbahan. Nagsisimula ang nobena sa Biyernes Santo at nagtatapos sa bisperas ng Linggo ng Banal na Awa. Bawat isa sa siyam na araw ay nagdadala ng iba't ibang kategorya ng mga kaluluwa sa harap ng trono ng awa.",
    prayerText:
      "Naghingalo Ka, Jesus, ngunit ang bukal ng buhay ay umagos para sa mga kaluluwa, at ang karagatan ng awa ay nabuksan para sa buong mundo. O Bukal ng Buhay, hindi-masusukat na Awa ng Diyos, balutin Mo ang buong mundo at ibuhos Mo ang Iyong sarili sa amin. O Dugo at Tubig na umagos mula sa Puso ni Hesus bilang bukal ng awa para sa amin, nagtitiwala ako sa Iyo!",
    instructions:
      "Manalangin minsan sa isang araw sa loob ng siyam na magkakasunod na araw, tradisyonal na nagsisimula sa Biyernes Santo. Bawat araw ay may natatanging intensyon at pambungad na panalangin. Pagkatapos ng pagbubukas, nagtatapos ang panalangin sa Koronilya ng Banal na Awa. Ang buong nobena ay tumatagal ng halos labinglimang minuto bawat araw.",
    patronSaint: "Santa Maria Faustina Kowalska",
    feastDay: "Linggo ng Banal na Awa",
    source: "Diary: Divine Mercy in My Soul (St. Faustina) + CBCP Tagalog. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-our-lady-perpetual-help",
    name: "Nobena sa Ina ng Laging Saklolo",
    description:
      "Ang Ina ng Laging Saklolo (Our Lady of Perpetual Help) ay isa sa pinakamamahal na pamagat na Marian sa Simbahang Katoliko. Ang debosyon ay nakatuon sa isang Byzantine icon mula sa ika-15 siglo na nagpapakita kay Hesukristo Bata na hawak sa mga bisig ni Maria habang lumalapit ang mga arkanghel na sina Miguel at Gabriel, bawat isa ay may dala-dalang mga kasangkapan ng Pagdurusa. Ipinagkatiwala ni Papa Pius IX ang icon sa mga Redemptorist fathers noong 1866. Sa Pilipinas, ang debosyon ay napaka-malakas, partikular sa pamamagitan ng mga Redemptorist parishes; ang Baclaran Church (National Shrine of Our Mother of Perpetual Help) sa Parañaque ay isa sa pinakamalaking Marian shrine sa Asia at host sa lingguhang Wednesday novena na dinaluhan ng libu-libo.",
    prayerText:
      "O Ina ng Laging Saklolo, ipagkaloob Mong palagi kong matatawagan ang Iyong pinaka-makapangyarihang pangalan, na ay tagapag-ingat ng mga buhay at kaligtasan ng mga naghihingalo. O pinakadalisay na Maria, o pinakamatamis na Maria, nawa ang Iyong pangalan ay palaging nasa aking mga labi mula ngayon. Huwag Kang magtagal, O Mapalad na Maria, na tulungan ako tuwing tinatawagan kita, sapagkat sa lahat ng aking mga pangangailangan, sa lahat ng aking mga tukso, hindi ako titigil sa pagtawag sa Iyo, palaging inuulit ang Iyong sagradong pangalan. O anong aliw, anong tamis, anong pagtitiwala, anong damdamin ang pumupuno sa aking kaluluwa kapag binibigkas ko ang Iyong sagradong pangalan o kahit lamang pag-iisipan Kita. Amen.",
    instructions:
      "Manalangin minsan sa isang araw sa loob ng siyam na magkakasunod na araw. Sa Pilipinas, ang Wednesday Perpetual Help novena ay ginaganap sa libu-libong parokyang Katoliko, lalo na sa Baclaran. Ang tradisyonal na istraktura: (1) Tanda ng Krus; (2) Idasal ang panalangin ng nobena; (3) Tapusin sa tatlong Aba Ginoong Maria at Aba Po Santa Mariang Hari; (4) Banggitin ang iyong intensyon.",
    patronSaint: "Ina ng Laging Saklolo",
    feastDay: "Hunyo 27",
    source: "Redemptorist tradition + Baclaran Church (Parañaque) + Pius IX 1866 entrustment. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "litany-sacred-heart",
    name: "Litanya sa Banal na Puso ni Hesus",
    description:
      "Ang Litanya sa Banal na Puso ni Hesus ay isa sa anim na litanyang inaprobahan ng Holy See para sa pampublikong liturgical use. Binuo noong 1718 ni Sister Jeanne Madeleine Joly. Ibinigay ni Papa Leo XIII ang pormal na pag-apruba noong Abril 2, 1899 — sa parehong taon na inilaan niya ang buong sangkatauhan sa Banal na Puso sa kanyang encyclical na Annum Sacrum. Ang litanya ay binubuo ng tatlumpu't tatlong pagtawag sa Puso ni Kristo sa ilalim ng iba't ibang pamagat. Sa bawat pagtawag ay sinasagot ng «Maawa Ka sa amin».",
    instructions:
      "Ang litanya ay idinadasal nang responsorial. Sinasambit ng isang lider ang bawat pagtawag at ang sama-samang komunidad ay sumasagot. Sumusunod ang tatlumpu't tatlong pagtawag sa Puso ni Hesus, bawat isa ay may sagot na «Maawa Ka sa amin». Angkop na idinadasal: sa mga Unang Biyernes; sa buwan ng Hunyo; sa Nobena sa Banal na Puso.",
    patronSaint: "Banal na Puso ni Hesus",
    feastDay: "Biyernes pagkatapos ng Corpus Christi",
    source: "Annum Sacrum (Leo XIII, 1899) + CBCP Tagalog. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "litany-blessed-virgin",
    name: "Litanya ng Mahal na Birhen (Litanya ng Loreto)",
    description:
      "Ang Litanya ng Mahal na Birhen — kilala sa tradisyon bilang Litanya ng Loreto — ay ang pinaka-matanda at pinaka-mahal na Marian litany ng Latin Church. Pormal na inaprobahan ni Papa Sixtus V noong 1587. Sa loob ng mga siglo, ang sumunod na mga Papa ay nagdagdag ng mga pagtawag. Pinaka-bagong, idinagdag ni Papa Francisco ang «Mother of Mercy», «Mother of Hope», at «Comfort of Migrants» noong 2020.",
    instructions:
      "Ang litanya ay idinadasal nang responsorial. Sinasambit ng isang lider ang bawat pamagat ni Maria at ang sama-samang komunidad ay sumasagot ng «Ipanalangin mo kami». Ang Litanya ng Loreto ay tradisyonal na idinadasal pagkatapos ng Banal na Rosaryo; sa buwan ng Mayo at Oktubre.",
    patronSaint: "Mahal na Birhen Maria",
    feastDay: null,
    source: "Sixtus V 1587 approval + papal additions through Francis 2020 + CBCP Tagalog. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "prayer-conversion",
    name: "Panalangin para sa Pagbabalik-loob ng Isang Mahal sa Buhay",
    description:
      "Ang Katolikong panalangin para sa pagbabalik-loob ng isang mahal sa buhay ay nakaugat sa isa sa mga dakilang pastoral na patotoo ng kasaysayan ng Kristiyano: ang mahaba at tapat na panalangin ni Santa Monica para sa kanyang anak na si San Agustin. Si Monica ay nanalangin para sa pagbabalik-loob ng kanyang anak sa loob ng mga taon, sa pamamagitan ng kanyang mga luha at ang payo na natanggap niya mula kay San Ambrosio ng Milan («Hindi posible na ang anak ng napakaraming luha ay mawala»). Binyagan si Agustin noong 387 sa edad na tatlumpu't tatlo; namatay si Monica di-nagtagal pagkatapos sa Ostia. Itinala ni Agustin ang kanyang pagtitiyaga sa kanyang Confessions (Aklat IX).",
    instructions:
      "Manalangin araw-araw, perpekto sa parehong oras at sa parehong postura (nakaluhod, sa harap ng krusipiho o larawan ng Banal na Puso). Banggitin ang pangalan ng tao sa malakas sa panalangin. Pagkatapos ng panalangin, mag-ukol ng isang minuto ng katahimikan upang panatilihin siya sa harap ng Banal na Puso. Maraming Katoliko ang sumusuporta sa panalanging ito sa pamamagitan ng: (1) pang-araw-araw na pag-aalay ng maliliit na sakripisyo; (2) regular na intensyon ng Misa para sa tao; (3) Nobena kay Santa Monica o San Agustin; (4) Koronilya ng Banal na Awa sa ika-3:00 ng hapon.",
    patronSaint: "Santa Monica",
    feastDay: "Agosto 27",
    source: "Augustine's Confessions Book IX + CBCP Tagalog pastoral resources. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── Locale-anchored devotions (Philippines) ───────────────
  {
    prayerSlug: "novena-santo-nino",
    name: "Nobena sa Santo Niño ng Cebu",
    description:
      "Ang Santo Niño de Cebú ay ang sentral na imahe ng Filipinong Katolikong identidad at ang pinaka-matandang Kristiyanong imahe sa Pilipinas. Ang kuwento ay kabilang sa sandali na ang Kristiyanismo ay pumasok sa kapuluan: noong 1521, dinala ng Portuges na explorer na si Ferdinand Magellan — naglalayag sa ilalim ng Spanish crown — ang isang maliit na kahoy na estatwa ng Batang Kristo at iniharap kay Reyna Juana, ang asawa ni Rajah Humabon, sa pagkakataon ng kanyang binyag noong Abril 14, 1521. Si Juana, ang unang Filipino Christian queen, ay tumanggap ng imahe nang may malalim na pagmamahal, at ang Magellan's chronicler na si Antonio Pigafetta ay nagtala ng kanyang mga luha sa regalo. Nang bumalik ang Spanish missionaries sa Cebu noong 1565 sa ilalim ni Miguel López de Legazpi — apatnapu't apat na taon pagkatapos ng kamatayan ni Magellan sa Battle of Mactan — natagpuan nila ang imahe na napreserba sa isang maliit na bahay, na pinarangalan pa rin ng lokal na mga tao na nagpanatili ng debosyon. Ang Basilica Minore del Santo Niño sa Cebu City ay itinayo sa paligid ng nabawing imahe at ito ang pinaka-matandang simbahan sa Pilipinas. Ang taunang Sinulog Festival — ginaganap sa ikatlong Linggo ng Enero sa Cebu City — ay ang pinakamalaking Katolikong selebrasyon sa Asia, naghahatid ng milyon-milyong peregrino at nagtatampok ng mga araw ng prusisyon, mga misa, at ang katangiang Sinulog dance («isang hakbang pasulong, dalawang hakbang paatras») kung saan gumagalaw ang mga mananayaw kasabay ng ritmo ng agos ng ilog.",
    instructions:
      "Manalangin minsan sa isang araw sa loob ng siyam na magkakasunod na araw. Ang nobena ay tradisyonal na idinadasal sa siyam na araw na nauuna sa Kapistahan ng Santo Niño (ang ikatlong Linggo ng Enero, ang pinaka-mahalagang araw ng Sinulog Festival sa Cebu City). Sa Filipino tradition, ang nobena ay madalas idinadasal kasama ng: (a) isang Santo Niño image na nakalantad sa bahay — maraming Filipino-Catholic na sambahayan ang nagpapanatili ng Santo Niño altar; (b) pagdalo sa parish-wide novena Masses (isang siyam-na-araw na Mass series); (c) pagkanta ng mga tradisyonal na Cebuano at Tagalog Santo Niño hymns («Bato Balani sa Gugma» — «Magnet of Love» — ang pinakamamahal); (d) para sa maraming devotee, paglahok sa Sinulog dance sa prusisyon. Ang nobena ay angkop para sa: pagpapagaling ng pamilya; proteksyon ng mga bata (ang Santo Niño ay patron ng mga bata); paghahanda para sa o pagbawi mula sa binyag; pagbabalik-loob ng nahihiwalay na mga miyembro ng pamilya; ligtas na biyahe; at anumang mahirap na sandali kung saan ang kaluluwa ay nangangailangan ng pagtitiwala ng bata na hinihingi ni Kristo (Mateo 18:3). Maraming Filipino-Catholic families ang nagdarasal ng maikling Santo Niño aspiration araw-araw — «Viva Santo Niño!» o «Pit Señor, Sinulog ka!» — bilang isang sandali ng masayang pagtitiwala.",
    patronSaint: "Santo Niño (Banal na Bata ng Cebu)",
    feastDay: "Ikatlong Linggo ng Enero (Sinulog Festival)",
    source: "Antonio Pigafetta's chronicle of Magellan voyage (1521) + Basilica Minore del Santo Niño Cebu City + CBCP Tagalog. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "simbang-gabi",
    name: "Simbang Gabi (Mga Madaling-Araw na Misa bago ang Pasko)",
    description:
      "Ang Simbang Gabi (Tagalog para sa «Night Mass») — tinatawag ding Misa de Gallo (Spanish, «Mass of the Rooster») sa mas matandang Filipino-Spanish na tradisyon — ay isang kakaibang Filipinong Katolikong Advent devotion na binubuo ng siyam na magkakasunod na madaling-araw na Misa na ipinagdiriwang mula Disyembre 16 hanggang Disyembre 24, kaagad na nauuna sa Araw ng Pasko. Ang pinagmulan ay matatagpuan sa maagang Spanish missionary period sa Pilipinas (huling bahagi ng ika-16 siglo): ang mga Spanish friars, na kinikilala na ang agricultural rhythms ng Filipino farming communities ay nangangahulugang ang mga manggagawa ay nasa kabukiran bago ang madaling-araw, ay nagbigay ng pahintulot mula sa Vatican upang ipagdiwang ang Advent Mass sa unang liwanag — sa pagitan ng 3:00 at 5:00 AM — upang ang mga manggagawa ay makadalo bago magsimula ang trabaho ng araw. Pormal na ibinigay ni Papa Sixtus V ang pribilehiyo ng pre-dawn Advent Mass sa Pilipinas noong 1587. Ang pattern ng nobena (siyam na araw, kahalintulad sa siyam na buwan ng pagbubuntis ni Maria kay Kristo) ay nakapanahan sa devotion, at lumitaw ang popular na tradisyon na ang pagkumpleto sa lahat ng siyam na Misa — nang walang nakaligtaan — ay nagkakamit ng isang espesyal na intensyon mula sa Batang Kristo. Ngayon, ang Simbang Gabi ay nananatiling pinakamamahal na Filipino Catholic Christmas tradition, ginagawa sa buong Pilipinas at sa pandaigdigang Filipino diaspora. Sa Estados Unidos, ang USCCB ay nagbigay ng pormal na liturgical recognition sa Simbang Gabi noong 1989; ang mga Misa ay ipinagdiriwang tuwing gabi sa mga Filipino-American na parokya mula Disyembre 15-23.",
    instructions:
      "Dumalo sa Banal na Misa sa bawat isa sa siyam na magkakasunod na araw, mula Disyembre 16 hanggang Disyembre 24. Sa Pilipinas, ang mga Misa ay ipinagdiriwang bago ang madaling-araw (tradisyonal na 4:00 AM); sa Filipino-American diaspora, ang mga Misa sa gabi sa Disyembre 15-23 (anticipated, na tumutupad sa parehong siyam-na-araw na nobena) ang pamantayan. Ang pattern: (1) Dumating sa parish church sa oras para sa Misa (madalas itong nangangahulugang gumising sa 3:00 AM sa Pilipinas, naglalakad sa madilim na kalye papunta sa parokya); (2) Tumanggap ng mga Sakramento — ang Confession sa panahon ng Advent ay bahagi ng paghahanda; (3) Pagkatapos ng Misa, magbahagi ng samahan at tradisyonal na Filipino Christmas foods (bibingka, puto bumbong, salabat) kasama ng parish community; (4) Dalhin ang intensyon ng araw nang tahimik sa buong umaga. Maraming Filipino ang nakikipag-sapi sa pananalangin para sa isang tiyak na intensyon sa lahat ng siyam na Misa, na may tradisyonal na paniniwala na ang pagkumpleto ng buong nobena ay nagkakamit ng isang espesyal na biyaya mula sa Batang Kristo. Para sa Filipino-American na mga pamilya, ang Simbang Gabi ay madalas ang pinaka-mahalagang catechetical link sa tinubuang bayan — natututunan ng mga bata ang mga rhythm, foods, at panalangin ng Filipino Catholic culture sa pamamagitan ng pagdalo kasama ng mga magulang at lolo't lola.",
    patronSaint: null,
    feastDay: "Disyembre 16-24 (siyam na araw bago ang Pasko)",
    source: "Sixtus V's 1587 papal permission for Philippine pre-dawn Advent Mass + USCCB 1989 liturgical recognition + CBCP Tagalog liturgical materials. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── ROUND 3 (fil) ─────────────────────────────────────────
  {
    prayerSlug: "litany-st-joseph",
    name: "Litanya kay San Jose",
    description:
      "Ang Litanya kay San Jose ay isa sa anim na litanya na inaprubahan ng Banal na Luklukan para sa pampublikong liturgical na paggamit sa Latin Rite. Unti-unting binuo sa ika-17 at ika-18 na siglo habang lumalalim ang debosyon kay San Jose sa buong mundo ng Katoliko, natanggap ng litanya ang pormal na Magisterial approval mula kay Papa San Pio X noong 18 ng Marso 1909 — bisperas ng Kapistahan ni San Jose — para sa Esposo ni Maria, ama-amahan ni Hesus, at Patron ng Pandaigdigang Simbahan. Sumusunod ang istraktura sa pattern ng iba pang inaprubahan na Katolikong litanya: isang pagbubukas ng Kyrie, isang Trinitarian invocation, at saka isang mahabang sequence ng mga invocation na tinutukoy si San Jose sa iba't ibang titulo, bawat isa ay may sagot na «Ipanalangin mo kami»: «Tanyag na anak ni David», «Liwanag ng mga patriarka», «Esposo ng Ina ng Diyos», «Malinis na tagapag-alaga ng Birhen», «Ama-amahan ng Anak ng Diyos», «Masipag na tagapagtanggol ni Kristo», «Pinuno ng Banal na Pamilya», «Jose na pinakamatuwid», «Jose na pinakamalinis», «Jose na pinakamaingat», «Salamin ng pagtitiis», «Umiibig sa kahirapan», «Modelo ng mga manggagawa», «Kaluwalhatian ng buhay-tahanan», «Tagapag-alaga ng mga birhen», «Haligi ng mga pamilya», «Aliw ng mga nahihirapan», «Pag-asa ng mga maysakit», «Patron ng mga naghihingalo», «Sindak ng mga demonyo», «Tagapagtanggol ng Banal na Simbahan». Noong Mayo 2021, kaugnay ng Taon ni San Jose (Disyembre 2020 - Disyembre 2021) at ng kanyang apostolic letter na Patris Corde, pormal na idinagdag ni Papa Francisco ang pitong bagong invocation sa litanya, direktang hinugot mula sa wika ng Patris Corde: «Tagapag-alaga ng Manunubos», «Lingkod ni Kristo», «Ministro ng kaligtasan», «Suporta sa mga kahirapan», «Patron ng mga pinapatapon», «Patron ng mga nahihirapan», at «Patron ng mga mahihirap». Ang mga karagdagang ito ay sumasalamin sa partikular na pastoral framing ni Francisco kay San Jose bilang modelo para sa mga ama, mga manggagawa, at mga pinakaaba sa kontemporanyong mundo.",
    instructions:
      "Ang litanya ay dinarasal nang responsorial. Binibigkas ng leader ang bawat invocation («Jose na pinakamatuwid…») at sumasagot ang nagtipon-tipon ng «Ipanalangin mo kami» sa bawat isa. Ang pagbubukas ng Kyrie pattern at ang Trinitarian invocation ay gumagamit ng «Maawa Ka sa amin» bilang sagot; ang katawan ng litanya — ang mahabang sequence ng mga titulo — ay gumagamit ng «Ipanalangin mo kami». Nagtatapos ang litanya sa tatlong invocation sa Kordero ng Diyos (Agnus Dei), isang versicle-response pair na hinugot mula sa Genesis («Ginawa siyang panginoon ng kanyang sambahayan, at katiwala ng lahat niyang ari-arian»), at isang collect prayer kay San Jose. Tinatagal ng halos sampung minuto kapag binibigkas sa banayad na devotional pace. Ang Litanya kay San Jose ay tradisyonal na dinarasal: sa buong buwan ng Marso, ang Buwan ni San Jose; sa mga araw bago ang Dakilang Kapistahan ni San Jose (19 ng Marso) o ang Kapistahan ni San Jose Manggagawa (1 ng Mayo); sa pagtatapos ng isang Holy Hour o Eucharistic adoration; sa mga family context na humihingi ng proteksyon ni San Jose sa tahanan. Ang mga 2021 additions ay maaaring isama sa anumang tradisyonal na printed text sa pamamagitan ng pagpapasok ng pitong bagong invocation sa kanilang nararapat na lugar sa sequence ng litanya (karamihan sa mga published current version ay inilalakip ang mga ito); parehong inilathala ng Catholic Bishops' Conference of the Philippines (CBCP) at ng website ng Holy See ang updated full text. Maraming Catholic family ang nagdadasal ng litanya magkakasama tuwing Miyerkules ng gabi (ang tradisyonal na araw na inilaan kay San Jose sa lumang Catholic devotional calendar). Kapag dinarasal nang mag-isa, basahin lamang ang invocation at ang sagot nang malakas o tahimik.",
    patronSaint: "San Jose",
    feastDay: "19 ng Marso",
    source: "CBCP + Patris Corde (Papa Francisco, 8 Disyembre 2020) + Pope Pius X 1909 approval. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-holy-spirit",
    name: "Nobena sa Banal na Espiritu",
    description:
      "Ang Nobena sa Banal na Espiritu ay ang orihinal na nobena — ang pattern ng panalangin kung saan nagmula ang bawat iba pang siyam-na-araw na nobenang Katoliko. Ang biblical foundation nito ay ang aklat ng Mga Gawa ng mga Apostol: «Patuloy na nagtitipon sa pananalangin ang lahat ng mga ito, kasama ang ilang mga babae, at si Maria na ina ni Hesus, at ang kanyang mga kapatid» (Mga Gawa 1:14). Sa loob ng siyam na araw matapos ang Pag-akyat sa Langit ni Kristo, nanatili ang mga disipulo at ang Mahal na Birheng Maria sa upper room sa Jerusalem sa panalangin; sa ikasampung araw, ang Kapistahan ng Pentekostes (Mga Gawa 2:1-4), bumaba ang Banal na Espiritu sa kanila na may tunog ng malakas na hangin at mga dilang-apoy. Bawat Catholic novena pagkatapos ay kumukuha ng siyam-na-araw na pattern nito mula sa nag-iisang precedent na ito na ibinigay ng Espiritu. Tinatawag ng nobena ang pitong kaloob ng Banal na Espiritu na nakatala sa Isaias 11:2-3: karunungan, pang-unawa, payo, lakas, kaalaman, kabanalan, at takot sa Panginoon. Sa mga ito, idinaragdag ng Catholic tradition ang labindalawang bunga ng Banal na Espiritu na pinangalanan sa Sulat sa mga Taga-Galacia (5:22-23 sa Vulgate enumeration): pag-ibig, kagalakan, kapayapaan, pagtitiis, kabaitan, kabutihan, kabukasan ng loob, kahinahunan, katapatan, kalinisan, pagpipigil sa sarili, at kalinisang-puri. Ang tono ng nobena ay petitionary ngunit puno ng pagtitiwala — ang Espiritu ang regalo na ipinangako ni Hesus na ipapadala (Juan 14:16-17; 16:7-15), at nagdarasal ang Simbahan nang may pagtitiwala na ang Espiritung bumaba sa mga apostol ay patuloy na bumababa sa mga tapat. Ang nobena ay lalo na nararapat para sa pagdidiskreto ng bokasyon, ang pagpapahid sa mga maysakit, ang paghahanda ng mga tatanggap ng Sakramento (Kumpil, kasal, ordinasyon), at anumang sandali kapag nararamdaman ng isang kaluluwa na hindi niya makita ang kalinawan sa pamamagitan lamang ng sariling katwiran at kailangan ang inspirasyon ng Espiritu.",
    prayerText:
      "Halina, Espiritu Santo, punuin Mo ang mga puso ng Iyong mga tapat at pag-alabin Mo sa kanila ang apoy ng Iyong pag-ibig. Ipadala Mo ang Iyong Espiritu at sila ay lilikhain, at babaguhin Mo ang mukha ng lupa. O Diyos, na nagturo sa mga puso ng mga tapat sa pamamagitan ng liwanag ng Espiritu Santo, ipagkaloob Mong sa pamamagitan ng parehong Espiritu Santo, kami ay maging tunay na matalino at lagi naming tamasahin ang Kanyang aliw. Sa pamamagitan ni Kristong aming Panginoon. Amen.",
    instructions:
      "Magdasal isang beses sa isang araw sa loob ng siyam na magkakasunod na araw. Tradisyonal, dinarasal ang nobena sa pagitan ng Pag-akyat sa Langit (Ascension Thursday) at Linggo ng Pentekostes — ang orihinal na siyam na araw na patuloy na ipinagdadasal ng Simbahan mula sa mga apostol. (Sa mga diyosesis kung saan inililipat ang Ascension sa sumusunod na Linggo, nagsisimula ang nobena sa Biyernes pagkatapos ng Linggong iyon; tingnan ang lokal na liturgical calendar.) Maaari ring idasal ang nobena sa anumang panahon ng taon para sa pribadong intensyon. Ang tradisyonal na istraktura para sa bawat araw: (1) Magsimula sa Tanda ng Krus; (2) Bigkasin o awitin ang Veni Creator Spiritus («Halina, Espiritu Lumikha») o ang Veni Sancte Spiritus («Halina, Banal na Espiritu») — ang dalawang dakilang Latin sequence para sa Pentekostes; (3) Idasal ang panalangin ng nobena; (4) Magmuni-muni nang sandali sa isa sa pitong kaloob ng Espiritu (isa kada araw sa unang pitong araw; sa ikawalo at ikasiyam, sa labindalawang bunga at sa isang personal na intensyon); (5) Tapusin ng Ama Namin, Aba Ginoong Maria, at Luwalhati. Ang kabuuang tagal ay halos sampung minuto sa isang araw. Madalas na nagdadasal ang mga pamilyang may maliliit na anak ng mas maikling bersyon gamit lamang ang invocation na Halina, Banal na Espiritu at isang child-friendly explanation ng isang kaloob sa isang araw. Nararapat din ang nobena bago ang isang mahalagang desisyon, bago ang isang mahirap na pag-uusap, o bago ang anumang gawain kung saan ang tao ay nangangailangan ng payo, lakas, o karunungan nang higit sa kanyang likas na kakayahan.",
    patronSaint: null,
    feastDay: "Pentekostes",
    source: "CBCP + Mga Gawa 1:14, 2:1-4 + Vatican.va Tagalog liturgical sources. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-st-therese",
    name: "Nobena kay Santa Teresita ng Sanggol na Hesus",
    description:
      "Si Santa Teresita ng Sanggol na Hesus at ng Banal na Mukha — mas kilala bilang Teresa ng Lisieux o «ang Munting Bulaklak» — ay isang Discalced Carmelite nun na pumasok sa monasteryo sa Lisieux, Normandy, sa edad na labinlimang taon at namatay sa tuberculosis sa edad na dalawampu't apat (1873-1897). Ang kanyang espirituwal na autobiograpiya, Kasaysayan ng Isang Kaluluwa, ay inilathala ilang sandali matapos ang kanyang kamatayan at agad na naging isa sa mga pinakamababasang Katolikong aklat sa modernong panahon. Mula sa kawalang-kilala ng isang provincial cloister itinuro niya ang tinatawag niyang Munting Daan: pagtitiwala sa maawaing pag-ibig ng Diyos na ipinahayag sa pinakamaliliit na gawa ng pang-araw-araw na katapatan, sa halip na sa mga heroic external feat. «Gugugulin ko ang aking langit sa paggawa ng mabuti sa lupa», sikat niyang ipinangako, «pababagsakin ko ang ulan ng mga rosas». Ang tradisyon ng «ulan ng mga rosas» — ang paniniwalang ang mga intercession na sinasagot sa pamamagitan ni Santa Teresita ay madalas na sinasamahan ng isang hindi inaasahang rosas, literal o simboliko — ay humubog sa Catholic devotion sa kanya simula noon. Kinanonisa siya ni Papa Pio XI noong 1925, pinangalanan na Patroness of the Missions noong 1927 (kahit hindi siya umalis sa cloister), at ipinahayag bilang Doctor of the Church ni Papa San Juan Pablo II noong 1997 — isa sa apat na babae lamang na ganitong pinangalanan, kasama ang mga Santa Teresa ng Avila, Catalina ng Siena, at Hildegard ng Bingen. Ang kanyang doctrinal contribution ay ang teolohiya ng pagkabata: ang turo ng Ebanghelyo na ang isang tao ay dapat maging tulad ng isang maliit na bata upang makapasok sa Kaharian (Mateo 18:3) na binigyan ng matagalang, contemplative articulation. Nararapat ang nobena kay Santa Teresita para sa: pagdidiskreto ng relihiyosong o lay na bokasyon, paggaling mula sa sakit (ang kanyang sariling tuberculosis ay tiniis nang may malaking paghihirap), espirituwal na pagkatuyo, ang pagbabago ng malalayong mahal sa buhay (patuloy siyang nagdasal para kay Pranzini, isang hinatulang mamamatay-tao, bilang kanyang «unang anak»), at anumang sandali kapag nararamdaman ng isang kaluluwa ang sariling pagkamaliit sa harap ng isang malaking pangangailangan.",
    prayerText:
      "O Munting Teresita ng Sanggol na Hesus, mangyaring pumitas para sa akin ng isang rosas mula sa mga makalangit na hardin at ipadala ito sa akin bilang mensahe ng pag-ibig. O Munting Bulaklak ni Hesus, hilingin Mo sa Diyos ngayon na ipagkaloob ang mga pabor na inilalagay ko ngayon nang may tiwala sa Iyong mga kamay. (Banggitin ang intensyon.) Santa Teresita, tulungan Mo akong laging maniwala, gaya ng paniniwala Mo, sa dakilang pag-ibig ng Diyos para sa akin, upang aking magaya ang Iyong Munting Daan araw-araw. Amen.",
    instructions:
      "Magdasal isang beses sa isang araw sa loob ng siyam na magkakasunod na araw. Ang tradisyonal na istraktura: (1) Magsimula sa Tanda ng Krus; (2) Idasal ang panalangin ng nobena kay Santa Teresita (humihingi ng kanyang pagiging tagapamagitan at ng kanyang sikat na rosas); (3) Sabihin ang iyong intensyon nang tahimik o malakas; (4) Tapusin ng Ama Namin, Aba Ginoong Maria, at Luwalhati. Nararapat na idasal ang nobena sa siyam na araw bago ang kanyang kapistahan (1 ng Oktubre) o sa anumang panahon ng taon para sa pribadong intensyon. Maraming Katoliko ang nag-iingat ng isang maliit na larawan o relikya ni Santa Teresita sa tahanan o nagdadala ng isang rose-themed prayer card sa panahon ng nobena. Ang tradisyon ng «ulan ng mga rosas» ay eksaktong iyon — isang tradisyon, hindi isang magical guarantee. Ang isang rosas na natanggap sa panahon o pagkatapos ng nobena ay binabasa bilang isang personal na tanda na narinig ng santa ang panalangin at nakikipamagitan sa harapan ni Kristo; ang kawalan ng rosas ay hindi binabasa bilang kawalan ng pamamagitan. Ang puntong ito ay ang disposisyon: inanyayahan ng Munting Daan ni Teresita ang nagdarasal sa parehong childlike trust na kanyang inihalimbawa, na siya mismong biyaya na hinihiling. Nararapat din ang nobena bilang katuwang sa mga partikular na gawa ng maliit na katapatan sa loob ng siyam na araw — pagtitiis sa isang mahirap na miyembro ng pamilya, pagtanggap ng isang maliit na abala nang hindi nagrereklamo, pagpipigil ng isang matalas na salita, paggawa ng isang nakatagong gawa ng kabaitan araw-araw. Ang mga «munting daan» na ito ang naglalaman ng hinihiling ng nobena: hindi heroic na pagbabago, kundi ang daan ng maliliit na bagay na ginagawa nang may dakilang pag-ibig na itinuro at ipinamuhay ni Teresita.",
    patronSaint: "Santa Teresita ng Sanggol na Hesus",
    feastDay: "1 ng Oktubre",
    source: "CBCP + Kasaysayan ng Isang Kaluluwa + Papa San Juan Pablo II Divini Amoris Scientia (1997, deklarasyon bilang Doctor of the Church). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-miraculous-medal",
    name: "Nobena sa Mahimalang Medalya",
    description:
      "Sa gabi ng Hulyo 18-19, 1830, sa kapilya ng Daughters of Charity sa Rue du Bac sa Paris, isang batang novice na nagngangalang Catherine Labouré ang ginising ng kanyang guardian angel at dinala sa kapilya para sa isang pribadong pagpapakita ng Mahal na Birheng Maria. Nakipag-usap si Maria sa kanya nang mahigit dalawang oras tungkol sa magulong kalagayan ng France at ng mas malawak na Simbahan. Sa pangalawang pagpapakita noong Nobyembre, nakita ni Catherine si Maria na nakatayo sa isang globo na may mga sinag ng liwanag na bumubuga mula sa kanyang mga kamay, napapaligiran ng isang frame na nakaukit ng mga salitang: «O Maria na ipinaglihi nang walang kasalanan, ipanalangin mo kami na sumasalig sa iyo!» Sa likod ng pangitain na ito ay isang cruciform M na may labindalawang bituin, isang puso ni Kristo na may koronang tinik, at isang puso ni Maria na tinutusok ng tabak. Iniutos ni Maria kay Catherine: «Magpagawa ng medalya ayon sa modelong ito. Ang mga magsusuot nito ay tatanggap ng dakilang biyaya, lalo na kung isuot nila ito sa kanilang leeg». Ginawa ang medalya noong 1832 nang may pag-apruba ng Arsobispo ng Paris. Sa loob ng limang taon ito ay napamahagi sa napakaraming bilang at sinamahan ng napakaraming naiulat na pamamagitan na pinalitan ng popular na Katolikong imahinasyon ang pangalan nito bilang «ang Mahimalang Medalya», isang pangalang sa kalaunan ay tinanggap ng Simbahan. Ang 1830 apparitions ay kapansin-pansin bilang isa sa mga pangunahing Marian events ng modernong panahon, mas matanda sa Lourdes (1858) ng dalawampu't walong taon at sa Fatima (1917) ng walumpu't pitong taon. Ang doktrina ng Immaculate Conception — sa puso ng central inscription ng medalya — ay pormal na idineklara ni Papa Pio IX noong 1854, dalawampu't apat na taon pagkatapos ng mga pangitain ni Catherine. Nanatili si Catherine Labouré sa kanyang convent sa Reuilly, nagtatrabaho kasama ang mga matatandang mahihirap, sa natitirang apatnapu't anim na taon ng kanyang buhay. Kinanonisa siya noong 1947 ni Papa Pio XII. Nararapat ang nobena sa Mahimalang Medalya para sa: sakit (lalo na sa mahirap na prognosis — nagsimula ang reputasyon ng medalya sa mga paggaling), pagbabago ng mga miyembro ng pamilya, proteksyon sa pagbubuntis (isang matagal nang Katolikong tradisyon na ipinipin ang medalya sa damit ng ina o dinadala ito sa panganganak), at anumang mahirap na sandali kapag ang isang kaluluwa ay naghahanap ng partikular na maternal na pamamagitan ni Maria sa pamamagitan ng partikular na tanda na ito.",
    prayerText:
      "O Imakuladang Birheng Maria, Ina ng aming Panginoong Hesus at aming Ina, puno ng pinaka-mabilis na pagtitiwala sa Iyong makapangyarihan at hindi-kailanmang-nabibigong pamamagitan, na napakadalas na ipinakita sa pamamagitan ng Mahimalang Medalya, kami na Iyong mga nagmamahal at nagtitiwalang mga anak ay nakikiusap sa Iyo na makamit para sa amin ang mga biyaya at pabor na hinihiling namin sa nobenang ito, kung mga ito ay nakapagpapakinabang sa aming walang-kamatayang mga kaluluwa at sa mga kaluluwang pinagdadasalan namin. (Banggitin ang intensyon.) Alam Mo, O Maria, kung gaano kadalas naging dambana ng Iyong Anak ang aming mga kaluluwa, ang Iyong Anak na napopoot sa kasamaan. Ipagkaloob Mo nga sa amin ang malalim na pagkapoot sa kasalanan at ang kalinisan ng puso na magkakabit sa amin sa Diyos lamang. Amen.",
    instructions:
      "Magdasal isang beses sa isang araw sa loob ng siyam na magkakasunod na araw. Ang tradisyonal na istraktura: (1) Magsimula sa Tanda ng Krus; (2) Idasal ang Memorare o tatlong Aba Ginoong Maria bilang panimulang Marian invocation; (3) Idasal ang panalangin ng nobena sa Immaculate Virgin sa pamamagitan ng Mahimalang Medalya; (4) Tapusin sa central inscription ng medalya bilang aspiration: «O Maria na ipinaglihi nang walang kasalanan, ipanalangin mo kami na sumasalig sa iyo!»; (5) Sabihin ang iyong partikular na intensyon. Kung maaari, suotin ang Mahimalang Medalya — pisikal — sa panahon ng nobena. Ang medalya ay hindi anting-anting; ang tradisyon ay ang pagsusuot nito ay nagpapahayag ng pagtitiwala sa pamamagitan ni Maria at ng pagkabukas ng nagsusuot sa biyaya. Ang mga Catholic chapel at shrine ay namamahagi ng Miraculous Medal nang libre. Maaaring idasal ang nobena sa anumang panahon ngunit lalo na nararapat sa mga araw bago ang Kapistahan ng Mahal na Birhen ng Mahimalang Medalya (27 ng Nobyembre) o ang Dakilang Kapistahan ng Immaculate Conception (8 ng Disyembre). Maraming Katoliko ang gumagamit din ng Mahimalang Medalya bilang tanda ng consecration sa Immaculate Heart of Mary — ipinapares ang nobena sa Total Consecration prayer ni San Maximilian Kolbe o ang mas mahabang 33-day preparation para sa Marian consecration (ang de Montfort tradition). Para sa mga pamilya na nagdadasal para sa isang wala o nahihirapang mahal sa buhay, isang tradisyonal na kasanayan ay ang pagdulot ng isang Miraculous Medal sa mga gamit ng mahal sa buhay — isang pitaka, isang bulsa ng amerikana, isang backpack — bilang isang maliit na tanda ng patuloy na maternal accompaniment.",
    patronSaint: "Santa Catherine Labouré",
    feastDay: "27 ng Nobyembre",
    source: "CBCP + Rue du Bac apparition narrative (1830) + Papa Pio XII canonization 1947. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "st-michael-prayer",
    name: "Panalangin kay San Miguel Arkanghel",
    description:
      "Binuo ng Papa Leon XIII ang Panalangin kay San Miguel Arkanghel noong 1886 matapos, ayon sa matagal nang naipatototohanang tradisyon, magkaroon ang Papa ng biglaang mistikal na karanasan habang nagdiriwang ng Misa — isang uri ng waking vision kung saan narinig niya ang isang colloquy sa pagitan ni Kristo at ni Satanas kung saan ipinagmamalaki ni Satanas na kaya niyang sirain ang Simbahan kung bibigyan ng sapat na oras at kapangyarihan. Nayanig sa kanyang nakita, binuo ni Leon XIII ang panalangin kay San Miguel sa parehong araw at iniutos na idagdag ito sa mga panalanging dinarasal ng pari at ng mga tapat sa pagtatapos ng bawat Low Mass sa buong unibersal na Simbahan. Ang kasanayang ito — ang «Leonine Prayers» pagkatapos ng Misa — ay nagpatuloy nang halos walumpung taon hanggang sa mga liturgical reform ng dekada 1960. Hindi binura ang panalangin kay San Miguel ngunit ang pormal nitong lugar sa post-Mass prayers ay natapos. Ibinangon ni Papa San Juan Pablo II ang prominence ng panalangin sa isang 1994 Sunday Angelus address, kung saan hinimok niya ang mga tapat na «huwag kalimutan na bigkasin» ang panalangin kay San Miguel «upang makakuha ng tulong sa labanan laban sa mga puwersa ng kadiliman at laban sa espiritu ng mundong ito». Ang teksto ng panalangin ay nakabatay sa Judas 1:9 (Pakikipagtalo ni Miguel sa diyablo tungkol sa katawan ni Moises), Apocalipsis 12:7-9 (Pagpapatalsik ni Miguel sa dragon), at ang mas malawak na Catholic tradition ni San Miguel bilang lider ng heavenly host laban sa mga kapangyarihan ng kasamaan. Nararapat ang panalangin para sa: espirituwal na pakikidigma sa anumang anyo, pagkabalisa sa kasamaan sa mundo o sa personal na buhay, proteksyon sa panahon ng paglalakbay o bago ang isang mahirap na engkwentro, ang pagbabago ng mga nahulog sa grabeng kasalanan, at bilang pang-araw-araw na panalangin ng consecration sa proteksyon ni San Miguel. Ito ang panalangin na pinakakaraniwang itinuturo sa mga batang Katoliko bilang unang «protection prayer» kasama ang Panalangin sa Guardian Angel.",
    instructions:
      "Magdasal isang beses nang may buong atensyon at debosyon. Ang Panalangin kay San Miguel ay sapat na maikli upang isaulo at idasal kahit saan — sa kotse bago ang isang mahirap na pagpupulong, sa pintuan ng isang ospital, naglalakad sa isang lugar kung saan nararamdaman ang espirituwal na kaguluhan, bago matulog sa katapusan ng araw. Ang tradisyonal na Katolikong kasanayan — at ang orihinal na itinatag ni Leon XIII — ay idasal ito kaagad pagkatapos ng pagtatapos ng Banal na Misa, alinman sa katahimikan na sumusunod sa dismissal o bilang bahagi ng isang pampublikong sequence ng Leonine Prayers. Maraming parokya ang nagbangon ng post-Mass St. Michael prayer pagkatapos ng tawag ni JPII noong 1994; kung ang iyong parokya ay hindi gumagawa nito, ganap na nararapat na manatili sa iyong upuan sa loob ng tatlumpung segundo pagkatapos ng dismissal at idasal ito nang pribado. Madalas ding kasama ang panalangin: sa pagtatapos ng Rosaryo o ng isang Holy Hour; sa pagtatapos ng pang-gabing panalangin ng pamilya; bago ang anumang gawain kung saan nararamdaman ng isang Katoliko ang totoong espirituwal na pagsalungat. Ipinapaskil ng ilang Katolikong sambahayan ang panalangin sa itaas ng pangunahing pinto ng tahanan bilang tanda ng consecration sa proteksyon ni San Miguel sa sambahayan. Natural na ipinapares ang panalangin sa Panalangin sa Guardian Angel para sa mga bata: si San Miguel bilang prinsipe ng angelic host, at ang guardian angel bilang ang partikular na ministering spirit na itinalaga sa bawat tao sa binyag.",
    patronSaint: "San Miguel Arkanghel",
    feastDay: "29 ng Setyembre",
    source: "CBCP + Leon XIII 1886 composition + Papa San Juan Pablo II Sunday Angelus, April 24, 1994. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "anima-christi",
    name: "Anima Christi (Kaluluwa ni Kristo)",
    description:
      "Ang Anima Christi («Kaluluwa ni Kristo») ay isa sa pinakamamahal at pinakalumang Eucharistic prayers sa Katolikong tradisyon. Ang pinagmulan nito ay medieval — malamang ika-14 siglo — at sa loob ng maraming taon ito ay itinuring na ginawa ni San Ignacio ng Loyola dahil inilagay niya ito sa pinakasimula ng kanyang Spiritual Exercises (1522-1524) at inirekomenda bilang pang-araw-araw na panalangin para sa mga retreatant. Ang modernong iskolar ay nagpetsa ng panalangin nang hindi bababa sa isang siglo bago ang kapanganakan ni Ignacio; lumitaw ito sa mga manuskrito noong 1314, posibleng ginawa ni Juan XXII o ng isang anonymous na monghe ng Cartusian o Franciscan tradition. Hindi ito isinulat ni Ignacio, ngunit minahal niya ito, at ibinigay ng kanyang Spiritual Exercises ang malawak na pamamahagi na tinatamasa nito ngayon sa buong Katolikong mundo. Ang panalangin ay isang sustained meditation sa Eucharistic Christ — Kanyang Kaluluwa, Kanyang Katawan, Kanyang Dugo, ang tubig at dugo na bumukas mula sa Kanyang tinusok na tagiliran sa Krusipiksyon (Juan 19:34), Kanyang Pagpapakasakit. Ang bawat linya ay parehong confession of faith at petition: «Kaluluwa ni Kristo, gawin mo akong banal» ay ang panalangin ng isang taong humihingi na maging banal sa loob sa pamamagitan ng sariling kabanalan ni Kristo; «Katawan ni Kristo, iligtas mo ako» ay ang pag-amin na nagmumula ang kaligtasan sa parehong katawan na natatanggap na ngayon sa anyo ng tinapay; «Sa loob ng Iyong mga sugat itago mo ako» ay ang medieval mystical longing na makahanap ng kanlungan sa mismong mga sugat ng krusipikadong Panginoon. Ang pagtatapos ng panalangin — «Sa oras ng aking kamatayan tawagin mo ako» — ay ginawa itong tradisyonal na Katolikong panalangin para sa mga naghihingalo, idinadasal sa tabi ng kama sa mga huling oras ng mga hospice chaplain, miyembro ng pamilya, at Katolikong nars. Nararapat ang Anima Christi para sa: pasasalamat kaagad matapos tumanggap ng Banal na Komunyon (ang pangunahing tradisyonal na paggamit nito), isang Holy Hour o pagbisita sa Blessed Sacrament, ang pagtatapos ng personal na panalangin, ang tabi ng kama ng mga naghihingalo, at bilang pang-araw-araw na debosyon na nagpapahayag ng Eucharistic intimacy.",
    instructions:
      "Magdasal nang may debosyon, mainam sa postura ng masusing katahimikan — nakaluhod, nakaupong nakatayo nang may mga bukas na kamay, o nakatayo sa harap ng Blessed Sacrament. Ang panalangin ay nilalayong walang pagmamadali; bawat linya ay isang natatanging petition at ang natural na bilis ay nagpapahintulot ng isang maikling paghinto sa pagitan ng mga parirala upang ang bawat linya ay manirahan sa puso. Ang tradisyonal na mga sandali para sa Anima Christi: (1) Kaagad pagkatapos tumanggap ng Banal na Komunyon sa Misa, sa katahimikan ng personal na pasasalamat — ito ang pangunahing devotional na paggamit ng panalangin, at ang rekomendasyon ni San Ignacio; (2) Sa panahon ng isang Holy Hour o Eucharistic adoration sa harap ng exposed Blessed Sacrament; (3) Sa pagtatapos ng personal na umagang o gabing panalangin, lalo na bilang bahagi ng Eucharistic spirituality; (4) Sa tabi ng kama ng isang grabe na maysakit o naghihingalo — ang huling linya, «Sa oras ng aking kamatayan tawagin mo ako at iutos sa akin na pumunta sa Iyo», ay nagiging partikular na nararapat na deathbed devotion; (5) Inaawit na bersyon sa Latin («Anima Christi, sanctifica me…») sa mga monastic at traditional liturgical setting. Maraming Catholic prayer card ang nagdadala ng Anima Christi sa likod kasama ng isang Communion-reception prayer. Maaaring isaulo ang panalangin sa isang hapon at idasal kahit saan; ang kaiklian nito at density ng Eucharistic content ay gumagawa nito bilang isa sa mga pinakamadiing maikling panalangin sa Katolikong devotional repertoire.",
    patronSaint: "San Ignacio ng Loyola",
    feastDay: null,
    source: "Vatican.va Tagalog + Spiritual Exercises ni San Ignacio (1522-1524) + ika-14 siglong manuscript tradition. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── ROUND 4 (fil) ─────────────────────────────────────────
  {
    prayerSlug: "litany-saints",
    name: "Litanya ng mga Santo",
    description:
      "Ang Litanya ng mga Santo ay ang pinakamatanda at pinakasolemne na litanya sa Simbahang Katolika. Ang mga ugat nito ay umaabot sa mga unang siglo — lumitaw ang mga pira-piraso ng anyo sa ika-pitong siglong Western liturgical books, at itinatag ng Papa Gregorio Magno ang dakilang litanic processions ng Roma noong 590, hinihiling sa mga tapat na tawagin ang mga santo sa pangalan sa supplication sa panahon ng salot. Ang litanya ay naging bahagi ng Easter Vigil baptismal liturgy man lamang sa ika-walong siglo. Ang kanyang kasalukuyang Roman-rite na teksto ay pormal na itinakda ni Papa Pio V noong 1568 at binago sa post-Vatican II liturgical reform (1969). Lumalabas ang istraktura sa limang pangunahing kilos: (1) Mga invocation ng Kyrie eleison at mga petisyon ng Trinitarian; (2) ang dakilang roll-call ng mga santo sa pangalan — una ang Mahal na Birheng Maria, pagkatapos ay ang mga arkanghel (Miguel, Gabriel, Rafael), mga patriarka at propeta (Abraham, Moises, Elias, Juan Bautista), mga apostol at evangelista (Pedro, Pablo, Andres, Juan, Jaime, atbp.), mga martir (Esteban, Lorenzo, Polycarp, Ignacio ng Antioquia, Cipriano, Sebastian, Águeda, Inés), mga obispo-confessor at doctors (Athanasius, Basil, Gregory, Augustine, Jerome, Ambrose), mga tagapagtatag at birhen (Antonio ng Desyerto, Benito, Francisco, Domingo, Catalina ng Siena, Teresa ng Avila); (3) mga petisyon ng deliverance («Mula sa lahat ng masama, iligtas Mo kami, Panginoon»); (4) mga petisyon ng supplication («Upang Inyong pamahalaan at pangalagaan ang Inyong banal na Simbahan, kami nakikiusap sa Inyo, dinggin Mo kami»); (5) pagsasara ng Agnus Dei at collect. Ang litanya ay isa sa mga pangunahing dasal ng Catholic liturgy at ginagamit sa: ang Easter Vigil (sa panahon ng Liturgy of Baptism), Holy Saturday baptisms, priestly at episcopal ordinations (ang mga kandidato ay nakahandusay habang inaawit ng nagtipon-tipon na Simbahan ang litanya sa kanila), ang Rite of Christian Initiation of Adults (RCIA) sa Rite of Election, ang dedication ng simbahan, ang consecration ng mga altar, at ang pagbibigay ng religious vows. Karaniwan din ito sa maraming parokya sa Dakilang Kapistahan ng Lahat ng Santo (1 ng Nobyembre), sa mga libing ng pari at religious, sa mga sandali ng matinding pangangailangan ng publiko (digmaan, pandemya, natural disaster), at bilang panghuling dasal ng pilgrimage processions.",
    instructions:
      "Ang Litanya ng mga Santo ay dinarasal nang responsorial, karaniwang inaawit sa mga liturgical setting. Ang isang leader (pari, deacon, o sinanay na cantor) ay nag-intone sa invocation; ang assembly ay sumasagot ng nararapat na formula. Sumusunod ang mga sagot sa istraktura: «Ipanalangin mo kami» pagkatapos ng bawat santo na pinangalanan o grupo ng mga santo; «Iligtas Mo kami, Panginoon» pagkatapos ng bawat invocation ng deliverance («Mula sa lahat ng masama…»); «Kami nakikiusap sa Inyo, dinggin Mo kami» pagkatapos ng bawat petisyon ng supplication («Upang Inyong…»). Tinatagal ng litanya ng halos labinlima hanggang dalawampung minuto kapag inaawit sa solemneng tempo sa isang liturgical setting; mas kaunti kapag dinarasal sa bahay sa anyong sinasabi. Para sa pribadong devotion, maaaring dasalin ang litanya mula sa anumang inaprubahang printed text (ang Roman Missal, isang parish prayer book, o ang website ng CBCP). Kapag dinarasal sa bahay, umupo, tumayo, o lumuhod ayon sa nais; ang tempo ng litanya ay contemplative sa halip na nagmamadali. Nararapat na gamitin ang litanya: (1) sa Lahat ng Santo (1 ng Nobyembre) at Lahat ng Kaluluwa (2 ng Nobyembre) bilang dasal ng pamilya sa mga araw na iyon; (2) sa tabi ng kama ng isang grabe na maysakit o naghihingalo — maraming Catholic hospital chaplain ang nagdadasal ng litanya habang papalapit ang last rites; (3) sa simula ng isang mahalagang pilgrimage o family undertaking, humihingi na palibutan ng dakilang ulap ng mga saksi (Hebreo 12,1) ang mga petitioner; (4) sa panahon ng salot, sakuna, o pampublikong emergency, sa pagkakatuloy ng pagtatatag ni Gregorio Magno ng litanic processions sa panahon ng Romang salot ng 590. Ang particular na espirituwal na kaloob ng litanya ay ang nararamdamang presensya ng communion of saints — ang katotohanan na ang mga tapat na nagdarasal sa lupa at silang mga matagumpay sa langit ay iisang katawan kay Kristo.",
    patronSaint: null,
    feastDay: "1 ng Nobyembre (Lahat ng Santo)",
    source: "CBCP + Papa Pio V codification 1568 + post-Vatican II 1969 revision + Gregorio Magno 590 institution. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "prayer-expectant-mothers",
    name: "Panalangin para sa mga Nagdadalantao",
    description:
      "Ang Katolikong panalangin para sa mga nagdadalantao ay nagmumula sa siglo-siglong tradisyon ng Simbahan na samahan ang mga babae sa pagbubuntis sa ilalim ng patrocinio ng Mahal na Birheng Maria, na nagdala kay Kristo sa kanyang sariling sinapupunan ng siyam na buwan. Ang pangunahing biblical foundation ay ang Pagdalaw (Lucas 1,39-56): si Maria, na siya mismo nasa mga unang buwan ng pagbubuntis kay Hesus, nagmamadali patungo sa kabundukan ng Judea upang makasama ang kanyang pinsang si Isabel, na nasa kanyang ikaanim na buwan kay Juan Bautista. Ang Magnificat («Itinatampok ng aking kaluluwa ang Panginoon…») ay panalangin ng dalawang nagdadalantao na nagsasaya magkasama. Ang Katolikong devotional tradition ay matagal nang ipinagkatiwala ang mga nagdadalantao kay Maria sa ilalim ng ilang partikular na titulo: Nuestra Señora de la Expectación o ng O (ang Dakilang Kapistahan ng Disyembre 18, isang Spanish-tradition feast siyam na araw bago ang Pasko, na nagmamarka ng papalapit na panganganak ni Maria); Nuestra Señora de Guadalupe (na ang larawan ay nagpapakita sa kanya na nagdadalantao); at San Gerardo Majella (1726-1755), isang Italian Redemptorist lay brother na ang pangalan ay naging napakaugnay sa ligtas na panganganak na ang mga rebulto niya ay inilalagay sa maternity wards ng Catholic hospitals sa buong mundo. Nararapat ang panalangin para sa mga nagdadalantao sa bawat yugto ng pagbubuntis: sa unang positive test, sa pamamagitan ng first-trimester anxiety na nararamdaman ng maraming ina, sa loob ng mahabang gitnang mga buwan ng paghihintay, sa mga linggo ng paghahanda bago ang panganganak, sa panahon mismo ng panganganak (kapag madalas itong dinarasal ng mga miyembro ng pamilya sa tabi ng kama), at kaagad pagkatapos ng panganganak sa pasasalamat. Idinadasal din ito ng mga komunidad — mga parokya, prayer group, ang circle of friends ng babae — bilang paraan ng paligid sa kanya ng intercession sa loob ng siyam na buwan ng paghihintay na sumasalamin kay Maria.",
    instructions:
      "Magdasal isang beses sa isang araw para sa nagdadalantao, mainam sa parehong oras araw-araw upang ang gawain ay maging bahagi ng kanyang ordinaryong ritmo. Ang panalangin ay sapat na maikli upang isaulo; maraming nagdadalantao ang nagdadala nito sa isang maliit na card na nakatago sa isang Bibliya, libro ng dasal, o pitaka, at idinadasal habang naghihinto sila sa araw-araw na trabaho ng paghahanda para sa sanggol. Mga karaniwang gawain na ipinapares sa panalangin: (1) Magsindi ng kandila sa Marian shrine sa parish church para sa bawat buwan ng pagbubuntis — maraming parokya ang nag-iingat ng designated «expectant mothers» candle stand at iniaakda ang mga pangalan ng mga babaeng pinagdadasalan; (2) Magdasal ng pang-araw-araw na decade ng Rosaryo, nagninilay sa Joyful Mysteries (ang Pagbati, ang Pagdalaw, ang Pagsilang, ang Paghahandog, ang Pagkawala at Pagkahanap sa Templo); (3) Hingiin ang pamamagitan ni San Gerardo Majella — maaaring ipares ang panalangin para sa mga nagdadalantao sa nobena kay San Gerardo, lalo na sa siyam na araw bago ang panganganak; (4) Pang-pamilyang o pang-komunidad na panalangin sa tabi ng kama sa panahon ng panganganak, kung saan ang asawa ng nagdadalantao o ibang miyembro ng pamilya ay nagdadasal ng Memorare o ang panalangin na ito ng malakas habang umuusad ang panganganak. Malinaw ang Catholic tradition na ang pagbubuntis ay sa kanyang sarili ay isang anyo ng panalangin. Pagkatapos ng panganganak, nagpapatuloy ang panalangin sa pasasalamat at natural na bumabaling sa mga panalangin ng pagiging ina para sa bagong-silang.",
    patronSaint: "Mahal na Birhen",
    feastDay: null,
    source: "CBCP + Lucas 1,39-56 + tradisyon ni San Gerardo Majella. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "adoration-hour",
    name: "Banal na Oras ng Adorasyon",
    description:
      "Ang Banal na Oras ng Eucharistic Adoration ay isa sa pinakamatanda at pinakasentral na anyo ng Katolikong panalangin — patuloy, tahimik na panalangin sa real presence ni Jesucristo sa Banal na Sakramento, nakalantad sa monstrance sa altar. Direktang nagmumula ang gawain sa Gospel scene sa Gethsemani: tinanong ni Kristo ang mga apostol Niya, «Hindi ba kayo makapagbantay ng isang oras kasama ko?» (Mateo 26,40). Ang «isang oras» ay hindi arbitrary na haba — ito ang malinaw na hiling ng Panginoon sa gabi ng Kanyang pagpapakasakit, at direktang sinasagot ng Catholic Holy Hour ang hiling na iyon. Ang devotional practice ng sustained Eucharistic adoration ay nagcrystallize sa Counter-Reformation at binigyan ng particular na lakas sa pamamagitan ng mga pagpapakita ng Sagradong Puso kay Santa Margarita Maria Alacoque sa Paray-le-Monial (1673-1675); partikular na hinihiling ni Kristo kay Margarita Maria ang isang oras ng reparation sa Kanyang presensya tuwing Huwebes ng gabi, sa pag-alala sa Agonya sa Hardin. Ang Holy Hour ay naging sentral sa «Apostleship of Prayer» (itinatag 1844) at malawakang ipinangaral sa ikadalawampung siglo ni Venerable Fulton Sheen (1895-1979), na sikat na nag-commit sa Holy Hour araw-araw ng kanyang priestly life — mahigit 60 taon — at iniugnay ang bawat biyaya ng kanyang ministry sa oras na iyon. Ngayon ay maraming kapilya ng perpetual Eucharistic adoration ang gumagana sa libu-libong parokya sa buong mundo, pinangangalagaan ng mga lay volunteer na nag-cocommit sa mga partikular na oras sa kabuuan ng gabi at araw upang hindi kailanman maiwan si Kristo nang mag-isa sa Kanyang naka-exposed na Sakramento. Nararapat ang Holy Hour para sa: anumang sustained intercession, lalo na para sa kagalingan, pagbabago, o vocational discernment; reparation para sa kasalanan (sa sarili o sa mundo); espirituwal na pagkatuyo; paghahanda para sa mahalagang life decisions; pasasalamat pagkatapos tumanggap ng biyaya. Ito ang panalangin na tinawag ni Sheen na «ang sikreto ng bawat paring naging santo».",
    instructions:
      "Bisitahin ang iyong parokya sa mga oras ng Adoration — tingnan ang website o bulletin ng parokya para sa schedule. Maraming parokya ang nag-aalok ng Eucharistic adoration tuwing Huwebes (hiling ni Kristo kay Margarita Maria), Biyernes (ang tradisyonal na araw ng reparation), o bilang extended Holy Hour pagkatapos ng weekday Mass. May mga nagpapanatili ng perpetual adoration na may Blessed Sacrament na exposed 24/7. Sa pagdating: (1) Lumuhod sa parehong tuhod (ang tradisyonal na tanda ng paggalang sa exposed Eucharist, naiiba sa one-knee genuflection para sa reserved Sacrament sa tabernacle); (2) Maghanap ng lugar upang umupo o lumuhod; (3) Yumuko sa tahimik na pagkilala na nasa literal na presensya ka ng Diyos na nagkatawang-tao. Ang oras mismo ay walang structure ayon sa disenyo — ang patuloy na presensya ang dasal. Ang ilang patterns na ginagamit ng mga Katoliko upang punuin ang oras: (a) Magdasal ng Rosaryo, nagninilay sa Sorrowful Mysteries; (b) Magbasa ng Banal na Kasulatan (ang Passion narratives, ang Ebanghelyo ni Juan, ang mga Salmo); (c) Magdasal ng Chaplet of Divine Mercy, lalo na sa oras ng 3:00 PM; (d) Magbasa mula sa isang espirituwal na klasiko; (e) Umupo sa tahimik na presensya — ang pinakamataas na anyo ng contemplative prayer; (f) Magsulat ng usapan kay Hesus tungkol sa taong inihahandog mo ang oras. Sa buong oras, pangalanan ang tao at ang intensyon nang madalas. Nagtatapos ang oras sa isa pang genuflection at maikling dasal ng pasasalamat para sa regalo ng Kanyang presensya.",
    patronSaint: null,
    feastDay: null,
    source: "CBCP + Mateo 26,40 + mga pagpapakita ng Sagradong Puso sa Paray-le-Monial (1673-1675) + tradisyon ni Fulton Sheen. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "stations-of-the-cross",
    name: "Daan ng Krus (Stations of the Cross)",
    description:
      "Ang Daan ng Krus (tinatawag ding Way of the Cross, Via Crucis, o Via Dolorosa) ay isang meditative devotion kung saan sumusunod ang mananampalataya sa Pagpapakasakit ni Kristo sa labing-apat na natatanging stations — mga sandali sa Kanyang paglalakbay mula sa praetorium ni Pilato hanggang sa libingan. Nag-umpisa ang gawain sa pinakaunang Kristiyanong siglo bilang literal na peregrinasyon sa mga banal na lugar sa Jerusalem; naglalakad ang mga peregrino sa aktwal na landas na nilakaran ni Kristo, naghihinto sa bawat makabuluhang istasyon upang manalangin. Nang mahulog ang Jerusalem sa Muslim control noong ika-pitong siglo at ang peregrinasyon ay naging mapanganib at bihira, sinimulan ng mga Franciscan — na binigyan ng custody ng Holy Land ni Papa Clemente VI noong 1342 — ang muling pagtatayo ng Via Dolorosa sa anyo ng mga devotional station sa kanilang mga simbahan sa buong Europe, upang ang sinumang Katoliko ay maaaring «maglakad» sa Daan ng Krus nang espirituwal nang hindi naglalakbay sa Jerusalem. Ipinagkaloob ni Papa Inocencio XI sa mga Franciscan ang indulgences para sa pagdarasal ng mga stations noong 1686, at pinalawak ito ni Papa Clemente XII sa lahat ng tapat noong 1731. Ang standard na labing-apat na stations ay itinakda sa ikadalawampu't walong siglo: (1) Si Hesus ay hinatulan ng kamatayan; (2) Si Hesus ay binigyan ng Kanyang krus; (3) Si Hesus ay natumba sa unang pagkakataon; (4) Si Hesus ay nakatagpo ang Kanyang inang si Maria; (5) Tumutulong si Simon ng Cyrene kay Hesus na buhatin ang krus; (6) Pinunasan ni Veronica ang mukha ni Hesus; (7) Si Hesus ay natumba sa pangalawang pagkakataon; (8) Si Hesus ay nakatagpo ng mga babae ng Jerusalem; (9) Si Hesus ay natumba sa pangatlong pagkakataon; (10) Si Hesus ay hinubaran ng Kanyang mga damit; (11) Si Hesus ay ipinako sa krus; (12) Si Hesus ay namatay sa krus; (13) Si Hesus ay ibinaba mula sa krus; (14) Si Hesus ay inilibing. Ang Daan ng Krus ay tradisyonal na dinarasal tuwing Biyernes sa panahon ng Kuwaresma at ang sentral na pampublikong devotion ng Mahal na Araw sa karamihan ng Catholic parishes sa buong mundo. Pinangungunahan ng Papa ang Daan ng Krus sa Colosseum sa Roma tuwing Biyernes Santo.",
    instructions:
      "Bisitahin ang isang Katolikong simbahan — ang karamihan ay may labing-apat na stations na nakakabit sa mga side wall ng nave. Ang tradisyonal na gawain: (1) Magsimula sa unang istasyon; lumuhod; (2) Ipahayag ang istasyon nang malakas («Unang Istasyon: Si Hesus ay hinatulan ng kamatayan»); (3) Dasalin ang sagot na «Sinasamba Ka namin, O Kristo, at pinapurihan Ka namin, sapagkat sa Iyong banal na Krus, tinubos Mo ang mundo»; (4) Magnilay-nilay sandali sa eksenang Pasyon ni Kristo na tumutugma sa istasyon; (5) Magdasal ng Ama Namin, Aba Ginoong Maria, at Luwalhati; (6) Ialay ang istasyon sa iyong intensyon. Lumipat sa susunod na istasyon — pisikal na paglalakad mula sa isa patungo sa susunod ay bahagi ng panalangin; ang Daan ng Krus ay pinagniniig na lakaran. Kabuuang tagal: halos tatlumpu hanggang apatnapu't limang minuto kapag dinasal sa walang madaliang tempo sa isang simbahan. Sa bahay, isang printed Way of the Cross booklet ang gumagana — walang physical presence requirement. Ang devotion ay nararapat na dinasal: (a) Sa mga Biyernes sa panahon ng Kuwaresma, ang tradisyonal na Katolikong disiplina; (b) Sa Mahal na Araw mismo, ang araw na nilakad ni Kristo ang Via Dolorosa; (c) Sa anumang Biyernes sa buong taon; (d) Kapag pinapasan ang isang mabigat na personal na krus — sakit, lumbay, dependency, persekusyon — pinagsasama ang iyong paghihirap sa kay Kristo; (e) Kapag nagdadasal para sa isang nahihirapan o naghihingalo; (f) Kapag naghahanap ng biyaya ng pagtitiis sa pagdurusa.",
    patronSaint: null,
    feastDay: "Biyernes Santo",
    source: "CBCP + Franciscan custody of Holy Land (1342) + Papa Inocencio XI 1686 + Clemente XII 1731. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "morning-offering",
    name: "Pag-aalay sa Umaga",
    description:
      "Ang Pag-aalay sa Umaga ay ang pundasyong pang-araw-araw na panalangin ng Apostleship of Prayer — isang Catholic spiritual movement na itinatag noong 1844 ng Jesuit Father François-Xavier Gautrelet sa Vals, France, at pinangalanan muli noong 2015 ni Papa Francisco bilang Pope's Worldwide Prayer Network. Ang sentral na pananaw ng kilusan ay simple ngunit nagbabago: bawat ordinaryong aksyon ng araw ng isang Katoliko — trabaho, pag-aaral, pakikipag-usap, pagkain, pagod, kagalakan, paghihirap, kahit pagtulog — ay maaaring iaalay sa Diyos bilang intentional act of love, binabago ang buong araw sa isang sustained act of prayer. Ang Pag-aalay sa Umaga ang gumagawa ng pag-aalay na ito, dinarasal kaagad sa paggising, bago pa makontrol ng araw ang kalagayan. Ang traditional text — binuo sa huling bahagi ng ikadalawampung siglo at pinino sa pamamagitan ng ilang papal-approved versions — inilalagay ang pag-aalay ng araw «sa pamamagitan ng Immaculate Heart of Mary» at iniuugnay ito «sa Banal na Sakripisyo ng Misa sa buong mundo». Tuwing buwan, ang Papa ay naglalabas ng partikular na universal prayer intentions sa pamamagitan ng Pope's Worldwide Prayer Network — halimbawa, «para sa pag-aalaga sa mga bata» o «para sa pagtatapos ng human trafficking» — at ang mga Katolikong nagdadasal ng Pag-aalay sa Umaga ay iniuugnay ang maliliit na aksyon ng kanilang araw sa mas malawak na intensyon. Ang Pag-aalay sa Umaga ay isang makapangyarihang dasal ng intercession para sa partikular na tao: isang maysakit na miyembro ng pamilya, isang adult na anak na umalis sa pananampalataya, isang magulang na nakikipagbuno sa addiction.",
    prayerText:
      "O Hesus, sa pamamagitan ng Kalinis-linisang Puso ni Maria, inihahandog ko sa Iyo ang aking mga panalangin, gawain, kagalakan, at paghihirap sa araw na ito para sa lahat ng intensyon ng Iyong Sagradong Puso, sa pakikiisa sa Banal na Sakripisyo ng Misa sa buong mundo, sa pasasalamat sa Iyong mga biyaya, sa pagbabayad-puri sa aking mga kasalanan, para sa intensyon ng lahat ng aking mga kasama, at lalo na para kay (banggitin ang pangalan at intensyon ng tao). Amen.",
    instructions:
      "Magdasal kaagad sa paggising, bago pa makontrol ng abala ng araw ang kalagayan. Ang tradisyonal na disiplina ay idasal ito bago bumangon sa kama, habang ang isip ay malambot pa at ang araw ay parang regalo pa; ang ilang mga Katoliko ay nagdadasal sa unang tahimik na sandali ng morning routine (sa unang tasa ng kape, sa lababo ng kusina, habang pinapakain ang sanggol). Ang panalangin ay sapat na maikli upang isaulo sa isang araw lamang. Upang gawin itong bahagi ng buhay: (1) Ilagay ang panalangin sa lugar kung saan makikita mo agad — nakadikit sa salamin ng banyo, sa loob ng pintuan ng kuwarto, sa isang card sa tabi ng coffee maker; (2) Pangalanan ang partikular na tao at ang intensyon sa nararapat na lugar ng dasal (ang linyang «at lalo na para kay…»), na ginagawang concrete ang pag-aalay; (3) Sa buong araw, kapag ang trabaho ay naging mahirap o isang abala ang sumira sa iyong mga plano, sandali na lamang renewahin ang pag-aalay: «Ibinigay ko sa Iyo ang araw na ito para kay (pangalan); ang sandaling ito ay bahagi nito». Maraming Catholic households ang nagdadasal ng Pag-aalay sa Umaga nang malakas na magkasama habang bumabangon ang pamilya. Inilalathala ng Pope's Worldwide Prayer Network ang monthly universal intentions ng Papa. Para sa sustained intercession (isang nobena ng mga araw para sa maysakit na mahal sa buhay, ang tagal ng isang mahirap na discernment, ang mga buwan ng chemotherapy ng miyembro ng pamilya), ang Pag-aalay sa Umaga ay nagiging gulugod ng dasal.",
    patronSaint: null,
    feastDay: null,
    source: "CBCP + Apostleship of Prayer / Pope's Worldwide Prayer Network (1844, pinangalanan muli 2015). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "three-oclock-prayer",
    name: "Panalangin sa Ika-tatlo ng Hapon (Oras ng Awa)",
    description:
      "Ang Panalangin sa Ika-tatlo ng Hapon — tinatawag ding Oras ng Awa o Oras ng Dakilang Awa — ay ibinigay ni Hesus kay Santa Maria Faustina Kowalska sa mga rebelasyon ng Divine Mercy na nakatala sa kanyang Talaarawan: Divine Mercy in My Soul. Itinuro ni Hesus kay Faustina na ang 3:00 PM bawat araw — ang oras ng Kanyang kamatayan sa Kalbaryo — ay parangalan bilang Oras ng Dakilang Awa, kung saan ang isang maikling pagdarasal ay nakakakuha ng pambihirang biyaya. Ang eksaktong pangako, nakatala sa Talaarawan ni Faustina (entry 1320): «Sa ika-tatlo ng hapon, hingiin ang Aking awa, lalo na para sa mga makasalanan; at, kahit saglit lamang, isubsob ang iyong sarili sa Aking Pasyon, lalo na sa Aking pagpapabaya sa sandali ng paghihirap. Ito ang oras ng dakilang awa para sa buong mundo… Sa oras na ito hindi Ako tatanggi ng anuman sa kaluluwang humihingi sa Akin sa bisa ng Aking Pasyon». Tumutugma ang oras sa ikasiyam na oras ng Hudyong araw sa gospel chronology (Marcos 15,34) — ang oras kung kailan «sumigaw si Hesus ng malakas… at namatay» (Marcos 15,37). Ang Panalangin sa Ika-tatlo ng Hapon ang pinakasimple at pinaka-access na anyo ng Divine Mercy devotion — mas maikli pa kaysa sa chaplet, accessible sa kahit sino na maaaring huminto ng tatlumpung segundo sa oras ng kamatayan ni Kristo. Ito ang panalangin na inilalagay ng Catholic tradition sa puso ng araw para sa mga hindi kayang gumawa ng buong Holy Hour, na hindi kayang magdasal ng chaplet, na nasa trabaho o sa paaralan o sa tabi ng kama sa ospital. Ang devotion ay pinigil sa loob ng maraming taon (ang parehong panahon kung kailan ang mga sulat ni Faustina ay nasa provisional restriction), ngunit kinanonisa ng Papa San Juan Pablo II si Faustina noong April 30, 2000, at itinatag ang Divine Mercy Sunday bilang kapistahan para sa unibersal na Simbahan.",
    prayerText:
      "Naghingalo Ka, Jesus, ngunit ang bukal ng buhay ay umagos para sa mga kaluluwa, at ang karagatan ng awa ay nabuksan para sa buong mundo. O Bukal ng Buhay, hindi-masusukat na Awa ng Diyos, balutin Mo ang buong mundo at ibuhos Mo ang Iyong sarili sa amin. O Dugo at Tubig na umagos mula sa Puso ni Hesus bilang bukal ng awa para sa amin, nagtitiwala ako sa Iyo! Banal na Diyos, Banal na Makapangyarihan, Banal na Walang-hanggan, kaawaan Mo kami at ang buong mundo. (3 ulit)",
    instructions:
      "Sa 3:00 PM bawat araw, huminto nang sandali — anuman ang ginagawa mo — at magdasal. Ang panalangin ay sapat na maikli upang isaulo sa isang hapon at idasal kahit saan: sa isang desk, sa sasakyan, sa silid-aralan, sa tabi ng kama sa ospital, naglalakad sa bangketa. Malinaw ang Catholic tradition na «kahit isang sandali ng panalangin sa oras na ito ay makapangyarihan» — kung ang isang abala na buhay ay makakapag-alay lamang ng dalawampung segundo para sa isang «Hesus, nagtitiwala ako sa Iyo» sa 3:00 PM, ang maikling sandali na iyon mismo ang gawain. Para sa mga may mas maraming oras: (1) Idasal ang buong Chaplet of Divine Mercy (halos sampung minuto); (2) Gumawa ng maikling «pagbisita» sa kalapit na Katolikong simbahan o Eucharistic adoration chapel; (3) Huminto upang basahin ang isang talata mula sa Talaarawan ni Santa Faustina; (4) Magdasal para sa mga makasalanan — itinala ni Faustina na sinabi sa kanya ni Hesus na ito ang pinakamakapangyarihang intercession sa oras na ito. Ang mga tradisyonal na Katolikong disiplina na ipinapares sa Panalangin sa Ika-tatlo ng Hapon: (a) Magtakda ng pang-araw-araw na alarm sa 3:00 PM bilang paalala hanggang sa maging ugali; (b) Magdala ng maliit na Divine Mercy holy card; (c) Magdasal sa paanan ng krusipiho; (d) Magdagdag ng sandali ng pisikal na katahimikan.",
    patronSaint: "Santa Maria Faustina Kowalska",
    feastDay: null,
    source: "CBCP + Talaarawan ni Santa Faustina (1320) + JPII canonization April 30, 2000 + Marcos 15,34-37. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
];
