import type { PrayerTranslationSeed } from "./types";

/**
 * Polish (pl) translations of PrayerType content.
 *
 * Authoring conventions:
 *  - **Source tier**: KEP (Konferencja Episkopatu Polski), Vatican.va
 *    Polish, Wydawnictwo M / Salwator / Pallottinum publishers for
 *    canonical Polish prayer texts.
 *  - **Register**: liturgically formal. Polish Catholic devotional
 *    speech is more formal than pt-BR / fil; lean into that convention.
 *    Use established Polish prayer phrases ("Ojcze nasz", "Zdrowaś
 *    Maryjo", "Chwała Ojcu") rather than reinventing.
 *  - **Catholic register**: `módlmy się za` ("za" is the devotional
 *    preposition; matches the email dictionary convention).
 *  - **Brand names stay English**: `PrayerTrain`, `Surrender Novena`.
 *  - **`prayerText` left null** — canonical Polish prayer wording
 *    should be drawn from KEP / Vatican.va sources in a separate
 *    focused pass. Helper falls back to English prayer text under
 *    the Polish description + instructions.
 */
export const plTranslations: PrayerTranslationSeed[] = [
  {
    prayerSlug: "novena-sacred-heart",
    name: "Nowenna do Najświętszego Serca Jezusa",
    description:
      "Nowenna do Najświętszego Serca Jezusa jest jedną z najbardziej umiłowanych form pobożności w Kościele katolickim, narodzoną z objawień Jezusa świętej Małgorzacie Marii Alacoque w Paray-le-Monial we Francji w latach 1673-1675. W tych objawieniach Chrystus ukazał głębię swojej miłości do ludzkości, symbolizowanej przez Jego Serce przebite i ukoronowane cierniem, i poprosił, aby ta miłość była czczona przez nabożeństwo do Jego Najświętszego Serca. Nowenna obejmuje dziewięć kolejnych dni modlitwy (liczba dziewięć przypomina dziewięć dni, które apostołowie i Maryja spędzili na modlitwie między Wniebowstąpieniem a Zesłaniem Ducha Świętego) i jest tradycyjnie ofiarowana z ufnością w miłosierdzie Chrystusa wobec cierpiących. Jest szczególnie odpowiednia w czasach choroby, trudności rodzinnych, duchowej oschłości lub wytrwałych intencji, które dotąd nie znalazły odpowiedzi. Najświętsze Serce nie jest jedynie symbolem; jest historycznym, fizycznym Sercem Chrystusa, w pełni ludzkim i w pełni boskim, źródłem Jego nieskończonej miłości. Encyklika Haurietis Aquas papieża Piusa XII (1956) opisuje Najświętsze Serce jako «tron miłosierdzia» i potwierdza centralne miejsce tego nabożeństwa w życiu Kościoła. Wojownicy modlitwy, którzy ofiarowują tę nowennę, dołączają do wieków katolików, którzy złożyli swoją ufność w zranionym Sercu Zbawiciela.",
    instructions:
      "Módl się raz dziennie przez dziewięć kolejnych dni, mniej więcej o tej samej porze każdego dnia. Wybierz ciche miejsce i rozpocznij od Znaku Krzyża. Tradycyjna struktura: (1) modlitwa wstępna, często «O Najświętsze Serce Jezusa, w Tobie pokładam całą moją ufność»; (2) sam tekst nowenny; (3) Ojcze nasz, Zdrowaś Maryjo i Chwała Ojcu; (4) osobista intencja wymieniona głośno lub w milczeniu. Wielu dodaje Litanię do Najświętszego Serca Jezusa w ostatnim dniu lub modli się nowenną w połączeniu z nabożeństwem Pierwszych Piątków — przyjmując Komunię Świętą w dziewięć kolejnych pierwszych piątków, jak sam Chrystus prosił świętą Małgorzatę Marię. Nowenna może być odmawiana o każdej porze roku, ale jest szczególnie odpowiednia w miesiącu czerwcu (miesiąc Najświętszego Serca), w dniach poprzedzających Uroczystość Najświętszego Serca (piątek po Bożym Ciele), lub gdy ktoś staje wobec szczególnie trudnego momentu. Jeśli zostanie pominięty jeden dzień, tradycyjna rada brzmi: rozpocząć od pierwszego dnia zamiast pomijać; dyscyplina kolejnych dni modlitwy jest sama w sobie częścią łaski tej pobożności. Niektórzy modlą się każdego dnia nowenny za konkretną osobę; inni ofiarują wszystkie dziewięć dni za jedną intencję.",
    patronSaint: "Święta Małgorzata Maria Alacoque",
    feastDay: "Piątek po Bożym Ciele",
    source:
      "KEP materials in Polish + Vatican.va Polish-language editions + traditional Polish Catholic devotional sources for the Sacred Heart novena. Historical claims verified against Haurietis Aquas (Pius XII, 1956) and the published account of the Paray-le-Monial apparitions. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-st-joseph",
    name: "Nowenna do świętego Józefa",
    description:
      "Święty Józef, ojciec adopcyjny Jezusa i czysty oblubieniec Najświętszej Maryi Panny, jest jednym z najukochaniej szych pośredników w tradycji katolickiej. Choć Pismo Święte nie zapisuje od niego żadnego słowa, jego wierność jest niezaprzeczalna: ochronił Świętą Rodzinę w ucieczce do Egiptu, utrzymywał ich pracą swoich rąk i nauczył Jezusa rzemiosła stolarskiego oraz drogi wiernej męskości. Papież Pius IX nadał mu tytuł Patrona Kościoła Powszechnego w 1870 roku, a papież Franciszek ogłosił okres 2020-2021 Rokiem Świętego Józefa przez list apostolski Patris Corde («Z Sercem Ojca»). Ta nowenna czerpie z długiej tradycji katolickiej rozpoznającej świętego Józefa jako patrona ojców, robotników, rodzin, spraw nieruchomościowych i dobrej śmierci — czterech filarów jego ziemskiego posługiwania. Wzywany jest szczególnie w chwilach trudności finansowych, niezgody w rodzinie, problemów zawodowych i przy rozeznawaniu powołania. Wielu katolików zobowiązuje się do nowenny w dniach poprzedzających jedno z jego świąt: 19 marca (Uroczystość świętego Józefa, Oblubieńca Najświętszej Maryi Panny) lub 1 maja (święty Józef Robotnik, ustanowione przez papieża Piusa XII w 1955 roku dla uświęcenia pracy ludzkiej). Święta Teresa z Ávili napisała: «Innym świętym, jak się wydaje, Pan dał łaskę, by wspomagali nas w pewnych szczególnych potrzebach; lecz temu chwalebnemu świętemu, jak wiem z doświadczenia, dał łaskę, by wspomagał nas we wszystkich».",
    instructions:
      "Módl się raz dziennie przez dziewięć kolejnych dni. Tradycyjna struktura: rozpocznij od Znaku Krzyża; odmów tekst nowenny; zakończ Ojcze nasz, Zdrowaś Maryjo i Chwała Ojcu; wymień swoją konkretną intencję. Niektóre katolickie rodziny dodają Litanię do świętego Józefa lub siedem Ojcze nasz, Zdrowaś Maryjo i Chwała Ojcu na cześć Siedmiu Boleści i Siedmiu Radości świętego Józefa — tradycyjna pobożność związana z jego radosnymi i bolesnymi doświadczeniami w życiu Świętej Rodziny. Dla rodzin rozeznających ważną decyzję życiową (zmiana pracy, przeprowadzka, małżeństwo) zwyczajem jest rozpocząć nowennę dziewięć dni przed momentem, w którym decyzja musi być podjęta, prosząc o wstawiennictwo świętego Józefa o jasność i łaskę przyjęcia woli Bożej. Nowenna jest też tradycyjnie odmawiana w miesiącu marcu (miesiąc świętego Józefa) lub w połączeniu z popularną praktyką zakopywania figurki świętego Józefa w związku ze sprzedażą domu — tradycja ludowa, która podkreśla spokojną ufność, a nie przesąd. Czy nowenna jest odmawiana o rozeznanie powołania, o zaopatrzenie finansowe, o uzdrowienie rodziny czy o dobrą śmierć (jedno z czterech tradycyjnych celów tej pobożności), duch powinien być cichy i pracowicie ufny — sama postawa, którą święty Józef ukazał w Piśmie Świętym.",
    patronSaint: "Święty Józef",
    feastDay: "19 marca / 1 maja",
    source:
      "Patris Corde (Francis, 2020) + KEP materials in Polish + traditional Polish Catholic devotional sources for the St. Joseph novena. The St. Teresa of Ávila quotation is from her Życie (autobiography, chapter 6). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "holy-rosary",
    name: "Różaniec Święty",
    description:
      "Różaniec Święty jest centralnym nabożeństwem maryjnym Kościoła katolickiego — modlitwą kontemplacyjną, w której wierzący rozważa wielkie tajemnice życia, śmierci i zmartwychwstania Chrystusa, odmawiając powtarzające się dziesiątki Zdrowaś Maryjo. Różaniec w obecnym kształcie nabrał formy na przestrzeni wieków; tradycja głosi, że Najświętsza Maryja Panna dała Różaniec świętemu Dominikowi w 1208 roku jako duchową broń przeciwko herezji albigensów, a struktura piętnastu tajemnic została skodyfikowana przez papieża świętego Piusa V w 1569 roku. W 2002 roku papież święty Jan Paweł II dodał Tajemnice Światła w swoim liście apostolskim Rosarium Virginis Mariae, doprowadzając całość do dwudziestu tajemnic zgrupowanych w czterech zestawach. Każda dziesiątka jest medytacją: gdy palce poruszają się po koralikach, a usta wymawiają Zdrowaś Maryjo, umysł zatrzymuje się na chwili z Ewangelii — Zwiastowanie, Ukrzyżowanie, Zmartwychwstanie, Przemienienie. Różaniec nie jest pustym powtarzaniem (Mt 6,7), ale szkołą kontemplacji, pozwalającą rytmowi modlitw uwolnić umysł do refleksji nad tajemnicami zbawienia. Papieże, od Leona XIII (którego jedenaście encyklik o Różańcu pozostaje magisterialnymi punktami odniesienia) do Franciszka, wzywali wiernych do codziennej modlitwy Różańcem. To modlitwa ofiarowana w Lourdes, Fatimie i niezliczonych innych objawieniach maryjnych, oraz modlitwa najczęściej odmawiana przez katolickie rodziny zgromadzone przy łóżku chorego lub przy grobie.",
    instructions:
      "Pełny Różaniec składa się z pięciu dziesiątek, zazwyczaj odmawiany w około dwadzieścia minut. Rozpocznij od Znaku Krzyża i Składu Apostolskiego na krzyżyku. Na pierwszym dużym koraliku odmów Ojcze nasz; na każdym z trzech małych koralików, które następują, odmów Zdrowaś Maryjo (o wzrost trzech cnót teologalnych — wiary, nadziei i miłości); na następnym dużym koraliku odmów Chwała Ojcu. Następnie ogłoś pierwszą tajemnicę głośno i krótko rozważ jej znaczenie; odmów Ojcze nasz na dużym koraliku, dziesięć Zdrowaś Maryjo na dziesięciu małych koralikach (po jednym na koralik), kontynuując rozważanie tajemnicy, potem Chwała Ojcu i Modlitwę Fatimską («O mój Jezu, przebacz nam nasze grzechy, zachowaj nas od ognia piekielnego…»). Powtórz dla czterech kolejnych dziesiątek, ogłaszając każdą tajemnicę. Zakończ Pod Twoją obronę i modlitwą Różańca. Cztery zestawy tajemnic są tradycyjnie odmawiane: Tajemnice Radosne w poniedziałki i soboty (Zwiastowanie, Nawiedzenie, Narodzenie, Ofiarowanie, Znalezienie w świątyni); Bolesne we wtorki i piątki (Modlitwa w Ogrójcu, Biczowanie, Cierniem Ukoronowanie, Niesienie Krzyża, Ukrzyżowanie); Chwalebne w środy i niedziele (Zmartwychwstanie, Wniebowstąpienie, Zesłanie Ducha Świętego, Wniebowzięcie, Ukoronowanie Maryi); Światła w czwartki (Chrzest, Wesele w Kanie, Głoszenie Królestwa, Przemienienie, Ustanowienie Eucharystii). Dla pokrycia w PrayerTrain pojedyncza dziesiątka — lub nawet jedno Zdrowaś Maryjo ofiarowane z intencją — jest również ważną ofiarą Różańca.",
    patronSaint: "Matka Boża Różańcowa",
    feastDay: "7 października",
    source:
      "Rosarium Virginis Mariae (St. John Paul II, 2002) + Leo XIII's eleven rosary encyclicals + KEP-approved Polish prayer book editions of the Rosary text. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "chaplet-divine-mercy",
    name: "Koronka do Bożego Miłosierdzia",
    description:
      "Koronka do Bożego Miłosierdzia została dana przez Jezusa świętej Marii Faustynie Kowalskiej, polskiej zakonnicy, w serii objawień między 1931 a 1938 rokiem, zapisanych w jej Dzienniczku: Miłosierdzie Boże w mojej duszy. Koronka jest potężną modlitwą wstawienniczą ofiarowaną za nawrócenie grzeszników, pocieszenie umierających i miłosierdzie Boże dla całego świata. Jezus powiedział Faustynie, że kto odmówi tę koronkę, otrzyma «wielkie miłosierdzie w godzinie śmierci» — i że szczególnie raduje się tą modlitwą odmawianą o godzinie 15:00, Godzinie Miłosierdzia (godzinie Jego śmierci na Kalwarii). Koronka jest odmawiana na zwykłym różańcu, co czyni ją dostępną każdemu, kto ma różaniec, i zajmuje około dziesięciu minut. Nabożeństwo do Bożego Miłosierdzia było stłumione przez wiele lat, ale papież święty Jan Paweł II — sam Polak i rodak świętej Faustyny — kanonizował ją 30 kwietnia 2000 roku i ustanowił Święto Bożego Miłosierdzia (druga niedziela wielkanocna) jako święto dla całego Kościoła powszechnego. Koronka do Bożego Miłosierdzia stała się jedną z najczęściej odmawianych form pobożności we współczesnym Kościele, szczególnie cenioną przez kapelanów szpitalnych, wolontariuszy hospicjów i tych, którzy modlą się o nawrócenie bliskich. To codzienna modlitwa w Narodowym Sanktuarium Bożego Miłosierdzia w Stockbridge w Massachusetts i w Sanktuarium Bożego Miłosierdzia w Łagiewnikach w Krakowie — miejscu, gdzie Faustyna żyła, umarła i obecnie spoczywa.",
    instructions:
      "Używając zwykłego różańca pięciodziesiątkowego, rozpocznij od Znaku Krzyża, Ojcze nasz, Zdrowaś Maryjo i Składu Apostolskiego na krzyżyku i początkowych koralikach. Na każdym z pięciu dużych koralików (gdzie zazwyczaj odmawia się Ojcze nasz) odmów: «Ojcze Przedwieczny, ofiaruję Ci Ciało i Krew, Duszę i Bóstwo najmilszego Syna Twojego, a Pana naszego Jezusa Chrystusa na przebłaganie za grzechy nasze i całego świata». Na każdym z dziesięciu małych koralików każdej dziesiątki odmów: «Dla Jego bolesnej męki miej miłosierdzie dla nas i całego świata». Po wszystkich pięciu dziesiątkach zakończ trzykrotnym: «Święty Boże, Święty Mocny, Święty Nieśmiertelny, zmiłuj się nad nami i nad całym światem». Koronka jest szczególnie potężna, gdy odmawiana o godzinie 15:00 (Godzina Miłosierdzia), przy łóżku umierających, w dziewięć dni przed Niedzielą Bożego Miłosierdzia (Nowenna do Miłosierdzia Bożego, rozpoczynająca się w Wielki Piątek) oraz w chwilach osobistego cierpienia lub lęku. Można ją odmawiać w ciszy, na głos, samemu lub w grupie. Wiele parafii odmawia koronkę co tydzień, często w piątki, w pamięć o męce Chrystusa. Katolicy modlący się o nawrócenie lub spokojną śmierć bliskiej osoby często zobowiązują się do codziennego odmawiania koronki przez dłuższy okres — miesiąc, czas trwania choroby, czas poprzedzający ważną decyzję. Koronka naturalnie łączy się z udziałem w Nowennie do Bożego Miłosierdzia od Wielkiego Piątku do Niedzieli Bożego Miłosierdzia.",
    patronSaint: "Święta Faustyna Kowalska",
    feastDay: "Niedziela Miłosierdzia Bożego",
    source:
      "Dzienniczek: Miłosierdzie Boże w mojej duszy (św. Faustyna Kowalska) + canonical chaplet text approved by the Holy See following St. John Paul II's canonization of Faustina (April 30, 2000). The Łagiewniki Sanctuary's official Polish-language chaplet text is the canonical source. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "memorare",
    name: "Modlitwa Memorare (Pomnij)",
    description:
      "Memorare jest krótką, ale niezwykle potężną modlitwą zaufania we wstawiennictwo Najświętszej Maryi Panny. Bierze swoją nazwę od pierwszego łacińskiego słowa tekstu, Memorare («Pomnij»), i w obecnej formie przypisywana jest księdzu Claude'owi Bernardowi, francuskiemu kapłanowi z XVII wieku znanemu jako «Ubogi Kapłan» ze względu na jego apostolstwo wśród więźniów i umierających. Modlitwa zyskała popularność dzięki rozdaniu przez księdza Bernarda ponad 200 000 ulotek w Paryżu przed Rewolucją, choć jej korzenie pobożności sięgają dalej — prawdopodobnie do dłuższej modlitwy przypisywanej świętemu Bernardowi z Clairvaux (1090-1153), wielkiemu cysterskiemu opatowi i Doktorowi Kościoła, którego maryjne nabożeństwo ukształtowało zachodnią pobożność. Struktura modlitwy jest pełnym ufności wezwaniem: uznaje powszechne macierzyństwo Maryi («O Dziewico nad dziewicami, moja Matko»), odwołuje się do nieprzerwanej tradycji Jej wstawiennictwa («nigdy nie słyszano, by ktokolwiek, kto uciekał się pod Twoją opiekę… został opuszczony»), i kończy pokorną prośbą («w Twoim miłosierdziu wysłuchaj mnie i odpowiedz mi»). Święci na przestrzeni wieków świadczyli o jej mocy: Matka Teresa z Kalkuty odmawiała dziewięć kolejnych Memorare codziennie — co nazywała swoją «pospieszną nowenną» — gdy potrzebowała czegoś szybko. Memorare jest katolicką modlitwą ostatniej deski ratunku, odmawianą w chwilach intensywnej potrzeby, przy łóżku umierających, w kaplicy przed trudną rozmową, lub szeptaną gdy rodzic czeka na wieści z sali szpitalnej.",
    instructions:
      "Odmów raz z pełnym skupieniem i pobożnością, przywołując w pamięci osobę i intencję, którą przedstawiasz Maryi. Memorare jest wystarczająco krótkie, aby zapamiętać i odmawiać wszędzie — w samochodzie, na spacerze, przed snem, w chwilach poprzedzających każde trudne zadanie. Dla bardziej trwałego wstawiennictwa odmów dziewięć kolejnych Memorare z rzędu (to jest «pospieszna nowenna», którą preferowała Matka Teresa dla pilnych intencji). Niektóre tradycje dodają krótki moment ciszy przed modlitwą, wymieniając intencję głośno lub w sercu. Modlitwa może być również włączona jako modlitwa kończąca dłuższy Różaniec lub nowennę, pieczętując prośbę pełnym ufności macierzyńskim oddaniem Maryi. Katolickie rodziny często odmawiają Memorare przy łóżku ciężko chorych, na wieść o trudnej diagnozie lub podczas porodu. Ponieważ modlitwa jest krótka, a jej słowa starożytne i ukochane, stała się rodzajem duchowej reakcji awaryjnej — modlitwy, która automatycznie napływa na usta, gdy brakuje innych słów. Dzieci mogą uczyć się jej tak wcześnie, jak tylko potrafią ją wyrecytować; jest to jedna z najodpowiedniejszych modlitw do nauczenia dziecka jako «pierwszej modlitwy w trudnych chwilach». Łacińska wersja oryginalna jest czasami wciąż odmawiana przez tych, którzy są przyciągani do form tradycyjnych: «Memorare, O piissima Virgo Maria, non esse auditum a saeculo…»",
    patronSaint: "Święty Bernard z Clairvaux",
    feastDay: null,
    source:
      "KEP-approved Polish devotional text of the Memorare (Pomnij) + traditional Polish Catholic prayer books. Historical attribution to Fr. Claude Bernard verified against the Catholic Encyclopedia entry. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── Round 2: 6 more prayers from PR #71 ────────────────────
  {
    prayerSlug: "novena-st-jude",
    name: "Nowenna do świętego Judy Tadeusza",
    description:
      "Święty Juda Tadeusz, zwany Apostołem Nadziei, był jednym z Dwunastu i krewnym Pana. Jest wymieniony w Ewangeliach jako jeden z apostołów (Łk 6,16) i jest autorem krótkiego Listu Judy. Przez wieki popularna pobożność katolicka wzywała świętego Judę jako patrona spraw rozpaczliwych. Powody podawane przez tradycję są praktyczne: ponieważ jego imię (Juda) było łatwo mylone z Judaszem Iskariotą, zdrajcą, jego wstawiennictwo było unikane przez zwykłych chrześcijan przez wieki — i dlatego, jak głosi przysłowie, pragnie pomóc każdemu, kto zwraca się do niego w prawdziwej potrzebie. Współczesna pobożność do świętego Judy została spopularyzowana w Stanach Zjednoczonych przez ojców klaretynów (Narodowe Sanktuarium świętego Judy w Chicago, 1929). W Polsce święty Juda Tadeusz jest patronem trudnych spraw zawodowych i sytuacji wymagających szczególnego zaufania w Bożą Opatrzność.",
    instructions:
      "Módl się raz dziennie przez dziewięć kolejnych dni. Struktura: rozpocznij od Znaku Krzyża; odmów tekst nowenny; zakończ Ojcze nasz, Zdrowaś Maryjo i Chwała Ojcu; wymień intencję. Nowenna szczególnie odpowiednia w dziewięć dni poprzedzających święto świętego Judy (28 października).",
    patronSaint: "Święty Juda Tadeusz",
    feastDay: "28 października",
    source: "KEP Polish + Claretian National Shrine (Chicago, 1929). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-divine-mercy",
    name: "Nowenna do Miłosierdzia Bożego",
    description:
      "Nowenna do Miłosierdzia Bożego została dana przez Jezusa świętej Marii Faustynie Kowalskiej, polskiej zakonnicy, w serii objawień zapisanych w jej Dzienniczku. Papież święty Jan Paweł II — sam Polak i rodak — kanonizował ją 30 kwietnia 2000 roku i ustanowił Święto Miłosierdzia Bożego (drugą niedzielę wielkanocną) jako święto dla Kościoła powszechnego. Nowenna rozpoczyna się w Wielki Piątek. Każdy z dziewięciu dni przyprowadza inną kategorię dusz przed tron miłosierdzia. Duchowym domem nowenny jest Sanktuarium Miłosierdzia Bożego w Łagiewnikach w Krakowie — miejsce szczególne dla polskiej pobożności.",
    instructions:
      "Módl się raz dziennie przez dziewięć kolejnych dni, zaczynając w Wielki Piątek. Każdy dzień ma swoją intencję i modlitwę wstępną. Po otwarciu dnia, modlitwa kończy się Koronką do Miłosierdzia Bożego. Pełna nowenna trwa około piętnaście minut dziennie.",
    patronSaint: "Święta Faustyna Kowalska",
    feastDay: "Niedziela Miłosierdzia Bożego",
    source: "Dzienniczek św. Faustyny + Sanktuarium Łagiewniki Kraków. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-our-lady-perpetual-help",
    name: "Nowenna do Matki Bożej Nieustającej Pomocy",
    description:
      "Matka Boża Nieustającej Pomocy to jeden z najukochaniej szych tytułów maryjnych w Kościele katolickim. Nabożeństwo skupia się wokół XV-wiecznej bizantyjskiej ikony przedstawiającej Dzieciątko Jezus w ramionach Maryi, podczas gdy archaniołowie Michał i Gabriel zbliżają się z narzędziami Męki Pańskiej. Ikona została powierzona przez papieża Piusa IX ojcom redemptorystom w 1866 roku z zaleceniem: «Uczyńcie ją znaną na całym świecie». W Polsce nabożeństwo jest mocne, szczególnie w parafiach redemptorystowskich; cotygodniowa nowenna we środy jest tradycyjną polską praktyką.",
    instructions:
      "Módl się raz dziennie przez dziewięć kolejnych dni. Tradycyjna struktura: (1) Znak Krzyża; (2) Odmów modlitwę nowenny; (3) Zakończ trzema Zdrowaś Maryjo i «Pod Twoją obronę»; (4) Wymień intencję. Wiele polskich parafii organizuje cotygodniowe nabożeństwa we środy.",
    patronSaint: "Matka Boża Nieustającej Pomocy",
    feastDay: "27 czerwca",
    source: "Redemptorist tradition + KEP Polish + Pius IX 1866 entrustment. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "litany-sacred-heart",
    name: "Litania do Najświętszego Serca Pana Jezusa",
    description:
      "Litania do Najświętszego Serca Pana Jezusa jest jedną z sześciu litanii zatwierdzonych przez Stolicę Apostolską. Skomponowana w 1718 roku przez siostrę Joannę Magdalenę Joly z Zakonu Wizytek w Dijon. Papież Leon XIII zatwierdził litanię formalnie do publicznego użytku liturgicznego 2 kwietnia 1899 roku — w tym samym roku poświęcił całą ludzkość Najświętszemu Sercu w encyklice Annum Sacrum. Litania jest zbudowana z trzydziestu trzech wezwań odpowiadających trzydziestu trzem latom ziemskiego życia Chrystusa. Na każde wezwanie odpowiada się «Zmiłuj się nad nami».",
    instructions:
      "Litania odmawiana responsoryjnie. Prowadzący wypowiada każde wezwanie, wspólnota odpowiada. Trzydzieści trzy wezwania do Serca Jezusa, każde z odpowiedzią «Zmiłuj się nad nami». Czas trwania: dziesięć do piętnastu minut. Odpowiednia: Pierwsze Piątki; miesiąc czerwiec; Godzina Święta.",
    patronSaint: "Najświętsze Serce Pana Jezusa",
    feastDay: "Piątek po Bożym Ciele",
    source: "Annum Sacrum (Leo XIII, 1899) + KEP Polish. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "litany-blessed-virgin",
    name: "Litania Loretańska do Najświętszej Maryi Panny",
    description:
      "Litania Loretańska jest najstarszą i najukochaniej szą maryjną litanią Kościoła łacińskiego. Bierze swoją nazwę od Świętego Domku w Loreto we Włoszech. Papież Sykstus V formalnie zatwierdził litanię w 1587 roku. Polska tradycja Nabożeństw Majowych — codziennie w maju przed obrazem Matki Bożej — ma w sobie Litanię Loretańską jako centralną modlitwę. W ciągu wieków papieże dodawali wezwania, ostatnio Franciszek dodał «Matko Miłosierdzia», «Matko Nadziei», «Pociecho Migrantów» (2020).",
    instructions:
      "Litania odmawiana responsoryjnie. Prowadzący wypowiada każdy tytuł Maryi, wspólnota odpowiada «Módl się za nami». Polska tradycja Nabożeństw Majowych — codzienne nabożeństwo w maju — ma Litanię Loretańską jako centralną modlitwę. Tradycyjnie odmawiana po Różańcu Świętym.",
    patronSaint: "Najświętsza Maryja Panna",
    feastDay: null,
    source: "Sixtus V 1587 + papal additions through Francis 2020 + KEP Polish. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "prayer-conversion",
    name: "Modlitwa o Nawrócenie Bliskiej Osoby",
    description:
      "Katolicka modlitwa o nawrócenie bliskiej osoby jest zakorzeniona w długiej, wiernej modlitwie świętej Moniki za jej syna świętego Augustyna. Monika modliła się przez lata, przez łzy i radę świętego Ambrożego z Mediolanu («Nie jest możliwe, aby syn tylu łez zginął»). Augustyn został ochrzczony w 387 roku; Monika zmarła wkrótce potem w Ostii. Augustyn zapisał jej wytrwałość w Wyznaniach (Księga IX).",
    instructions:
      "Módl się codziennie, najlepiej o tej samej porze i w tej samej postawie. Wymień osobę głośno w modlitwie. Wielu katolików łączy tę modlitwę z: (1) codziennymi małymi poświęceniami; (2) Mszą świętą w dzień św. Moniki (27 sierpnia) lub św. Augustyna (28 sierpnia); (3) Nowenną do św. Moniki; (4) Koronką do Miłosierdzia Bożego o 15:00.",
    patronSaint: "Święta Monika",
    feastDay: "27 sierpnia",
    source: "Augustine's Confessions Book IX + KEP Polish. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── Locale-anchored devotions (Poland) ────────────────────
  {
    prayerSlug: "novena-czestochowa",
    name: "Nowenna do Matki Bożej Częstochowskiej",
    description:
      "Matka Boża Częstochowska — Czarna Madonna — jest centralnym maryjnym nabożeństwem polskiego katolicyzmu i ikoną w sercu polskiej tożsamości narodowej. Obraz, ikona Maryi trzymającej Dzieciątko Jezus, namalowana na drewnie cyprysowym, jest umieszczony w klasztorze Jasnogórskim w Częstochowie. Tradycja przypisuje malowanie ikony świętemu Łukaszowi Ewangeliście; współczesna analiza historii sztuki datuje obecny obraz na późne średniowiecze. Ikona przybyła na Jasną Górę w 1382 roku, sprowadzona z Bełza przez księcia Władysława Opolczyka jako dar dla nowo założonego klasztoru paulinów. Dwa równoległe rysy na prawym policzku Maryi — najbardziej rozpoznawalna cecha ikony — datują się na 1430 rok, gdy husyci splądrowali klasztor i pocięli obraz; tradycja głosi, że obraz krwawił, przerażając napastników. Ikona stała się centralna dla polskiej świadomości narodowej podczas «Potopu» szwedzkiego z 1655 roku: gdy praktycznie cała Polska upadła pod siłami szwedzkimi protestanckimi, sam mały klasztor Jasnogórski wytrzymał — niewielka grupa paulinów i polskich żołnierzy broniła go przez sześciotygodniowe oblężenie. Szwedzi się wycofali, a król Jan II Kazimierz formalnie ogłosił Maryję Królową Polski w katedrze lwowskiej w 1656 roku. Papież Pius XI udzielił obrazowi kanonicznej koronacji jako Królowej Polski w 1717 i 1923 roku. Przez wieki polskich rozbiorów, okupacji, komunistycznej supresji i odnowy, Czarna Madonna była duchowym sercem polskiej katolickiej tożsamości. Papież święty Jan Paweł II, urodzony Karol Wojtyła w 1920 roku, wielokrotnie pielgrzymował na Jasną Górę zarówno przed jak i po swoim wyborze.",
    instructions:
      "Módl się raz dziennie przez dziewięć kolejnych dni. Nowenna jest tradycyjnie odmawiana w ciągu dziewięciu dni poprzedzających święto Matki Bożej Częstochowskiej (26 sierpnia) lub święto Najświętszej Maryi Panny Królowej Polski (3 maja). Struktura nowenny: (1) Znak Krzyża; (2) Czytanie krótkiej refleksji o historii ikony lub polskiej katolickiej tożsamości; (3) Modlitwa nowennowa; (4) Trzy Zdrowaś Maryjo; (5) Wymienienie konkretnej intencji. Wiele polskich katolickich rodzin modli się nowennę przed domową reprodukcją ikony — obraz Czarnej Madonny jest jednym z najszerzej kopiowanych katolickich ikon na świecie. Pielgrzymka na Jasną Górę pozostaje potężnym elementem polskiego życia pobożnościowego: każdego sierpnia, setki tysięcy pielgrzymów idzie pieszo z Warszawy, Krakowa i innych polskich miast do klasztoru, przybywając na lub przed Uroczystość Wniebowzięcia (15 sierpnia). W polskiej-amerykańskiej diasporze — skoncentrowanej w Chicago, Nowym Jorku i parafiach Nowej Anglii — Częstochowska Niedziela w końcu sierpnia jest obchodzona z procesjami, śpiewem «Czarnej Madonny» i polską Mszą. Nowenna jest odpowiednia dla: każdego momentu narodowego lub osobistego kryzysu; nawrócenia członków rodziny; ochrony nienarodzonych; uzdrowienia duchowego w długim łuku pokoleń.",
    patronSaint: "Matka Boża Częstochowska, Królowa Polski",
    feastDay: "26 sierpnia",
    source: "Jasna Góra Monastery devotional sources + Jan II Kazimierz's 1656 proclamation + KEP Polish. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-maximilian-kolbe",
    name: "Nowenna do świętego Maksymiliana Marii Kolbego",
    description:
      "Święty Maksymilian Maria Kolbe (1894-1941) był polskim franciszkaninem konwentualnym, dziennikarzem, misjonarzem i męczennikiem Auschwitz — jednym z najpotężniejszych świadectw XX wieku. Urodzony jako Rajmund Kolbe pod Łodzią w rozbiorowej Polsce, w dzieciństwie doświadczył wizji Najświętszej Maryi Panny: ofiarowała mu dwie korony, jedną białą (czystość) i jedną czerwoną (męczeństwo), i zapytała, którą wybierze. Wybrał obie. Wstąpił do franciszkanów konwentualnych w wieku szesnastu lat, został wyświęcony na kapłana w 1918 roku i założył Rycerstwo Niepokalanej (Militia Immaculatae) w 1917 roku, maryjny apostolat poświęcony nawróceniu grzeszników i szerzeniu nabożeństwa do Niepokalanego Poczęcia. Założył Niepokalanów («Miasto Niepokalanej») pod Warszawą w 1927 roku, który urósł do jednego z największych domów zakonnych na świecie; bracia tam publikowali masowy nakład Rycerza Niepokalanej, który osiągnął milion czytelników do końca lat 30. W latach 1930-1936 służył jako misjonarz w Japonii, zakładając Mugenzai no Sono («Ogród Niepokalanej») w Nagasaki — klasztor który, wbrew wszelkim oczekiwaniom, przetrwał bombardowanie atomowe z 1945 roku nienaruszony. Wracając do Polski w przededniu II wojny światowej, schronił około 2000 żydowskich uchodźców w Niepokalanowie. Został aresztowany przez Gestapo 17 lutego 1941 roku i przeniesiony do Auschwitz 28 maja 1941 roku jako więzień numer 16670. W lipcu 1941 roku, po ucieczce więźnia z bloku 14, komendant obozu wybrał dziesięciu mężczyzn do śmierci głodowej w odwecie. Jeden z wybranych, Franciszek Gajowniczek, zawołał z udręką o swoją żonę i dzieci. Kolbe wystąpił i poprosił, by zająć miejsce Gajowniczka. Wymiana została dozwolona. Kolbe spędził dwa tygodnie w bunkrze głodowym, prowadząc innych skazanych w modlitwie i pieśni; był ostatnim, który umarł, zabity śmiertelnym zastrzykiem 14 sierpnia 1941 roku, w wigilię Wniebowzięcia. Papież święty Jan Paweł II — sam Polak, który przeżył tę samą nazistowską okupację — kanonizował Kolbego jako «męczennika miłości» w 1982 roku, ogłaszając go «patronem naszego trudnego stulecia». Franciszek Gajowniczek przeżył wojnę i dożył 1995 roku, świadcząc przez pięćdziesiąt trzy lata o człowieku, który zmarł zamiast niego.",
    instructions:
      "Módl się raz dziennie przez dziewięć kolejnych dni. Nowenna jest tradycyjnie odmawiana w dziewięć dni poprzedzających święto świętego Maksymiliana Kolbego (14 sierpnia) lub w związku z 15-sierpniową Uroczystością Wniebowzięcia (Kolbe zmarł w wigilię Wniebowzięcia, oblekając czas swojej śmierci w maryjne znaczenie). Struktura nowenny: (1) Znak Krzyża; (2) Czytanie krótkiej refleksji o momencie z życia Kolbego — jego wizji dwóch koron, jego założeniu Niepokalanowa, jego japońskiej misji, jego ofierze w Auschwitz; (3) Modlitwa nowennowa; (4) Trzy Zdrowaś Maryjo (na cześć jego maryjnego nabożeństwa); (5) Wymienienie konkretnej intencji. Nowenna jest szczególnie odpowiednia dla: każdego w więzieniu lub uwięzieniu, uchodźców i wysiedlonych, tych zmagających się z uzależnieniem (Kolbe jest patronem uzależnionych, szczególnie od narkotyków), dziennikarzy i pisarzy w trudnych powołaniach, rodzin pod zagrożeniem, i sprawy pro-life (świadectwo Kolbego — oddania życia, by ojciec mógł wrócić do swoich dzieci — uczyniło go potężnym orędownikiem nienarodzonych i ojców). Rycerstwo Niepokalanej kontynuuje dziś jako międzynarodowy maryjny apostolat. Cela w Auschwitzu, gdzie Kolbe zmarł (Blok 11, Cela 18), jest zachowana jako miejsce pielgrzymki.",
    patronSaint: "Święty Maksymilian Maria Kolbe",
    feastDay: "14 sierpnia",
    source: "Polish Conventual Franciscan sources + Niepokalanów + Auschwitz Block 11 documentation + JPII canonization homily (1982). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── ROUND 3 (pl) ──────────────────────────────────────────
  {
    prayerSlug: "litany-st-joseph",
    name: "Litania do świętego Józefa",
    description:
      "Litania do świętego Józefa jest jedną z sześciu litanii zatwierdzonych przez Stolicę Apostolską do publicznego użytku liturgicznego w obrządku łacińskim. Powstawała stopniowo w XVII i XVIII wieku w miarę pogłębiania się nabożeństwa do świętego Józefa w całym świecie katolickim; otrzymała formalne magisterialne zatwierdzenie od papieża świętego Piusa X 18 marca 1909 roku, w wigilię uroczystości świętego Józefa, jako Oblubieńca Maryi, przybranego ojca Jezusa i Patrona Kościoła Powszechnego. Struktura litanii odpowiada wzorcowi innych zatwierdzonych katolickich litanii: otwarcie Kyrie, inwokacja trynitarna, a następnie długa sekwencja wezwań kierowanych do świętego Józefa pod różnymi tytułami, z każdym z odpowiedzią «Módl się za nami»: «Sławny potomku Dawida», «Światło patriarchów», «Oblubieńcze Bogarodzicy», «Czysty Stróżu Dziewicy», «Żywicielu Syna Bożego», «Troskliwy obrońco Chrystusa», «Głowo świętej Rodziny», «Józefie najsprawiedliwszy», «Józefie najczystszy», «Józefie najroztropniejszy», «Zwierciadło cierpliwości», «Miłośniku ubóstwa», «Wzorze pracujących», «Ozdobo życia rodzinnego», «Opiekunie dziewic», «Filaru rodzin», «Pociecho strapionych», «Nadziejo chorych», «Patronie umierających», «Postrachu duchów piekielnych», «Opiekunie Kościoła świętego». W maju 2021 roku, w związku z Rokiem świętego Józefa (grudzień 2020 - grudzień 2021) i listem apostolskim Patris Corde, papież Franciszek formalnie dodał siedem nowych wezwań do litanii, zaczerpniętych bezpośrednio z języka Patris Corde: «Opiekunie Odkupiciela», «Sługo Chrystusa», «Sługo zbawienia», «Wsparcie w trudnościach», «Patronie wygnańców», «Patronie strapionych» i «Patronie ubogich». Te dodatki odzwierciedlają specyficzne pastoralne ujęcie Franciszka świętego Józefa jako wzoru dla ojców, robotników i marginalizowanych we współczesnym świecie.",
    instructions:
      "Litanię odmawia się responsoryjnie. Prowadzący wymawia każde wezwanie («Józefie najsprawiedliwszy…») a zgromadzeni odpowiadają «Módl się za nami» na każde z nich. Wstępny wzór Kyrie i inwokacja trynitarna używają «Zmiłuj się nad nami» jako odpowiedzi; korpus litanii — długa sekwencja tytułów — używa «Módl się za nami». Litania kończy się trzema wezwaniami do Baranka Bożego (Agnus Dei), parą wersetowo-responsoryjną zaczerpniętą z Księgi Rodzaju («Ustanowił go panem domu swego, I rządcą wszystkiej posiadłości swojej»), i kolektą do świętego Józefa. Całkowity czas wynosi około dziesięciu minut, gdy modli się w niespiesznym tempie dewocyjnym. Litania do świętego Józefa jest tradycyjnie odmawiana: w miesiącu marcu, miesiącu świętego Józefa; w dniach poprzedzających uroczystość świętego Józefa (19 marca) lub święto świętego Józefa Rzemieślnika (1 maja); pod koniec Godziny świętej lub adoracji eucharystycznej; w kontekstach rodzinnych proszących o opiekę świętego Józefa nad domem. Dodatki z 2021 roku można włączyć do każdego tradycyjnego wydrukowanego tekstu, wstawiając siedem nowych wezwań w odpowiednie miejsca w sekwencji litanii (większość aktualnie publikowanych wersji je wymienia); zarówno Konferencja Episkopatu Polski (KEP), jak i strona Stolicy Apostolskiej publikują zaktualizowany pełny oficjalny tekst po polsku. Wiele katolickich rodzin modli się litanią razem w środowe wieczory (tradycyjny dzień poświęcony świętemu Józefowi w starszym katolickim kalendarzu dewocyjnym). Gdy modli się samemu, po prostu czytaj zarówno wezwanie, jak i odpowiedź na głos lub w ciszy.",
    patronSaint: "święty Józef",
    feastDay: "19 marca",
    source: "KEP + Patris Corde (papież Franciszek, 8 grudnia 2020) + zatwierdzenie papieża Piusa X z 1909 roku. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-holy-spirit",
    name: "Nowenna do Ducha Świętego",
    description:
      "Nowenna do Ducha Świętego jest pierwotną nowenną — wzorcem modlitwy, od którego pochodzi każda inna katolicka dziewięciodniowa nowenna. Jej fundament biblijny stanowią Dzieje Apostolskie: «Wszyscy oni trwali jednomyślnie na modlitwie razem z niewiastami, Maryją, Matką Jezusa, i braćmi Jego» (Dz 1,14). Przez dziewięć dni po Wniebowstąpieniu Chrystusa uczniowie i Najświętsza Maryja Panna pozostawali w wieczerniku w Jerozolimie na modlitwie; dziesiątego dnia, w uroczystość Pięćdziesiątnicy (Dz 2,1-4), Duch Święty zstąpił na nich z szumem gwałtownego wiatru i językami ognia. Każda kolejna katolicka nowenna czerpie swój dziewięciodniowy wzór z tego jedynego precedensu danego przez Ducha. Nowenna wzywa siedem darów Ducha Świętego wymienionych w Księdze Izajasza 11,2-3: mądrość, rozum, rada, męstwo, umiejętność, pobożność i bojaźń Boża. Do nich tradycja katolicka dodaje dwanaście owoców Ducha Świętego wymienionych w Liście do Galatów (5,22-23 w enumeracji Wulgaty): miłość, radość, pokój, cierpliwość, uprzejmość, dobroć, wspaniałomyślność, łagodność, wierność, skromność, wstrzemięźliwość i czystość. Ton nowenny jest błagalny, ale ufny — Duch jest darem, który Jezus obiecał posłać (J 14,16-17; 16,7-15), a Kościół modli się z ufnością, że ten sam Duch, który zstąpił na apostołów, nadal zstępuje na wiernych. Nowenna jest szczególnie odpowiednia dla rozeznawania powołania, namaszczenia chorych, przygotowania tych, którzy przyjmują sakramenty (bierzmowanie, małżeństwo, święcenia kapłańskie), i każdego momentu, gdy dusza odczuwa, że nie może znaleźć jasności sama z siebie i potrzebuje natchnienia Ducha.",
    instructions:
      "Módl się raz dziennie przez dziewięć kolejnych dni. Tradycyjnie nowenna jest odmawiana między Wniebowstąpieniem a niedzielą Zesłania Ducha Świętego — pierwotnymi dziewięcioma dniami, które Kościół modlił się nieprzerwanie od czasów apostołów. (W diecezjach, gdzie Wniebowstąpienie jest przeniesione na niedzielę następującą po tradycyjnym czwartku, nowenna zaczyna się w piątek po tej niedzieli; sprawdź lokalny kalendarz liturgiczny.) Nowennę można również odmawiać o każdej innej porze roku w prywatnej intencji. Tradycyjna struktura na każdy dzień: (1) Rozpocznij od Znaku Krzyża; (2) Recytuj lub śpiewaj Veni Creator Spiritus («Przyjdź, Duchu Stworzycielu») lub Veni Sancte Spiritus («Przyjdź, Duchu Święty») — dwie wielkie łacińskie sekwencje Zesłania Ducha Świętego; (3) Odmów modlitwę nowenny; (4) Medytuj krótko nad jednym z siedmiu darów Ducha (jeden na dzień przez pierwsze siedem dni; w dniach ósmym i dziewiątym nad dwunastoma owocami i osobistą intencją); (5) Zakończ Ojcze Nasz, Zdrowaś Maryjo i Chwała Ojcu. Całkowity czas wynosi około dziesięciu minut dziennie. Rodziny z małymi dziećmi często odmawiają krótszą wersję, używając tylko wezwania Przyjdź, Duchu Święty i wyjaśnienia jednego daru dziennie odpowiedniego dla dziecka. Nowenna jest również odpowiednia przed ważną decyzją, przed trudną rozmową lub przed jakimkolwiek zadaniem, w którym osoba potrzebuje rady, męstwa lub mądrości wykraczającej poza jej naturalne możliwości.",
    patronSaint: null,
    feastDay: "Zesłanie Ducha Świętego",
    source: "KEP + Dz 1,14, 2,1-4 + polskie źródła liturgiczne Vatican.va. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-st-therese",
    name: "Nowenna do świętej Teresy od Dzieciątka Jezus",
    description:
      "Święta Teresa od Dzieciątka Jezus i Najświętszego Oblicza — lepiej znana jako Teresa z Lisieux lub «Mały Kwiatek» — była zakonnicą bosych karmelitanek, która wstąpiła do klasztoru w Lisieux w Normandii w wieku piętnastu lat i zmarła na gruźlicę w wieku dwudziestu czterech (1873-1897). Jej duchowa autobiografia, Dzieje duszy, została opublikowana wkrótce po jej śmierci i szybko stała się jedną z najczęściej czytanych książek katolickich epoki nowożytnej. Z mroku prowincjonalnego klasztoru nauczała tego, co nazwała Małą Drogą: ufności w miłosierną miłość Boga wyrażoną w najmniejszych aktach codziennej wierności, zamiast w heroicznych zewnętrznych wyczynach. «Spędzę moje niebo, czyniąc dobro na ziemi», słynnie obiecała; «sprawię, że spadnie deszcz róż». Tradycja «deszczu róż» — przekonanie, że wstawiennictwo uzyskane przez świętą Teresę często towarzyszy nieoczekiwana róża, dosłowna lub symboliczna — kształtowała katolicką cześć do niej od tamtej pory. Została kanonizowana przez papieża Piusa XI w 1925 roku, ogłoszona Patronką Misji w 1927 roku (mimo że nigdy nie opuściła klasztoru) i ogłoszona Doktorem Kościoła przez papieża świętego Jana Pawła II w 1997 roku — jedną z zaledwie czterech kobiet tak nazwanych, obok świętych Teresy z Avili, Katarzyny ze Sieny i Hildegardy z Bingen. Jej wkład doktrynalny to teologia dzieciństwa: ewangeliczna nauka, że trzeba stać się jak małe dziecko, by wejść do Królestwa (Mt 18,3), otrzymując trwałą, kontemplacyjną artykulację. Nowenna do świętej Teresy jest odpowiednia dla: rozeznania powołania zakonnego lub świeckiego, powrotu do zdrowia z choroby (jej własna gruźlica była znoszona z wielkim cierpieniem), suchości duchowej, nawrócenia dalekich ukochanych osób (modliła się nieustannie za Pranziniego, skazanego mordercę, jako swojego «pierwszego dziecka»), i każdego momentu, gdy dusza wyczuwa swoją własną małość wobec wielkiej potrzeby.",
    instructions:
      "Módl się raz dziennie przez dziewięć kolejnych dni. Tradycyjna struktura: (1) Rozpocznij od Znaku Krzyża; (2) Odmów modlitwę nowenny do świętej Teresy (prosząc o jej wstawiennictwo i jej słynną różę); (3) Wymień swoją intencję cicho lub na głos; (4) Zakończ Ojcze Nasz, Zdrowaś Maryjo i Chwała Ojcu. Nowennę odmawia się właściwie w dziewięć dni poprzedzających jej święto (1 października) lub o każdej porze roku w prywatnej intencji. Wielu katolików przechowuje w domu mały obrazek lub relikwię świętej Teresy lub nosi obrazek z motywem róży podczas nowenny. Tradycja «deszczu róż» jest dokładnie tym — tradycją, nie magiczną gwarancją. Róża otrzymana podczas lub po nowennie jest odczytywana jako osobisty znak, że święta wysłuchała modlitwy i wstawia się przed Chrystusem; brak róży nie jest odczytywany jako brak wstawiennictwa. Chodzi o dyspozycję: Mała Droga Teresy zaprasza proszącego do tej samej dziecięcej ufności, którą ona zamodelowała, która sama w sobie jest łaską, o którą się prosi. Nowenna jest również odpowiednim towarzyszem konkretnym aktom małej wierności w ciągu dziewięciu dni — cierpliwości wobec trudnego członka rodziny, przyjmowania małej niedogodności bez narzekania, powstrzymywania ostrego słowa, wykonywania jednego ukrytego aktu dobroci dziennie. Te «małe drogi» ucieleśniają to, o co prosi nowenna: nie heroiczne przemienienie, ale drogę małych rzeczy uczynionych z wielką miłością, której Teresa nauczała i którą żyła.",
    patronSaint: "święta Teresa od Dzieciątka Jezus",
    feastDay: "1 października",
    source: "KEP + Dzieje duszy + papież święty Jan Paweł II Divini Amoris Scientia (1997, ogłoszenie Doktorem Kościoła). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-miraculous-medal",
    name: "Nowenna do Cudownego Medalika",
    description:
      "W nocy z 18 na 19 lipca 1830 roku, w kaplicy Córek Miłosierdzia przy Rue du Bac w Paryżu, młoda nowicjuszka o imieniu Katarzyna Labouré została zbudzona przez swojego anioła stróża i zaprowadzona do kaplicy na prywatne objawienie Najświętszej Maryi Panny. Maryja rozmawiała z nią ponad dwie godziny o niespokojnym stanie Francji i szerszego Kościoła. W drugim objawieniu w listopadzie Katarzyna zobaczyła Maryję stojącą na globusie z promieniami światła wytryskującymi z jej rąk, otoczoną ramą z wpisanymi słowami: «O Maryjo bez grzechu poczęta, módl się za nami, którzy się do Ciebie uciekamy!» Na rewersie tej wizji była krzyżowa M z dwunastoma gwiazdami, Serce Chrystusa ukoronowane cierniami i Serce Maryi przebite mieczem. Maryja poleciła Katarzynie: «Zrób medalik według tego wzoru. Ci, którzy go będą nosić, otrzymają wielkie łaski, zwłaszcza jeśli będą go nosić na szyi». Medalik został wybity w 1832 roku za zgodą arcybiskupa Paryża. W ciągu pięciu lat został rozdystrybuowany w takich ilościach i towarzyszył tylu zgłoszonym wstawiennictwom, że popularna katolicka wyobraźnia przemianowała go na «Cudowny Medalik», nazwę, którą Kościół ostatecznie przyjął. Objawienia z 1830 roku są godne uwagi jako jedno z głównych wydarzeń maryjnych epoki nowożytnej, wyprzedzające Lourdes (1858) o dwadzieścia osiem lat i Fatimę (1917) o osiemdziesiąt siedem lat. Doktryna Niepokalanego Poczęcia — w sercu centralnego napisu medalika — została formalnie zdefiniowana przez papieża Piusa IX w 1854 roku, dwadzieścia cztery lata po wizjach Katarzyny. Katarzyna Labouré pozostała w swoim klasztorze w Reuilly, pracując ze starymi biednymi, przez pozostałe czterdzieści sześć lat swojego życia. Została kanonizowana w 1947 roku przez papieża Piusa XII. Nowenna do Cudownego Medalika jest odpowiednia dla: choroby (zwłaszcza z złym rokowaniem — reputacja medalika zaczęła się od uzdrowień), nawrócenia członków rodziny, ochrony w czasie ciąży (długa katolicka tradycja przypinania medalika do sukni matki lub noszenia go podczas porodu), i każdej trudnej chwili, gdy dusza szuka konkretnego macierzyńskiego wstawiennictwa Maryi przez ten szczególny znak.",
    instructions:
      "Módl się raz dziennie przez dziewięć kolejnych dni. Tradycyjna struktura: (1) Rozpocznij od Znaku Krzyża; (2) Odmów Pomnij lub trzy Zdrowaś Maryjo jako otwierające maryjne wezwanie; (3) Odmów modlitwę nowenny do Niepokalanej Dziewicy przez Cudowny Medalik; (4) Zakończ centralnym napisem medalika jako aspiracją: «O Maryjo bez grzechu poczęta, módl się za nami, którzy się do Ciebie uciekamy!»; (5) Wymień konkretną intencję. Jeśli to możliwe, noś Cudowny Medalik — fizycznie — podczas nowenny. Medalik nie jest amuletem; tradycja jest taka, że jego noszenie wyraża zaufanie do wstawiennictwa Maryi i otwartość noszącego na łaskę. Katolickie kaplice i sanktuaria rozdają Cudowne Medaliki bezpłatnie. Nowennę można odmawiać o każdej porze, ale jest szczególnie odpowiednia w dniach poprzedzających święto Matki Bożej od Cudownego Medalika (27 listopada) lub uroczystość Niepokalanego Poczęcia (8 grudnia). Wielu katolików używa również Cudownego Medalika jako znaku zawierzenia Niepokalanemu Sercu Maryi — łącząc nowennę z modlitwą Totalnego Zawierzenia świętego Maksymiliana Kolbego lub dłuższym 33-dniowym przygotowaniem do zawierzenia maryjnego (tradycja Montfortańska). Dla rodzin modlących się za nieobecną lub zmagającą się ukochaną osobę, tradycyjną praktyką jest wsunięcie Cudownego Medalika do rzeczy ukochanej osoby — portfela, kieszeni płaszcza, plecaka — jako mały znak nieustannego macierzyńskiego towarzyszenia.",
    patronSaint: "święta Katarzyna Labouré",
    feastDay: "27 listopada",
    source: "KEP + narracja objawienia z Rue du Bac (1830) + kanonizacja papieża Piusa XII 1947. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "st-michael-prayer",
    name: "Modlitwa do świętego Michała Archanioła",
    description:
      "Modlitwa do świętego Michała Archanioła została skomponowana przez papieża Leona XIII w 1886 roku po tym, jak — według długo poświadczanej tradycji — papież miał nagłe mistyczne doświadczenie podczas odprawiania Mszy świętej — rodzaj wizji na jawie, w której usłyszał kolokwium między Chrystusem a szatanem, w którym szatan przechwalał się, że może zniszczyć Kościół, jeśli zostanie mu dany wystarczający czas i władza. Wstrząśnięty tym, co zobaczył, Leon XIII skomponował modlitwę do świętego Michała tego samego dnia i nakazał dodać ją do modlitw odmawianych przez kapłana i wiernych na zakończenie każdej Mszy cichej w całym Kościele powszechnym. Ta praktyka — «Modlitwy Leonińskie» po Mszy — kontynuowała się przez prawie osiemdziesiąt lat, aż do reform liturgicznych lat sześćdziesiątych. Modlitwy do świętego Michała nie zniesiono, ale jej formalne miejsce w modlitwach po Mszy wygasło. Papież święty Jan Paweł II przywrócił prominencję modlitwy w niedzielnym wystąpieniu na Anioł Pański w 1994 roku, w którym wezwał wiernych, aby «nie zapominali odmawiać» modlitwy do świętego Michała «aby otrzymać pomoc w walce z siłami ciemności i przeciwko duchowi tego świata». Tekst modlitwy opiera się na Liście świętego Judy 1,9 (Michał spierający się z diabłem o ciało Mojżesza), Apokalipsie 12,7-9 (Michał strącający smoka) i szerszej katolickiej tradycji świętego Michała jako wodza zastępów niebieskich przeciwko mocom zła. Modlitwa jest odpowiednia dla: walki duchowej w każdej formie, niepokoju o zło w świecie lub w życiu osobistym, ochrony podczas podróży lub przed trudnym spotkaniem, nawrócenia tych, którzy popadli w ciężki grzech, i jako codzienna modlitwa zawierzenia ochronie świętego Michała. Jest to modlitwa najczęściej uczona katolickim dzieciom jako pierwsza «modlitwa ochronna» wraz z Modlitwą do Anioła Stróża.",
    instructions:
      "Módl się raz z pełną uwagą i pobożnością. Modlitwa do świętego Michała jest na tyle krótka, że można ją zapamiętać i odmawiać wszędzie — w samochodzie przed trudnym spotkaniem, przy drzwiach szpitala, idąc obok miejsca, gdzie wyczuwa się duchowy zamęt, przed snem na koniec dnia. Tradycyjna katolicka praktyka — i ta, którą Leon XIII pierwotnie ustanowił — to odmawiać ją natychmiast po zakończeniu Mszy świętej, albo w ciszy następującej po rozesłaniu, albo jako część publicznej sekwencji Modlitw Leonińskich. Wiele parafii wskrzesiło modlitwę do świętego Michała po Mszy po wezwaniu JPII z 1994 roku; jeśli twoja parafia tego nie robi, jest całkowicie odpowiednie, aby pozostać w ławce przez trzydzieści sekund po rozesłaniu i odmówić ją prywatnie. Modlitwa jest również często włączana: na zakończenie Różańca lub Godziny świętej; na zakończenie wieczornej modlitwy rodzinnej; przed jakimkolwiek zadaniem, w którym katolik wyczuwa rzeczywistą duchową opozycję. W niektórych katolickich domach modlitwa jest umieszczana nad drzwiami wejściowymi domu jako znak zawierzenia ochronie świętego Michała nad domem, w ciągłości ze starszą tradycją wpisywania «Christus vincit, Christus regnat, Christus imperat» («Chrystus zwycięża, Chrystus króluje, Chrystus rozkazuje») nad progami. Modlitwa łączy się naturalnie z Modlitwą do Anioła Stróża dla dzieci: święty Michał jako książę anielskich zastępów, a anioł stróż jako szczególny duch posługujący przydzielony każdej osobie w chrzcie.",
    patronSaint: "święty Michał Archanioł",
    feastDay: "29 września",
    source: "KEP + Leon XIII kompozycja z 1886 + papież święty Jan Paweł II niedzielny Anioł Pański, 24 kwietnia 1994. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "anima-christi",
    name: "Anima Christi (Duszo Chrystusowa)",
    description:
      "Anima Christi («Duszo Chrystusowa») jest jedną z najbardziej umiłowanych i najstarszych modlitw eucharystycznych w tradycji katolickiej. Jej pochodzenie jest średniowieczne — prawdopodobnie z XIV wieku — i przez wiele lat była przypisywana świętemu Ignacemu Loyoli, ponieważ umieścił ją na samym początku swoich Ćwiczeń Duchowych (1522-1524) i zalecił jako codzienną modlitwę dla rekolektantów. Współczesna nauka datowała modlitwę co najmniej sto lat przed narodzinami Ignacego; pojawia się w rękopisach już w 1314 roku, prawdopodobnie skomponowana przez Jana XXII lub przez anonimowego mnicha z tradycji kartuzów lub franciszkanów. Ignacy jej nie napisał, ale ją kochał, a jego Ćwiczenia Duchowe nadały jej szeroką cyrkulację, którą cieszy się dzisiaj w całym katolickim świecie. Modlitwa jest podtrzymywaną medytacją nad Chrystusem Eucharystycznym — Jego Duszą, Jego Ciałem, Jego Krwią, wodą i krwią, które wypłynęły z Jego przebitego boku przy Ukrzyżowaniu (J 19,34), Jego Męką. Każda linijka jest jednocześnie wyznaniem wiary i prośbą: «Duszo Chrystusowa, uświęć mnie» jest modlitwą kogoś, kto prosi o uświęcenie wewnętrzne przez samą świętość Chrystusa; «Ciało Chrystusowe, zbaw mnie» jest wyznaniem, że zbawienie pochodzi przez to samo Ciało otrzymywane teraz pod postacią chleba; «W Twoich ranach ukryj mnie» jest średniowiecznym mistycznym pragnieniem znalezienia schronienia w samych ranach ukrzyżowanego Pana. Zakończenie modlitwy — «W godzinę śmierci mojej wezwij mnie» — uczyniło ją tradycyjną katolicką modlitwą za umierających, odmawianą przy łożu w ostatnich godzinach przez kapelanów hospicjów, członków rodziny i katolickie pielęgniarki. Anima Christi jest odpowiednia dla: dziękczynienia natychmiast po przyjęciu Komunii świętej (jej główne tradycyjne zastosowanie), Godziny świętej lub nawiedzenia Najświętszego Sakramentu, zakończenia osobistej modlitwy, łoża umierających, i jako codzienne nabożeństwo wyrażające intymność eucharystyczną.",
    instructions:
      "Módl się z pobożnością, najlepiej w postawie uważnej ciszy — klęcząc, siedząc prosto z otwartymi rękami lub stojąc przed Najświętszym Sakramentem. Modlitwa jest pomyślana jako niespieszna; każda linijka jest odrębną prośbą, a naturalne tempo pozwala na krótką pauzę między frazami, aby każda linijka mogła osiąść w sercu. Tradycyjne momenty na Anima Christi: (1) Natychmiast po przyjęciu Komunii świętej na Mszy, w ciszy osobistego dziękczynienia — jest to główne dewocyjne zastosowanie modlitwy i rekomendacja świętego Ignacego; (2) Podczas Godziny świętej lub adoracji eucharystycznej przed wystawionym Najświętszym Sakramentem; (3) Na zakończenie osobistej porannej lub wieczornej modlitwy, zwłaszcza jako część duchowości eucharystycznej; (4) Przy łóżku kogoś poważnie chorego lub umierającego — ostatnia linijka, «W godzinę śmierci mojej wezwij mnie i każ mi przyjść do Siebie», czyni modlitwę szczególnie odpowiednią jako nabożeństwo łoża śmierci; (5) Śpiewana wersja po łacinie («Anima Christi, sanctifica me…») w monastycznych i tradycyjnych liturgicznych warunkach. Wiele katolickich obrazków modlitewnych nosi Anima Christi na odwrocie obok modlitwy przyjęcia Komunii. Modlitwę można zapamiętać w jedno popołudnie i odmawiać wszędzie; jej zwięzłość i gęstość treści eucharystycznej czynią ją jedną z najwyższej wartości krótkich modlitw w katolickim repertuarze dewocyjnym.",
    patronSaint: "święty Ignacy Loyola",
    feastDay: null,
    source: "Vatican.va polski + Ćwiczenia Duchowe świętego Ignacego (1522-1524) + tradycja rękopisów z XIV wieku. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── ROUND 4 (pl) ──────────────────────────────────────────
  {
    prayerSlug: "litany-saints",
    name: "Litania do Wszystkich Świętych",
    description:
      "Litania do Wszystkich Świętych jest najstarszą i najuroczystszą litanią w Kościele katolickim. Jej korzenie sięgają pierwszych wieków — fragmenty formy pojawiają się w siódmowiecznych zachodnich księgach liturgicznych, a papież Grzegorz Wielki ustanowił wielkie procesje litanijne Rzymu w 590 roku, prosząc wiernych, aby wezwali świętych po imieniu w błaganiu podczas zarazy. Litania stała się częścią liturgii chrzcielnej Wigilii Paschalnej najpóźniej w VIII wieku. Jej obecny tekst rytu rzymskiego został formalnie ustalony przez papieża Piusa V w 1568 roku i zrewidowany w posoborowej reformie liturgicznej (1969). Struktura rozwija się w pięciu głównych ruchach: (1) Wezwania Kyrie eleison i prośby trynitarne; (2) wielkie wyliczenie świętych po imieniu — najpierw Najświętsza Maryja Panna, następnie archaniołowie (Michał, Gabriel, Rafał), patriarchowie i prorocy (Abraham, Mojżesz, Eliasz, Jan Chrzciciel), apostołowie i ewangeliści (Piotr, Paweł, Andrzej, Jan, Jakub, itd.), męczennicy (Szczepan, Wawrzyniec, Polikarp, Ignacy z Antiochii, Cyprian, Sebastian, Agata, Agnieszka), biskupi-wyznawcy i doktorzy (Atanazy, Bazyli, Grzegorz, Augustyn, Hieronim, Ambroży), założyciele i dziewice (Antoni Pustelnik, Benedykt, Franciszek, Dominik, Katarzyna ze Sieny, Teresa z Avili); (3) prośby o uwolnienie («Od wszelkiego zła, wybaw nas Panie»); (4) prośby błagalne («Abyś nami rządził i zachował twój święty Kościół, Ciebie prosimy, wysłuchaj nas»); (5) końcowe Agnus Dei i kolekta. Litania jest jedną z głównych modlitw katolickiej liturgii i jest używana w: Wigilii Paschalnej (podczas Liturgii Chrztu), chrztach Wielkiej Soboty, święceniach kapłańskich i biskupich (kandydaci leżą krzyżem, podczas gdy zgromadzony Kościół śpiewa nad nimi litanię), Obrzędzie Chrześcijańskiego Wtajemniczenia Dorosłych (OCWD) w Obrzędzie Wybrania, poświęceniu kościoła, konsekracji ołtarzy i składaniu ślubów zakonnych. Jest również zwyczajem w wielu parafiach w uroczystość Wszystkich Świętych (1 listopada), na pogrzebach kapłanów i osób zakonnych, w chwilach poważnej publicznej potrzeby (wojna, pandemia, klęska żywiołowa) i jako modlitwa zamykająca procesje pielgrzymkowe.",
    instructions:
      "Litania do Wszystkich Świętych odmawia się responsoryjnie, zwykle śpiewa w warunkach liturgicznych. Prowadzący (kapłan, diakon lub wyszkolony kantor) intonuje wezwanie; zgromadzenie odpowiada odpowiednią formułą. Odpowiedzi następują strukturę: «Módl się za nami» po każdym świętym wymienionym z imienia lub grupie świętych; «Wybaw nas, Panie» po każdym wezwaniu uwolnienia («Od wszelkiego zła…»); «Ciebie prosimy, wysłuchaj nas» po każdej prośbie błagalnej («Abyś…»). Litania trwa około piętnastu do dwudziestu minut, gdy jest śpiewana w uroczystym tempie w warunkach liturgicznych; nieco mniej, gdy odmawia się ją w domu w formie mówionej. Do prywatnej dewocji litanię można odmawiać z dowolnego zatwierdzonego drukowanego tekstu (Mszał Rzymski, parafialna księga modlitw lub strona Konferencji Episkopatu Polski). Gdy odmawia się ją w domu, siedź, stój lub klęcz, jak chcesz; tempo litanii jest kontemplacyjne, a nie pospieszne. Litanię używa się odpowiednio: (1) w Wszystkich Świętych (1 listopada) i w Zaduszki (2 listopada) jako modlitwę rodzinną tych dni; (2) przy łóżku kogoś poważnie chorego lub umierającego — wielu katolickich kapelanów szpitalnych odmawia litanię w miarę zbliżania się ostatnich sakramentów; (3) na początku ważnej pielgrzymki lub rodzinnego przedsięwzięcia, prosząc, aby wielki obłok świadków (Hbr 12,1) otoczył proszących; (4) w czasie zarazy, klęski lub publicznego stanu wyjątkowego, w ciągłości z ustanowieniem procesji litanijnych przez Grzegorza Wielkiego podczas rzymskiej zarazy z 590 roku. Szczególnym duchowym darem litanii jest odczuwana obecność komunii świętych — prawda, że wierni modlący się na ziemi i ci tryumfujący w niebie są jednym ciałem w Chrystusie.",
    patronSaint: null,
    feastDay: "1 listopada (Wszystkich Świętych)",
    source: "KEP + papież Pius V kodyfikacja 1568 + posoborowa rewizja 1969 + ustanowienie Grzegorza Wielkiego 590. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "prayer-expectant-mothers",
    name: "Modlitwa za matki oczekujące dziecka",
    description:
      "Katolicka modlitwa za matki oczekujące dziecka czerpie z wielowiekowej tradycji Kościoła towarzyszenia kobietom w czasie ciąży pod opieką Najświętszej Maryi Panny, która sama nosiła Chrystusa w swoim łonie przez dziewięć miesięcy. Głównym fundamentem biblijnym jest Nawiedzenie (Łk 1,39-56): Maryja, sama w pierwszych miesiącach ciąży z Jezusem, śpieszy w góry Judei, aby być ze swoją kuzynką Elżbietą, która jest w szóstym miesiącu ciąży z Janem Chrzcicielem. Magnificat («Wielbi dusza moja Pana…») jest modlitwą dwóch kobiet w ciąży radujących się razem. Katolicka tradycja dewocyjna od dawna powierza matki oczekujące dziecka Maryi pod różnymi tytułami: Matka Boża Oczekująca (uroczystość 18 grudnia, święto z tradycji hiszpańskiej dziewięć dni przed Bożym Narodzeniem, znaczące zbliżające się rozwiązanie Maryi); Matka Boża z Guadalupe (której obraz pokazuje ją w ciąży); i święty Gerard Majella (1726-1755), włoski brat zakonny redemptorystów, którego imię stało się tak związane z bezpiecznym rozwiązaniem, że jego statuy umieszczane są na oddziałach położniczych szpitali katolickich na całym świecie. Modlitwa za matki oczekujące dziecka jest odpowiednia na każdym etapie ciąży: przy pierwszym pozytywnym teście, podczas niepokoju pierwszego trymestru, który odczuwa wiele matek, podczas długich środkowych miesięcy oczekiwania, w tygodniach przygotowań przed rozwiązaniem, w czasie samego porodu (gdy członkowie rodziny często odmawiają ją przy łóżku) i bezpośrednio po porodzie w dziękczynieniu. Odmawiają ją również wspólnoty — parafie, grupy modlitewne, krąg przyjaciółek kobiety — jako sposób otaczania jej wstawiennictwem przez dziewięć miesięcy oczekiwania.",
    instructions:
      "Módl się raz dziennie za matkę oczekującą dziecka, najlepiej o tej samej porze każdego dnia, aby praktyka stała się częścią jej zwykłego rytmu. Modlitwa jest na tyle krótka, że można ją zapamiętać; wiele matek oczekujących dziecka nosi ją na małej karteczce przechowywanej w Biblii, modlitewniku lub portfelu i odmawia, gdy zatrzymują się w codziennej pracy przygotowywania się do dziecka. Powszechne praktyki towarzyszące modlitwie: (1) Zapalanie świecy w sanktuarium maryjnym w kościele parafialnym na każdy miesiąc ciąży — wiele parafii utrzymuje wyznaczony stojak na świece «matek oczekujących» i wywieszają imiona kobiet, za które się modlą; (2) Codzienne odmawianie jednego dziesiątka różańca, medytując nad Tajemnicami Radosnymi (Zwiastowanie, Nawiedzenie, Narodzenie, Ofiarowanie, Znalezienie w świątyni — pięć tajemnic, które przechodzą duchowy łuk od poczęcia do młodego macierzyństwa); (3) Proszenie o wstawiennictwo świętego Gerarda Majelli — modlitwę za matki oczekujące można połączyć z nowenną do świętego Gerarda, szczególnie w ostatnich dziewięciu dniach przed rozwiązaniem; (4) Rodzinna lub wspólnotowa modlitwa przy łóżku podczas porodu, w której małżonek matki oczekującej lub inny członek rodziny odmawia Pomnij (krótką maryjną modlitwę ufności) lub tę modlitwę na głos w miarę postępu porodu. Tradycja katolicka jest jasna, że ciąża jest sama w sobie formą modlitwy. Po porodzie modlitwa kontynuuje w dziękczynieniu i naturalnie zwraca się ku modlitwom macierzyństwa za nowonarodzone dziecko.",
    patronSaint: "Matka Boża",
    feastDay: null,
    source: "KEP + Łk 1,39-56 + tradycja świętego Gerarda Majelli. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "adoration-hour",
    name: "Godzina święta adoracji",
    description:
      "Godzina święta adoracji eucharystycznej jest jedną z najstarszych i najbardziej centralnych form katolickiej modlitwy — trwałej, cichej modlitwy w rzeczywistej obecności Jezusa Chrystusa w Najświętszym Sakramencie, wystawionym w monstrancji na ołtarzu. Praktyka czerpie bezpośrednio ze sceny ewangelicznej w Getsemani: Chrystus pyta swoich apostołów: «Tak, jednej godziny nie mogliście czuwać ze mną?» (Mt 26,40). «Jedna godzina» nie jest arbitralną długością — to wyraźna prośba Pana w nocy Jego męki, a katolicka Godzina święta odpowiada bezpośrednio na tę prośbę. Praktyka dewocyjna trwałej adoracji eucharystycznej skrystalizowała się w okresie kontrreformacji i otrzymała szczególny impuls dzięki objawieniom Najświętszego Serca świętej Małgorzacie Marii Alacoque w Paray-le-Monial (1673-1675); Chrystus konkretnie poprosił Małgorzatę Marię o godzinę wynagrodzenia w Jego obecności każdego czwartku w nocy, na pamiątkę Konania w Ogrójcu. Godzina święta stała się centralna dla «Apostolstwa Modlitwy» (założonego w 1844 roku) i była szeroko głoszona w XX wieku przez Czcigodnego Fultona Sheena (1895-1979), który słynnie zobowiązał się do Godziny świętej każdego dnia swojego kapłańskiego życia — ponad 60 lat — i każdą łaskę swojej posługi przypisywał tej godzinie. Dziś w tysiącach parafii na całym świecie działają kaplice wieczystej adoracji eucharystycznej, obsadzone przez świeckich wolontariuszy, którzy zobowiązują się do konkretnych godzin przez noc i dzień, aby Chrystus nigdy nie pozostał sam w swoim wystawionym Sakramencie. Godzina święta jest odpowiednia dla: każdego trwałego wstawiennictwa, zwłaszcza o uzdrowienie, nawrócenie lub rozeznanie powołania; wynagrodzenia za grzech (własny lub świata); suchości duchowej; przygotowania do ważnych decyzji życiowych; dziękczynienia po otrzymaniu łaski. To modlitwa, którą Sheen nazywał «tajemnicą każdego kapłana, który stał się świętym».",
    instructions:
      "Odwiedź swoją parafię w godzinach adoracji — sprawdź stronę internetową lub biuletyn swojej parafii, aby poznać harmonogram. Wiele parafii oferuje adorację eucharystyczną w czwartki (prośba Chrystusa do Małgorzaty Marii), w piątki (tradycyjny dzień wynagrodzenia) lub jako rozszerzoną Godzinę świętą po Mszy świętej w dni powszednie. Niektóre utrzymują wieczystą adorację z Najświętszym Sakramentem wystawionym 24/7. Po przybyciu: (1) Uklęknij na obu kolanach (tradycyjny znak czci dla wystawionej Eucharystii, w odróżnieniu od jednokolanowej genuflekcji dla Sakramentu zachowanego w tabernakulum); (2) Znajdź miejsce do siedzenia lub klęczenia; (3) Pokłoń się w cichym uznaniu, że jesteś w dosłownej obecności Boga wcielonego. Sama godzina jest nieustrukturyzowana z założenia — trwała obecność jest modlitwą. Niektóre wzory, których używają katolicy, aby wypełnić godzinę: (a) Odmawiać Różaniec, medytując nad Tajemnicami Bolesnymi; (b) Czytać Pismo Święte (opisy Męki, Ewangelię świętego Jana, Psalmy — Psalmy 23 i 91); (c) Odmawiać Koronkę do Bożego Miłosierdzia, zwłaszcza podczas godziny 15:00; (d) Czytać z klasyki duchowej; (e) Siedzieć w cichej obecności — najwyższej formie modlitwy kontemplacyjnej; (f) Zapisać rozmowę z Jezusem o osobie, za którą ofiarujesz godzinę. Przez całą godzinę często wymieniaj imię osoby i intencję. Godzina kończy się kolejną genuflekcją i krótką modlitwą dziękczynną za dar Jego obecności.",
    patronSaint: null,
    feastDay: null,
    source: "KEP + Mt 26,40 + objawienia Najświętszego Serca w Paray-le-Monial (1673-1675) + tradycja Fultona Sheena. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "stations-of-the-cross",
    name: "Droga Krzyżowa",
    description:
      "Droga Krzyżowa (zwana również Drogą Krzyża, Via Crucis lub Via Dolorosa po łacinie) jest medytacyjnym nabożeństwem, w którym wierny podąża za Męką Chrystusa przez czternaście odrębnych stacji — momentów wzdłuż Jego drogi z pretorium Piłata do grobu. Praktyka powstała w pierwszych wiekach chrześcijańskich jako dosłowna pielgrzymka do miejsc świętych w Jerozolimie; pielgrzymi chodzili rzeczywistą ścieżką, którą szedł Chrystus, zatrzymując się na każdej znaczącej stacji, aby się modlić. Gdy Jerozolima padła pod kontrolę muzułmańską w VII wieku i pielgrzymka stała się niebezpieczna i rzadka, franciszkanie — którym papież Klemens VI dał kustodię Ziemi Świętej w 1342 roku — zaczęli rekonstruować Drogę Krzyżową w formie dewocyjnych stacji w swoich kościołach w całej Europie, aby każdy katolik mógł «pójść» Drogą Krzyżową duchowo, nie podróżując do Jerozolimy. Papież Innocenty XI nadał franciszkanom odpusty za odmawianie stacji w 1686 roku, a papież Klemens XII rozszerzył to na wszystkich wiernych w 1731 roku. Czternaście standardowych stacji ustalono w XVIII wieku: (1) Jezus jest skazany na śmierć; (2) Jezus bierze krzyż na swoje ramiona; (3) Jezus upada pierwszy raz pod krzyżem; (4) Jezus spotyka swoją Matkę Maryję; (5) Szymon Cyrenejczyk pomaga Jezusowi nieść krzyż; (6) Weronika ociera twarz Jezusowi; (7) Jezus upada drugi raz; (8) Jezus spotyka płaczące niewiasty jerozolimskie; (9) Jezus upada trzeci raz; (10) Jezus z szat obnażony; (11) Jezus przybity do krzyża; (12) Jezus umiera na krzyżu; (13) Jezus zdjęty z krzyża; (14) Jezus złożony do grobu. Niektóre wspólnoty katolickie dodają piętnastą stację Zmartwychwstania. Droga Krzyżowa jest tradycyjnie odmawiana w piątki w okresie Wielkiego Postu i jest centralnym publicznym nabożeństwem Wielkiego Piątku w większości katolickich parafii na całym świecie. Papież przewodniczy Drodze Krzyżowej w Koloseum w Rzymie w każdy Wielki Piątek — tradycji wskrzeszonej przez papieża Pawła VI i kontynuowanej przez każdego papieża od tego czasu.",
    instructions:
      "Odwiedź kościół katolicki — większość ma czternaście stacji zamontowanych wzdłuż bocznych ścian nawy, zwykle jako małe obrazy, tablice lub płaskorzeźby. Tradycyjna praktyka: (1) Rozpocznij od pierwszej stacji; uklęknij; (2) Ogłoś stację na głos («Stacja pierwsza: Jezus skazany na śmierć»); (3) Odmów odpowiedź «Kłaniamy Ci się, Panie Jezu Chryste, i błogosławimy Tobie, żeś przez Krzyż i Mękę swoją świat odkupić raczył»; (4) Krótko medytuj nad sceną z Męki Chrystusa odpowiadającą stacji; (5) Odmów Ojcze Nasz, Zdrowaś Maryjo i Chwała Ojcu (lub inne modlitwy z książeczki Drogi Krzyżowej); (6) Ofiaruj stację za swoją intencję. Przejdź do następnej stacji — fizyczne przechodzenie od jednej do drugiej jest częścią modlitwy; Droga Krzyżowa ma być przebyta, choćby krótko. Całkowity czas: około trzydziestu do czterdziestu pięciu minut, gdy odmawia się w niespiesznym tempie w kościele. W domu drukowana książeczka Drogi Krzyżowej działa dobrze — nie ma wymogu fizycznej obecności. Nabożeństwo jest odpowiednio odmawiane: (a) W piątki w okresie Wielkiego Postu, tradycyjna katolicka dyscyplina; (b) W sam Wielki Piątek, dzień, w którym Chrystus przeszedł Via Dolorosa; (c) W każdy piątek przez cały rok (jako tradycyjny dzień pamięci o Męce); (d) Gdy niesie się ciężki osobisty krzyż — choroba, żałoba, uzależnienie, prześladowanie — łącząc swoje cierpienie z cierpieniem Chrystusa; (e) Gdy modli się za kogoś, kto cierpi lub umiera; (f) Gdy szuka się łaski cierpliwości pod brzemieniem.",
    patronSaint: null,
    feastDay: "Wielki Piątek",
    source: "KEP + franciszkańska kustodia Ziemi Świętej (1342) + papież Innocenty XI 1686 + Klemens XII 1731. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "morning-offering",
    name: "Ofiarowanie poranne",
    description:
      "Ofiarowanie poranne jest fundamentalną codzienną modlitwą Apostolstwa Modlitwy — katolickiego ruchu duchowego założonego w 1844 roku przez jezuitę księdza François-Xaviera Gautreleta w Vals we Francji, przemianowanego w 2015 roku przez papieża Franciszka na Światową Sieć Modlitewną Papieża. Centralna intuicja ruchu jest prosta, ale przemieniająca: każde zwykłe działanie dnia katolika — praca, nauka, rozmowa, posiłki, zmęczenie, radość, cierpienie, nawet sen — może być ofiarowane Bogu jako celowy akt miłości, przekształcając cały dzień w jeden trwały akt modlitwy. Ofiarowanie poranne jest aktem, który dokonuje tego ofiarowania, odmawianym jako pierwsza rzecz po przebudzeniu, zanim dzień przejmie kontrolę. Tradycyjny tekst — skomponowany pod koniec XIX wieku w broszurach dewocyjnych Apostolstwa i udoskonalony przez kilka wersji zatwierdzonych przez papieży — umieszcza ofiarowanie dnia «przez Niepokalane Serce Maryi» (maryjne pośrednictwo, które ujmuje życie katolickie jako synowskie) i łączy je «ze Świętą Ofiarą Mszy świętej na całym świecie» (tak że ofiarowanie dnia gromadzi się w ofierze eucharystycznej sprawowanej w jakiejś katolickiej parafii gdzieś na ziemi w każdej minucie każdej godziny). Co miesiąc papież publikuje konkretne uniwersalne intencje modlitewne przez Światową Sieć Modlitewną Papieża. Ofiarowanie poranne jest także potężną modlitwą wstawienniczą za konkretną osobę: chorego członka rodziny, dorosłego dziecka, które odeszło od wiary, rodzica zmagającego się z uzależnieniem, każdego, czyja sytuacja jest stale obecna w sercu proszącego.",
    instructions:
      "Módl się natychmiast po przebudzeniu, zanim zajętość dnia przejmie kontrolę. Tradycyjna dyscyplina to odmówienie jej przed wstaniem z łóżka, gdy umysł jest jeszcze miękki, a dzień wciąż wydaje się darem; niektórzy katolicy odmawiają ją w pierwszej cichej chwili porannej rutyny (przy pierwszej filiżance kawy, przy zlewie kuchennym, karmiąc dziecko). Modlitwa jest na tyle krótka, że można ją zapamiętać w jeden dzień. Aby uczynić ją częścią życia: (1) Umieść modlitwę w miejscu, gdzie zobaczysz ją jako pierwszą — przyklejoną do lustra w łazience, wewnątrz drzwi sypialni, na karteczce obok ekspresu do kawy; (2) Wymień konkretną osobę i intencję w odpowiednim miejscu modlitwy (linia «a w szczególności za…»), czyniąc ofiarowanie konkretnym, a nie abstrakcyjnym; (3) W ciągu dnia, gdy praca staje się trudna lub przerwa łamie twoje plany, krótko odnów ofiarowanie: «Oddałem ten dzień Tobie za (imię); ta chwila jest tego częścią». Wiele katolickich domów odmawia Ofiarowanie poranne razem na głos, gdy rodzina wstaje. Światowa Sieć Modlitewna Papieża publikuje comiesięczne uniwersalne intencje papieża. Dla trwałego wstawiennictwa (nowenny dni za chorego ukochanego, czasu trudnego rozeznania, miesięcy chemioterapii członka rodziny) Ofiarowanie poranne staje się kręgosłupem modlitwy.",
    patronSaint: null,
    feastDay: null,
    source: "KEP + Apostolstwo Modlitwy / Światowa Sieć Modlitewna Papieża (1844, przemianowana 2015). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "three-oclock-prayer",
    name: "Modlitwa o godzinie trzeciej (Godzina Miłosierdzia)",
    description:
      "Modlitwa o godzinie trzeciej — zwana również Godziną Miłosierdzia lub Godziną Wielkiego Miłosierdzia — została dana przez Jezusa świętej Marii Faustynie Kowalskiej w objawieniach Bożego Miłosierdzia zapisanych w jej Dzienniczku: Miłosierdzie Boże w mojej duszy. Jezus pouczył Faustynę, że godzina 15:00 każdego dnia — godzina Jego śmierci na Kalwarii — ma być czczona jako Godzina Wielkiego Miłosierdzia, w której krótki akt modlitwy uzyskuje nadzwyczajne łaski. Dokładna obietnica, zapisana w Dzienniczku Faustyny (wpis 1320): «O trzeciej godzinie błagaj mojego miłosierdzia, szczególnie dla grzeszników; i choćby przez krótki moment zanurz się w mojej Męce, szczególnie w moim opuszczeniu w chwili konania. Jest to godzina wielkiego miłosierdzia dla całego świata… W tej godzinie nie odmówię niczego duszy, która prosi mnie przez wzgląd na moją Mękę». Godzina odpowiada dziewiątej godzinie dnia żydowskiego w chronologii ewangelicznej (Mk 15,34) — godzinie, w której «Jezus zawołał donośnym głosem… i oddał ducha» (Mk 15,37). Modlitwa o godzinie trzeciej jest najprostszą i najbardziej dostępną formą nabożeństwa do Bożego Miłosierdzia — znacznie krótszą niż koronka, dostępną dla każdego, kto może zatrzymać się na trzydzieści sekund w godzinie śmierci Chrystusa. Jest to modlitwa, którą tradycja katolicka umieszcza w sercu dnia dla tych, którzy nie mogą odprawić pełnej Godziny świętej, którzy nie mogą odmówić koronki, którzy są w pracy lub w szkole lub przy łóżku szpitalnym. Nabożeństwo było tłumione przez wiele lat (ten sam okres, gdy pisma Faustyny były pod prowizoryczną restrykcją), ale papież święty Jan Paweł II kanonizował Faustynę 30 kwietnia 2000 roku i ustanowił Niedzielę Bożego Miłosierdzia świętem dla Kościoła powszechnego. Modlitwa o godzinie trzeciej jest teraz odmawiana codziennie w niezliczonych katolickich domach, wspólnotach zakonnych, kapelaniach szpitalnych i w Sanktuarium Bożego Miłosierdzia w Łagiewnikach w Krakowie.",
    instructions:
      "O godzinie 15:00 każdego dnia zatrzymaj się na krótko — cokolwiek robisz — i módl się. Modlitwa jest na tyle krótka, że można ją zapamiętać w jedno popołudnie i odmawiać wszędzie: przy biurku, w samochodzie, w klasie, przy łóżku szpitalnym, idąc chodnikiem. Tradycja katolicka jest jasna, że «nawet chwila modlitwy w tej godzinie jest potężna» — jeśli zajęte życie może poświęcić tylko dwadzieścia sekund na jedno «Jezu, ufam Tobie» o godzinie 15:00, ta krótka chwila sama w sobie jest praktyką. Dla tych, którzy mają więcej czasu w tej godzinie: (1) Odmówić pełną Koronkę do Bożego Miłosierdzia (około dziesięciu minut); (2) Złożyć krótką «wizytę» w pobliskim katolickim kościele lub kaplicy adoracji eucharystycznej; (3) Zatrzymać się, aby przeczytać akapit z Dzienniczka świętej Faustyny; (4) Modlić się za grzeszników — Faustyna zapisała, że Jezus powiedział jej, że jest to najpotężniejsze wstawiennictwo w tej godzinie. Tradycyjne katolickie dyscypliny, które łączą się z Modlitwą o godzinie trzeciej: (a) Ustawienie codziennego alarmu na godzinę 15:00 jako przypomnienia; (b) Noszenie małego obrazka Bożego Miłosierdzia; (c) Modlitwa u stóp krucyfiksu; (d) Dodanie chwili fizycznej ciszy. Godzina jest codzienną kotwicą życia dewocyjnego Bożego Miłosierdzia: koronka o godzinie 15:00, codzienna Msza święta, comiesięczna spowiedź w pierwszy piątek, coroczna Nowenna do Bożego Miłosierdzia od Wielkiego Piątku do Niedzieli Bożego Miłosierdzia.",
    patronSaint: "święta Maria Faustyna Kowalska",
    feastDay: null,
    source: "KEP + Dzienniczek świętej Faustyny (1320) + JPII kanonizacja 30 kwietnia 2000 + Mk 15,34-37 + Sanktuarium w Łagiewnikach. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
];
