import type { PrayerTranslationSeed } from "./types";

/**
 * Brazilian Portuguese (pt-BR) translations of PrayerType content.
 *
 * Authoring conventions:
 *  - **Source tier**: CNBB (Conferência Nacional dos Bispos do Brasil),
 *    Vatican.va Portuguese, Paulus / Canção Nova / Aparecida publishers
 *    for canonical prayer texts. Cite source + retrieval date.
 *  - **Variant**: macro-tag `pt-BR` — Brazilian Portuguese register.
 *    `você` form, `e-mail` with hyphen. Avoid Portugal-specific
 *    `vós` / `telemóvel` / `casa de banho`. pt-PT support is a future
 *    layer.
 *  - **Catholic register**: `rezar por` (devotional preposition);
 *    same convention as the email dictionary's `por` prefix.
 *  - **Brand names stay English**: `PrayerTrain`, `Surrender Novena`.
 *  - **`prayerText` left null** — canonical Brazilian Portuguese
 *    prayer wording should be drawn from CNBB / Aparecida / Vatican
 *    sources in a separate focused pass rather than rendered from
 *    translation memory. Helper falls back to English prayer text
 *    under the Portuguese description + instructions.
 */
export const ptBRTranslations: PrayerTranslationSeed[] = [
  {
    prayerSlug: "novena-sacred-heart",
    name: "Novena ao Sagrado Coração de Jesus",
    description:
      "A Novena ao Sagrado Coração de Jesus é uma das devoções mais amadas da Igreja Católica, nascida das aparições de Jesus a Santa Margarida Maria Alacoque em Paray-le-Monial, França, entre 1673 e 1675. Nessas visões, Cristo revelou a profundidade de seu amor pela humanidade, simbolizado por seu Coração trespassado e coroado de espinhos, e pediu que esse amor fosse honrado pela devoção ao seu Sagrado Coração. A novena se estende por nove dias consecutivos de oração (o número nove recorda os nove dias em que os apóstolos e Maria permaneceram em oração entre a Ascensão e Pentecostes) e é tradicionalmente oferecida com confiança na compaixão de Cristo por aqueles que sofrem. É especialmente apropriada em tempos de doença, dificuldade familiar, desolação espiritual ou intenções persistentes que ainda não encontraram resposta. O Sagrado Coração não é apenas um símbolo; é o coração histórico e físico de Cristo, plenamente humano e plenamente divino, fonte de sua caridade infinita. A encíclica Haurietis Aquas de Pio XII (1956) descreve o Sagrado Coração como «o trono da misericórdia» e confirma o lugar central dessa devoção na vida da Igreja. Os guerreiros de oração que oferecem esta novena se unem a séculos de católicos que depositaram sua confiança no Coração ferido do Salvador.",
    instructions:
      "Reze uma vez ao dia por nove dias consecutivos, aproximadamente no mesmo horário a cada dia. Escolha um lugar tranquilo e comece com o Sinal da Cruz. A estrutura tradicional é: (1) uma invocação inicial, frequentemente «Ó Sacratíssimo Coração de Jesus, em Ti deposito toda a minha confiança»; (2) o próprio texto da novena; (3) um Pai-Nosso, uma Ave-Maria e um Glória; (4) uma intenção pessoal nomeada em voz alta ou em silêncio. Muitos acrescentam as Ladainhas do Sagrado Coração no último dia ou rezam a novena junto com a devoção das Primeiras Sextas-Feiras, recebendo a Sagrada Comunhão em nove primeiras sextas-feiras consecutivas como o próprio Cristo pediu a Santa Margarida Maria. A novena pode ser rezada em qualquer época do ano, mas é especialmente apropriada durante o mês de junho (mês do Sagrado Coração), nos dias que antecedem a Solenidade do Sagrado Coração (sexta-feira após Corpus Christi), ou sempre que alguém enfrenta um momento particularmente difícil. Se um dia for perdido, o conselho tradicional é começar novamente desde o primeiro dia em vez de saltá-lo; a disciplina da oração consecutiva é parte da graça da devoção. Alguns rezam por uma pessoa específica em cada dia da novena; outros oferecem todos os nove dias por uma única intenção.",
    patronSaint: "Santa Margarida Maria Alacoque",
    feastDay: "Sexta-feira após Corpus Christi",
    source:
      "CNBB materials in Portuguese + Vatican.va Brazilian Portuguese editions + traditional Catholic devotional sources for the Sacred Heart novena. Historical claims verified against Haurietis Aquas (Pius XII, 1956) and the published account of the apparitions at Paray-le-Monial. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-st-joseph",
    name: "Novena a São José",
    description:
      "São José, pai adotivo de Jesus e casto esposo da Santíssima Virgem Maria, é um dos intercessores mais amados na tradição católica. Embora a Escritura não registre nenhuma palavra pronunciada por ele, sua fidelidade é inconfundível: protegeu a Sagrada Família na fuga ao Egito, sustentou-os com o trabalho de suas mãos e ensinou a Jesus o ofício da carpintaria e os caminhos da masculinidade fiel. O Papa Pio IX o nomeou Patrono da Igreja Universal em 1870, e o Papa Francisco declarou o período 2020-2021 como Ano de São José por meio da carta apostólica Patris Corde («Com Coração de Pai»). Esta novena se nutre de uma longa tradição católica que reconhece São José como patrono dos pais, dos trabalhadores, das famílias, dos assuntos imobiliários e da boa morte — os quatro pilares de seu ministério terreno. É invocado especialmente em momentos de dificuldade financeira, discórdia familiar, dificuldades no trabalho e no discernimento vocacional. Muitos católicos se comprometem com a novena nos dias que antecedem uma de suas festas: 19 de março (Solenidade de São José, Esposo da Bem-Aventurada Virgem Maria) ou 1 de maio (São José Operário, instituída pelo Papa Pio XII em 1955 para santificar o trabalho humano). Santa Teresa de Ávila escreveu famosamente: «A outros santos parece que o Senhor deu graça para socorrer em alguma necessidade particular; mas a este glorioso santo, por experiência sei, tem-lhe dado graça para nos socorrer em todas as nossas necessidades».",
    instructions:
      "Reze uma vez ao dia por nove dias consecutivos. A estrutura tradicional: comece com o Sinal da Cruz; reze o texto da novena; conclua com um Pai-Nosso, uma Ave-Maria e um Glória; nomeie sua intenção específica. Algumas famílias católicas acrescentam as Ladainhas de São José ou sete Pai-Nossos, Ave-Marias e Glórias em honra das Sete Dores e Sete Alegrias de São José — uma devoção tradicional ligada às suas experiências dolorosas e alegres na vida da Sagrada Família. Para famílias que estão discernindo uma decisão importante (mudança de emprego, mudança de cidade, casamento), é costume começar a novena nove dias antes do prazo da decisão, pedindo a intercessão de São José para obter clareza e a graça de aceitar a vontade de Deus. A novena também é tradicionalmente rezada durante o mês de março (mês de São José) ou junto com a prática popular de enterrar uma estátua de São José em relação com a venda de uma casa — uma tradição popular que enfatiza a confiança serena, não a superstição. Seja a novena rezada pelo discernimento vocacional, pela provisão econômica, pela cura familiar ou por uma boa morte (um dos quatro fins tradicionais desta devoção), o espírito deve ser de confiança tranquila e trabalhadora — a mesma disposição que São José modelou nas Escrituras.",
    patronSaint: "São José",
    feastDay: "19 de março / 1 de maio",
    source:
      "Patris Corde (Francis, 2020) + CNBB materials in Portuguese + traditional Brazilian Catholic devotional sources for the St. Joseph novena. The St. Teresa of Ávila quotation is from her Vida (chapter 6). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "holy-rosary",
    name: "O Santo Rosário",
    description:
      "O Santo Rosário é a devoção mariana central da Igreja Católica — uma oração contemplativa em que o crente medita os grandes mistérios da vida, morte e ressurreição de Cristo enquanto reza dezenas repetidas de Ave-Marias. O Rosário, como o conhecemos hoje, tomou forma ao longo dos séculos; a tradição sustenta que a Santíssima Virgem Maria entregou o Rosário a São Domingos em 1208 como arma espiritual contra a heresia albigense, e a estrutura de quinze mistérios foi codificada pelo Papa São Pio V em 1569. Em 2002, o Papa São João Paulo II acrescentou os Mistérios Luminosos (Mistérios da Luz) em sua carta apostólica Rosarium Virginis Mariae, levando o total a vinte mistérios agrupados em quatro conjuntos. Cada dezena é uma meditação: enquanto os dedos percorrem as contas e os lábios recitam a Ave-Maria, a mente se detém num momento dos Evangelhos — a Anunciação, a Crucificação, a Ressurreição, a Transfiguração. O Rosário não é repetição vã (Mateus 6,7) mas uma escola de contemplação, permitindo que o ritmo das orações libere a mente para refletir sobre os mistérios da salvação. Os Papas, de Leão XIII (cujas onze encíclicas sobre o Rosário continuam sendo referências magisteriais) até Francisco, têm exortado os fiéis a rezar o Rosário diariamente. É a oração oferecida em Lourdes, Fátima e em inúmeras outras aparições marianas, e a oração mais frequentemente rezada por famílias católicas reunidas junto a um leito de doente ou diante de uma sepultura.",
    instructions:
      "Um Rosário completo consiste em cinco dezenas, geralmente rezado em cerca de vinte minutos. Comece com o Sinal da Cruz e o Creio dos Apóstolos sobre o crucifixo. Na primeira conta grande, reze o Pai-Nosso; em cada uma das três contas pequenas que seguem, reze uma Ave-Maria (pelo aumento das três virtudes teologais — fé, esperança e amor); na próxima conta grande, reze o Glória. Em seguida anuncie o primeiro mistério em voz alta e medite brevemente sobre seu significado; reze um Pai-Nosso na conta grande, dez Ave-Marias nas dez contas pequenas (uma por conta) continuando a meditar sobre o mistério, depois um Glória e a Oração de Fátima («Ó meu Jesus, perdoai-nos, livrai-nos do fogo do inferno…»). Repita por mais quatro dezenas, nomeando cada mistério. Conclua com a Salve-Rainha e a oração do Rosário. Os quatro conjuntos de mistérios são tradicionalmente rezados: Mistérios Gozosos nas segundas e sábados (Anunciação, Visitação, Nascimento, Apresentação, Encontro no Templo); Dolorosos nas terças e sextas (Agonia, Flagelação, Coroação de Espinhos, Caminho do Calvário, Crucificação); Gloriosos nas quartas e domingos (Ressurreição, Ascensão, Pentecostes, Assunção, Coroação); Luminosos nas quintas (Batismo, Bodas de Caná, Anúncio do Reino, Transfiguração, Instituição da Eucaristia). Para a cobertura de um PrayerTrain, uma única dezena — ou mesmo uma única Ave-Maria oferecida com intenção — também é uma oferta válida do Rosário.",
    patronSaint: "Nossa Senhora do Rosário",
    feastDay: "7 de outubro",
    source:
      "Rosarium Virginis Mariae (St. John Paul II, 2002) + Leo XIII's eleven rosary encyclicals + Catechism of the Catholic Church paragraphs 971, 2678, 2708 on the Marian dimension of prayer. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "chaplet-divine-mercy",
    name: "Terço da Divina Misericórdia",
    description:
      "O Terço da Divina Misericórdia foi entregue por Jesus a Santa Maria Faustina Kowalska, religiosa polonesa, em uma série de revelações ocorridas entre 1931 e 1938 e registradas em seu Diário: A Divina Misericórdia em Minha Alma. O terço é uma poderosa oração de intercessão oferecida pela conversão dos pecadores, pela consolação dos moribundos e pela misericórdia de Deus sobre o mundo inteiro. Jesus disse a Faustina que quem rezasse este terço receberia «grande misericórdia na hora da morte» — e que se deleitava especialmente nesta oração quando rezada às 3:00 da tarde, a Hora da Misericórdia (a hora de sua morte no Calvário). O terço é rezado num rosário comum, o que o torna acessível a qualquer pessoa que tenha um rosário, e leva aproximadamente dez minutos. A devoção à Divina Misericórdia esteve suprimida por muitos anos, mas o Papa São João Paulo II — ele próprio polonês e compatriota de Santa Faustina — a canonizou em 30 de abril de 2000 e estabeleceu o Domingo da Divina Misericórdia (segundo domingo de Páscoa) como festa para a Igreja universal. O Terço da Divina Misericórdia tornou-se uma das devoções mais rezadas na Igreja contemporânea, especialmente apreciada por capelães de hospital, voluntários de cuidados paliativos e por aqueles que rezam pela conversão de entes queridos. É a oração diária no Santuário Nacional da Divina Misericórdia em Stockbridge, Massachusetts, e no Santuário da Divina Misericórdia em Łagiewniki, Cracóvia — o lugar onde Faustina viveu, morreu e está hoje sepultada.",
    prayerText:
      "Pai Eterno, eu Vos ofereço o Corpo e o Sangue, a Alma e a Divindade de Vosso diletíssimo Filho, nosso Senhor Jesus Cristo, em expiação dos nossos pecados e dos do mundo inteiro. Pela Sua dolorosa Paixão, tende misericórdia de nós e do mundo inteiro.",
    instructions:
      "Usando um rosário comum de cinco dezenas, comece com o Sinal da Cruz, um Pai-Nosso, uma Ave-Maria e o Creio dos Apóstolos no crucifixo e nas contas iniciais. Em cada uma das cinco contas grandes (onde normalmente se reza o Pai-Nosso), reze: «Eterno Pai, eu Vos ofereço o Corpo e o Sangue, a Alma e a Divindade de Vosso diletíssimo Filho, Nosso Senhor Jesus Cristo, em expiação dos nossos pecados e dos do mundo inteiro». Em cada uma das dez contas pequenas de cada dezena, reze: «Pela Sua dolorosa Paixão, tende misericórdia de nós e do mundo inteiro». Ao terminar as cinco dezenas, conclua rezando três vezes: «Santo Deus, Santo Forte, Santo Imortal, tende piedade de nós e do mundo inteiro». O terço é especialmente poderoso quando rezado às 3:00 da tarde (a Hora da Misericórdia), junto ao leito dos moribundos, nos nove dias que antecedem o Domingo da Divina Misericórdia (a Novena à Divina Misericórdia, que começa na Sexta-feira Santa), e em momentos de angústia ou medo pessoal. Pode ser rezado em silêncio, em voz alta, sozinho ou em grupo. Muitas paróquias rezam o terço semanalmente, frequentemente às sextas-feiras em memória da Paixão de Cristo. Os católicos que rezam pela conversão ou pela morte serena de um ente querido frequentemente se comprometem a rezar o terço diariamente por um período sustentado — um mês, a duração de uma doença, o tempo que antecede uma decisão importante. O terço se associa naturalmente com a participação na Novena à Divina Misericórdia, da Sexta-feira Santa ao Domingo da Divina Misericórdia.",
    patronSaint: "Santa Faustina Kowalska",
    feastDay: "Domingo da Divina Misericórdia",
    source:
      "Diary: Divine Mercy in My Soul (St. Faustina Kowalska) + canonical chaplet text as approved by the Holy See following St. John Paul II's canonization of Faustina (April 30, 2000). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "memorare",
    name: "O Lembrai-vos (Memorare)",
    description:
      "O Memorare é uma oração breve mas extraordinariamente poderosa de confiança na intercessão da Santíssima Virgem Maria. Toma seu nome da primeira palavra latina do texto, Memorare («Lembrai-vos»), e em sua forma moderna é atribuída ao Pe. Claude Bernard, sacerdote francês do século XVII conhecido como «o Sacerdote Pobre» por seu apostolado entre prisioneiros e moribundos. A oração se popularizou pela distribuição que o Pe. Bernard fez de mais de 200 mil folhetos no Paris pré-Revolução, embora suas raízes devocionais remontem mais atrás — provavelmente a uma oração mais extensa atribuída a São Bernardo de Claraval (1090-1153), o grande abade cisterciense e Doutor da Igreja cuja devoção mariana moldou a piedade ocidental. A estrutura da oração é um apelo confiante: reconhece a maternidade universal de Maria («Ó Virgem das virgens, minha Mãe»), faz referência à tradição ininterrupta de sua intercessão («jamais se ouviu dizer que algum daqueles que recorreram à vossa proteção… tenha sido abandonado»), e conclui com uma petição humilde («em vossa misericórdia ouvi-me e atendei-me»). Os santos ao longo dos séculos testemunharam seu poder: Madre Teresa de Calcutá rezava nove Memorares consecutivos por dia — o que ela chamava sua «novena rápida» — quando precisava de algo com urgência. O Memorare é a oração católica de último recurso, rezada em momentos de necessidade aguda, junto ao leito dos moribundos, na capela antes de uma conversa difícil, ou sussurrada enquanto um pai ou uma mãe espera notícias de um quarto de hospital.",
    prayerText:
      "Lembrai-vos, ó piíssima Virgem Maria, que nunca se ouviu dizer que algum daqueles que recorreram à vossa proteção, imploraram vossa assistência e reclamaram vosso socorro, fosse por vós desamparado. Animado eu, pois, com igual confiança, a vós, ó Virgem das virgens, ó Mãe, recorro; de vós me valho; e, gemendo sob o peso de meus pecados, me prostro a vossos pés. Não desprezeis as minhas súplicas, ó Mãe do Verbo Divino, mas dignai-vos de me ouvir propícia. Amém.",
    instructions:
      "Reze uma vez com plena atenção e devoção, trazendo à mente a pessoa e a intenção que você está apresentando diante de Maria. O Memorare é suficientemente breve para ser memorizado e rezado em qualquer lugar — no carro, durante uma caminhada, antes de dormir, nos momentos que antecedem qualquer tarefa difícil. Para uma intercessão mais sustentada, reze nove Memorares consecutivos em sequência (esta é a «novena rápida» que Madre Teresa preferia para intenções urgentes). Algumas tradições acrescentam um breve momento de silêncio antes de rezar, nomeando a intenção em voz alta ou no coração. A oração também pode ser incorporada como oração de encerramento ao fim de um Rosário mais extenso ou de uma novena, selando o pedido com confiança serena no amor maternal de Maria. As famílias católicas costumam rezar o Memorare junto ao leito de alguém gravemente doente, ao receber um diagnóstico difícil, ou durante o trabalho de parto. Por ser uma oração breve cujas palavras são antigas e amadas, tornou-se uma espécie de resposta espiritual de emergência — uma oração que vem espontaneamente aos lábios quando outras palavras faltam. As crianças podem aprendê-la desde muito cedo, assim que conseguem recitá-la; é uma das orações mais apropriadas para ensinar a uma criança como «primeira oração de momentos de dificuldade». A versão latina original ainda é rezada por aqueles que se sentem atraídos pelas formas tradicionais: «Memorare, O piissima Virgo Maria, non esse auditum a saeculo…»",
    patronSaint: "São Bernardo de Claraval",
    feastDay: null,
    source:
      "Traditional Brazilian Catholic devotional text of the Memorare (Lembrai-vos), as published in CNBB-approved breviary editions and standard Brazilian Catholic prayer books. Historical attribution to Fr. Claude Bernard verified against the Catholic Encyclopedia entry. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── Round 2: 6 more prayers from PR #71 ────────────────────
  {
    prayerSlug: "novena-st-jude",
    name: "Novena a São Judas Tadeu",
    description:
      "São Judas Tadeu, chamado o Apóstolo da Esperança, foi um dos Doze e parente do Senhor, tradicionalmente considerado irmão de Tiago Menor. É mencionado nos Evangelhos como um dos apóstolos (Lucas 6,16) e é o autor da breve Carta de Judas. Por séculos, a devoção popular católica invocou São Judas como padroeiro das causas desesperadas e dos casos impossíveis. As razões oferecidas pela tradição são práticas: porque seu nome (Judas) era facilmente confundido com Judas Iscariotes, o traidor, sua intercessão foi evitada pelos cristãos comuns durante séculos — e assim, diz o ditado, ele anseia ajudar quem o procura em verdadeira necessidade. A devoção moderna foi popularizada nos Estados Unidos pelos padres claretianos, que construíram o Santuário Nacional de São Judas em Chicago em 1929 — em plena Grande Depressão. No Brasil, São Judas Tadeu tem profunda devoção popular, com o Santuário de São Judas Tadeu em Jabaquara (São Paulo) recebendo milhões de devotos no dia 28 de outubro. A devoção é fortemente associada à prática de publicar agradecimentos em anúncios de jornais. Esta novena é apropriada para doença com prognóstico difícil, colapso financeiro, afastamento familiar que parece sem solução, infertilidade e qualquer situação que uma pessoa vivencia como «além da esperança».",
    instructions:
      "Reze uma vez ao dia por nove dias consecutivos. A estrutura tradicional: comece com o Sinal da Cruz; reze o texto da novena a São Judas; conclua com um Pai-Nosso, uma Ave-Maria e um Glória; nomeie sua intenção específica. Muitos católicos acrescentam três Pai-Nossos, Ave-Marias e Glórias em honra à Santíssima Trindade. A novena pode ser rezada em qualquer época do ano, mas é especialmente apropriada nos nove dias que antecedem a festa de São Judas (28 de outubro). No Brasil, a devoção ganha intensidade especial em outubro, com missas especiais no Santuário de Jabaquara. Uma prática complementar tradicional é comprometer-se, quando a oração é atendida, a agradecer publicamente a São Judas.",
    patronSaint: "São Judas Tadeu",
    feastDay: "28 de outubro",
    source: "CNBB Portuguese + Santuário de São Judas Tadeu (Jabaquara, São Paulo). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-divine-mercy",
    name: "Novena à Divina Misericórdia",
    description:
      "A Novena à Divina Misericórdia foi entregue por Jesus a Santa Maria Faustina Kowalska, religiosa polonesa, em uma série de revelações registradas em seu Diário. Os escritos místicos de Faustina foram reabilitados pelo Papa São João Paulo II — ele próprio polonês e conterrâneo — que a canonizou em 30 de abril de 2000 e estabeleceu o Domingo da Divina Misericórdia (segundo domingo de Páscoa) como festa para a Igreja universal. A novena começa na Sexta-feira Santa e termina na véspera do Domingo da Divina Misericórdia. Cada um dos nove dias traz uma categoria diferente de almas ante o trono da misericórdia: Dia 1, toda a humanidade; Dia 2, sacerdotes e religiosos; Dia 3, almas devotas e fiéis; Dia 4, os que não creem; Dia 5, as almas dos irmãos separados; Dia 6, os humildes e as crianças; Dia 7, as almas que veneram a Divina Misericórdia; Dia 8, as almas do purgatório; Dia 9, as almas mornas. O lar espiritual da novena é o Santuário da Divina Misericórdia em Łagiewniki, Cracóvia.",
    instructions:
      "Reze uma vez ao dia por nove dias consecutivos, tradicionalmente começando na Sexta-feira Santa. Cada dia tem uma intenção única e uma invocação inicial única que Jesus ditou a Santa Faustina; após a abertura do dia, a oração conclui com o Terço da Divina Misericórdia. A estrutura tradicional de cada dia: (1) Leia a intenção específica do dia; (2) Reze a oração inicial; (3) Reze o Terço da Divina Misericórdia inteiro; (4) Conclua com uma intenção pessoal. A novena completa toma aproximadamente quinze minutos por dia.",
    patronSaint: "Santa Faustina Kowalska",
    feastDay: "Domingo da Divina Misericórdia",
    source: "Diary: Divine Mercy in My Soul + canonical Portuguese-language novena texts. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-our-lady-perpetual-help",
    name: "Novena a Nossa Senhora do Perpétuo Socorro",
    description:
      "Nossa Senhora do Perpétuo Socorro é um dos títulos marianos mais amados na Igreja Católica. A devoção centra-se em um ícone bizantino do século XV mostrando o Menino Jesus segurado nos braços de Maria enquanto os arcanjos Miguel e Gabriel se aproximam, cada um carregando instrumentos da Paixão. O Menino Jesus volta seu rosto para sua Mãe com aparente temor; uma sandália pende solta de seu pé, um detalhe tradicionalmente lido como o Menino recuando diante da Paixão prenunciada. O ícone chegou a Roma em 1499 e foi venerado por séculos antes de desaparecer durante as supressões napoleônicas; foi redescoberto em 1862 e entregue pelo Papa Pio IX aos padres redentoristas em 1866. No Brasil, a devoção é particularmente forte: o Santuário Basílica de Nossa Senhora do Perpétuo Socorro em Salvador (Bahia), administrado pelos redentoristas brasileiros, é um dos principais centros marianos do país.",
    instructions:
      "Reze uma vez ao dia por nove dias consecutivos. A novena redentorista tradicionalmente acompanha a oração de cada dia com o canto do hino «Mãe de Cristo». Muitas paróquias ainda realizam serviços semanais de novena ao Perpétuo Socorro às quartas-feiras. A estrutura tradicional: (1) Sinal da Cruz; (2) Reze a oração da novena; (3) Conclua com três Ave-Marias e uma Salve-Rainha; (4) Nomeie sua intenção. A novena é apropriadamente rezada nos dias que antecedem a Festa (27 de junho), mas pode ser rezada a qualquer momento.",
    patronSaint: "Nossa Senhora do Perpétuo Socorro",
    feastDay: "27 de junho",
    source: "Redemptorist tradition + Santuário Basílica em Salvador + Pius IX 1866 entrustment. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "litany-sacred-heart",
    name: "Ladainha do Sagrado Coração de Jesus",
    description:
      "A Ladainha do Sagrado Coração de Jesus é uma das seis ladainhas aprovadas pela Santa Sé para uso litúrgico público no Rito Latino. Composta em 1718 por Irmã Joana Madalena Joly da Ordem da Visitação em Dijon, a ladainha foi refinada e ampliada durante o século seguinte. O Papa Leão XIII deu à ladainha aprovação formal para uso litúrgico público em 2 de abril de 1899 — no mesmo ano em que consagrou toda a raça humana ao Sagrado Coração em sua encíclica Annum Sacrum. A ladainha é estruturada como trinta e três invocações ao Coração de Cristo sob títulos distintos correspondentes aos trinta e três anos da vida terrena de Cristo. A cada invocação é dada a resposta «Tende piedade de nós».",
    instructions:
      "A ladainha é rezada responsorialmente. Um líder pronuncia cada invocação e a comunidade reunida responde com a fórmula indicada. Seguem-se as trinta e três invocações ao Coração de Jesus. A duração total é de aproximadamente dez a quinze minutos. Apropriadamente rezada: nas Primeiras Sextas-feiras; durante o mês de junho; durante a Novena ao Sagrado Coração; no final de uma Hora Santa de adoração eucarística.",
    patronSaint: "Sagrado Coração de Jesus",
    feastDay: "Sexta-feira após Corpus Christi",
    source: "Annum Sacrum (Leo XIII, 1899) + CNBB Portuguese. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "litany-blessed-virgin",
    name: "Ladainha de Nossa Senhora (Ladainha de Loreto)",
    description:
      "A Ladainha de Nossa Senhora — conhecida tradicionalmente como Ladainha de Loreto — é a ladainha mariana mais antiga e amada da Igreja Latina. Leva seu nome comum da Santa Casa de Loreto nas Marcas italianas. O Papa Sisto V aprovou formalmente a ladainha para uso litúrgico e devocional em 1587. Ao longo dos séculos: Pio VII acrescentou «Auxílio dos Cristãos» em 1815; Pio IX «Rainha concebida sem pecado original» após 1854; Pio XII «Rainha assunta ao céu» após 1950; São João Paulo II «Mãe da Igreja» em 1980 e «Rainha das Famílias» em 1995. Mais recentemente, o Papa Francisco acrescentou «Mãe da Misericórdia», «Mãe da Esperança» e «Consolo dos Migrantes» em 2020.",
    instructions:
      "A ladainha é rezada responsorialmente. Um líder pronuncia cada título de Maria e a comunidade reunida responde «Rogai por nós». A Ladainha de Loreto é tradicionalmente rezada após o Santo Rosário; durante os meses marianos de maio e outubro; ao final da novena mariana antes das solenidades marianas.",
    patronSaint: "Nossa Senhora",
    feastDay: null,
    source: "Sixtus V 1587 approval + papal additions through Francis 2020 + CNBB Portuguese. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "prayer-conversion",
    name: "Oração pela Conversão de um Ente Querido",
    description:
      "A oração católica pela conversão de um ente querido está enraizada num dos grandes testemunhos pastorais da história cristã: a longa e fiel oração de Santa Mônica por seu filho Santo Agostinho. Mônica rezou pela conversão de seu filho durante anos, através de suas próprias lágrimas e o conselho que recebeu de Santo Ambrósio de Milão («Não é possível que pereça o filho de tantas lágrimas»). Agostinho foi batizado em 387 aos trinta e três anos; Mônica morreu pouco depois em Óstia, tendo vivido para ver o que havia pedido. Agostinho registrou sua perseverança em suas Confissões (Livro IX). O testemunho pastoral que Mônica encarna não é uma garantia de resultado — a conversão de Agostinho aconteceu no tempo de Deus, não no de Mônica — mas uma postura de fidelidade inabalável.",
    instructions:
      "Reze diariamente, idealmente na mesma hora e na mesma postura (de joelhos, ante um crucifixo ou uma imagem do Sagrado Coração). Nomeie a pessoa em voz alta na oração onde o texto diz «(nome)». Após a oração, dedique um minuto de silêncio a sustentá-la diante do Sagrado Coração. Muitos católicos combinam esta oração com: (1) oferecimento diário de pequenos sacrifícios pela intenção; (2) intenção regular de Missa pela pessoa, especialmente no dia de Santa Mônica (27 de agosto) ou Santo Agostinho (28 de agosto); (3) Novena a Santa Mônica ou a Santo Agostinho; (4) Terço da Divina Misericórdia às 15:00.",
    patronSaint: "Santa Mônica",
    feastDay: "27 de agosto",
    source: "Augustine's Confissões Book IX + CNBB Portuguese pastoral resources. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── Locale-anchored devotion (Brazil) ─────────────────────
  {
    prayerSlug: "novena-aparecida",
    name: "Novena a Nossa Senhora Aparecida",
    description:
      "Nossa Senhora Aparecida (Our Lady of Aparecida, ou Nossa Senhora Que Apareceu) é a Padroeira Principal do Brasil e a devoção mariana central do maior país católico do mundo. A história de origem pertence a outubro de 1717 no rio Paraíba do Sul, na pequena cidade pesqueira de Guaratinguetá, estado de São Paulo. Três pescadores locais — Domingos Garcia, João Alves e Filipe Pedroso — haviam sido ordenados pela vila a fornecer peixe para um dignitário visitante, o Conde de Assumar, mas não haviam pescado nada o dia todo. Após horas de trabalho infrutífero, João Alves lançou sua rede mais uma vez e trouxe à tona o corpo decapitado de uma estátua de terracota da Imaculada Conceição. Lançando novamente, trouxe a cabeça. Os homens juntaram as peças, rezaram pela intercessão da Virgem e lançaram suas redes uma última vez — recolhendo uma pesca milagrosa de peixes tão abundante que suas canoas quase afundaram. A pequena estátua de argila escura (originalmente marrom claro, as águas ricas em ferro do rio a haviam escurecido) foi levada para casa por Filipe Pedroso e venerada em sua casa por quinze anos; relatos de curas e intercessões se espalharam, e uma pequena capela foi construída em 1745. O Papa São Pio X declarou Nossa Senhora Aparecida Padroeira Principal do Brasil em 1930. Sua festa (12 de outubro) foi elevada a feriado nacional brasileiro em 1980 pelo Presidente João Figueiredo a pedido do Papa São João Paulo II durante sua primeira peregrinação ao Brasil. A atual Basílica de Nossa Senhora Aparecida — concluída em 1980 — é a segunda maior igreja católica do mundo, depois da Basílica de São Pedro em Roma, e um dos santuários marianos mais visitados do mundo.",
    instructions:
      "Reze uma vez ao dia por nove dias consecutivos. A novena é tradicionalmente rezada nos nove dias que antecedem a Festa de Nossa Senhora Aparecida (12 de outubro), o feriado nacional brasileiro. No Brasil, o dia é observado com: (a) a celebração da Santa Missa na Basílica de Aparecida, transmitida nacionalmente pela Rede Vida e Canção Nova; (b) o canto do tradicional hino «Nossa Senhora Aparecida» nas paróquias de todo o país; (c) encontros familiares apresentando a refeição tradicional brasileira de peixe (em lembrança da pesca milagrosa dos pescadores); (d) altares domésticos exibindo a imagem de barro escuro de Aparecida frequentemente coroada com um pequeno véu branco. A estrutura da novena em casa: (1) Sinal da Cruz; (2) Leitura de uma breve reflexão sobre a aparição; (3) Reze o texto da novena; (4) Três Ave-Marias; (5) Nomeie a intenção específica. Os católicos brasileiros comumente rezam a novena de Aparecida pela cura dos enfermos, pela proteção da família, por viagens seguras (a Basílica é um importante destino de peregrinação), pela conversão de membros distantes da família, e em tempos de dificuldade nacional. A devoção também é forte na diáspora brasileira — nos Estados Unidos, o apostolado brasileiro da Arquidiocese de Newark e as comunidades católicas brasileiras de Boston, Miami e Massachusetts mantêm procissões de Aparecida em 12 de outubro.",
    patronSaint: "Nossa Senhora Aparecida",
    feastDay: "12 de outubro",
    source: "CNBB + Basílica de Nossa Senhora Aparecida + Pope St. John Paul II's 1980 visit. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── ROUND 3 (pt-BR) ───────────────────────────────────────
  {
    prayerSlug: "litany-st-joseph",
    name: "Ladainha de São José",
    description:
      "A Ladainha de São José é uma das seis ladainhas aprovadas pela Santa Sé para uso litúrgico público no Rito Latino. Composta gradualmente durante os séculos XVII e XVIII, conforme a devoção a São José se aprofundava em todo o mundo católico, a ladainha recebeu sua aprovação magisterial formal do Papa São Pio X em 18 de março de 1909 — véspera da Festa de São José — para o Esposo de Maria, pai adotivo de Jesus e Patrono da Igreja Universal. A estrutura segue o padrão das outras ladainhas católicas aprovadas: uma abertura de Kyrie, uma invocação trinitária, e então uma longa sequência de invocações dirigidas a São José sob títulos distintos, cada um com a resposta «Rogai por nós»: «Ilustre filho de Davi», «Luz dos patriarcas», «Esposo da Mãe de Deus», «Casto guardião da Virgem», «Pai adotivo do Filho de Deus», «Solícito defensor de Cristo», «Chefe da Sagrada Família», «José justíssimo», «José castíssimo», «José prudentíssimo», «Espelho de paciência», «Amante da pobreza», «Modelo dos trabalhadores», «Glória da vida doméstica», «Guardião dos virgens», «Sustentáculo das famílias», «Consolo dos aflitos», «Esperança dos enfermos», «Patrono dos moribundos», «Terror dos demônios», «Protetor da Santa Igreja». Em maio de 2021, em conexão com o Ano de São José (dezembro de 2020 - dezembro de 2021) e sua carta apostólica Patris Corde, o Papa Francisco adicionou formalmente sete novas invocações à ladainha, tiradas diretamente da linguagem de Patris Corde: «Guardião do Redentor», «Servo de Cristo», «Ministro da salvação», «Apoio nas dificuldades», «Patrono dos exilados», «Patrono dos aflitos» e «Patrono dos pobres». Essas adições refletem o enquadramento pastoral específico de Francisco de São José como modelo para os pais, os trabalhadores e os marginalizados do mundo contemporâneo.",
    instructions:
      "A ladainha é rezada responsorialmente. Um guia pronuncia cada invocação («José justíssimo…») e a assembleia responde «Rogai por nós» a cada uma. O padrão inicial do Kyrie e a invocação trinitária usam «Tende piedade de nós» como resposta; o corpo da ladainha — a longa sequência de títulos — usa «Rogai por nós». A ladainha conclui com três invocações ao Cordeiro de Deus (Agnus Dei), um par de versículo-resposta tirado do Gênesis («Ele o constituiu senhor de sua casa, e administrador de todos os seus bens»), e uma coleta a São José. A duração total é aproximadamente dez minutos quando rezada em ritmo devocional sem pressa. A Ladainha de São José é tradicionalmente rezada: durante o mês de março, Mês de São José; nos dias que antecedem a Solenidade de São José (19 de março) ou a Festa de São José Operário (1º de maio); ao final de uma Hora Santa ou adoração eucarística; em contextos familiares pedindo a proteção de São José sobre o lar. As adições de 2021 podem ser incorporadas em qualquer texto impresso tradicional inserindo as sete novas invocações em seus lugares apropriados na sequência da ladainha (a maioria das versões atuais publicadas as inclui); tanto a Conferência Nacional dos Bispos do Brasil (CNBB) quanto o site da Santa Sé publicam o texto oficial completo atualizado em português. Muitas famílias católicas rezam a ladainha juntas nas noites de quarta-feira (o dia tradicionalmente dedicado a São José no calendário devocional católico antigo). Quando rezada sozinho, simplesmente leia tanto a invocação quanto a resposta em voz alta ou silenciosamente.",
    patronSaint: "São José",
    feastDay: "19 de março",
    source: "CNBB + Patris Corde (Papa Francisco, 8 de dezembro de 2020) + Aprovação do Papa Pio X de 1909. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-holy-spirit",
    name: "Novena ao Espírito Santo",
    description:
      "A Novena ao Espírito Santo é a novena original — o padrão de oração do qual desce toda outra novena católica de nove dias. Seu fundamento bíblico é o livro dos Atos dos Apóstolos: «Todos eles perseveravam unanimemente em oração, com algumas mulheres, e com Maria, mãe de Jesus, e seus irmãos» (Atos 1,14). Por nove dias após a Ascensão de Cristo, os discípulos e a Bem-Aventurada Virgem Maria permaneceram no cenáculo em Jerusalém em oração; no décimo dia, a Festa de Pentecostes (Atos 2,1-4), o Espírito Santo desceu sobre eles com o som de um vento impetuoso e línguas de fogo. Toda novena católica desde então toma seu padrão de nove dias deste único precedente dado pelo Espírito. A novena invoca os sete dons do Espírito Santo enumerados em Isaías 11,2-3: sabedoria, entendimento, conselho, fortaleza, ciência, piedade e temor de Deus. A estes a tradição católica acrescenta os doze frutos do Espírito Santo nomeados na Carta aos Gálatas (5,22-23 na enumeração da Vulgata): caridade, alegria, paz, paciência, benignidade, bondade, longanimidade, mansidão, fé, modéstia, continência e castidade. O tom da novena é petitório mas confiante — o Espírito é o dom que Jesus prometeu enviar (João 14,16-17; 16,7-15), e a Igreja reza com confiança de que o mesmo Espírito que desceu sobre os apóstolos continua descendo sobre os fiéis. A novena é especialmente apropriada para o discernimento da vocação, a unção dos enfermos, a preparação daqueles que recebem sacramentos (Crisma, matrimônio, ordenação), e qualquer momento em que uma alma sente que não pode encontrar clareza por sua sola razão e precisa da inspiração do Espírito.",
    prayerText:
      "Vinde, Espírito Santo, enchei os corações dos vossos fiéis e acendei neles o fogo do Vosso amor. Enviai o Vosso Espírito e tudo será criado, e renovareis a face da terra. Ó Deus, que instruístes os corações dos vossos fiéis com a luz do Espírito Santo, fazei que apreciemos retamente todas as coisas segundo o mesmo Espírito e gozemos sempre da sua consolação. Por Cristo, Nosso Senhor. Amém.",
    instructions:
      "Reze uma vez ao dia por nove dias consecutivos. Tradicionalmente, a novena é rezada entre a Ascensão e o Domingo de Pentecostes — os nove dias originais que a Igreja tem rezado continuamente desde os apóstolos. (Em dioceses onde a Ascensão é transferida para o domingo seguinte à quinta-feira tradicional, a novena começa na sexta-feira depois desse domingo; consulte o calendário litúrgico local.) A novena também pode ser rezada em qualquer outro momento do ano por uma intenção privada. A estrutura tradicional para cada dia: (1) Começar com o Sinal da Cruz; (2) Recitar ou cantar o Veni Creator Spiritus («Vinde, Espírito Criador») ou o Veni Sancte Spiritus («Vinde, Espírito Santo») — as duas grandes sequências latinas de Pentecostes; (3) Rezar a oração da novena; (4) Meditar brevemente sobre um dos sete dons do Espírito (um por dia durante os primeiros sete dias; nos dias oito e nove, sobre os doze frutos e sobre uma intenção pessoal); (5) Concluir com um Pai-Nosso, uma Ave-Maria e um Glória. A duração total é aproximadamente dez minutos por dia. Famílias com crianças pequenas frequentemente rezam uma versão mais curta usando apenas a invocação Vinde, Espírito Santo e uma explicação apropriada para crianças de um dom por dia — os dons e frutos são tangíveis o suficiente para que uma criança de cinco anos possa começar a reconhecê-los em sua própria vida ao longo de nove anoiteceres. A novena também é apropriada antes de uma decisão importante, antes de uma conversa difícil, ou antes de qualquer tarefa em que uma pessoa precisa de conselho, fortaleza ou sabedoria além de sua capacidade natural.",
    patronSaint: null,
    feastDay: "Pentecostes",
    source: "CNBB + Atos 1,14, 2,1-4 + Vatican.va Portuguese liturgical sources. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-st-therese",
    name: "Novena a Santa Teresinha do Menino Jesus",
    description:
      "Santa Teresinha do Menino Jesus e da Sagrada Face — mais conhecida como Teresa de Lisieux ou «a Florzinha» — foi uma religiosa carmelita descalça que entrou no claustro de Lisieux, na Normandia, aos quinze anos e morreu de tuberculose aos vinte e quatro (1873-1897). Sua autobiografia espiritual, História de uma Alma, foi publicada logo após sua morte e rapidamente se tornou um dos livros católicos mais lidos da era moderna. Da obscuridade de um claustro provincial ela ensinou o que chamou de Caminho Pequeno: confiança no amor misericordioso de Deus expresso nos menores atos de fidelidade diária, em vez de em feitos externos heroicos. «Passarei meu céu fazendo o bem sobre a terra», ela prometeu célebremente; «farei cair uma chuva de rosas». A tradição da «chuva de rosas» — a crença de que as intercessões respondidas através de Santa Teresinha são frequentemente acompanhadas por uma rosa inesperada, literal ou simbólica — moldou a devoção católica a ela desde então. Foi canonizada pelo Papa Pio XI em 1925, nomeada Padroeira das Missões em 1927 (apesar de nunca ter deixado o claustro), e proclamada Doutora da Igreja pelo Papa São João Paulo II em 1997 — uma de apenas quatro mulheres assim nomeadas, junto com as Santas Teresa d'Ávila, Catarina de Sena e Hildegarda de Bingen. Sua contribuição doutrinal é a teologia da infância: o ensinamento evangélico de que é preciso tornar-se como uma criança pequena para entrar no Reino (Mateus 18,3) recebendo uma articulação contemplativa sustentada. A novena a Santa Teresinha é apropriada para: discernimento da vocação religiosa ou leiga, recuperação de doença (sua própria tuberculose foi suportada com grande sofrimento), aridez espiritual, a conversão de entes queridos distantes (ela rezou continuamente por Pranzini, um assassino condenado, como seu «primeiro filho»), e qualquer momento em que uma alma sente sua própria pequenez diante de uma grande necessidade.",
    instructions:
      "Reze uma vez ao dia por nove dias consecutivos. A estrutura tradicional: (1) Comece com o Sinal da Cruz; (2) Reze a oração da novena a Santa Teresinha (pedindo sua intercessão e sua famosa rosa); (3) Nomeie sua intenção silenciosamente ou em voz alta; (4) Conclua com um Pai-Nosso, uma Ave-Maria e um Glória. A novena é rezada apropriadamente nos nove dias que antecedem sua festa (1º de outubro) ou em qualquer momento do ano por uma intenção privada. Muitos católicos guardam uma pequena imagem ou relíquia de Santa Teresinha em casa ou carregam um santinho com tema de rosas durante a novena. A tradição da «chuva de rosas» é exatamente isso — uma tradição, não uma garantia mágica. Uma rosa recebida durante ou depois da novena é lida como um sinal pessoal de que a santa ouviu a oração e está intercedendo diante de Cristo; a ausência de uma rosa não é lida como a ausência de intercessão. O ponto é a disposição: o Caminho Pequeno de Teresinha convida o peticionário à mesma confiança infantil que ela modelou, que é em si mesma a graça pedida. A novena também é um acompanhamento apropriado a atos específicos de pequena fidelidade durante os nove dias — paciência com um familiar difícil, aceitar um pequeno desconforto sem reclamar, conter uma palavra cortante, realizar um ato oculto de bondade diariamente. Esses «pequenos caminhos» encarnam o que a novena pede: não transformação heroica, mas o caminho das pequenas coisas feitas com grande amor que Teresinha ensinou e viveu.",
    patronSaint: "Santa Teresinha do Menino Jesus",
    feastDay: "1º de outubro",
    source: "CNBB + História de uma Alma + Papa São João Paulo II Divini Amoris Scientia (1997, declaração como Doutora da Igreja). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "novena-miraculous-medal",
    name: "Novena da Medalha Milagrosa",
    description:
      "Na noite de 18 para 19 de julho de 1830, na capela das Filhas da Caridade na Rue du Bac em Paris, uma jovem noviça chamada Catarina Labouré foi acordada por seu anjo da guarda e conduzida à capela para uma aparição privada da Bem-Aventurada Virgem Maria. Maria falou com ela por mais de duas horas sobre o estado conturbado da França e da Igreja em geral. Em uma segunda aparição em novembro, Catarina viu Maria em pé sobre um globo com raios de luz emanando de suas mãos, cercada por um quadro inscrito com as palavras: «Ó Maria, concebida sem pecado, rogai por nós que recorremos a vós!» No verso desta visão havia um M cruciforme com doze estrelas, um coração de Cristo coroado de espinhos, e um coração de Maria traspassado por uma espada. Maria instruiu Catarina: «Mande cunhar uma medalha segundo este modelo. Aqueles que a usarem com devoção receberão grandes graças, especialmente se a usarem ao pescoço». A medalha foi cunhada em 1832 com a aprovação do Arcebispo de Paris. Em cinco anos havia sido distribuída em tais quantidades e acompanhada por tantas intercessões relatadas que a imaginação católica popular a renomeou «a Medalha Milagrosa», nome que a Igreja eventualmente adotou. As aparições de 1830 são notáveis como um dos principais eventos marianos da era moderna, anteriores a Lourdes (1858) por vinte e oito anos e a Fátima (1917) por oitenta e sete. A doutrina da Imaculada Conceição — no coração da inscrição central da medalha — foi formalmente definida pelo Papa Pio IX em 1854, vinte e quatro anos após as visões de Catarina. Catarina Labouré permaneceu em seu convento de Reuilly, trabalhando com os idosos pobres, pelos quarenta e seis anos restantes de sua vida. Foi canonizada em 1947 pelo Papa Pio XII. A novena à Medalha Milagrosa é apropriada para: doença (especialmente com mau prognóstico — a reputação da medalha começou com curas), conversão de familiares, proteção durante a gravidez (uma longa tradição católica de prender a medalha ao vestido da mãe ou levá-la durante o parto), e qualquer momento difícil em que uma alma busca a intercessão maternal específica de Maria através deste sinal particular.",
    instructions:
      "Reze uma vez ao dia por nove dias consecutivos. A estrutura tradicional: (1) Começar com o Sinal da Cruz; (2) Rezar o Memorare ou três Ave-Marias como invocação mariana inicial; (3) Rezar a oração da novena à Imaculada Virgem pela Medalha Milagrosa; (4) Concluir com a inscrição central da medalha como jaculatória: «Ó Maria, concebida sem pecado, rogai por nós que recorremos a vós!»; (5) Nomear a intenção específica. Se possível, use a Medalha Milagrosa — fisicamente — durante a novena. A medalha não é um amuleto; a tradição é que usá-la expressa a confiança na intercessão de Maria e a abertura de quem a usa à graça. Capelas e santuários católicos distribuem Medalhas Milagrosas gratuitamente. A novena pode ser rezada em qualquer momento mas é especialmente apropriada nos dias que antecedem a Festa de Nossa Senhora da Medalha Milagrosa (27 de novembro) ou a Solenidade da Imaculada Conceição (8 de dezembro). Muitos católicos também usam a Medalha Milagrosa como sinal de consagração ao Imaculado Coração de Maria — emparelhando a novena com a oração de Consagração Total de São Maximiliano Kolbe ou a preparação mais longa de 33 dias para a consagração mariana (a tradição de Montfort). Para famílias rezando por um ente querido ausente ou em dificuldade, uma prática tradicional é deslizar uma Medalha Milagrosa entre os pertences do ente querido — uma carteira, o bolso de um casaco, uma mochila — como um pequeno sinal de constante acompanhamento maternal.",
    patronSaint: "Santa Catarina Labouré",
    feastDay: "27 de novembro",
    source: "CNBB + narrativa da aparição de Rue du Bac (1830) + Papa Pio XII canonização de 1947. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "st-michael-prayer",
    name: "Oração a São Miguel Arcanjo",
    description:
      "A Oração a São Miguel Arcanjo foi composta pelo Papa Leão XIII em 1886 após, segundo a tradição longamente atestada, o Papa ter uma súbita experiência mística enquanto celebrava a Missa — uma espécie de visão em vigília na qual ele ouviu um colóquio entre Cristo e Satanás no qual Satanás se vangloriava de poder destruir a Igreja se lhe fosse concedido tempo e poder suficientes. Abalado pelo que havia visto, Leão XIII compôs a oração a São Miguel naquele mesmo dia e ordenou que fosse adicionada às orações rezadas pelo sacerdote e pelos fiéis ao final de cada Missa rezada em toda a Igreja universal. Esta prática — as «Orações Leoninas» depois da Missa — continuou por quase oitenta anos até as reformas litúrgicas dos anos sessenta. A oração a São Miguel não foi abolida mas seu lugar formal nas orações pós-Missa decaiu. O Papa São João Paulo II reviveu a proeminência da oração em uma alocução do Angelus dominical de 1994, na qual instou os fiéis a «não esquecer de recitar» a oração a São Miguel «para obter ajuda na batalha contra as forças das trevas e contra o espírito deste mundo». O texto da oração baseia-se em Judas 1,9 (Miguel disputando com o diabo pelo corpo de Moisés), Apocalipse 12,7-9 (Miguel derrubando o dragão), e a tradição católica mais ampla de São Miguel como o líder da milícia celestial contra as potências do mal. A oração é apropriada para: guerra espiritual em qualquer forma, ansiedade pelo mal no mundo ou na vida pessoal, proteção durante uma viagem ou antes de um encontro difícil, a conversão daqueles que caíram em pecado grave, e como oração diária de consagração à proteção de São Miguel. É a oração mais comumente ensinada às crianças católicas como primeira «oração de proteção» juntamente com a oração do Anjo da Guarda.",
    instructions:
      "Reze uma vez com plena atenção e devoção. A Oração a São Miguel é curta o suficiente para memorizar e rezar em qualquer lugar — no carro antes de uma reunião difícil, à porta de um hospital, caminhando perto de um local onde se percebe discórdia espiritual, antes de dormir ao final do dia. A prática católica tradicional — e a que Leão XIII instituiu originalmente — é rezá-la imediatamente após a conclusão da Santa Missa, seja no silêncio que segue a despedida ou como parte de uma sequência pública de Orações Leoninas. Muitas paróquias reviveram a oração a São Miguel pós-Missa após o chamado de JPII em 1994; se sua paróquia não o faz, é completamente apropriado permanecer no seu banco por trinta segundos após a despedida e rezá-la privadamente. A oração também é frequentemente incluída: no encerramento do Rosário ou de uma Hora Santa; ao concluir as orações noturnas em família; antes de qualquer tarefa em que um católico perceba uma real oposição espiritual. Alguns lares católicos colocam a oração sobre a porta principal da casa como sinal de consagração à proteção de São Miguel sobre o lar, em continuidade com a tradição mais antiga de inscrever «Christus vincit, Christus regnat, Christus imperat» («Cristo vence, Cristo reina, Cristo impera») sobre os umbrais. A oração se emparelha naturalmente com a oração do Anjo da Guarda para crianças: São Miguel como príncipe da hoste angélica, e o anjo da guarda como o espírito ministrante particular designado a cada pessoa no batismo.",
    patronSaint: "São Miguel Arcanjo",
    feastDay: "29 de setembro",
    source: "CNBB + Composição de Leão XIII de 1886 + Papa São João Paulo II Angelus de Domingo, 24 de abril de 1994. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "anima-christi",
    name: "Alma de Cristo (Anima Christi)",
    description:
      "O Anima Christi («Alma de Cristo») é uma das orações eucarísticas mais amadas e mais antigas da tradição católica. Sua origem é medieval — provavelmente do século XIV — e por muitos anos foi atribuída a Santo Inácio de Loyola porque ele a colocou no próprio início de seus Exercícios Espirituais (1522-1524) e a recomendou como oração diária para os retirantes. A erudição moderna datou a oração pelo menos um século antes do nascimento de Inácio; aparece em manuscritos já em 1314, possivelmente composta por João XXII ou por um monge anônimo da tradição cartuxa ou franciscana. Inácio não a escreveu, mas a amava, e seus Exercícios Espirituais lhe deram a ampla circulação que ela goza hoje em todo o mundo católico. A oração é uma meditação sustentada sobre o Cristo Eucarístico — Sua alma, Seu corpo, Seu sangue, a água e o sangue que fluíram do Seu lado traspassado na Crucificação (João 19,34), Sua Paixão. Cada linha é ao mesmo tempo uma confissão de fé e uma petição: «Alma de Cristo, santificai-me» é a oração de quem pede ser interiormente santificado pela própria santidade de Cristo; «Corpo de Cristo, salvai-me» é a confissão de que a salvação vem através do mesmo corpo agora recebido sob a aparência de pão; «Dentro de Vossas chagas, escondei-me» é o anseio místico medieval de encontrar refúgio nas próprias chagas do Senhor crucificado. O encerramento da oração — «Na hora da minha morte, chamai-me» — fez dela uma oração católica tradicional para os moribundos, rezada à beira do leito nas horas finais por capelães de hospícios, familiares e enfermeiros católicos. O Anima Christi é apropriado para: ação de graças imediatamente após receber a Sagrada Comunhão (seu uso devocional principal), uma Hora Santa ou visita ao Santíssimo Sacramento, o encerramento da oração pessoal, o leito dos moribundos, e como devoção diária que expressa intimidade eucarística.",
    instructions:
      "Reze com devoção, idealmente numa postura de quietude atenta — de joelhos, sentado ereto com as mãos abertas, ou em pé diante do Santíssimo Sacramento. A oração é pensada para ser sem pressa; cada linha é uma petição distinta e o ritmo natural permite uma breve pausa entre as frases para que cada linha se assente no coração. Os momentos tradicionais para o Anima Christi: (1) Imediatamente após receber a Sagrada Comunhão na Missa, no silêncio da ação de graças pessoal — este é o uso devocional principal da oração, e a recomendação de Santo Inácio; (2) Durante uma Hora Santa ou adoração eucarística diante do Santíssimo Sacramento exposto; (3) No encerramento da oração pessoal matutina ou vespertina, especialmente como parte de uma espiritualidade eucarística; (4) À beira do leito de alguém gravemente enfermo ou moribundo — a linha final, «Na hora da minha morte, chamai-me e mandai-me ir a Vós», faz a oração particularmente apropriada como devoção de leito de morte, rezada pela pessoa moribunda se consciente ou por familiares ao lado dela; (5) Versão cantada em latim («Anima Christi, sanctifica me…») em ambientes monásticos e litúrgicos tradicionais. Muitos santinhos católicos trazem o Anima Christi no verso junto com uma oração de recepção da Comunhão; alguns livros devocionais católicos abrem com ela (seguindo o padrão dos Exercícios Espirituais). A oração pode ser memorizada em uma única tarde e rezada em qualquer lugar; sua brevidade e densidade de conteúdo eucarístico a fazem uma das orações breves de maior alcance no repertório devocional católico.",
    patronSaint: "Santo Inácio de Loyola",
    feastDay: null,
    source: "Vatican.va Portuguese + Exercícios Espirituais de Santo Inácio (1522-1524) + tradição manuscrita do século XIV. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },

  // ─── ROUND 4 (pt-BR) ───────────────────────────────────────
  {
    prayerSlug: "litany-saints",
    name: "Ladainha de Todos os Santos",
    description:
      "A Ladainha de Todos os Santos é a ladainha mais antiga e solene da Igreja Católica. Suas raízes remontam aos primeiros séculos — fragmentos da forma aparecem em livros litúrgicos ocidentais do século VII, e o Papa Gregório Magno instituiu as grandes procissões letânicas de Roma em 590, pedindo aos fiéis que invocassem os santos pelo nome em súplica durante a peste. A ladainha tornou-se parte da liturgia batismal da Vigília Pascal pelo menos no século VIII. Seu texto atual no rito romano foi formalmente fixado pelo Papa Pio V em 1568 e revisado na reforma litúrgica pós-Vaticano II (1969). A estrutura desdobra-se em cinco movimentos principais: (1) Invocações do Kyrie eleison e petições trinitárias; (2) o grande chamado dos santos pelo nome — primeiro a Bem-Aventurada Virgem Maria, depois os arcanjos (Miguel, Gabriel, Rafael), patriarcas e profetas (Abraão, Moisés, Elias, João Batista), apóstolos e evangelistas (Pedro, Paulo, André, João, Tiago, etc.), mártires (Estêvão, Lourenço, Policarpo, Inácio de Antioquia, Cipriano, Sebastião, Águeda, Inês), bispos confessores e doutores (Atanásio, Basílio, Gregório, Agostinho, Jerônimo, Ambrósio), fundadores e virgens (Antônio do Deserto, Bento, Francisco, Domingos, Catarina de Sena, Teresa d'Ávila); (3) petições de libertação («De todo mal, livrai-nos, Senhor»); (4) petições de súplica («Para que governeis e conserveis vossa santa Igreja, nós Vos pedimos, ouvi-nos»); (5) Agnus Dei final e coleta. A ladainha é uma das principais orações da liturgia católica e é usada em: a Vigília Pascal (durante a Liturgia do Batismo), batismos do Sábado Santo, ordenações sacerdotais e episcopais (os candidatos jazem prostrados enquanto a Igreja reunida canta a ladainha sobre eles), o Rito de Iniciação Cristã de Adultos (RICA) no Rito de Eleição, a dedicação de uma igreja, a consagração de altares, e a profissão de votos religiosos. Também é costume em muitas paróquias na Solenidade de Todos os Santos (1º de novembro), em funerais de padres e religiosos, em momentos de grave necessidade pública (guerra, pandemia, desastre natural), e como oração final de procissões de peregrinação.",
    instructions:
      "A Ladainha de Todos os Santos é rezada responsorialmente, geralmente cantada em ambientes litúrgicos. Um guia (padre, diácono ou cantor treinado) entoa a invocação; a assembleia responde com a fórmula apropriada. As respostas seguem a estrutura: «Rogai por nós» depois de cada santo nomeado ou grupo de santos; «Livrai-nos, Senhor» depois de cada invocação de libertação («De todo mal…»); «Nós Vos pedimos, ouvi-nos» depois de cada petição de súplica («Para que…»). A ladainha leva aproximadamente quinze a vinte minutos quando cantada em ritmo solene em um ambiente litúrgico; algo menos quando rezada em casa em forma falada. Para a devoção privada, a ladainha pode ser rezada a partir de qualquer texto impresso aprovado (o Missal Romano, um livro de orações paroquial, ou o site da CNBB carrega os textos oficiais em latim e português). Quando rezada em casa, sente-se, fique de pé ou ajoelhe-se conforme desejar; o ritmo da ladainha é contemplativo em vez de apressado. A ladainha é usada apropriadamente: (1) em Todos os Santos (1º de novembro) e Finados (2 de novembro) como oração familiar desses dias; (2) à beira do leito de alguém gravemente enfermo ou moribundo — muitos capelães católicos de hospital rezam a ladainha à medida que os últimos sacramentos se aproximam; (3) no início de uma peregrinação importante ou de uma empreitada familiar, pedindo à grande nuvem de testemunhas (Hebreus 12,1) que rodeie os peticionários; (4) em tempo de peste, desastre ou emergência pública, em continuidade com a instituição das procissões letânicas por Gregório Magno durante a peste romana de 590. O dom espiritual particular da ladainha é a presença sentida da comunhão dos santos — a verdade de que os fiéis que oram na terra e aqueles triunfantes no céu são um só corpo em Cristo.",
    patronSaint: null,
    feastDay: "1º de novembro (Todos os Santos)",
    source: "CNBB + Papa Pio V codificação 1568 + revisão pós-Vaticano II 1969 + instituição de Gregório Magno 590. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "prayer-expectant-mothers",
    name: "Oração pelas Gestantes",
    description:
      "A oração católica pelas gestantes nutre-se da tradição secular da Igreja de acompanhar as mulheres durante a gravidez sob o patrocínio da Bem-Aventurada Virgem Maria, que carregou Cristo em seu próprio ventre por nove meses. O fundamento bíblico principal é a Visitação (Lucas 1,39-56): Maria, ela mesma nos primeiros meses de gravidez com Jesus, apressa-se para as montanhas da Judeia para estar com sua prima Isabel, que está em seu sexto mês com João Batista. O Magnificat («Minha alma engrandece o Senhor…») é a oração de duas mulheres grávidas regozijando-se juntas. A tradição devocional católica tem confiado por muito tempo as gestantes a Maria sob vários títulos específicos: Nossa Senhora da Expectação (a Solenidade de 18 de dezembro, uma festa de tradição espanhola nove dias antes do Natal, marcando o iminente parto de Maria); Nossa Senhora de Guadalupe (cuja imagem a mostra grávida, vestindo o cinto de maternidade do costume indígena mexicano); e São Gerardo Majella (1726-1755), um irmão leigo redentorista italiano cujo nome se tornou tão associado ao parto seguro que suas estátuas são colocadas em alas de maternidade em hospitais católicos em todo o mundo. A oração pelas gestantes é apropriada em cada estágio da gravidez: no primeiro teste positivo, durante a ansiedade do primeiro trimestre que muitas mães sentem, durante os longos meses centrais de espera, nas semanas de preparação antes do parto, durante o próprio trabalho de parto (quando familiares frequentemente a rezam à beira do leito), e imediatamente após o parto em ação de graças. Também é rezada por comunidades — paróquias, grupos de oração, o círculo de amigas da mulher — como uma forma de cercá-la com intercessão durante os nove meses de espera que espelham os de Maria.",
    instructions:
      "Reze uma vez ao dia pela gestante, idealmente na mesma hora todos os dias para que a prática se torne parte de seu ritmo ordinário. A oração é curta o suficiente para ser memorizada; muitas gestantes a carregam em um pequeno cartão guardado em uma Bíblia, livro de orações ou carteira, e a rezam enquanto fazem uma pausa no trabalho cotidiano de preparação para o bebê. Práticas comuns que se emparelham com a oração: (1) Acender uma vela em um santuário mariano na igreja paroquial por cada mês da gravidez — muitas paróquias mantêm um suporte de velas designado para «gestantes» e publicam os nomes das mulheres pelas quais se reza; (2) Rezar uma dezena diária do Rosário, meditando nos Mistérios Gozosos (a Anunciação, a Visitação, a Natividade, a Apresentação, o Reencontro no Templo — cinco mistérios que percorrem o arco espiritual da concepção à maternidade jovem); (3) Pedir a intercessão de São Gerardo Majella — a oração pelas gestantes pode ser emparelhada com a novena a São Gerardo, especialmente nos nove dias finais antes do parto; (4) Oração familiar ou comunitária à beira do leito durante o parto, em que o esposo da gestante ou outro familiar reza o Memorare (a breve oração mariana de confiança) ou esta oração em voz alta à medida que o parto progride. A tradição católica é clara que a gravidez é em si mesma uma forma de oração. Depois do parto, a oração continua em ação de graças e volta-se naturalmente para as orações de maternidade pelo recém-nascido.",
    patronSaint: "Nossa Senhora",
    feastDay: null,
    source: "CNBB + Lucas 1,39-56 + tradição de São Gerardo Majella. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "adoration-hour",
    name: "Hora Santa de Adoração",
    description:
      "A Hora Santa de Adoração Eucarística é uma das formas mais antigas e centrais de oração católica — oração sustentada e silenciosa na real presença de Jesus Cristo no Santíssimo Sacramento, exposto em um ostensório sobre o altar. A prática nutre-se diretamente da cena evangélica em Getsêmani: Cristo pergunta a seus apóstolos: «Não pudestes vigiar uma hora comigo?» (Mateus 26,40). A «uma hora» não é uma duração arbitrária — é a petição explícita do Senhor na noite de sua paixão, e a Hora Santa católica responde diretamente a essa petição. A prática devocional da adoração eucarística sustentada cristalizou-se na Contra-Reforma e recebeu impulso particular das aparições do Sagrado Coração a Santa Margarida Maria Alacoque em Paray-le-Monial (1673-1675); Cristo pediu especificamente a Margarida Maria uma hora de reparação em sua presença a cada quinta-feira à noite, em lembrança da Agonia no Horto. A Hora Santa tornou-se central para o «Apostolado da Oração» (fundado em 1844) e foi pregada amplamente no século XX pelo Venerável Fulton Sheen (1895-1979), que célebremente se comprometeu a uma Hora Santa todos os dias de sua vida sacerdotal — mais de 60 anos — e creditou cada graça de seu ministério a essa hora. Hoje capelas de adoração eucarística perpétua operam em milhares de paróquias em todo o mundo, atendidas por voluntários leigos que se comprometem a horas específicas através da noite e do dia para que Cristo nunca fique sozinho em seu Sacramento exposto. A Hora Santa é apropriada para: qualquer intercessão sustentada, especialmente por cura, conversão ou discernimento vocacional; reparação pelo pecado (próprio ou do mundo); aridez espiritual (quando a oração se sente seca, a presença da Eucaristia sustenta a alma mesmo quando os sentimentos estão ausentes); preparação para decisões importantes da vida; ação de graças após receber uma graça. É a oração que Sheen chamava «o segredo de todo padre que se tornou santo».",
    instructions:
      "Visite sua paróquia durante as horas de Adoração — consulte o site ou o boletim de sua paróquia para o horário. Muitas paróquias oferecem adoração eucarística nas quintas-feiras (o pedido de Cristo a Margarida Maria), nas sextas-feiras (o dia tradicional de reparação), ou como uma Hora Santa estendida após a Missa de dia de semana. Algumas mantêm adoração perpétua com o Santíssimo Sacramento exposto 24/7. Ao chegar: (1) Genuflexione com ambos os joelhos (o sinal tradicional de reverência para a Eucaristia exposta, distinto da genuflexão com um joelho para o Sacramento reservado no tabernáculo); (2) Encontre um lugar para sentar-se ou ajoelhar-se; (3) Incline-se em silencioso reconhecimento de que você está na presença literal de Deus encarnado. A hora em si é desestruturada por design — a presença sustentada é a oração. Alguns padrões que os católicos usam para preencher a hora: (a) Rezar o Rosário, meditando nos Mistérios Dolorosos; (b) Ler a Sagrada Escritura (as narrativas da Paixão, o Evangelho de João, os Salmos — Salmos 23 e 91 são escrituras comuns de adoração eucarística); (c) Rezar a Coroinha da Divina Misericórdia, especialmente durante a hora das 15h00; (d) Ler de um clássico espiritual (os escritos de Fulton Sheen, a Imitação de Cristo de Tomás de Kempis, o diário de Santa Faustina); (e) Sentar-se em presença silenciosa — a forma mais alta de oração contemplativa; (f) Anotar uma conversa com Jesus sobre a pessoa pela qual você oferece a hora. Ao longo da hora, nomeie a pessoa e a intenção frequentemente. A hora termina com outra genuflexão e uma breve oração de ação de graças pelo dom de sua presença.",
    patronSaint: null,
    feastDay: null,
    source: "CNBB + Mateus 26,40 + aparições do Sagrado Coração em Paray-le-Monial (1673-1675) + tradição de Fulton Sheen. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "stations-of-the-cross",
    name: "Via-Sacra (Estações da Cruz)",
    description:
      "A Via-Sacra (também chamada Via-Crúcis, Caminho da Cruz, ou Via Dolorosa em latim) é uma devoção meditativa em que o crente segue a Paixão de Cristo através de quatorze estações distintas — momentos ao longo de sua jornada do pretório de Pilatos ao sepulcro. A prática originou-se nos primeiros séculos cristãos como peregrinação literal aos lugares santos em Jerusalém; os peregrinos caminhavam o caminho real que Cristo caminhou, parando em cada estação significativa para orar. Quando Jerusalém caiu sob controle muçulmano no século VII e a peregrinação se tornou perigosa e rara, os franciscanos — a quem o Papa Clemente VI deu a custódia da Terra Santa em 1342 — começaram a reconstruir a Via Dolorosa na forma de estações devocionais em suas igrejas por toda a Europa, para que qualquer católico pudesse «caminhar» o Caminho da Cruz espiritualmente sem viajar a Jerusalém. O Papa Inocêncio XI concedeu aos franciscanos indulgências por rezar as estações em 1686, e o Papa Clemente XII estendeu isso a todos os fiéis em 1731. As quatorze estações padrão foram fixadas no século XVIII: (1) Jesus é condenado à morte; (2) Jesus carrega a cruz; (3) Jesus cai pela primeira vez; (4) Jesus encontra sua Mãe Maria; (5) Simão de Cirene ajuda Jesus a carregar a cruz; (6) Verônica enxuga o rosto de Jesus; (7) Jesus cai pela segunda vez; (8) Jesus encontra as mulheres de Jerusalém; (9) Jesus cai pela terceira vez; (10) Jesus é despojado de suas vestes; (11) Jesus é pregado na cruz; (12) Jesus morre na cruz; (13) Jesus é descido da cruz; (14) Jesus é depositado no sepulcro. Algumas comunidades católicas acrescentam uma décima quinta estação para a Ressurreição. A Via-Sacra é tradicionalmente rezada nas sextas-feiras durante a Quaresma e é a devoção pública central da Sexta-Feira Santa na maioria das paróquias católicas em todo o mundo. O Papa preside a Via-Sacra no Coliseu de Roma todas as Sextas-Feiras Santas — uma tradição revivida pelo Papa Paulo VI e continuada por todo papa desde então, transmitida globalmente.",
    instructions:
      "Visite uma igreja católica — a maioria tem as quatorze estações montadas ao longo das paredes laterais da nave, geralmente como pequenas pinturas, placas ou baixos-relevos. A prática tradicional: (1) Começar na primeira estação; genuflexionar; (2) Anunciar a estação em voz alta («Primeira Estação: Jesus é condenado à morte»); (3) Rezar a resposta «Nós Vos adoramos, ó Cristo, e Vos bendizemos, porque pela vossa santa Cruz remistes o mundo»; (4) Meditar brevemente sobre a cena da Paixão de Cristo correspondente à estação; (5) Rezar um Pai-Nosso, uma Ave-Maria e um Glória (ou outras orações de um livreto de Via-Sacra); (6) Oferecer a estação por sua intenção. Passe para a próxima estação — caminhar fisicamente de uma para a próxima é parte da oração; a Via-Sacra é pensada para ser caminhada, mesmo que brevemente. Duração total: aproximadamente trinta a quarenta e cinco minutos quando rezada em ritmo sem pressa em uma igreja. Em casa, um livreto impresso de Via-Sacra funciona bem — não há requisito de presença física. A devoção é rezada apropriadamente: (a) Nas sextas-feiras durante a Quaresma, a disciplina católica tradicional; (b) Na própria Sexta-Feira Santa, o dia em que Cristo caminhou a Via Dolorosa; (c) Em qualquer sexta-feira ao longo do ano (como o dia tradicional de lembrança da Paixão); (d) Quando se carrega uma cruz pessoal pesada — doença, luto, dependência, perseguição — unindo seu sofrimento ao de Cristo; (e) Quando se reza por alguém que sofre ou está morrendo; (f) Quando se busca a graça da paciência sob a aflição.",
    patronSaint: null,
    feastDay: "Sexta-Feira Santa",
    source: "CNBB + custódia franciscana da Terra Santa (1342) + Papa Inocêncio XI 1686 + Clemente XII 1731. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "morning-offering",
    name: "Oferecimento da Manhã",
    description:
      "O Oferecimento da Manhã é a oração diária fundadora do Apostolado da Oração — um movimento espiritual católico fundado em 1844 pelo padre jesuíta François-Xavier Gautrelet em Vals, França, e renomeado em 2015 pelo Papa Francisco como a Rede Mundial de Oração do Papa. A intuição central do movimento é simples mas transformadora: cada ação ordinária do dia de um católico — o trabalho, o estudo, a conversa, as refeições, o cansaço, a alegria, o sofrimento, até o sono — pode ser oferecida a Deus como um ato intencional de amor, transformando todo o dia em um ato sustentado de oração. O Oferecimento da Manhã é o ato que realiza este oferecimento, rezado em primeiro lugar ao acordar, antes que o dia tome conta. O texto tradicional — composto no final do século XIX nos folhetos devocionais do Apostolado e refinado através de várias versões aprovadas pelos papas — coloca o oferecimento do dia «através do Imaculado Coração de Maria» (a mediação mariana que enquadra a vida católica como filial) e o une «com o Santo Sacrifício da Missa em todo o mundo» (de modo que o oferecimento do dia seja reunido ao sacrifício eucarístico sendo celebrado em alguma paróquia católica em algum lugar da terra a cada minuto de cada hora). A cada mês, o Papa publica intenções específicas de oração universal através da Rede Mundial de Oração do Papa — por exemplo, «pela proteção das crianças» ou «pelo fim do tráfico humano» — e os católicos que rezam o Oferecimento da Manhã unem as pequenas ações de seu dia a essas intenções mais amplas. O Oferecimento da Manhã é também uma poderosa oração de intercessão por uma pessoa em particular: um familiar doente, um filho adulto que abandonou a fé, um pai lutando com vício, qualquer pessoa cuja situação o peticionário experimenta como constantemente presente.",
    prayerText:
      "Ó Jesus, pelo Imaculado Coração de Maria, eu Vos ofereço as orações, os trabalhos, as alegrias e os sofrimentos deste dia, por todas as intenções do Vosso Sagrado Coração, em união com o Santo Sacrifício da Missa em todo o mundo, em ação de graças pelos Vossos favores, em reparação pelos meus pecados, pelas intenções de todos os meus associados e, em particular, por (mencione o nome e a intenção da pessoa). Amém.",
    instructions:
      "Reze imediatamente ao acordar, antes que a agitação do dia possa tomar conta. A disciplina tradicional é rezá-lo antes de levantar-se da cama, enquanto a mente ainda está leve e o dia ainda parece um presente; alguns católicos rezam durante o primeiro momento tranquilo da rotina matinal (com a primeira xícara de café, na pia da cozinha, enquanto alimentam o bebê). A oração é curta o suficiente para ser memorizada em um único dia. Para torná-la parte da vida: (1) Coloque a oração em um lugar onde você a verá primeiro — colada ao espelho do banheiro, dentro da porta do quarto, em um cartão ao lado da cafeteira; (2) Nomeie a pessoa específica e a intenção no lugar apropriado da oração (a linha «e em particular por…»), tornando o oferecimento concreto e não abstrato; (3) Ao longo do dia, quando o trabalho se torna difícil ou uma interrupção quebra seus planos, renove brevemente o oferecimento: «Eu lhe dei este dia por (nome); este momento é parte disso». Muitos lares católicos rezam o Oferecimento da Manhã em voz alta juntos quando a família se levanta — pais e filhos rezando juntos antes do café da manhã. A Rede Mundial de Oração do Papa publica as intenções universais mensais do Papa; alinhar seu oferecimento diário com a intenção do Papa a cada mês acrescenta uma dimensão de solidariedade católica universal à sua oração. Para uma intercessão sustentada (uma novena de dias por um ente querido doente, a duração de um discernimento difícil, os meses de quimioterapia de um familiar), o Oferecimento da Manhã se torna a espinha dorsal da oração.",
    patronSaint: null,
    feastDay: null,
    source: "CNBB + Apostolado da Oração / Rede Mundial de Oração do Papa (1844, renomeado 2015). Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
  {
    prayerSlug: "three-oclock-prayer",
    name: "Oração das Três da Tarde (Hora da Misericórdia)",
    description:
      "A Oração das Três da Tarde — também chamada Hora da Misericórdia ou Hora da Grande Misericórdia — foi dada por Jesus a Santa Maria Faustina Kowalska nas revelações da Divina Misericórdia registradas em seu Diário: A Misericórdia Divina em Minha Alma. Jesus instruiu Faustina que as 15h00 de cada dia — a hora de sua morte no Calvário — seja honrada como a Hora da Grande Misericórdia, na qual um breve ato de oração obtém graças extraordinárias. A promessa exata, registrada no Diário de Faustina (entrada 1320): «Às três da tarde, implora minha misericórdia, especialmente pelos pecadores; e, mesmo que por um breve momento, mergulha em minha Paixão, particularmente em meu abandono no momento da agonia. Esta é a hora de grande misericórdia para todo o mundo… Nesta hora não recusarei nada à alma que me faz um pedido em virtude da minha Paixão». A hora corresponde à hora nona do dia judaico na cronologia evangélica (Marcos 15,34) — a hora em que «Jesus deu um grande grito… e expirou» (Marcos 15,37). A Oração das Três da Tarde é a forma mais simples e mais acessível de devoção à Divina Misericórdia — muito mais curta que a coroinha, acessível a qualquer um que possa parar por trinta segundos na hora da morte de Cristo. É a oração que a tradição católica coloca no coração do dia para aqueles que não podem fazer uma Hora Santa completa, que não podem rezar a coroinha, que estão no trabalho ou na escola ou à beira do leito de um hospital — o breve momento oferecido que toma Cristo em sua palavra e pede a misericórdia que ele prometeu. A devoção foi suprimida por muitos anos (o mesmo período em que os escritos de Faustina estavam sob restrição provisória), mas o Papa São João Paulo II canonizou Faustina em 30 de abril de 2000, e estabeleceu o Domingo da Divina Misericórdia como festa para a Igreja universal.",
    prayerText:
      "Vós expirastes, Jesus, mas a fonte da vida jorrou para as almas e abriu-se o oceano de misericórdia para o mundo inteiro. Ó Fonte de Vida, insondável Divina Misericórdia, envolvei o mundo inteiro e derramai-Vos sobre nós. Ó Sangue e Água, que jorrastes do Coração de Jesus como fonte de misericórdia para nós, eu confio em Vós! Deus Santo, Santo Forte, Santo Imortal, tende piedade de nós e do mundo inteiro. (3 vezes)",
    instructions:
      "Às 15h00 de cada dia, pare brevemente — qualquer coisa que esteja fazendo — e reze. A oração é curta o suficiente para ser memorizada em uma única tarde e para ser rezada em qualquer lugar: em uma mesa, em um carro, em uma sala de aula, à beira de um leito hospitalar, caminhando por uma calçada. A tradição católica é clara que «mesmo um momento de oração nesta hora é poderoso» — se uma vida ocupada só pode dedicar vinte segundos para um único «Jesus, eu confio em Vós» às 15h00, esse breve momento é em si mesmo a prática. Para aqueles com mais tempo na hora: (1) Rezar a Coroinha completa da Divina Misericórdia (aproximadamente dez minutos); (2) Fazer uma breve «visita» a uma igreja católica próxima ou capela de adoração eucarística; (3) Parar para ler um parágrafo do Diário de Santa Faustina; (4) Rezar pelos pecadores — Faustina registrou que Jesus lhe disse que esta é a intercessão mais poderosa nesta hora. As disciplinas católicas tradicionais que se emparelham com a Oração das Três da Tarde: (a) Definir um alarme diário às 15h00 como lembrete até que a disciplina se torne hábito; (b) Carregar um pequeno santinho ou imagem da Divina Misericórdia como lembrete tátil ao longo do dia; (c) Rezar ao pé de um crucifixo (a postura literal de Cristo em sua morte); (d) Acrescentar um momento de quietude física — pausando qualquer movimento em curso, mesmo que brevemente. A hora é uma âncora diária para a vida devocional da Divina Misericórdia.",
    patronSaint: "Santa Maria Faustina Kowalska",
    feastDay: null,
    source: "CNBB + Diário de Santa Faustina (1320) + JPII canonização 30 abril 2000 + Marcos 15,34-37. Retrieved 2026-05-14.",
    reviewedAt: new Date("2026-05-14"),
  },
];
