import "dotenv/config";
import { PrismaClient, PrayerCategory, DifficultyLevel, SituationCategory } from "../src/generated/prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const prayers = [
  // ─── NOVENAS ────────────────────────────────────────────────
  {
    slug: "novena-sacred-heart",
    name: "Novena to the Sacred Heart of Jesus",
    category: PrayerCategory.NOVENA,
    description: "The Novena to the Sacred Heart of Jesus is one of the most beloved devotions in the Catholic Church, born from the apparitions of Jesus to St. Margaret Mary Alacoque at Paray-le-Monial, France, in 1673-1675. In these visions, Christ revealed the depth of His love for humanity, symbolized by His Heart pierced and crowned with thorns, and asked that this love be honored through devotion to His Sacred Heart. The novena spans nine consecutive days of prayer (the number nine recalling the nine days the apostles and Mary spent in prayer between the Ascension and Pentecost) and is traditionally offered with confidence in Christ's compassion for those who suffer. It is especially fitting in times of illness, family difficulty, spiritual desolation, or persistent intentions that have not yet found resolution. The Sacred Heart is not merely a symbol; it is the historical, physical heart of Christ, fully human and fully divine, the source of His infinite charity. Pope Pius XII's 1956 encyclical Haurietis Aquas describes the Sacred Heart as 'the throne of mercy' and confirms the central place of this devotion in the Church's life. Prayer warriors who offer this novena join centuries of Catholics who have placed their trust in the wounded Heart of the Savior.",
    instructions: "Pray once daily for nine consecutive days at approximately the same time each day. Choose a quiet space and begin with the Sign of the Cross. The traditional structure is: (1) an opening invocation, often 'O Most Sacred Heart of Jesus, I place my trust in Thee'; (2) the novena prayer text itself; (3) an Our Father, Hail Mary, and Glory Be; (4) a personal intention named aloud or silently. Many add the Litany of the Sacred Heart on the final day or pray the novena in conjunction with First Friday devotions, receiving Holy Communion on nine consecutive First Fridays as Christ Himself requested of St. Margaret Mary. The novena may be prayed at any time of year, but is especially appropriate during the month of June (the Month of the Sacred Heart), in the days leading up to the Solemnity of the Sacred Heart (Friday after Corpus Christi), or whenever someone faces a particularly difficult moment. If a day is missed, the traditional counsel is to begin again from day one rather than skip; the discipline of consecutive prayer is itself part of the devotion's grace. Some pray for a specific person each day of the novena; others offer all nine days for a single intention.",
    prayerText: "O most holy Heart of Jesus, fountain of every blessing, I adore You, I love You, and with lively sorrow for my sins I offer You this poor heart of mine. Make me humble, patient, pure and wholly obedient to Your will. Grant, Good Jesus, that I may live in You and for You. Protect me in the midst of danger. Comfort me in my afflictions. Give me health of body, assistance in my temporal needs, Your blessing on all that I do, and the grace of a holy death. Amen.",
    duration: 15,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Margaret Mary Alacoque",
    feastDay: "Friday after Corpus Christi",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.MENTAL_HEALTH, SituationCategory.GENERAL],
  },
  {
    slug: "novena-st-blaise",
    name: "Novena to St. Blaise",
    category: PrayerCategory.NOVENA,
    description: "St. Blaise was a fourth-century bishop and physician who, according to tradition, miraculously cured a child choking on a fishbone. He is the patron of those suffering from ailments of the throat and lungs, and his intercession is invoked for healing of any sickness affecting breath or voice. The Church blesses throats in his name on his feast day, February 3.",
    instructions: "Pray once daily for nine consecutive days. Traditionally prayed in the days leading up to the Feast of St. Blaise (February 3), but can be prayed at any time, especially when someone is suffering from a throat, lung, or respiratory illness. Many add the Our Father, Hail Mary, and Glory Be at the end of each day.",
    prayerText: "O glorious St. Blaise, who by your martyrdom left to the Church a precious witness to the faith, obtain for us the grace to preserve within ourselves this divine gift, and to defend — without human respect — both by word and example, the truth of that same faith. You miraculously restored a little child when it was at the point of death because of an affliction of the throat. Grant us your mighty patronage in like misfortunes, and especially intercede for (mention your intention). Above all, obtain for us the grace of trusting in God's providence, that whatever the outcome of this affliction, we may be drawn closer to His Sacred Heart. Amen.\n\nThrough the intercession of Saint Blaise, bishop and martyr, may God deliver you from every disease of the throat and from every other illness. In the name of the Father, and of the Son, and of the Holy Spirit. Amen.",
    duration: 8,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Blaise",
    feastDay: "February 3",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.SURGERY],
  },
  {
    slug: "novena-st-jude",
    name: "Novena to St. Jude",
    category: PrayerCategory.NOVENA,
    description: "The patron saint of impossible causes and desperate situations. This novena is prayed when all hope seems lost, asking St. Jude's powerful intercession.",
    instructions: "Pray once daily for nine consecutive days. Many include the Our Father, Hail Mary, and Glory Be at the end of each day's prayer.",
    prayerText: "Most holy apostle, St. Jude, faithful servant and friend of Jesus, the Church honors and invokes you universally as the patron of hope. Please intercede on my behalf. Make use of that particular privilege given to you to bring hope, comfort, and help where they are needed most. Come to my assistance in this great need that I may receive the consolation and help of heaven as I work with my challenges, particularly (mention your intention). I praise God with you and all the saints forever. I promise, blessed St. Jude, to be ever mindful of this great favor, to always honor you as my special and powerful patron, and to gratefully encourage devotion to you. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Jude Thaddeus",
    feastDay: "October 28",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.FINANCIAL, SituationCategory.CAREER, SituationCategory.FERTILITY, SituationCategory.OTHER],
  },
  {
    slug: "novena-divine-mercy",
    name: "Divine Mercy Novena",
    category: PrayerCategory.NOVENA,
    description: "Given by Jesus to St. Faustina, this novena begins on Good Friday and ends on Divine Mercy Sunday. Each day brings a different group of souls before God's throne of mercy.",
    instructions: "Pray once daily for nine consecutive days. Each day has a unique intention and group of souls to pray for. Conclude each day with the Chaplet of Divine Mercy.",
    prayerText: "You expired, Jesus, but the source of life gushed forth for souls, and the ocean of mercy opened up for the whole world. O Fount of Life, unfathomable Divine Mercy, envelop the whole world and empty Yourself out upon us. O Blood and Water, which gushed forth from the Heart of Jesus as a fount of mercy for us, I trust in You!",
    duration: 20,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 9,
    patronSaint: "St. Faustina Kowalska",
    feastDay: "Second Sunday of Easter",
    situationTags: [SituationCategory.CONVERSION, SituationCategory.GRIEF, SituationCategory.GENERAL, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "novena-our-lady-perpetual-help",
    name: "Novena to Our Lady of Perpetual Help",
    category: PrayerCategory.NOVENA,
    description: "A tender devotion to Mary under her title of Perpetual Help, asking her constant maternal intercession in times of difficulty and distress.",
    instructions: "Pray once daily for nine consecutive days. Many parishes hold weekly Perpetual Help novena services on Wednesdays.",
    prayerText: "O Mother of Perpetual Help, grant that I may ever invoke your most powerful name, which is the safeguard of the living and the salvation of the dying. O Purest Mary, O Sweetest Mary, let your name henceforth be ever on my lips. Delay not, O Blessed Lady, to help me whenever I call on you, for in all my needs, in all my temptations, I shall never cease to call on you, ever repeating your sacred name. O what consolation, what sweetness, what confidence, what emotion fills my soul when I pronounce your sacred name or even only think of you. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "Our Lady of Perpetual Help",
    feastDay: "June 27",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.PREGNANCY, SituationCategory.FAMILY, SituationCategory.GRIEF],
  },
  {
    slug: "novena-st-joseph",
    name: "Novena to St. Joseph",
    category: PrayerCategory.NOVENA,
    description: "St. Joseph, the foster father of Jesus and chaste spouse of the Blessed Virgin Mary, is one of the most beloved intercessors in the Catholic tradition. Though scripture records no words from him, his fidelity is unmistakable: he protected the Holy Family in flight to Egypt, provided for them by the labor of his hands, and taught Jesus the trades of carpentry and faithful manhood. Pope Pius IX named him Patron of the Universal Church in 1870, and Pope Francis declared 2020-2021 the Year of St. Joseph through the apostolic letter Patris Corde (With a Father's Heart). This novena draws on a long tradition of Catholic devotion to St. Joseph as the patron of fathers, workers, families, real estate matters, and a happy death — the four pillars of his earthly ministry. He is invoked especially in moments of financial hardship, family discord, employment difficulty, and the discernment of vocation. Many Catholics commit to the novena leading up to either of his feasts: March 19 (Solemnity of St. Joseph, Spouse of the Blessed Virgin Mary) or May 1 (St. Joseph the Worker, instituted by Pope Pius XII in 1955 to sanctify human labor). St. Teresa of Ávila famously wrote: 'To other saints the Lord seems to have given grace to succor us in some particular necessity, but to this glorious saint, I know by experience, He has given grace to help us in all.'",
    instructions: "Pray once daily for nine consecutive days. The traditional structure is: open with the Sign of the Cross; pray the novena prayer text; conclude with an Our Father, Hail Mary, and Glory Be; and name your specific intention. Some Catholic families add the Litany of St. Joseph or seven Our Fathers, Hail Marys, and Glory Bes in honor of the Seven Sorrows and Seven Joys of St. Joseph — a traditional devotion connected to his joyful and sorrowful experiences in the life of the Holy Family. For families discerning a major life decision (a job change, a move, a marriage), it is customary to begin the novena nine days before the decision must be made, asking St. Joseph's intercession for clarity and the grace to accept God's will. The novena is also traditionally prayed during the month of March (the Month of St. Joseph) or alongside the popular practice of burying a St. Joseph statue in association with the sale of a home — a folk tradition that emphasizes confident trust rather than superstition. Whether prayed for vocational discernment, financial provision, family healing, or a happy death (one of the four traditional ends of this devotion), the spirit should be one of quiet, hardworking confidence — the very disposition St. Joseph modeled in scripture.",
    prayerText: "O St. Joseph, whose protection is so great, so strong, so prompt before the throne of God, I place in you all my interests and desires. O St. Joseph, do assist me by your powerful intercession and obtain for me from your divine Son all spiritual blessings through Jesus Christ, Our Lord; so that having engaged here below your heavenly power, I may offer my thanksgiving and homage to the most loving of Fathers. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Joseph",
    feastDay: "March 19 / May 1",
    situationTags: [SituationCategory.FAMILY, SituationCategory.FINANCIAL, SituationCategory.CAREER, SituationCategory.MARRIAGE],
  },
  {
    slug: "novena-infant-of-prague",
    name: "Novena to the Infant Jesus of Prague",
    category: PrayerCategory.NOVENA,
    description: "A devotion to the Christ Child, honoring His divine infancy and asking for His childlike trust and provision in our needs.",
    instructions: "Pray once daily for nine consecutive days.",
    prayerText: "O Jesus, who said, 'Ask and you shall receive, seek and you shall find, knock and it shall be opened to you,' through the intercession of Mary, Your most holy Mother, I knock, I seek, I ask that my prayer be granted. (Make your request.) O Jesus, who said, 'All that you ask of the Father in My name, He will grant you,' through the intercession of Mary, Your most holy Mother, I humbly and urgently ask Your Father in Your name that my prayer be granted. (Make your request.) Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.FINANCIAL, SituationCategory.ILLNESS, SituationCategory.GENERAL],
  },
  {
    slug: "novena-st-therese",
    name: "Novena to St. Therese of Lisieux",
    category: PrayerCategory.NOVENA,
    description: "The Little Flower promised to spend her heaven doing good upon the earth. This novena invokes her childlike confidence in God's merciful love.",
    instructions: "Pray once daily for nine consecutive days. Tradition holds that a rose may be received as a sign of St. Therese's intercession.",
    prayerText: "O Little Therese of the Child Jesus, please pick for me a rose from the heavenly gardens and send it to me as a message of love. O Little Flower of Jesus, ask God today to grant the favors I now place with confidence in your hands. (Mention your intention.) St. Therese, help me to always believe, as you did, in God's great love for me, so that I might imitate your Little Way each day. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Therese of Lisieux",
    feastDay: "October 1",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.DISCERNMENT, SituationCategory.CONVERSION, SituationCategory.GENERAL],
  },
  {
    slug: "novena-holy-spirit",
    name: "Novena to the Holy Spirit",
    category: PrayerCategory.NOVENA,
    description: "The original novena: the Apostles prayed for nine days between the Ascension and Pentecost. This novena invokes the sevenfold gifts of the Holy Spirit.",
    instructions: "Pray once daily for nine consecutive days. Traditionally prayed between Ascension Thursday and Pentecost Sunday, but may be prayed at any time.",
    prayerText: "Come, Holy Spirit, fill the hearts of Your faithful and enkindle in them the fire of Your love. Send forth Your Spirit and they shall be created, and You shall renew the face of the earth. O God, who by the light of the Holy Spirit did instruct the hearts of the faithful, grant that by the same Holy Spirit we may be truly wise and ever enjoy His consolations. Through Christ Our Lord. Amen.",
    duration: 15,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: null,
    feastDay: "Pentecost",
    situationTags: [SituationCategory.DISCERNMENT, SituationCategory.CONVERSION, SituationCategory.CAREER, SituationCategory.GENERAL],
  },
  {
    slug: "novena-miraculous-medal",
    name: "Novena of the Miraculous Medal",
    category: PrayerCategory.NOVENA,
    description: "Based on the apparitions of the Blessed Virgin to St. Catherine Laboure, this novena asks Mary's intercession through the graces symbolized by the Miraculous Medal.",
    instructions: "Pray once daily for nine consecutive days. If possible, wear the Miraculous Medal during the novena.",
    prayerText: "O Immaculate Virgin Mary, Mother of Our Lord Jesus and our Mother, penetrated with the most lively confidence in your all-powerful and never-failing intercession, manifested so often through the Miraculous Medal, we your loving and trustful children implore you to obtain for us the graces and favors we ask during this novena, if they be beneficial to our immortal souls, and the souls for whom we pray. (Mention your intention.) You know, O Mary, how often our souls have been the sanctuaries of your Son who hates iniquity. Obtain for us then a deep hatred of sin and that purity of heart which will attach us to God alone. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Catherine Laboure",
    feastDay: "November 27",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.PREGNANCY, SituationCategory.CONVERSION, SituationCategory.GENERAL],
  },
  {
    slug: "novena-st-anthony",
    name: "Novena to St. Anthony of Padua",
    category: PrayerCategory.NOVENA,
    description: "Known as the Wonder Worker and finder of lost things, St. Anthony is a beloved intercessor. This novena asks his help in recovering what is lost, whether material or spiritual.",
    instructions: "Pray once daily for nine consecutive days, traditionally on Tuesdays.",
    prayerText: "Holy St. Anthony, gentlest of saints, your love for God and charity for His creatures made you worthy when on earth to possess miraculous powers. Miracles waited on your word, which you were ever ready to speak for those in trouble or anxiety. Encouraged by this thought, I implore you to obtain for me (state your intention). The answer to my prayer may require a miracle; even so, you are the Saint of Miracles. O gentle and loving St. Anthony, whose heart was ever full of human sympathy, whisper my petition into the ears of the sweet Infant Jesus, who loved to be folded in your arms. The gratitude of my heart will ever be yours. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Anthony of Padua",
    feastDay: "June 13",
    situationTags: [SituationCategory.GENERAL, SituationCategory.FINANCIAL, SituationCategory.FAMILY],
  },

  // ─── ROSARY ─────────────────────────────────────────────────
  {
    slug: "holy-rosary",
    name: "The Holy Rosary",
    category: PrayerCategory.ROSARY,
    description: "The Holy Rosary is the central Marian devotion of the Catholic Church — a contemplative prayer in which the believer meditates on the great mysteries of Christ's life, death, and resurrection while praying repeated decades of Hail Marys. The rosary as we know it took shape over centuries; tradition holds that the Blessed Virgin Mary gave the rosary to St. Dominic in 1208 as a spiritual weapon against the Albigensian heresy, and the structure of fifteen mysteries was codified by Pope St. Pius V in 1569. In 2002, Pope St. John Paul II added the Luminous Mysteries (the Mysteries of Light) in his apostolic letter Rosarium Virginis Mariae, bringing the total to twenty mysteries grouped into four sets. Each decade is a meditation: as the fingers move along the beads and the lips recite the Hail Mary, the mind dwells on a moment from the Gospels — the Annunciation, the Crucifixion, the Resurrection, the Transfiguration. The rosary is not vain repetition (Matthew 6:7) but a school of contemplation, allowing the rhythm of the prayers to free the mind for reflection on the mysteries of salvation. Popes from Leo XIII (whose eleven encyclicals on the rosary remain magisterial reference points) to Francis have urged the faithful to pray the rosary daily. It is the prayer offered at Lourdes, Fatima, and countless other Marian apparitions, and the prayer most commonly prayed by Catholic families gathered around a sickbed or a grave.",
    instructions: "A complete rosary is five decades, typically prayed in about twenty minutes. Begin with the Sign of the Cross and the Apostles' Creed on the crucifix. On the first large bead, pray the Our Father; on each of the three small beads that follow, pray a Hail Mary (for an increase in the three theological virtues — faith, hope, and love); on the next large bead, pray the Glory Be. Then announce the first mystery aloud and meditate briefly on its meaning; pray an Our Father on the large bead, ten Hail Marys on the ten small beads (one per bead) while continuing to meditate on the mystery, then a Glory Be and the Fatima Prayer ('O my Jesus, forgive us our sins, save us from the fires of hell…'). Repeat for four more decades, naming each mystery in turn. Close with the Hail Holy Queen and the Rosary prayer. The four sets of mysteries are traditionally prayed: Joyful Mysteries on Mondays and Saturdays (the Annunciation, Visitation, Nativity, Presentation, Finding in the Temple); Sorrowful on Tuesdays and Fridays (the Agony, Scourging, Crowning with Thorns, Carrying of the Cross, Crucifixion); Glorious on Wednesdays and Sundays (the Resurrection, Ascension, Pentecost, Assumption, Coronation); Luminous on Thursdays (the Baptism, Wedding at Cana, Proclamation of the Kingdom, Transfiguration, Institution of the Eucharist). For prayer-train coverage, a single decade — or even a single Hail Mary offered with intention — is also a valid offering of the rosary.",
    prayerText: null,
    duration: 20,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "Our Lady of the Rosary",
    feastDay: "October 7",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.PREGNANCY, SituationCategory.FAMILY, SituationCategory.MARRIAGE, SituationCategory.GENERAL, SituationCategory.CONVERSION, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "rosary-for-healing",
    name: "Rosary for Healing",
    category: PrayerCategory.ROSARY,
    description: "The full Rosary prayed with specific healing intentions. Each mystery is offered for a different aspect of healing: physical, emotional, spiritual, and relational.",
    instructions: "Pray the standard five-decade Rosary, but before each decade, state a healing intention: 1st decade for physical healing, 2nd for emotional healing, 3rd for spiritual healing, 4th for healing of relationships, 5th for the healing of those who care for the sick.",
    prayerText: null,
    duration: 25,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "Our Lady of Lourdes",
    feastDay: "February 11",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.SURGERY, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "54-day-rosary-novena",
    name: "54-Day Rosary Novena",
    category: PrayerCategory.ROSARY,
    description: "The most powerful Rosary devotion: 27 days of petition followed by 27 days of thanksgiving. Three complete rosary novenas of petition and three of thanksgiving.",
    instructions: "Pray five decades of the Rosary daily for 54 consecutive days. Days 1-27: Pray in petition. Days 28-54: Pray in thanksgiving (even before you see the answer). Rotate through all four sets of mysteries: Joyful, Sorrowful, Glorious, and Luminous.",
    prayerText: null,
    duration: 20,
    difficulty: DifficultyLevel.ADVANCED,
    daysRequired: 54,
    patronSaint: "Our Lady of the Rosary",
    feastDay: "October 7",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.FERTILITY, SituationCategory.CONVERSION, SituationCategory.DISCERNMENT],
  },

  // ─── CHAPLETS ───────────────────────────────────────────────
  {
    slug: "chaplet-divine-mercy",
    name: "Chaplet of Divine Mercy",
    category: PrayerCategory.CHAPLET,
    description: "The Chaplet of Divine Mercy was given by Jesus to St. Maria Faustina Kowalska, a Polish nun, in a series of revelations between 1931 and 1938 recorded in her Diary: Divine Mercy in My Soul. The chaplet is a powerful intercessory prayer offered for the conversion of sinners, the consolation of the dying, and the mercy of God upon the whole world. Jesus told Faustina that whoever prays this chaplet will receive 'great mercy at the hour of death' — and that He delights especially in this prayer offered at 3:00 PM, the Hour of Mercy (the hour of His death on Calvary). The chaplet is prayed on standard rosary beads, which makes it accessible to anyone with a rosary, and takes approximately ten minutes. Devotion to Divine Mercy was suppressed for many years, but Pope St. John Paul II — himself a Pole and a fellow countryman of St. Faustina — canonized her on April 30, 2000, and established Divine Mercy Sunday (the second Sunday of Easter) as a feast for the universal Church. The Chaplet of Divine Mercy has become one of the most widely-prayed devotions in the modern Church, especially favored by hospital chaplains, hospice volunteers, and those praying for the conversion of loved ones. It is the daily prayer at the National Shrine of the Divine Mercy in Stockbridge, Massachusetts, and at the Sanctuary of Divine Mercy in Łagiewniki, Kraków — the place where Faustina lived, died, and is now entombed.",
    instructions: "Using a standard five-decade rosary, begin with the Sign of the Cross, an Our Father, a Hail Mary, and the Apostles' Creed on the crucifix and opening beads. On each of the five large beads (where the Our Father is normally prayed), pray: 'Eternal Father, I offer You the Body and Blood, Soul and Divinity of Your dearly beloved Son, Our Lord Jesus Christ, in atonement for our sins and those of the whole world.' On each of the ten small beads of each decade, pray: 'For the sake of His sorrowful Passion, have mercy on us and on the whole world.' At the end of all five decades, conclude by praying three times: 'Holy God, Holy Mighty One, Holy Immortal One, have mercy on us and on the whole world.' The chaplet is especially powerful when prayed at 3:00 PM (the Hour of Mercy), at the bedside of the dying, on the nine days before Divine Mercy Sunday (the Divine Mercy Novena, beginning Good Friday), and in moments of personal anguish or fear. It can be prayed silently, aloud, alone, or in a group. Many parishes lead the chaplet weekly, often on Fridays in remembrance of Christ's Passion. Catholics praying for the conversion or peaceful death of a loved one often commit to praying the chaplet daily for a sustained period — a month, the duration of an illness, the time leading up to a major decision. The chaplet pairs naturally with attendance at the Divine Mercy Novena from Good Friday to Divine Mercy Sunday.",
    prayerText: "Eternal Father, I offer You the Body and Blood, Soul and Divinity of Your dearly beloved Son, Our Lord Jesus Christ, in atonement for our sins and those of the whole world. For the sake of His sorrowful Passion, have mercy on us and on the whole world.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Faustina Kowalska",
    feastDay: "Divine Mercy Sunday",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.CONVERSION, SituationCategory.GENERAL, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "chaplet-st-michael",
    name: "Chaplet of St. Michael the Archangel",
    category: PrayerCategory.CHAPLET,
    description: "This chaplet honors the nine choirs of angels and asks St. Michael's powerful protection against evil. Especially potent in times of spiritual warfare.",
    instructions: "Pray nine salutations, one for each choir of angels, each followed by one Our Father and three Hail Marys. Conclude with four Our Fathers: one to St. Michael, one to St. Gabriel, one to St. Raphael, and one to your guardian angel.",
    prayerText: null,
    duration: 15,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: "St. Michael the Archangel",
    feastDay: "September 29",
    situationTags: [SituationCategory.MENTAL_HEALTH, SituationCategory.CONVERSION, SituationCategory.DISCERNMENT, SituationCategory.GENERAL],
  },
  {
    slug: "seven-sorrows-rosary",
    name: "Rosary of the Seven Sorrows",
    category: PrayerCategory.CHAPLET,
    description: "Meditating on the seven sorrows of the Blessed Virgin Mary. Our Lady promised extraordinary graces to those who devote themselves to her tears and sorrows.",
    instructions: "Pray seven groups of seven Hail Marys, each group preceded by a meditation on one of Mary's sorrows: 1) Simeon's prophecy 2) Flight into Egypt 3) Loss of Jesus in the Temple 4) Meeting Jesus on the Way of the Cross 5) Crucifixion 6) Jesus taken from the Cross 7) Burial of Jesus.",
    prayerText: null,
    duration: 20,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: "Our Lady of Sorrows",
    feastDay: "September 15",
    situationTags: [SituationCategory.GRIEF, SituationCategory.ILLNESS, SituationCategory.MENTAL_HEALTH],
  },

  // ─── LITANIES ───────────────────────────────────────────────
  {
    slug: "litany-sacred-heart",
    name: "Litany of the Sacred Heart",
    category: PrayerCategory.LITANY,
    description: "A beautiful litany invoking the many titles of the Sacred Heart of Jesus, approved for public use by Pope Leo XIII in 1899.",
    instructions: "Pray responsively: the leader prays each invocation and the response is 'Have mercy on us' or 'Pray for us.' Best prayed on First Fridays.",
    prayerText: null,
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Margaret Mary Alacoque",
    feastDay: "Friday after Corpus Christi",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GENERAL, SituationCategory.CONVERSION],
  },
  {
    slug: "litany-blessed-virgin",
    name: "Litany of the Blessed Virgin Mary (Loreto)",
    category: PrayerCategory.LITANY,
    description: "The most famous Marian litany, traditionally prayed at the Shrine of Loreto. It invokes Mary under her many beautiful titles.",
    instructions: "Pray responsively with the response 'Pray for us' after each title of Mary. Often prayed after the Rosary.",
    prayerText: null,
    duration: 8,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.PREGNANCY, SituationCategory.FAMILY, SituationCategory.ILLNESS, SituationCategory.GENERAL],
  },
  {
    slug: "litany-st-joseph",
    name: "Litany of St. Joseph",
    category: PrayerCategory.LITANY,
    description: "Invoking St. Joseph under his many titles: Guardian of the Redeemer, Patron of Workers, Terror of Demons, and more.",
    instructions: "Pray responsively with the response 'Pray for us' after each title.",
    prayerText: null,
    duration: 8,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Joseph",
    feastDay: "March 19",
    situationTags: [SituationCategory.FAMILY, SituationCategory.CAREER, SituationCategory.FINANCIAL, SituationCategory.MARRIAGE],
  },
  {
    slug: "litany-saints",
    name: "Litany of the Saints",
    category: PrayerCategory.LITANY,
    description: "The Litany of the Saints is the oldest and most solemn litany in the Catholic Church. Its roots reach back to the early centuries — fragments of the form appear in seventh-century Western liturgical books, and Pope Gregory the Great instituted the great litanic processions of Rome in 590, asking the faithful to call upon the saints by name in supplication during plague. The litany became part of the Easter Vigil baptismal liturgy at least by the eighth century. Its current Roman-rite text was formally fixed by Pope Pius V in 1568 and revised in the post-Vatican II liturgical reform (1969). The structure unfolds in five major movements: (1) Kyrie eleison invocations and Trinitarian petitions; (2) the great roll-call of saints by name — Blessed Virgin Mary first, then archangels (Michael, Gabriel, Raphael), patriarchs and prophets (Abraham, Moses, Elijah, John the Baptist), apostles and evangelists (Peter, Paul, Andrew, John, James, etc.), martyrs (Stephen, Lawrence, Polycarp, Ignatius of Antioch, Cyprian, Sebastian, Agatha, Agnes), confessor-bishops and doctors (Athanasius, Basil, Gregory, Augustine, Jerome, Ambrose), founders and virgins (Anthony of the Desert, Benedict, Francis, Dominic, Catherine of Siena, Teresa of Ávila); (3) petitions of deliverance ('From all evil, deliver us, O Lord'); (4) petitions of supplication ('That You would govern and preserve Your holy Church, we beseech You, hear us'); (5) closing Agnus Dei and collect. The litany is one of the principal prayers of the Catholic liturgy and is used at: the Easter Vigil (during the Liturgy of Baptism), Holy Saturday baptisms, priestly and episcopal ordinations (the candidates lie prostrate while the gathered church sings the litany over them), the Rite of Christian Initiation of Adults (RCIA) at the Rite of Election, the dedication of a church, the consecration of altars, and the conferral of religious vows. It is also customary in many parishes on the Solemnity of All Saints (November 1), at funerals of priests and religious, in moments of grave public need (war, pandemic, natural disaster), and as the closing prayer of pilgrimage processions. The litany names many saints; the local diocese or community is also free to add the patron saints of the local church.",
    instructions: "The Litany of the Saints is prayed responsively, usually chanted in liturgical settings. A leader (priest, deacon, or trained cantor) intones the invocation; the assembly responds with the appropriate formula. The responses follow the structure: 'Pray for us' after each saint named or group of saints; 'Deliver us, O Lord' after each invocation of deliverance ('From all evil…'); 'We beseech You, hear us' after each petition of supplication ('That You would…'). The litany takes approximately fifteen to twenty minutes when sung at solemn pace in a liturgical setting; somewhat less when prayed at home in spoken form. For private devotion, the litany may be prayed from any approved printed text (the Roman Missal, a parish prayer book, or the United States Conference of Catholic Bishops website all carry the official Latin and English texts). When prayed at home, sit, stand, or kneel as you wish; the litany's pace is contemplative rather than rushed. The litany is appropriately used: (1) at All Saints (November 1) and All Souls (November 2) as the family prayer of those days; (2) at the bedside of someone gravely ill or dying — many Catholic hospital chaplains pray the litany as last rites approach; (3) at the start of a major pilgrimage or family undertaking, asking the great cloud of witnesses (Hebrews 12:1) to surround the petitioners; (4) in time of plague, disaster, or public emergency, in continuity with Gregory the Great's institution of the litanic processions during the Roman plague of 590. The litany's particular spiritual gift is the felt-presence of the communion of saints — the truth that the faithful praying on earth and those triumphant in heaven are one body in Christ, distinct in their stations but united in their prayer.",
    prayerText: null,
    duration: 15,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: null,
    feastDay: "November 1 (All Saints)",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GENERAL, SituationCategory.SURGERY],
  },

  // ─── SHORT PRAYERS ──────────────────────────────────────────
  {
    slug: "memorare",
    name: "The Memorare",
    category: PrayerCategory.SHORT_PRAYER,
    description: "The Memorare is a brief but extraordinarily powerful prayer of confidence in the intercession of the Blessed Virgin Mary. It takes its name from its opening Latin word, Memorare ('Remember'), and is attributed in its modern form to Fr. Claude Bernard, a 17th-century French priest known as 'the Poor Priest' for his apostolate to prisoners and the dying. The prayer was popularized through Fr. Bernard's distribution of more than 200,000 leaflets in pre-Revolution Paris, though its devotional roots reach further back — likely to a longer prayer attributed to St. Bernard of Clairvaux (1090-1153), the great Cistercian abbot and Doctor of the Church whose Marian devotion shaped Western piety. The prayer's structure is a confident appeal: it acknowledges Mary's universal maternity (O Virgin of virgins, my mother), references the unbroken tradition of her intercession (never was it known that anyone who fled to thy protection… was left unaided), and concludes with a humble petition (in thy mercy hear and answer me). Saints across the centuries have testified to its power: Mother Teresa of Calcutta prayed nine consecutive Memorares daily — what she called her 'flying novena' — when she needed something quickly. The Memorare is the Catholic prayer of last resort, prayed in moments of acute need, at the bedside of the dying, in the chapel before a difficult conversation, or whispered as a parent waits for word from a hospital room.",
    instructions: "Pray once with full attention and devotion, calling to mind the person and intention you are bringing before Mary. The Memorare is short enough to commit to memory and to pray anywhere — in the car, on a walk, before sleep, in the moments before any difficult task. For a more sustained intercession, pray nine consecutive Memorares in a row (this is the 'flying novena' Mother Teresa favored for urgent intentions). Some traditions add a brief moment of silence before praying, naming the intention aloud or in the heart. The prayer can also be incorporated as a closing prayer at the end of a longer rosary or novena, sealing the petition with confident trust in Mary's maternal love. Catholic families often pray the Memorare at the bedside of someone gravely ill, at the news of a difficult diagnosis, or during the labor of childbirth. Because the prayer is short and its words ancient and well-loved, it has become a kind of spiritual emergency response — a prayer that reaches automatically to the lips when words otherwise fail. Children can be taught it as early as they can recite it; it is one of the most appropriate prayers to teach a child as a 'first prayer of trouble.' The Latin original is sometimes still prayed by those drawn to traditional forms: 'Memorare, O piissima Virgo Maria, non esse auditum a saeculo…'",
    prayerText: "Remember, O most gracious Virgin Mary, that never was it known that anyone who fled to thy protection, implored thy help, or sought thy intercession was left unaided. Inspired by this confidence, I fly unto thee, O Virgin of virgins, my mother; to thee do I come, before thee I stand, sinful and sorrowful. O Mother of the Word Incarnate, despise not my petitions, but in thy mercy hear and answer me. Amen.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Bernard of Clairvaux",
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.PREGNANCY, SituationCategory.GENERAL, SituationCategory.SURGERY],
  },
  {
    slug: "st-michael-prayer",
    name: "Prayer to St. Michael the Archangel",
    category: PrayerCategory.SHORT_PRAYER,
    description: "Composed by Pope Leo XIII, this prayer asks St. Michael to defend us in battle against spiritual evil.",
    prayerText: "St. Michael the Archangel, defend us in battle. Be our defense against the wickedness and snares of the Devil. May God rebuke him, we humbly pray, and do thou, O Prince of the heavenly hosts, by the power of God, cast into hell Satan, and all the evil spirits, who prowl about the world seeking the ruin of souls. Amen.",
    instructions: "Pray once with devotion. Often prayed after Mass or at the end of a prayer session.",
    duration: 1,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Michael the Archangel",
    feastDay: "September 29",
    situationTags: [SituationCategory.MENTAL_HEALTH, SituationCategory.CONVERSION, SituationCategory.GENERAL],
  },
  {
    slug: "prayer-healing",
    name: "Prayer for Healing",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A simple, heartfelt prayer asking God for physical and spiritual healing, suitable for any illness or suffering.",
    prayerText: "Lord Jesus, You came to heal our infirmities and You bore our sufferings. We pray that You visit and relieve Your servant for whom we pray. Look upon them with the eyes of Your mercy. Comfort their suffering, grant them patience, restore them to health, and give them the grace to place their hope and trust in You above all things. We ask this through Your holy name. Amen.",
    instructions: "Pray once with your hands outstretched or placed on the person if present. Mention their name and specific needs.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.SURGERY, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "prayer-serenity",
    name: "Serenity Prayer",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A widely loved prayer asking God for the grace to accept what we cannot change, courage to change what we can, and wisdom to know the difference.",
    prayerText: "God, grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference. Living one day at a time, enjoying one moment at a time; accepting hardship as a pathway to peace; taking, as Jesus did, this sinful world as it is, not as I would have it; trusting that You will make all things right if I surrender to Your will; so that I may be reasonably happy in this life and supremely happy with You forever in the next. Amen.",
    instructions: "Pray slowly and reflectively, pausing at each phrase.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.MENTAL_HEALTH, SituationCategory.GRIEF, SituationCategory.FINANCIAL, SituationCategory.CAREER],
  },
  {
    slug: "prayer-st-francis",
    name: "Peace Prayer of St. Francis",
    category: PrayerCategory.SHORT_PRAYER,
    description: "An inspiring prayer seeking to be an instrument of God's peace, attributed to the spirit of St. Francis of Assisi.",
    prayerText: "Lord, make me an instrument of Your peace: where there is hatred, let me sow love; where there is injury, pardon; where there is doubt, faith; where there is despair, hope; where there is darkness, light; where there is sadness, joy. O divine Master, grant that I may not so much seek to be consoled as to console, to be understood as to understand, to be loved as to love. For it is in giving that we receive, it is in pardoning that we are pardoned, and it is in dying that we are born to eternal life. Amen.",
    instructions: "Pray once daily, asking God to help you be an instrument of peace in the life of the person you're praying for.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Francis of Assisi",
    feastDay: "October 4",
    situationTags: [SituationCategory.FAMILY, SituationCategory.MARRIAGE, SituationCategory.MENTAL_HEALTH, SituationCategory.GRIEF],
  },
  {
    slug: "anima-christi",
    name: "Anima Christi",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A medieval Eucharistic prayer beloved by St. Ignatius of Loyola. A beautiful prayer of union with Christ, especially after Communion.",
    prayerText: "Soul of Christ, sanctify me. Body of Christ, save me. Blood of Christ, inebriate me. Water from the side of Christ, wash me. Passion of Christ, strengthen me. O good Jesus, hear me. Within Thy wounds hide me. Suffer me not to be separated from Thee. From the malicious enemy defend me. In the hour of my death call me and bid me come unto Thee, that with Thy saints I may praise Thee forever and ever. Amen.",
    instructions: "Pray with devotion, especially after receiving Holy Communion or during a visit to the Blessed Sacrament.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Ignatius of Loyola",
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.SURGERY, SituationCategory.GENERAL],
  },
  {
    slug: "guardian-angel-prayer",
    name: "Guardian Angel Prayer",
    category: PrayerCategory.SHORT_PRAYER,
    description: "The classic prayer to one's guardian angel, asking for guidance, protection, and light on the path of life.",
    prayerText: "Angel of God, my guardian dear, to whom God's love commits me here, ever this day be at my side, to light and guard, to rule and guide. Amen.",
    instructions: "Pray with trust, asking your guardian angel to also watch over the person you are praying for.",
    duration: 1,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: "October 2",
    situationTags: [SituationCategory.GENERAL, SituationCategory.ILLNESS, SituationCategory.SURGERY],
  },
  {
    slug: "prayer-expectant-mothers",
    name: "Prayer for Expectant Mothers",
    category: PrayerCategory.SHORT_PRAYER,
    description: "Catholic prayer for expectant mothers draws on the Church's centuries-old tradition of accompanying women through pregnancy under the patronage of the Blessed Virgin Mary, who carried Christ in her own womb for nine months. The principal scriptural foundation is the Visitation (Luke 1:39-56): Mary, herself in the early months of pregnancy with Jesus, hastens into the hill country of Judea to be with her cousin Elizabeth, who is in her sixth month with John the Baptist. The Magnificat ('My soul magnifies the Lord…') is Mary's prayer of two pregnant women rejoicing together. The Catholic devotional tradition has long entrusted expectant mothers to Mary under several specific titles: Our Lady of the Expectation (the Solemnity of December 18, a Spanish-tradition feast nine days before Christmas, marking Mary's own approaching delivery); Our Lady of Guadalupe (whose image shows her pregnant, wearing the maternity sash of indigenous Mexican custom); and St. Gerard Majella (1726-1755), an Italian Redemptorist lay brother whose name has become so associated with safe delivery that statues of him are placed in maternity wards in Catholic hospitals around the world. The prayer for expectant mothers is appropriate at every stage of pregnancy: at the first positive test, through the first-trimester anxiety many mothers feel, during the long middle months of waiting, in the weeks of nesting before delivery, during labor itself (when family members often pray it at the bedside), and immediately after delivery in thanksgiving. It is also prayed by communities — parishes, prayer groups, the woman's circle of friends — as a way of surrounding her with intercession through nine months of waiting that mirror Mary's own.",
    prayerText: "O Blessed Mother, you received the good news of the incarnation of Christ, your Son, with faith and trust. Grant your comfort to all women as they await the birth of their child. They are anxious as they wait for the arrival of their baby. Calm their fears and strengthen their faith in God's loving providence. Help them to feel the peace of your loving arms around them as they wait for the miracle of new life. We ask this through Christ our Lord. Amen.",
    instructions: "Pray once daily for the expectant mother, ideally at the same time each day so the practice becomes part of her ordinary rhythm. The prayer is short enough to commit to memory; many expectant mothers carry it on a small card kept in a Bible, prayer book, or wallet, and pray it as they pause in the day-to-day work of preparing for the baby. Common practices that pair with the prayer: (1) Lighting a candle at a Marian shrine in the parish church for each month of the pregnancy — many parishes maintain a designated 'expectant mothers' candle stand and post the names of women being prayed for; (2) Praying a daily decade of the Rosary, meditating on the Joyful Mysteries (the Annunciation, the Visitation, the Nativity, the Presentation, the Finding in the Temple — five mysteries that walk the spiritual arc from conception through young motherhood); (3) Asking the intercession of St. Gerard Majella — the prayer of expectant mothers may be paired with the St. Gerard novena, especially in the final nine days before delivery; (4) Family or community prayer at the bedside during labor, in which the expectant mother's spouse or other family member prays the Memorare (the brief Marian prayer of confidence) or this prayer aloud as labor progresses. The Catholic tradition is clear that pregnancy is itself a form of prayer — the woman's body sheltering and forming new life is a participation in the work of Mary's own womb — and so the woman herself can pray simply 'Mary, share with me the strength you carried' even on days when more formal prayer is too tiring. After delivery, the prayer continues in thanksgiving and turns naturally toward the prayers of motherhood for the newborn child.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "Our Lady",
    feastDay: null,
    situationTags: [SituationCategory.PREGNANCY],
  },
  {
    slug: "prayer-fertility",
    name: "Prayer for the Gift of a Child",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A prayer for couples struggling with infertility, asking God through the intercession of Sts. Joachim and Anne for the gift of new life.",
    prayerText: "Lord God, Creator of all life, we humbly ask You to bless this couple with the gift of a child. You blessed Abraham and Sarah, Elizabeth and Zechariah, and Joachim and Anne with children in their waiting. We trust in Your divine plan and perfect timing. Grant them patience in their waiting, comfort in their sorrow, and hope in Your promises. Through the intercession of Sts. Joachim and Anne, hear our prayer. Amen.",
    instructions: "Pray once daily, trusting in God's timing and plan for the couple.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "Sts. Joachim and Anne",
    feastDay: "July 26",
    situationTags: [SituationCategory.FERTILITY],
  },

  // ─── MASS & SACRAMENTAL ────────────────────────────────────
  {
    slug: "mass-offering",
    name: "Offer a Mass",
    category: PrayerCategory.MASS_SACRAMENTAL,
    description: "The highest prayer of the Church. Having a Mass offered for someone's intention is the most powerful spiritual gift you can give.",
    instructions: "Contact your parish office and request a Mass be offered for the person's intention. A small stipend (typically $5-20) is customary. You may attend the Mass and offer your prayers during it.",
    prayerText: null,
    duration: 60,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.SURGERY, SituationCategory.GENERAL, SituationCategory.CONVERSION],
  },
  {
    slug: "adoration-hour",
    name: "Holy Hour of Adoration",
    category: PrayerCategory.MASS_SACRAMENTAL,
    description: "The Holy Hour of Eucharistic Adoration is one of the most ancient and central forms of Catholic prayer — sustained, silent prayer in the real presence of Jesus Christ in the Blessed Sacrament, exposed in a monstrance on the altar. The practice draws directly on the Gospel scene at Gethsemane: Christ asks His apostles, 'Could you not watch one hour with me?' (Matthew 26:40). The 'one hour' is no arbitrary length — it is the explicit request of the Lord on the night of His passion, and the Catholic Holy Hour answers that request directly. The devotional practice of sustained Eucharistic adoration crystallized in the Counter-Reformation and was given particular impetus by the apparitions of the Sacred Heart to St. Margaret Mary Alacoque at Paray-le-Monial (1673-1675); Christ specifically asked Margaret Mary for an hour of reparation in His presence each Thursday night, in remembrance of the Agony in the Garden. The Holy Hour became central to the 'Apostleship of Prayer' (founded 1844) and was preached widely in the twentieth century by Venerable Fulton Sheen (1895-1979), who famously committed to a Holy Hour every day of his priestly life — over 60 years — and credited every grace of his ministry to that hour. Today perpetual Eucharistic adoration chapels operate in thousands of parishes worldwide, staffed by lay volunteers who commit to specific hours through the night and day so that Christ is never left alone in His exposed Sacrament. The Holy Hour is appropriate for: any sustained intercession, especially for healing, conversion, or vocational discernment; reparation for sin (one's own or the world's); spiritual aridity (when prayer feels dry, the presence of the Eucharist sustains the soul even when feelings are absent); preparation for major life decisions; thanksgiving after grace received. It is the prayer Sheen called 'the secret of every priest who became a saint.'",
    instructions: "Visit your parish during Adoration hours — check your parish website or bulletin for the schedule. Many parishes offer Eucharistic adoration on Thursdays (Christ's request to Margaret Mary), Fridays (the traditional day of reparation), or as an extended Holy Hour after weekday Mass. Some maintain perpetual adoration with the Blessed Sacrament exposed 24/7. Upon arriving: (1) Genuflect on both knees (the traditional sign of reverence for the exposed Eucharist, distinct from the single-knee genuflection for the reserved Sacrament in the tabernacle); (2) Find a place to sit or kneel; (3) Bow in silent recognition that you are in the literal presence of God incarnate. The hour itself is unstructured by design — sustained presence is the prayer. Some patterns Catholics use to fill the hour: (a) Pray the Rosary, meditating on the Sorrowful Mysteries; (b) Read Scripture (the Passion narratives, the Gospel of John, the Psalms — Psalm 23 and 91 are common Eucharistic-adoration scriptures); (c) Pray the Chaplet of Divine Mercy, especially during the 3:00 PM hour; (d) Read from a spiritual classic (Fulton Sheen's writings, Thomas à Kempis's Imitation of Christ, the journal of St. Faustina); (e) Sit in silent presence — the highest form of contemplative prayer; (f) Journal a conversation with Jesus about the person you are offering the hour for. Throughout the hour, name the person and intention often — speak to the Lord directly as a friend present in the same room. The hour ends with another genuflection and a brief prayer of thanksgiving for the gift of His presence. For a sustained prayer commitment (a novena of hours, a week of nine Thursdays), it is appropriate to commit to the same parish chapel each time so the practice has a rhythm and a place.",
    prayerText: null,
    duration: 60,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.DISCERNMENT, SituationCategory.CONVERSION, SituationCategory.GRIEF, SituationCategory.GENERAL],
  },
  {
    slug: "stations-of-the-cross",
    name: "Stations of the Cross",
    category: PrayerCategory.MASS_SACRAMENTAL,
    description: "The Stations of the Cross (also called the Way of the Cross, Via Crucis, or Via Dolorosa in Latin) is a meditative devotion in which the believer follows Christ's Passion through fourteen distinct stations — moments along His journey from the praetorium of Pilate to the tomb. The practice originated in the earliest Christian centuries as literal pilgrimage to the holy sites in Jerusalem; pilgrims would walk the actual path Christ walked, pausing at each significant station to pray. When Jerusalem fell to Muslim control in the seventh century and pilgrimage became dangerous and rare, the Franciscans — given custody of the Holy Land by Pope Clement VI in 1342 — began to reconstruct the Via Dolorosa in the form of devotional stations in their churches across Europe, so that any Catholic could 'walk' the Way of the Cross spiritually without traveling to Jerusalem. Pope Innocent XI granted the Franciscans indulgences for praying the stations in 1686, and Pope Clement XII extended this to all the faithful in 1731. The standard fourteen stations were fixed in the eighteenth century: (1) Jesus is condemned to death; (2) Jesus is given His cross; (3) Jesus falls the first time; (4) Jesus meets His mother Mary; (5) Simon of Cyrene helps Jesus carry the cross; (6) Veronica wipes the face of Jesus; (7) Jesus falls the second time; (8) Jesus meets the women of Jerusalem; (9) Jesus falls the third time; (10) Jesus is stripped of His garments; (11) Jesus is nailed to the cross; (12) Jesus dies on the cross; (13) Jesus is taken down from the cross; (14) Jesus is laid in the tomb. Some Catholic communities add a fifteenth station for the Resurrection. The Way of the Cross is traditionally prayed on Fridays during Lent and is the central public devotion of Good Friday in most Catholic parishes worldwide. The Pope leads the Way of the Cross at the Colosseum in Rome every Good Friday — a tradition revived by Pope Paul VI and continued by every pope since, broadcast globally — with the meditations on each station composed each year by a different Catholic writer, theologian, or community.",
    prayerText: "We adore You, O Christ, and we bless You, because by Your holy Cross You have redeemed the world.",
    instructions: "Visit a Catholic church — most have the fourteen stations mounted along the side walls of the nave, usually as small paintings, plaques, or bas-relief sculptures. The traditional practice: (1) Begin at the first station; genuflect; (2) Announce the station aloud ('The First Station: Jesus is condemned to death'); (3) Pray the response 'We adore You, O Christ, and we bless You, because by Your holy Cross You have redeemed the world'; (4) Meditate briefly on the station's scene from Christ's Passion; (5) Pray an Our Father, Hail Mary, and Glory Be (or other prayers from a Way-of-the-Cross booklet); (6) Offer the station for your intention. Move to the next station — physically walking from one to the next is part of the prayer; the Way of the Cross is meant to be walked, however briefly. Total duration: approximately thirty to forty-five minutes when prayed at unhurried pace in a church. At home, a printed Way of the Cross booklet works fine — there is no physical-presence requirement. The devotion is appropriately prayed: (a) On Fridays during Lent, the traditional Catholic discipline; (b) On Good Friday itself, the day Christ walked the Via Dolorosa; (c) On any Friday throughout the year (as the traditional day of remembrance of the Passion); (d) When carrying a heavy personal cross — illness, grief, addiction, persecution — uniting your suffering to Christ's; (e) When praying for someone who is suffering or dying; (f) When seeking the grace of patience under affliction. The Way of the Cross is one of the most accessible Catholic devotions for the bereaved, the chronically ill, and those caring for the dying — Christ's own suffering, walked step by step, gives shape to ours.",
    prayerText: "We adore You, O Christ, and we bless You, because by Your holy Cross You have redeemed the world.",
    duration: 30,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: null,
    feastDay: "Good Friday",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.SURGERY, SituationCategory.MENTAL_HEALTH],
  },

  // ─── SCRIPTURE-BASED ────────────────────────────────────────
  {
    slug: "psalm-23",
    name: "Psalm 23 - The Lord is My Shepherd",
    category: PrayerCategory.SCRIPTURE,
    description: "The most beloved psalm of comfort and trust, assuring us that the Lord guides and protects us even through the valley of the shadow of death.",
    prayerText: "The Lord is my shepherd; I shall not want. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul. He leads me in paths of righteousness for His name's sake. Even though I walk through the valley of the shadow of death, I will fear no evil, for You are with me; Your rod and Your staff, they comfort me. You prepare a table before me in the presence of my enemies; You anoint my head with oil; my cup overflows. Surely goodness and mercy shall follow me all the days of my life, and I shall dwell in the house of the Lord forever.",
    instructions: "Read the psalm slowly and meditatively, perhaps reading it three times. First for understanding, second to savor the words, third to let them become your prayer for the person.",
    duration: 5,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.SURGERY, SituationCategory.MENTAL_HEALTH, SituationCategory.GENERAL],
  },
  {
    slug: "psalm-91",
    name: "Psalm 91 - Under the Shadow of the Almighty",
    category: PrayerCategory.SCRIPTURE,
    description: "A psalm of divine protection, promising that God shelters those who trust in Him from plague, terror, and harm.",
    prayerText: "He who dwells in the shelter of the Most High will rest in the shadow of the Almighty. I will say of the Lord, 'He is my refuge and my fortress, my God, in whom I trust.' Surely He will save you from the fowler's snare and from the deadly pestilence. He will cover you with His feathers, and under His wings you will find refuge; His faithfulness will be your shield and rampart.",
    instructions: "Pray the full psalm meditatively, inserting the name of the person you are praying for. You may also write out the psalm as a form of prayer.",
    duration: 5,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.SURGERY, SituationCategory.MENTAL_HEALTH, SituationCategory.GENERAL],
  },
  {
    slug: "lectio-divina",
    name: "Lectio Divina",
    category: PrayerCategory.SCRIPTURE,
    description: "An ancient monastic practice of prayerful Scripture reading in four steps: read, meditate, pray, and contemplate. Transform your Bible reading into deep prayer.",
    instructions: "Choose a Scripture passage. 1) Lectio (Read): Read slowly 2-3 times. 2) Meditatio (Meditate): What word or phrase stands out? 3) Oratio (Pray): Speak to God about what struck you, offering it for your intention. 4) Contemplatio (Contemplate): Rest in God's presence in silence. Recommended passages for healing: James 5:13-16, Matthew 11:28-30, Isaiah 41:10.",
    prayerText: null,
    duration: 20,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: "St. Benedict",
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.DISCERNMENT, SituationCategory.MENTAL_HEALTH, SituationCategory.GENERAL],
  },

  // ─── DEVOTIONS ──────────────────────────────────────────────
  {
    slug: "morning-offering",
    name: "Morning Offering",
    category: PrayerCategory.DEVOTION,
    description: "The Morning Offering is the foundational daily prayer of the Apostleship of Prayer — a Catholic spiritual movement founded in 1844 by Jesuit Father François-Xavier Gautrelet in Vals, France, and renamed in 2015 by Pope Francis as the Pope's Worldwide Prayer Network. The movement's central insight is simple but transformative: every ordinary action of a Catholic's day — work, study, conversation, meals, weariness, joy, suffering, even sleep — can be offered to God as an intentional act of love, transforming the entire day into one sustained act of prayer. The Morning Offering is the act that does this offering, prayed first thing upon waking, before the day takes over. The traditional text — composed in the late nineteenth century in the Apostleship's devotional pamphlets and refined through several papal-approved versions — places the day's offering 'through the Immaculate Heart of Mary' (the Marian mediation that frames Catholic life as filial) and unites it 'with the Holy Sacrifice of the Mass throughout the world' (so the day's offering is gathered into the Eucharistic sacrifice being celebrated in some Catholic parish somewhere on earth in every minute of every hour). Each month, the Pope publishes specific universal prayer intentions through the Pope's Worldwide Prayer Network — for example, 'for the protection of children' or 'for an end to human trafficking' — and Catholics who pray the Morning Offering unite their day's small actions to those broader intentions. The Morning Offering is also a powerful prayer of intercession for a particular person: a sick family member, an adult child who has left the faith, a parent struggling with addiction, anyone whose situation the petitioner experiences as constantly present. By offering the day for that person, the Catholic's ordinary work becomes intercessory prayer; the long discipline of the commute, the difficult conversation, the patience required at the office, the meal prepared with love — all of it is converted into intercession.",
    prayerText: "O Jesus, through the Immaculate Heart of Mary, I offer You my prayers, works, joys, and sufferings of this day for all the intentions of Your Sacred Heart, in union with the Holy Sacrifice of the Mass throughout the world, in thanksgiving for Your favors, in reparation for my sins, for the intentions of all my associates, and in particular for (mention the person's name and intention). Amen.",
    instructions: "Pray immediately upon waking, before the day's busyness can take over. The traditional discipline is to pray it before getting out of bed, while the mind is still soft and the day still feels like a gift; some Catholics pray it during the first quiet moment of the morning routine (with the first cup of coffee, at the kitchen sink, while feeding the baby). The prayer is short enough to commit to memory in a single day. To make it part of life: (1) Post the prayer in a place where you'll see it first thing — taped to the bathroom mirror, inside the bedroom door, on a card by the coffee maker; (2) Name the specific person and intention at the appropriate place in the prayer (the 'and in particular for…' line), making the offering concrete and not abstract; (3) Throughout the day, when work becomes difficult or an interruption breaks your plans, briefly renew the offering: 'I gave this day to You for (name); this moment is part of that.' Many Catholic households pray the Morning Offering aloud together as the family rises — parents and children praying it together before breakfast. The Pope's Worldwide Prayer Network publishes the Pope's monthly universal intentions; aligning your daily offering to the Pope's intention each month adds a dimension of Catholic-universal solidarity to your prayer. For a sustained intercession (a novena of days for a sick loved one, the duration of a difficult discernment, the months of a family member's chemotherapy), the Morning Offering becomes the spine of the prayer — every day's ordinary work offered for the named intention until the situation is resolved or the season closes.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.GENERAL, SituationCategory.ILLNESS, SituationCategory.FAMILY, SituationCategory.CAREER],
  },
  {
    slug: "offering-suffering",
    name: "Offering Up Suffering",
    category: PrayerCategory.DEVOTION,
    description: "The Catholic practice of uniting one's own suffering with Christ's on the Cross, offering it for the good of another. Transforms pain into powerful prayer.",
    prayerText: "Lord Jesus, I unite my sufferings to Yours on the Cross. I offer this pain, this difficulty, this trial for the intention of (name). May my small share in Your suffering bring grace and healing to those for whom I pray. I trust that nothing is wasted in Your economy of salvation. Amen.",
    instructions: "When you experience physical pain, emotional difficulty, or any hardship during the day, pause and consciously offer it to God for the person's intention.",
    duration: 1,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.MENTAL_HEALTH, SituationCategory.SURGERY],
  },
  {
    slug: "three-oclock-prayer",
    name: "Three O'Clock Prayer (Hour of Mercy)",
    category: PrayerCategory.DEVOTION,
    description: "The Three O'Clock Prayer — also called the Hour of Mercy or the Hour of Great Mercy — was given by Jesus to St. Maria Faustina Kowalska in the revelations of Divine Mercy recorded in her Diary: Divine Mercy in My Soul. Jesus instructed Faustina that 3:00 PM each day — the hour of His death on Calvary — is to be honored as the Hour of Great Mercy, in which a brief act of prayer obtains extraordinary graces. The exact promise, recorded in Faustina's Diary (entry 1320): 'At three o'clock, implore My mercy, especially for sinners; and, if only for a brief moment, immerse yourself in My Passion, particularly in My abandonment at the moment of agony. This is the hour of great mercy for the whole world… In this hour I will refuse nothing to the soul that makes a request of Me in virtue of My Passion.' The hour corresponds to the ninth hour of the Jewish day in the gospel chronology (Mark 15:34) — the hour at which 'Jesus cried out with a loud voice… and expired' (Mark 15:37). The Three O'Clock Prayer is the simplest and most accessible form of Divine Mercy devotion — much shorter than the chaplet, accessible to anyone who can pause for thirty seconds at the hour of Christ's death. It is the prayer the Catholic tradition places at the heart of the day for those who cannot make a full Holy Hour, who cannot pray the chaplet, who are at work or in school or at a hospital bedside — the brief offered moment that takes Christ at His word and asks the mercy He promised. The devotion was suppressed for many years (the same period when Faustina's writings were under provisional restriction), but Pope St. John Paul II canonized Faustina on April 30, 2000, and established Divine Mercy Sunday as a feast for the universal Church, restoring the full Divine Mercy devotional repertoire to the Catholic world. The Three O'Clock Prayer is now prayed daily in countless Catholic households, religious communities, hospital chaplaincies, and the Sanctuary of Divine Mercy in Łagiewniki, Kraków.",
    prayerText: "You expired, Jesus, but the source of life gushed forth for souls, and the ocean of mercy opened up for the whole world. O Fount of Life, unfathomable Divine Mercy, envelop the whole world and empty Yourself out upon us. O Blood and Water, which gushed forth from the Heart of Jesus as a fount of mercy for us, I trust in You! Holy God, Holy Mighty One, Holy Immortal One, have mercy on us and on the whole world. (3x)",
    instructions: "At 3:00 PM each day, pause briefly — whatever you are doing — and pray. The prayer is short enough to commit to memory in a single afternoon and to pray anywhere: at a desk, in a car, in a classroom, at a hospital bedside, walking down a sidewalk. The Catholic tradition is clear that 'even a moment of prayer at this hour is powerful' — if a busy life can only spare twenty seconds for a single 'Jesus, I trust in You' at 3:00 PM, that brief moment is itself the practice. For those with more time at the hour: (1) Pray the full Chaplet of Divine Mercy (approximately ten minutes; see the separate Chaplet of Divine Mercy entry); (2) Make a brief 'visit' to a nearby Catholic church or Eucharistic adoration chapel; (3) Pause to read a paragraph from St. Faustina's Diary; (4) Pray for sinners — Faustina recorded that Jesus told her this is the most powerful intercession at this hour. The traditional Catholic disciplines that pair with the Three O'Clock Prayer: (a) Setting a daily alarm for 3:00 PM as a reminder until the discipline becomes habit; (b) Wearing a small Divine Mercy holy card or image as a tactile reminder through the day; (c) Praying at the foot of a crucifix (the literal posture of Christ at His death); (d) Adding a moment of physical stillness — pausing whatever motion is in progress, even if briefly. The hour is a daily anchor for the Divine Mercy devotional life: the chaplet at 3:00 PM, the daily Mass, the monthly First Friday confession, the annual Divine Mercy Novena from Good Friday to Divine Mercy Sunday — all woven around this central moment of remembrance of Christ's death and the mercy that flowed from His pierced side.",
    duration: 3,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Faustina Kowalska",
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.GENERAL, SituationCategory.SURGERY],
  },
  {
    slug: "surrender-novena",
    name: "Surrender Novena",
    category: PrayerCategory.NOVENA,
    description: "Based on the words of Don Dolindo Ruotolo: 'O Jesus, I surrender myself to You, take care of everything.' A novena of radical trust and abandonment to God's will.",
    instructions: "Pray once daily for nine consecutive days. Each day has a unique meditation on a different aspect of surrender. After reading the day's meditation, close by repeating the refrain ten times: 'O Jesus, I surrender myself to You, take care of everything!'",
    prayerText: "O Jesus, I surrender myself to You, take care of everything!\n\n(Repeat ten times.)",
    // Per-day meditations from Don Dolindo Ruotolo's "Novena di
    // Abbandono." Operator (William) sourced and approved this
    // specific wording May 6 2026; queued for retroactive review with
    // Fr. Palladino (theology-review.md item #14). Light copy
    // normalization applied (curly quotes -> straight ASCII; en-dashes
    // softened to commas in Day 6 for parser-friendliness).
    //
    // Render is empty-gated everywhere — when this array is empty
    // (legacy rows, other novenas), the chain page and email fall
    // through to prayerText. With nine entries here, the chain page
    // shows a "Day N reflection" card above the refrain, and the
    // chain daily reminder email mirrors that block.
    dailyReflections: [
      "Why do you confuse yourselves by worrying? Leave the care of your affairs to me and everything will be peaceful. I say to you in truth that every act of true, blind, complete surrender to me produces the effect that you desire and resolves all difficult situations.",
      "Surrender to me does not mean to fret, to be upset, or to lose hope, nor does it mean offering to me a worried prayer asking me to follow you and change your worry into prayer. It is against this surrender, deeply against it, to worry, to be nervous and to desire to think about the consequences of anything.\n\nIt is like the confusion that children feel when they ask their mother to see to their needs, and then try to take care of those needs for themselves so that their childlike efforts get in their mother's way. Surrender means to placidly close the eyes of the soul, to turn away from thoughts of tribulation and to put yourself in my care, so that only I act, saying, 'You take care of it.'",
      "How many things I do when the soul, in so much spiritual and material need, turns to me, looks at me and says to me, 'You take care of it,' then closes its eyes and rests. In pain you pray for me to act, but that I act in the way you want. You do not turn to me, instead, you want me to adapt your ideas. You are not sick people who ask the doctor to cure you, but rather sick people who tell the doctor how to. So do not act this way, but pray as I taught you in the Our Father: 'Hallowed be thy Name,' that is, be glorified in my need. 'Thy kingdom come,' that is, let all that is in us and in the world be in accord with your kingdom. 'Thy will be done on Earth as it is in Heaven,' that is, in our need, decide as you see fit for our temporal and eternal life. If you say to me truly: 'Thy will be done,' which is the same as saying: 'You take care of it,' I will intervene with all my omnipotence, and I will resolve the most difficult situations.",
      "You see evil growing instead of weakening? Do not worry. Close your eyes and say to me with faith: 'Thy will be done, You take care of it.' I say to you that I will take care of it, and that I will intervene as does a doctor and I will accomplish miracles when they are needed. Do you see that the sick person is getting worse? Do not be upset, but close your eyes and say, 'You take care of it.' I say to you that I will take care of it, and that there is no medicine more powerful than my loving intervention. By my love, I promise this to you.",
      "And then I must lead you on a path different from the one you see, I will prepare you; I will carry you in my arms; I will let you find yourself, like children who have fallen asleep in their mother's arms, on the other bank of the river. What troubles you and hurts you immensely are your reason, your thoughts and worry, and your desire at all costs to deal with what afflicts you.",
      "You are sleepless; you want to judge everything, direct everything and see to everything and you surrender to human strength, or worse, to men themselves, trusting in their intervention. This is what hinders my words and my views. Oh, how much I wish from you this surrender, to help you; and how I suffer when I see you so agitated! Satan tries to do exactly this: to agitate you and to remove you from my protection and to throw you into the jaws of human initiative. So, trust only in me, rest in me, surrender to me in everything.",
      "I perform miracles in proportion to your full surrender to me and to your not thinking of yourselves. I sow treasure troves of graces when you are in deepest poverty. No person of reason, no thinker, has ever performed miracles, not even among the saints. He does divine works whosoever surrenders to God. So don't think about it any more, because your mind is acute and for you it is very hard to see evil and to trust in me and to not think of yourself. Do this for all your needs, do this, all of you, and you will see great continual silent miracles. I will take care of things, I promise this to you.",
      "Close your eyes and let yourself be carried away on the flowing current of my grace; close your eyes and do not think of the present, turning your thoughts away from the future just as you would from temptation. Repose in me, believing in my goodness, and I promise you by my love that if you say, 'You take care of it,' I will take care of it all; I will console you, liberate you and guide you.",
      "Pray always in readiness to surrender, and you will receive from it great peace and great rewards, even when I confer on you the grace of immolation, of repentance, and of love. Then what does suffering matter? It seems impossible to you? Close your eyes and say with all your soul, 'Jesus, you take care of it.' Do not be afraid, I will take care of things and you will bless my name by humbling yourself. A thousand prayers cannot equal one single act of surrender, remember this well. There is no novena more effective than this.",
    ],
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "Don Dolindo Ruotolo",
    feastDay: null,
    situationTags: [SituationCategory.MENTAL_HEALTH, SituationCategory.FINANCIAL, SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.DISCERNMENT],
  },
  {
    slug: "prayer-marriage",
    name: "Prayer for a Marriage",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A prayer for married couples experiencing difficulty, asking God to strengthen the bond of love and restore unity.",
    prayerText: "Lord Jesus, You blessed the wedding at Cana with Your presence and Your first miracle. We ask You to bless this marriage with Your grace. Strengthen the bond of love between husband and wife. Help them to forgive as You forgive, to love as You love, and to serve each other as You serve us. When trials come, let them lean on You and on each other. Restore what is broken, heal what is wounded, and renew what has grown weary. Through the intercession of the Holy Family, protect and sanctify this marriage. Amen.",
    instructions: "Pray daily for the couple, asking God to strengthen and heal their marriage.",
    duration: 3,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "Holy Family",
    feastDay: null,
    situationTags: [SituationCategory.MARRIAGE],
  },
  {
    slug: "prayer-financial-hardship",
    name: "Prayer in Financial Hardship",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A prayer asking God's providence in times of financial difficulty, trusting in the One who feeds the birds of the air and clothes the lilies of the field.",
    prayerText: "Heavenly Father, You know our needs before we ask. You feed the birds of the air and clothe the lilies of the field. We trust in Your providence as we face this financial difficulty. Grant us wisdom in our decisions, patience in our waiting, and hope in Your promises. Help us to be good stewards of whatever You provide. Through the intercession of St. Joseph the Worker, open doors of opportunity and provision. We trust in You. Amen.",
    instructions: "Pray daily, surrendering financial worries to God and asking for His guidance and provision.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Joseph the Worker",
    feastDay: "May 1",
    situationTags: [SituationCategory.FINANCIAL],
  },
  {
    slug: "prayer-conversion",
    name: "Prayer for Conversion of a Loved One",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A prayer for someone who has fallen away from the faith or does not yet know Christ, asking for the grace of conversion.",
    prayerText: "Lord Jesus, Good Shepherd, You seek out the lost sheep and carry them home on Your shoulders. We pray for (name), who is far from You. Send Your Holy Spirit to touch their heart. Remove every obstacle that keeps them from You. Open their eyes to Your love, their ears to Your voice, and their heart to Your mercy. Through the intercession of St. Monica, who prayed for years for her son Augustine's conversion, grant us perseverance in prayer and trust in Your timing. We place them in Your Sacred Heart. Amen.",
    instructions: "Pray daily with perseverance, remembering that St. Monica prayed for 17 years for her son's conversion. Trust in God's timing.",
    duration: 3,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Monica",
    feastDay: "August 27",
    situationTags: [SituationCategory.CONVERSION],
  },
  {
    slug: "prayer-discernment",
    name: "Prayer for Discernment",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A prayer asking the Holy Spirit for clarity and guidance in making an important life decision.",
    prayerText: "Come, Holy Spirit, source of all light. Shed Your radiance on this decision that lies before me. Grant me wisdom to see clearly, courage to choose rightly, and strength to follow through. Quiet the noise of my own desires and fears, that I may hear Your still, small voice. Through the intercession of Our Lady, Seat of Wisdom, guide me in the path You have prepared. I trust not in my own understanding, but in You alone. Amen.",
    instructions: "Pray daily, and spend time in silence after praying, listening for the movements of the Holy Spirit.",
    duration: 3,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.DISCERNMENT, SituationCategory.CAREER],
  },
];

async function main() {
  console.log("Seeding prayer types...");

  for (const prayer of prayers) {
    await prisma.prayerType.upsert({
      where: { slug: prayer.slug },
      update: prayer,
      create: prayer,
    });
    console.log(`  + ${prayer.name}`);
  }

  console.log(`\nSeeded ${prayers.length} prayers successfully!`);
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
