import "dotenv/config";
import { PrismaClient, PrayerCategory, DifficultyLevel, SituationCategory } from "../src/generated/prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const prayers = [
  // ─── NOVENAS ────────────────────────────────────────────────
  {
    slug: "novena-sacred-heart",
    name: "Novena to the Sacred Heart of Jesus",
    category: PrayerCategory.NOVENA,
    description: "The Novena to the Sacred Heart of Jesus is one of the most beloved devotions in the Catholic Church, born from the apparitions of Jesus to St. Margaret Mary Alacoque at Paray-le-Monial, France, in 1673-1675. In these visions, Christ revealed the depth of His love for humanity, symbolized by His Heart pierced and crowned with thorns, and asked that this love be honored through devotion to His Sacred Heart. The novena spans nine consecutive days of prayer (the number nine recalling the nine days the apostles and Mary spent in prayer between the Ascension and Pentecost) and is traditionally offered with confidence in Christ's compassion for those who suffer. It is especially fitting in times of illness, family difficulty, spiritual desolation, or persistent intentions that have not yet found resolution. The Sacred Heart is not merely a symbol; it is the historical, physical heart of Christ, fully human and fully divine, the source of His infinite charity. Pope Pius XII's 1956 encyclical Haurietis Aquas describes the Sacred Heart as 'the throne of mercy' and confirms the central place of this devotion in the Church's life. Prayer warriors who offer this novena join centuries of Catholics who have placed their trust in the wounded Heart of the Savior.",
    instructions: "Pray once daily for nine consecutive days at approximately the same time each day. Choose a quiet space and begin with the Sign of the Cross. The traditional structure is: (1) an opening invocation, often 'O Most Sacred Heart of Jesus, I place my trust in Thee'; (2) the novena prayer text itself; (3) an Our Father, Hail Mary, and Glory Be; (4) a personal intention named aloud or silently. Many add the Litany of the Sacred Heart on the final day or pray the novena in conjunction with First Friday devotions, receiving Holy Communion on nine consecutive First Fridays as Christ Himself requested of St. Margaret Mary. The novena may be prayed at any time of year, but is especially appropriate during the month of June (the Month of the Sacred Heart), in the days leading up to the Solemnity of the Sacred Heart (Friday after Corpus Christi), or whenever someone faces a particularly difficult moment. If a day is missed, the traditional counsel is to begin again from day one rather than skip; the discipline of consecutive prayer is itself part of the devotion's grace. Some pray for a specific person each day of the novena; others offer all nine days for a single intention.",
    prayerText: "O most holy Heart of Jesus, fountain of every blessing, I adore You, I love You, and with lively sorrow for my sins I offer You this poor heart of mine. Make me humble, patient, pure and wholly obedient to Your will. Grant, Good Jesus, that I may live in You and for You. Protect me in the midst of danger. Comfort me in my afflictions. Give me health of body, assistance in my temporal needs, Your blessing on all that I do, and the grace of a holy death. Amen.",
    duration: 15,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Margaret Mary Alacoque",
    feastDay: "Friday after Corpus Christi",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.MENTAL_HEALTH, SituationCategory.GENERAL],
  },
  {
    slug: "novena-st-blaise",
    name: "Novena to St. Blaise",
    category: PrayerCategory.NOVENA,
    description: "St. Blaise was a fourth-century bishop and physician who, according to tradition, miraculously cured a child choking on a fishbone. He is the patron of those suffering from ailments of the throat and lungs, and his intercession is invoked for healing of any sickness affecting breath or voice. The Church blesses throats in his name on his feast day, February 3.",
    instructions: "Pray once daily for nine consecutive days. Traditionally prayed in the days leading up to the Feast of St. Blaise (February 3), but can be prayed at any time, especially when someone is suffering from a throat, lung, or respiratory illness. Many add the Our Father, Hail Mary, and Glory Be at the end of each day.",
    prayerText: "O glorious St. Blaise, who by your martyrdom left to the Church a precious witness to the faith, obtain for us the grace to preserve within ourselves this divine gift, and to defend — without human respect — both by word and example, the truth of that same faith. You miraculously restored a little child when it was at the point of death because of an affliction of the throat. Grant us your mighty patronage in like misfortunes, and especially intercede for (mention your intention). Above all, obtain for us the grace of trusting in God's providence, that whatever the outcome of this affliction, we may be drawn closer to His Sacred Heart. Amen.\n\nThrough the intercession of Saint Blaise, bishop and martyr, may God deliver you from every disease of the throat and from every other illness. In the name of the Father, and of the Son, and of the Holy Spirit. Amen.",
    duration: 8,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Blaise",
    feastDay: "February 3",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.SURGERY],
  },
  {
    slug: "novena-st-jude",
    name: "Novena to St. Jude",
    category: PrayerCategory.NOVENA,
    description: "The patron saint of impossible causes and desperate situations. This novena is prayed when all hope seems lost, asking St. Jude's powerful intercession.",
    instructions: "Pray once daily for nine consecutive days. Many include the Our Father, Hail Mary, and Glory Be at the end of each day's prayer.",
    prayerText: "Most holy apostle, St. Jude, faithful servant and friend of Jesus, the Church honors and invokes you universally as the patron of hope. Please intercede on my behalf. Make use of that particular privilege given to you to bring hope, comfort, and help where they are needed most. Come to my assistance in this great need that I may receive the consolation and help of heaven as I work with my challenges, particularly (mention your intention). I praise God with you and all the saints forever. I promise, blessed St. Jude, to be ever mindful of this great favor, to always honor you as my special and powerful patron, and to gratefully encourage devotion to you. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Jude Thaddeus",
    feastDay: "October 28",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.FINANCIAL, SituationCategory.CAREER, SituationCategory.FERTILITY, SituationCategory.OTHER],
  },
  {
    slug: "novena-divine-mercy",
    name: "Divine Mercy Novena",
    category: PrayerCategory.NOVENA,
    description: "Given by Jesus to St. Faustina, this novena begins on Good Friday and ends on Divine Mercy Sunday. Each day brings a different group of souls before God's throne of mercy.",
    instructions: "Pray once daily for nine consecutive days. Each day has a unique intention and group of souls to pray for. Conclude each day with the Chaplet of Divine Mercy.",
    prayerText: "You expired, Jesus, but the source of life gushed forth for souls, and the ocean of mercy opened up for the whole world. O Fount of Life, unfathomable Divine Mercy, envelop the whole world and empty Yourself out upon us. O Blood and Water, which gushed forth from the Heart of Jesus as a fount of mercy for us, I trust in You!",
    duration: 20,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 9,
    patronSaint: "St. Faustina Kowalska",
    feastDay: "Second Sunday of Easter",
    situationTags: [SituationCategory.CONVERSION, SituationCategory.GRIEF, SituationCategory.GENERAL, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "novena-our-lady-perpetual-help",
    name: "Novena to Our Lady of Perpetual Help",
    category: PrayerCategory.NOVENA,
    description: "A tender devotion to Mary under her title of Perpetual Help, asking her constant maternal intercession in times of difficulty and distress.",
    instructions: "Pray once daily for nine consecutive days. Many parishes hold weekly Perpetual Help novena services on Wednesdays.",
    prayerText: "O Mother of Perpetual Help, grant that I may ever invoke your most powerful name, which is the safeguard of the living and the salvation of the dying. O Purest Mary, O Sweetest Mary, let your name henceforth be ever on my lips. Delay not, O Blessed Lady, to help me whenever I call on you, for in all my needs, in all my temptations, I shall never cease to call on you, ever repeating your sacred name. O what consolation, what sweetness, what confidence, what emotion fills my soul when I pronounce your sacred name or even only think of you. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "Our Lady of Perpetual Help",
    feastDay: "June 27",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.PREGNANCY, SituationCategory.FAMILY, SituationCategory.GRIEF],
  },
  {
    slug: "novena-st-joseph",
    name: "Novena to St. Joseph",
    category: PrayerCategory.NOVENA,
    description: "St. Joseph, the foster father of Jesus and chaste spouse of the Blessed Virgin Mary, is one of the most beloved intercessors in the Catholic tradition. Though scripture records no words from him, his fidelity is unmistakable: he protected the Holy Family in flight to Egypt, provided for them by the labor of his hands, and taught Jesus the trades of carpentry and faithful manhood. Pope Pius IX named him Patron of the Universal Church in 1870, and Pope Francis declared 2020-2021 the Year of St. Joseph through the apostolic letter Patris Corde (With a Father's Heart). This novena draws on a long tradition of Catholic devotion to St. Joseph as the patron of fathers, workers, families, real estate matters, and a happy death — the four pillars of his earthly ministry. He is invoked especially in moments of financial hardship, family discord, employment difficulty, and the discernment of vocation. Many Catholics commit to the novena leading up to either of his feasts: March 19 (Solemnity of St. Joseph, Spouse of the Blessed Virgin Mary) or May 1 (St. Joseph the Worker, instituted by Pope Pius XII in 1955 to sanctify human labor). St. Teresa of Ávila famously wrote: 'To other saints the Lord seems to have given grace to succor us in some particular necessity, but to this glorious saint, I know by experience, He has given grace to help us in all.'",
    instructions: "Pray once daily for nine consecutive days. The traditional structure is: open with the Sign of the Cross; pray the novena prayer text; conclude with an Our Father, Hail Mary, and Glory Be; and name your specific intention. Some Catholic families add the Litany of St. Joseph or seven Our Fathers, Hail Marys, and Glory Bes in honor of the Seven Sorrows and Seven Joys of St. Joseph — a traditional devotion connected to his joyful and sorrowful experiences in the life of the Holy Family. For families discerning a major life decision (a job change, a move, a marriage), it is customary to begin the novena nine days before the decision must be made, asking St. Joseph's intercession for clarity and the grace to accept God's will. The novena is also traditionally prayed during the month of March (the Month of St. Joseph) or alongside the popular practice of burying a St. Joseph statue in association with the sale of a home — a folk tradition that emphasizes confident trust rather than superstition. Whether prayed for vocational discernment, financial provision, family healing, or a happy death (one of the four traditional ends of this devotion), the spirit should be one of quiet, hardworking confidence — the very disposition St. Joseph modeled in scripture.",
    prayerText: "O St. Joseph, whose protection is so great, so strong, so prompt before the throne of God, I place in you all my interests and desires. O St. Joseph, do assist me by your powerful intercession and obtain for me from your divine Son all spiritual blessings through Jesus Christ, Our Lord; so that having engaged here below your heavenly power, I may offer my thanksgiving and homage to the most loving of Fathers. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Joseph",
    feastDay: "March 19 / May 1",
    situationTags: [SituationCategory.FAMILY, SituationCategory.FINANCIAL, SituationCategory.CAREER, SituationCategory.MARRIAGE],
  },
  {
    slug: "novena-infant-of-prague",
    name: "Novena to the Infant Jesus of Prague",
    category: PrayerCategory.NOVENA,
    description: "A devotion to the Christ Child, honoring His divine infancy and asking for His childlike trust and provision in our needs.",
    instructions: "Pray once daily for nine consecutive days.",
    prayerText: "O Jesus, who said, 'Ask and you shall receive, seek and you shall find, knock and it shall be opened to you,' through the intercession of Mary, Your most holy Mother, I knock, I seek, I ask that my prayer be granted. (Make your request.) O Jesus, who said, 'All that you ask of the Father in My name, He will grant you,' through the intercession of Mary, Your most holy Mother, I humbly and urgently ask Your Father in Your name that my prayer be granted. (Make your request.) Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.FINANCIAL, SituationCategory.ILLNESS, SituationCategory.GENERAL],
  },
  {
    slug: "novena-st-therese",
    name: "Novena to St. Therese of Lisieux",
    category: PrayerCategory.NOVENA,
    description: "The Little Flower promised to spend her heaven doing good upon the earth. This novena invokes her childlike confidence in God's merciful love.",
    instructions: "Pray once daily for nine consecutive days. Tradition holds that a rose may be received as a sign of St. Therese's intercession.",
    prayerText: "O Little Therese of the Child Jesus, please pick for me a rose from the heavenly gardens and send it to me as a message of love. O Little Flower of Jesus, ask God today to grant the favors I now place with confidence in your hands. (Mention your intention.) St. Therese, help me to always believe, as you did, in God's great love for me, so that I might imitate your Little Way each day. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Therese of Lisieux",
    feastDay: "October 1",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.DISCERNMENT, SituationCategory.CONVERSION, SituationCategory.GENERAL],
  },
  {
    slug: "novena-holy-spirit",
    name: "Novena to the Holy Spirit",
    category: PrayerCategory.NOVENA,
    description: "The original novena: the Apostles prayed for nine days between the Ascension and Pentecost. This novena invokes the sevenfold gifts of the Holy Spirit.",
    instructions: "Pray once daily for nine consecutive days. Traditionally prayed between Ascension Thursday and Pentecost Sunday, but may be prayed at any time.",
    prayerText: "Come, Holy Spirit, fill the hearts of Your faithful and enkindle in them the fire of Your love. Send forth Your Spirit and they shall be created, and You shall renew the face of the earth. O God, who by the light of the Holy Spirit did instruct the hearts of the faithful, grant that by the same Holy Spirit we may be truly wise and ever enjoy His consolations. Through Christ Our Lord. Amen.",
    duration: 15,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: null,
    feastDay: "Pentecost",
    situationTags: [SituationCategory.DISCERNMENT, SituationCategory.CONVERSION, SituationCategory.CAREER, SituationCategory.GENERAL],
  },
  {
    slug: "novena-miraculous-medal",
    name: "Novena of the Miraculous Medal",
    category: PrayerCategory.NOVENA,
    description: "Based on the apparitions of the Blessed Virgin to St. Catherine Laboure, this novena asks Mary's intercession through the graces symbolized by the Miraculous Medal.",
    instructions: "Pray once daily for nine consecutive days. If possible, wear the Miraculous Medal during the novena.",
    prayerText: "O Immaculate Virgin Mary, Mother of Our Lord Jesus and our Mother, penetrated with the most lively confidence in your all-powerful and never-failing intercession, manifested so often through the Miraculous Medal, we your loving and trustful children implore you to obtain for us the graces and favors we ask during this novena, if they be beneficial to our immortal souls, and the souls for whom we pray. (Mention your intention.) You know, O Mary, how often our souls have been the sanctuaries of your Son who hates iniquity. Obtain for us then a deep hatred of sin and that purity of heart which will attach us to God alone. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Catherine Laboure",
    feastDay: "November 27",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.PREGNANCY, SituationCategory.CONVERSION, SituationCategory.GENERAL],
  },
  {
    slug: "novena-st-anthony",
    name: "Novena to St. Anthony of Padua",
    category: PrayerCategory.NOVENA,
    description: "Known as the Wonder Worker and finder of lost things, St. Anthony is a beloved intercessor. This novena asks his help in recovering what is lost, whether material or spiritual.",
    instructions: "Pray once daily for nine consecutive days, traditionally on Tuesdays.",
    prayerText: "Holy St. Anthony, gentlest of saints, your love for God and charity for His creatures made you worthy when on earth to possess miraculous powers. Miracles waited on your word, which you were ever ready to speak for those in trouble or anxiety. Encouraged by this thought, I implore you to obtain for me (state your intention). The answer to my prayer may require a miracle; even so, you are the Saint of Miracles. O gentle and loving St. Anthony, whose heart was ever full of human sympathy, whisper my petition into the ears of the sweet Infant Jesus, who loved to be folded in your arms. The gratitude of my heart will ever be yours. Amen.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Anthony of Padua",
    feastDay: "June 13",
    situationTags: [SituationCategory.GENERAL, SituationCategory.FINANCIAL, SituationCategory.FAMILY],
  },

  // ─── ROSARY ─────────────────────────────────────────────────
  {
    slug: "holy-rosary",
    name: "The Holy Rosary",
    category: PrayerCategory.ROSARY,
    description: "The Holy Rosary is the central Marian devotion of the Catholic Church — a contemplative prayer in which the believer meditates on the great mysteries of Christ's life, death, and resurrection while praying repeated decades of Hail Marys. The rosary as we know it took shape over centuries; tradition holds that the Blessed Virgin Mary gave the rosary to St. Dominic in 1208 as a spiritual weapon against the Albigensian heresy, and the structure of fifteen mysteries was codified by Pope St. Pius V in 1569. In 2002, Pope St. John Paul II added the Luminous Mysteries (the Mysteries of Light) in his apostolic letter Rosarium Virginis Mariae, bringing the total to twenty mysteries grouped into four sets. Each decade is a meditation: as the fingers move along the beads and the lips recite the Hail Mary, the mind dwells on a moment from the Gospels — the Annunciation, the Crucifixion, the Resurrection, the Transfiguration. The rosary is not vain repetition (Matthew 6:7) but a school of contemplation, allowing the rhythm of the prayers to free the mind for reflection on the mysteries of salvation. Popes from Leo XIII (whose eleven encyclicals on the rosary remain magisterial reference points) to Francis have urged the faithful to pray the rosary daily. It is the prayer offered at Lourdes, Fatima, and countless other Marian apparitions, and the prayer most commonly prayed by Catholic families gathered around a sickbed or a grave.",
    instructions: "A complete rosary is five decades, typically prayed in about twenty minutes. Begin with the Sign of the Cross and the Apostles' Creed on the crucifix. On the first large bead, pray the Our Father; on each of the three small beads that follow, pray a Hail Mary (for an increase in the three theological virtues — faith, hope, and love); on the next large bead, pray the Glory Be. Then announce the first mystery aloud and meditate briefly on its meaning; pray an Our Father on the large bead, ten Hail Marys on the ten small beads (one per bead) while continuing to meditate on the mystery, then a Glory Be and the Fatima Prayer ('O my Jesus, forgive us our sins, save us from the fires of hell…'). Repeat for four more decades, naming each mystery in turn. Close with the Hail Holy Queen and the Rosary prayer. The four sets of mysteries are traditionally prayed: Joyful Mysteries on Mondays and Saturdays (the Annunciation, Visitation, Nativity, Presentation, Finding in the Temple); Sorrowful on Tuesdays and Fridays (the Agony, Scourging, Crowning with Thorns, Carrying of the Cross, Crucifixion); Glorious on Wednesdays and Sundays (the Resurrection, Ascension, Pentecost, Assumption, Coronation); Luminous on Thursdays (the Baptism, Wedding at Cana, Proclamation of the Kingdom, Transfiguration, Institution of the Eucharist). For prayer-train coverage, a single decade — or even a single Hail Mary offered with intention — is also a valid offering of the rosary.",
    prayerText: null,
    duration: 20,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "Our Lady of the Rosary",
    feastDay: "October 7",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.PREGNANCY, SituationCategory.FAMILY, SituationCategory.MARRIAGE, SituationCategory.GENERAL, SituationCategory.CONVERSION, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "rosary-for-healing",
    name: "Rosary for Healing",
    category: PrayerCategory.ROSARY,
    description: "The full Rosary prayed with specific healing intentions. Each mystery is offered for a different aspect of healing: physical, emotional, spiritual, and relational.",
    instructions: "Pray the standard five-decade Rosary, but before each decade, state a healing intention: 1st decade for physical healing, 2nd for emotional healing, 3rd for spiritual healing, 4th for healing of relationships, 5th for the healing of those who care for the sick.",
    prayerText: null,
    duration: 25,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "Our Lady of Lourdes",
    feastDay: "February 11",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.SURGERY, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "54-day-rosary-novena",
    name: "54-Day Rosary Novena",
    category: PrayerCategory.ROSARY,
    description: "The most powerful Rosary devotion: 27 days of petition followed by 27 days of thanksgiving. Three complete rosary novenas of petition and three of thanksgiving.",
    instructions: "Pray five decades of the Rosary daily for 54 consecutive days. Days 1-27: Pray in petition. Days 28-54: Pray in thanksgiving (even before you see the answer). Rotate through all four sets of mysteries: Joyful, Sorrowful, Glorious, and Luminous.",
    prayerText: null,
    duration: 20,
    difficulty: DifficultyLevel.ADVANCED,
    daysRequired: 54,
    patronSaint: "Our Lady of the Rosary",
    feastDay: "October 7",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.FERTILITY, SituationCategory.CONVERSION, SituationCategory.DISCERNMENT],
  },

  // ─── CHAPLETS ───────────────────────────────────────────────
  {
    slug: "chaplet-divine-mercy",
    name: "Chaplet of Divine Mercy",
    category: PrayerCategory.CHAPLET,
    description: "The Chaplet of Divine Mercy was given by Jesus to St. Maria Faustina Kowalska, a Polish nun, in a series of revelations between 1931 and 1938 recorded in her Diary: Divine Mercy in My Soul. The chaplet is a powerful intercessory prayer offered for the conversion of sinners, the consolation of the dying, and the mercy of God upon the whole world. Jesus told Faustina that whoever prays this chaplet will receive 'great mercy at the hour of death' — and that He delights especially in this prayer offered at 3:00 PM, the Hour of Mercy (the hour of His death on Calvary). The chaplet is prayed on standard rosary beads, which makes it accessible to anyone with a rosary, and takes approximately ten minutes. Devotion to Divine Mercy was suppressed for many years, but Pope St. John Paul II — himself a Pole and a fellow countryman of St. Faustina — canonized her on April 30, 2000, and established Divine Mercy Sunday (the second Sunday of Easter) as a feast for the universal Church. The Chaplet of Divine Mercy has become one of the most widely-prayed devotions in the modern Church, especially favored by hospital chaplains, hospice volunteers, and those praying for the conversion of loved ones. It is the daily prayer at the National Shrine of the Divine Mercy in Stockbridge, Massachusetts, and at the Sanctuary of Divine Mercy in Łagiewniki, Kraków — the place where Faustina lived, died, and is now entombed.",
    instructions: "Using a standard five-decade rosary, begin with the Sign of the Cross, an Our Father, a Hail Mary, and the Apostles' Creed on the crucifix and opening beads. On each of the five large beads (where the Our Father is normally prayed), pray: 'Eternal Father, I offer You the Body and Blood, Soul and Divinity of Your dearly beloved Son, Our Lord Jesus Christ, in atonement for our sins and those of the whole world.' On each of the ten small beads of each decade, pray: 'For the sake of His sorrowful Passion, have mercy on us and on the whole world.' At the end of all five decades, conclude by praying three times: 'Holy God, Holy Mighty One, Holy Immortal One, have mercy on us and on the whole world.' The chaplet is especially powerful when prayed at 3:00 PM (the Hour of Mercy), at the bedside of the dying, on the nine days before Divine Mercy Sunday (the Divine Mercy Novena, beginning Good Friday), and in moments of personal anguish or fear. It can be prayed silently, aloud, alone, or in a group. Many parishes lead the chaplet weekly, often on Fridays in remembrance of Christ's Passion. Catholics praying for the conversion or peaceful death of a loved one often commit to praying the chaplet daily for a sustained period — a month, the duration of an illness, the time leading up to a major decision. The chaplet pairs naturally with attendance at the Divine Mercy Novena from Good Friday to Divine Mercy Sunday.",
    prayerText: "Eternal Father, I offer You the Body and Blood, Soul and Divinity of Your dearly beloved Son, Our Lord Jesus Christ, in atonement for our sins and those of the whole world. For the sake of His sorrowful Passion, have mercy on us and on the whole world.",
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Faustina Kowalska",
    feastDay: "Divine Mercy Sunday",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.CONVERSION, SituationCategory.GENERAL, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "chaplet-st-michael",
    name: "Chaplet of St. Michael the Archangel",
    category: PrayerCategory.CHAPLET,
    description: "This chaplet honors the nine choirs of angels and asks St. Michael's powerful protection against evil. Especially potent in times of spiritual warfare.",
    instructions: "Pray nine salutations, one for each choir of angels, each followed by one Our Father and three Hail Marys. Conclude with four Our Fathers: one to St. Michael, one to St. Gabriel, one to St. Raphael, and one to your guardian angel.",
    prayerText: null,
    duration: 15,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: "St. Michael the Archangel",
    feastDay: "September 29",
    situationTags: [SituationCategory.MENTAL_HEALTH, SituationCategory.CONVERSION, SituationCategory.DISCERNMENT, SituationCategory.GENERAL],
  },
  {
    slug: "seven-sorrows-rosary",
    name: "Rosary of the Seven Sorrows",
    category: PrayerCategory.CHAPLET,
    description: "Meditating on the seven sorrows of the Blessed Virgin Mary. Our Lady promised extraordinary graces to those who devote themselves to her tears and sorrows.",
    instructions: "Pray seven groups of seven Hail Marys, each group preceded by a meditation on one of Mary's sorrows: 1) Simeon's prophecy 2) Flight into Egypt 3) Loss of Jesus in the Temple 4) Meeting Jesus on the Way of the Cross 5) Crucifixion 6) Jesus taken from the Cross 7) Burial of Jesus.",
    prayerText: null,
    duration: 20,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: "Our Lady of Sorrows",
    feastDay: "September 15",
    situationTags: [SituationCategory.GRIEF, SituationCategory.ILLNESS, SituationCategory.MENTAL_HEALTH],
  },

  // ─── LITANIES ───────────────────────────────────────────────
  {
    slug: "litany-sacred-heart",
    name: "Litany of the Sacred Heart",
    category: PrayerCategory.LITANY,
    description: "A beautiful litany invoking the many titles of the Sacred Heart of Jesus, approved for public use by Pope Leo XIII in 1899.",
    instructions: "Pray responsively: the leader prays each invocation and the response is 'Have mercy on us' or 'Pray for us.' Best prayed on First Fridays.",
    prayerText: null,
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Margaret Mary Alacoque",
    feastDay: "Friday after Corpus Christi",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GENERAL, SituationCategory.CONVERSION],
  },
  {
    slug: "litany-blessed-virgin",
    name: "Litany of the Blessed Virgin Mary (Loreto)",
    category: PrayerCategory.LITANY,
    description: "The most famous Marian litany, traditionally prayed at the Shrine of Loreto. It invokes Mary under her many beautiful titles.",
    instructions: "Pray responsively with the response 'Pray for us' after each title of Mary. Often prayed after the Rosary.",
    prayerText: null,
    duration: 8,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.PREGNANCY, SituationCategory.FAMILY, SituationCategory.ILLNESS, SituationCategory.GENERAL],
  },
  {
    slug: "litany-st-joseph",
    name: "Litany of St. Joseph",
    category: PrayerCategory.LITANY,
    description: "Invoking St. Joseph under his many titles: Guardian of the Redeemer, Patron of Workers, Terror of Demons, and more.",
    instructions: "Pray responsively with the response 'Pray for us' after each title.",
    prayerText: null,
    duration: 8,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Joseph",
    feastDay: "March 19",
    situationTags: [SituationCategory.FAMILY, SituationCategory.CAREER, SituationCategory.FINANCIAL, SituationCategory.MARRIAGE],
  },
  {
    slug: "litany-saints",
    name: "Litany of the Saints",
    category: PrayerCategory.LITANY,
    description: "The great litany invoking the communion of saints by name. Prayed at ordinations, baptisms, and other solemn occasions.",
    instructions: "Pray responsively with 'Pray for us' after each saint's name and 'Deliver us, O Lord' or 'We beseech You, hear us' as appropriate.",
    prayerText: null,
    duration: 15,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: null,
    feastDay: "November 1 (All Saints)",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GENERAL, SituationCategory.SURGERY],
  },

  // ─── SHORT PRAYERS ──────────────────────────────────────────
  {
    slug: "memorare",
    name: "The Memorare",
    category: PrayerCategory.SHORT_PRAYER,
    description: "The Memorare is a brief but extraordinarily powerful prayer of confidence in the intercession of the Blessed Virgin Mary. It takes its name from its opening Latin word, Memorare ('Remember'), and is attributed in its modern form to Fr. Claude Bernard, a 17th-century French priest known as 'the Poor Priest' for his apostolate to prisoners and the dying. The prayer was popularized through Fr. Bernard's distribution of more than 200,000 leaflets in pre-Revolution Paris, though its devotional roots reach further back — likely to a longer prayer attributed to St. Bernard of Clairvaux (1090-1153), the great Cistercian abbot and Doctor of the Church whose Marian devotion shaped Western piety. The prayer's structure is a confident appeal: it acknowledges Mary's universal maternity (O Virgin of virgins, my mother), references the unbroken tradition of her intercession (never was it known that anyone who fled to thy protection… was left unaided), and concludes with a humble petition (in thy mercy hear and answer me). Saints across the centuries have testified to its power: Mother Teresa of Calcutta prayed nine consecutive Memorares daily — what she called her 'flying novena' — when she needed something quickly. The Memorare is the Catholic prayer of last resort, prayed in moments of acute need, at the bedside of the dying, in the chapel before a difficult conversation, or whispered as a parent waits for word from a hospital room.",
    instructions: "Pray once with full attention and devotion, calling to mind the person and intention you are bringing before Mary. The Memorare is short enough to commit to memory and to pray anywhere — in the car, on a walk, before sleep, in the moments before any difficult task. For a more sustained intercession, pray nine consecutive Memorares in a row (this is the 'flying novena' Mother Teresa favored for urgent intentions). Some traditions add a brief moment of silence before praying, naming the intention aloud or in the heart. The prayer can also be incorporated as a closing prayer at the end of a longer rosary or novena, sealing the petition with confident trust in Mary's maternal love. Catholic families often pray the Memorare at the bedside of someone gravely ill, at the news of a difficult diagnosis, or during the labor of childbirth. Because the prayer is short and its words ancient and well-loved, it has become a kind of spiritual emergency response — a prayer that reaches automatically to the lips when words otherwise fail. Children can be taught it as early as they can recite it; it is one of the most appropriate prayers to teach a child as a 'first prayer of trouble.' The Latin original is sometimes still prayed by those drawn to traditional forms: 'Memorare, O piissima Virgo Maria, non esse auditum a saeculo…'",
    prayerText: "Remember, O most gracious Virgin Mary, that never was it known that anyone who fled to thy protection, implored thy help, or sought thy intercession was left unaided. Inspired by this confidence, I fly unto thee, O Virgin of virgins, my mother; to thee do I come, before thee I stand, sinful and sorrowful. O Mother of the Word Incarnate, despise not my petitions, but in thy mercy hear and answer me. Amen.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Bernard of Clairvaux",
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.PREGNANCY, SituationCategory.GENERAL, SituationCategory.SURGERY],
  },
  {
    slug: "st-michael-prayer",
    name: "Prayer to St. Michael the Archangel",
    category: PrayerCategory.SHORT_PRAYER,
    description: "Composed by Pope Leo XIII, this prayer asks St. Michael to defend us in battle against spiritual evil.",
    prayerText: "St. Michael the Archangel, defend us in battle. Be our defense against the wickedness and snares of the Devil. May God rebuke him, we humbly pray, and do thou, O Prince of the heavenly hosts, by the power of God, cast into hell Satan, and all the evil spirits, who prowl about the world seeking the ruin of souls. Amen.",
    instructions: "Pray once with devotion. Often prayed after Mass or at the end of a prayer session.",
    duration: 1,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Michael the Archangel",
    feastDay: "September 29",
    situationTags: [SituationCategory.MENTAL_HEALTH, SituationCategory.CONVERSION, SituationCategory.GENERAL],
  },
  {
    slug: "prayer-healing",
    name: "Prayer for Healing",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A simple, heartfelt prayer asking God for physical and spiritual healing, suitable for any illness or suffering.",
    prayerText: "Lord Jesus, You came to heal our infirmities and You bore our sufferings. We pray that You visit and relieve Your servant for whom we pray. Look upon them with the eyes of Your mercy. Comfort their suffering, grant them patience, restore them to health, and give them the grace to place their hope and trust in You above all things. We ask this through Your holy name. Amen.",
    instructions: "Pray once with your hands outstretched or placed on the person if present. Mention their name and specific needs.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.SURGERY, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "prayer-serenity",
    name: "Serenity Prayer",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A widely loved prayer asking God for the grace to accept what we cannot change, courage to change what we can, and wisdom to know the difference.",
    prayerText: "God, grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference. Living one day at a time, enjoying one moment at a time; accepting hardship as a pathway to peace; taking, as Jesus did, this sinful world as it is, not as I would have it; trusting that You will make all things right if I surrender to Your will; so that I may be reasonably happy in this life and supremely happy with You forever in the next. Amen.",
    instructions: "Pray slowly and reflectively, pausing at each phrase.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.MENTAL_HEALTH, SituationCategory.GRIEF, SituationCategory.FINANCIAL, SituationCategory.CAREER],
  },
  {
    slug: "prayer-st-francis",
    name: "Peace Prayer of St. Francis",
    category: PrayerCategory.SHORT_PRAYER,
    description: "An inspiring prayer seeking to be an instrument of God's peace, attributed to the spirit of St. Francis of Assisi.",
    prayerText: "Lord, make me an instrument of Your peace: where there is hatred, let me sow love; where there is injury, pardon; where there is doubt, faith; where there is despair, hope; where there is darkness, light; where there is sadness, joy. O divine Master, grant that I may not so much seek to be consoled as to console, to be understood as to understand, to be loved as to love. For it is in giving that we receive, it is in pardoning that we are pardoned, and it is in dying that we are born to eternal life. Amen.",
    instructions: "Pray once daily, asking God to help you be an instrument of peace in the life of the person you're praying for.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Francis of Assisi",
    feastDay: "October 4",
    situationTags: [SituationCategory.FAMILY, SituationCategory.MARRIAGE, SituationCategory.MENTAL_HEALTH, SituationCategory.GRIEF],
  },
  {
    slug: "anima-christi",
    name: "Anima Christi",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A medieval Eucharistic prayer beloved by St. Ignatius of Loyola. A beautiful prayer of union with Christ, especially after Communion.",
    prayerText: "Soul of Christ, sanctify me. Body of Christ, save me. Blood of Christ, inebriate me. Water from the side of Christ, wash me. Passion of Christ, strengthen me. O good Jesus, hear me. Within Thy wounds hide me. Suffer me not to be separated from Thee. From the malicious enemy defend me. In the hour of my death call me and bid me come unto Thee, that with Thy saints I may praise Thee forever and ever. Amen.",
    instructions: "Pray with devotion, especially after receiving Holy Communion or during a visit to the Blessed Sacrament.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Ignatius of Loyola",
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.SURGERY, SituationCategory.GENERAL],
  },
  {
    slug: "guardian-angel-prayer",
    name: "Guardian Angel Prayer",
    category: PrayerCategory.SHORT_PRAYER,
    description: "The classic prayer to one's guardian angel, asking for guidance, protection, and light on the path of life.",
    prayerText: "Angel of God, my guardian dear, to whom God's love commits me here, ever this day be at my side, to light and guard, to rule and guide. Amen.",
    instructions: "Pray with trust, asking your guardian angel to also watch over the person you are praying for.",
    duration: 1,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: "October 2",
    situationTags: [SituationCategory.GENERAL, SituationCategory.ILLNESS, SituationCategory.SURGERY],
  },
  {
    slug: "prayer-expectant-mothers",
    name: "Prayer for Expectant Mothers",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A tender prayer for mothers awaiting the birth of their child, asking for a safe pregnancy, healthy baby, and the grace of motherhood.",
    prayerText: "O Blessed Mother, you received the good news of the incarnation of Christ, your Son, with faith and trust. Grant your comfort to all women as they await the birth of their child. They are anxious as they wait for the arrival of their baby. Calm their fears and strengthen their faith in God's loving providence. Help them to feel the peace of your loving arms around them as they wait for the miracle of new life. We ask this through Christ our Lord. Amen.",
    instructions: "Pray once daily for the expectant mother, asking Mary to comfort and protect both mother and child.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "Our Lady",
    feastDay: null,
    situationTags: [SituationCategory.PREGNANCY],
  },
  {
    slug: "prayer-fertility",
    name: "Prayer for the Gift of a Child",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A prayer for couples struggling with infertility, asking God through the intercession of Sts. Joachim and Anne for the gift of new life.",
    prayerText: "Lord God, Creator of all life, we humbly ask You to bless this couple with the gift of a child. You blessed Abraham and Sarah, Elizabeth and Zechariah, and Joachim and Anne with children in their waiting. We trust in Your divine plan and perfect timing. Grant them patience in their waiting, comfort in their sorrow, and hope in Your promises. Through the intercession of Sts. Joachim and Anne, hear our prayer. Amen.",
    instructions: "Pray once daily, trusting in God's timing and plan for the couple.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "Sts. Joachim and Anne",
    feastDay: "July 26",
    situationTags: [SituationCategory.FERTILITY],
  },

  // ─── MASS & SACRAMENTAL ────────────────────────────────────
  {
    slug: "mass-offering",
    name: "Offer a Mass",
    category: PrayerCategory.MASS_SACRAMENTAL,
    description: "The highest prayer of the Church. Having a Mass offered for someone's intention is the most powerful spiritual gift you can give.",
    instructions: "Contact your parish office and request a Mass be offered for the person's intention. A small stipend (typically $5-20) is customary. You may attend the Mass and offer your prayers during it.",
    prayerText: null,
    duration: 60,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.SURGERY, SituationCategory.GENERAL, SituationCategory.CONVERSION],
  },
  {
    slug: "adoration-hour",
    name: "Holy Hour of Adoration",
    category: PrayerCategory.MASS_SACRAMENTAL,
    description: "Spending an hour in the presence of the Blessed Sacrament, praying for a specific intention. Jesus asked His apostles to watch one hour with Him.",
    instructions: "Visit your parish during Adoration hours (check your parish schedule). Spend one hour in prayer before the Blessed Sacrament. You may pray the Rosary, read Scripture, journal, or simply sit in silent communion with the Lord, offering all for the person's intention.",
    prayerText: null,
    duration: 60,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.DISCERNMENT, SituationCategory.CONVERSION, SituationCategory.GRIEF, SituationCategory.GENERAL],
  },
  {
    slug: "stations-of-the-cross",
    name: "Stations of the Cross",
    category: PrayerCategory.MASS_SACRAMENTAL,
    description: "Walking with Christ through His Passion in fourteen stations, offering the sufferings of Jesus for the intentions of those who are suffering.",
    instructions: "Visit a church with Stations displayed, or pray at home using a guide. At each station: genuflect, announce the station, meditate on the scene, pray an Our Father, Hail Mary, and Glory Be, then offer the station for your intention.",
    prayerText: "We adore You, O Christ, and we bless You, because by Your holy Cross You have redeemed the world.",
    duration: 30,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: null,
    feastDay: "Good Friday",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.SURGERY, SituationCategory.MENTAL_HEALTH],
  },

  // ─── SCRIPTURE-BASED ────────────────────────────────────────
  {
    slug: "psalm-23",
    name: "Psalm 23 - The Lord is My Shepherd",
    category: PrayerCategory.SCRIPTURE,
    description: "The most beloved psalm of comfort and trust, assuring us that the Lord guides and protects us even through the valley of the shadow of death.",
    prayerText: "The Lord is my shepherd; I shall not want. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul. He leads me in paths of righteousness for His name's sake. Even though I walk through the valley of the shadow of death, I will fear no evil, for You are with me; Your rod and Your staff, they comfort me. You prepare a table before me in the presence of my enemies; You anoint my head with oil; my cup overflows. Surely goodness and mercy shall follow me all the days of my life, and I shall dwell in the house of the Lord forever.",
    instructions: "Read the psalm slowly and meditatively, perhaps reading it three times. First for understanding, second to savor the words, third to let them become your prayer for the person.",
    duration: 5,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.SURGERY, SituationCategory.MENTAL_HEALTH, SituationCategory.GENERAL],
  },
  {
    slug: "psalm-91",
    name: "Psalm 91 - Under the Shadow of the Almighty",
    category: PrayerCategory.SCRIPTURE,
    description: "A psalm of divine protection, promising that God shelters those who trust in Him from plague, terror, and harm.",
    prayerText: "He who dwells in the shelter of the Most High will rest in the shadow of the Almighty. I will say of the Lord, 'He is my refuge and my fortress, my God, in whom I trust.' Surely He will save you from the fowler's snare and from the deadly pestilence. He will cover you with His feathers, and under His wings you will find refuge; His faithfulness will be your shield and rampart.",
    instructions: "Pray the full psalm meditatively, inserting the name of the person you are praying for. You may also write out the psalm as a form of prayer.",
    duration: 5,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.SURGERY, SituationCategory.MENTAL_HEALTH, SituationCategory.GENERAL],
  },
  {
    slug: "lectio-divina",
    name: "Lectio Divina",
    category: PrayerCategory.SCRIPTURE,
    description: "An ancient monastic practice of prayerful Scripture reading in four steps: read, meditate, pray, and contemplate. Transform your Bible reading into deep prayer.",
    instructions: "Choose a Scripture passage. 1) Lectio (Read): Read slowly 2-3 times. 2) Meditatio (Meditate): What word or phrase stands out? 3) Oratio (Pray): Speak to God about what struck you, offering it for your intention. 4) Contemplatio (Contemplate): Rest in God's presence in silence. Recommended passages for healing: James 5:13-16, Matthew 11:28-30, Isaiah 41:10.",
    prayerText: null,
    duration: 20,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 1,
    patronSaint: "St. Benedict",
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.DISCERNMENT, SituationCategory.MENTAL_HEALTH, SituationCategory.GENERAL],
  },

  // ─── DEVOTIONS ──────────────────────────────────────────────
  {
    slug: "morning-offering",
    name: "Morning Offering",
    category: PrayerCategory.DEVOTION,
    description: "Offer your entire day — joys, works, sufferings — for the intentions of the person in need. Transforms ordinary moments into powerful intercession.",
    prayerText: "O Jesus, through the Immaculate Heart of Mary, I offer You my prayers, works, joys, and sufferings of this day for all the intentions of Your Sacred Heart, in union with the Holy Sacrifice of the Mass throughout the world, in thanksgiving for Your favors, in reparation for my sins, for the intentions of all my associates, and in particular for (mention the person's name and intention). Amen.",
    instructions: "Pray first thing in the morning, offering every moment of your day for the person's intention. Throughout the day, recall your offering and unite your actions to it.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.GENERAL, SituationCategory.ILLNESS, SituationCategory.FAMILY, SituationCategory.CAREER],
  },
  {
    slug: "offering-suffering",
    name: "Offering Up Suffering",
    category: PrayerCategory.DEVOTION,
    description: "The Catholic practice of uniting one's own suffering with Christ's on the Cross, offering it for the good of another. Transforms pain into powerful prayer.",
    prayerText: "Lord Jesus, I unite my sufferings to Yours on the Cross. I offer this pain, this difficulty, this trial for the intention of (name). May my small share in Your suffering bring grace and healing to those for whom I pray. I trust that nothing is wasted in Your economy of salvation. Amen.",
    instructions: "When you experience physical pain, emotional difficulty, or any hardship during the day, pause and consciously offer it to God for the person's intention.",
    duration: 1,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.MENTAL_HEALTH, SituationCategory.SURGERY],
  },
  {
    slug: "three-oclock-prayer",
    name: "Three O'Clock Prayer (Hour of Mercy)",
    category: PrayerCategory.DEVOTION,
    description: "Jesus told St. Faustina that 3:00 PM is the Hour of Great Mercy. A brief prayer at this hour obtains extraordinary graces.",
    prayerText: "You expired, Jesus, but the source of life gushed forth for souls, and the ocean of mercy opened up for the whole world. O Fount of Life, unfathomable Divine Mercy, envelop the whole world and empty Yourself out upon us. O Blood and Water, which gushed forth from the Heart of Jesus as a fount of mercy for us, I trust in You! Holy God, Holy Mighty One, Holy Immortal One, have mercy on us and on the whole world. (3x)",
    instructions: "At 3:00 PM each day, pause briefly to pray. Even a moment of prayer at this hour is powerful. You may pray the Chaplet of Divine Mercy or simply this short prayer.",
    duration: 3,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Faustina Kowalska",
    feastDay: null,
    situationTags: [SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.GENERAL, SituationCategory.SURGERY],
  },
  {
    slug: "surrender-novena",
    name: "Surrender Novena",
    category: PrayerCategory.NOVENA,
    description: "Based on the words of Don Dolindo Ruotolo: 'O Jesus, I surrender myself to You, take care of everything.' A novena of radical trust and abandonment to God's will.",
    instructions: "Pray once daily for nine consecutive days. Each day has a unique meditation on a different aspect of surrender. After reading the day's meditation, close by repeating the refrain ten times: 'O Jesus, I surrender myself to You, take care of everything!'",
    prayerText: "O Jesus, I surrender myself to You, take care of everything!\n\n(Repeat ten times.)",
    // Per-day meditations from Don Dolindo Ruotolo's "Novena di
    // Abbandono." Operator (William) sourced and approved this
    // specific wording May 6 2026; queued for retroactive review with
    // Fr. Palladino (theology-review.md item #14). Light copy
    // normalization applied (curly quotes -> straight ASCII; en-dashes
    // softened to commas in Day 6 for parser-friendliness).
    //
    // Render is empty-gated everywhere — when this array is empty
    // (legacy rows, other novenas), the chain page and email fall
    // through to prayerText. With nine entries here, the chain page
    // shows a "Day N reflection" card above the refrain, and the
    // chain daily reminder email mirrors that block.
    dailyReflections: [
      "Why do you confuse yourselves by worrying? Leave the care of your affairs to me and everything will be peaceful. I say to you in truth that every act of true, blind, complete surrender to me produces the effect that you desire and resolves all difficult situations.",
      "Surrender to me does not mean to fret, to be upset, or to lose hope, nor does it mean offering to me a worried prayer asking me to follow you and change your worry into prayer. It is against this surrender, deeply against it, to worry, to be nervous and to desire to think about the consequences of anything.\n\nIt is like the confusion that children feel when they ask their mother to see to their needs, and then try to take care of those needs for themselves so that their childlike efforts get in their mother's way. Surrender means to placidly close the eyes of the soul, to turn away from thoughts of tribulation and to put yourself in my care, so that only I act, saying, 'You take care of it.'",
      "How many things I do when the soul, in so much spiritual and material need, turns to me, looks at me and says to me, 'You take care of it,' then closes its eyes and rests. In pain you pray for me to act, but that I act in the way you want. You do not turn to me, instead, you want me to adapt your ideas. You are not sick people who ask the doctor to cure you, but rather sick people who tell the doctor how to. So do not act this way, but pray as I taught you in the Our Father: 'Hallowed be thy Name,' that is, be glorified in my need. 'Thy kingdom come,' that is, let all that is in us and in the world be in accord with your kingdom. 'Thy will be done on Earth as it is in Heaven,' that is, in our need, decide as you see fit for our temporal and eternal life. If you say to me truly: 'Thy will be done,' which is the same as saying: 'You take care of it,' I will intervene with all my omnipotence, and I will resolve the most difficult situations.",
      "You see evil growing instead of weakening? Do not worry. Close your eyes and say to me with faith: 'Thy will be done, You take care of it.' I say to you that I will take care of it, and that I will intervene as does a doctor and I will accomplish miracles when they are needed. Do you see that the sick person is getting worse? Do not be upset, but close your eyes and say, 'You take care of it.' I say to you that I will take care of it, and that there is no medicine more powerful than my loving intervention. By my love, I promise this to you.",
      "And then I must lead you on a path different from the one you see, I will prepare you; I will carry you in my arms; I will let you find yourself, like children who have fallen asleep in their mother's arms, on the other bank of the river. What troubles you and hurts you immensely are your reason, your thoughts and worry, and your desire at all costs to deal with what afflicts you.",
      "You are sleepless; you want to judge everything, direct everything and see to everything and you surrender to human strength, or worse, to men themselves, trusting in their intervention. This is what hinders my words and my views. Oh, how much I wish from you this surrender, to help you; and how I suffer when I see you so agitated! Satan tries to do exactly this: to agitate you and to remove you from my protection and to throw you into the jaws of human initiative. So, trust only in me, rest in me, surrender to me in everything.",
      "I perform miracles in proportion to your full surrender to me and to your not thinking of yourselves. I sow treasure troves of graces when you are in deepest poverty. No person of reason, no thinker, has ever performed miracles, not even among the saints. He does divine works whosoever surrenders to God. So don't think about it any more, because your mind is acute and for you it is very hard to see evil and to trust in me and to not think of yourself. Do this for all your needs, do this, all of you, and you will see great continual silent miracles. I will take care of things, I promise this to you.",
      "Close your eyes and let yourself be carried away on the flowing current of my grace; close your eyes and do not think of the present, turning your thoughts away from the future just as you would from temptation. Repose in me, believing in my goodness, and I promise you by my love that if you say, 'You take care of it,' I will take care of it all; I will console you, liberate you and guide you.",
      "Pray always in readiness to surrender, and you will receive from it great peace and great rewards, even when I confer on you the grace of immolation, of repentance, and of love. Then what does suffering matter? It seems impossible to you? Close your eyes and say with all your soul, 'Jesus, you take care of it.' Do not be afraid, I will take care of things and you will bless my name by humbling yourself. A thousand prayers cannot equal one single act of surrender, remember this well. There is no novena more effective than this.",
    ],
    duration: 10,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "Don Dolindo Ruotolo",
    feastDay: null,
    situationTags: [SituationCategory.MENTAL_HEALTH, SituationCategory.FINANCIAL, SituationCategory.ILLNESS, SituationCategory.GRIEF, SituationCategory.DISCERNMENT],
  },
  {
    slug: "prayer-marriage",
    name: "Prayer for a Marriage",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A prayer for married couples experiencing difficulty, asking God to strengthen the bond of love and restore unity.",
    prayerText: "Lord Jesus, You blessed the wedding at Cana with Your presence and Your first miracle. We ask You to bless this marriage with Your grace. Strengthen the bond of love between husband and wife. Help them to forgive as You forgive, to love as You love, and to serve each other as You serve us. When trials come, let them lean on You and on each other. Restore what is broken, heal what is wounded, and renew what has grown weary. Through the intercession of the Holy Family, protect and sanctify this marriage. Amen.",
    instructions: "Pray daily for the couple, asking God to strengthen and heal their marriage.",
    duration: 3,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "Holy Family",
    feastDay: null,
    situationTags: [SituationCategory.MARRIAGE],
  },
  {
    slug: "prayer-financial-hardship",
    name: "Prayer in Financial Hardship",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A prayer asking God's providence in times of financial difficulty, trusting in the One who feeds the birds of the air and clothes the lilies of the field.",
    prayerText: "Heavenly Father, You know our needs before we ask. You feed the birds of the air and clothe the lilies of the field. We trust in Your providence as we face this financial difficulty. Grant us wisdom in our decisions, patience in our waiting, and hope in Your promises. Help us to be good stewards of whatever You provide. Through the intercession of St. Joseph the Worker, open doors of opportunity and provision. We trust in You. Amen.",
    instructions: "Pray daily, surrendering financial worries to God and asking for His guidance and provision.",
    duration: 2,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Joseph the Worker",
    feastDay: "May 1",
    situationTags: [SituationCategory.FINANCIAL],
  },
  {
    slug: "prayer-conversion",
    name: "Prayer for Conversion of a Loved One",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A prayer for someone who has fallen away from the faith or does not yet know Christ, asking for the grace of conversion.",
    prayerText: "Lord Jesus, Good Shepherd, You seek out the lost sheep and carry them home on Your shoulders. We pray for (name), who is far from You. Send Your Holy Spirit to touch their heart. Remove every obstacle that keeps them from You. Open their eyes to Your love, their ears to Your voice, and their heart to Your mercy. Through the intercession of St. Monica, who prayed for years for her son Augustine's conversion, grant us perseverance in prayer and trust in Your timing. We place them in Your Sacred Heart. Amen.",
    instructions: "Pray daily with perseverance, remembering that St. Monica prayed for 17 years for her son's conversion. Trust in God's timing.",
    duration: 3,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: "St. Monica",
    feastDay: "August 27",
    situationTags: [SituationCategory.CONVERSION],
  },
  {
    slug: "prayer-discernment",
    name: "Prayer for Discernment",
    category: PrayerCategory.SHORT_PRAYER,
    description: "A prayer asking the Holy Spirit for clarity and guidance in making an important life decision.",
    prayerText: "Come, Holy Spirit, source of all light. Shed Your radiance on this decision that lies before me. Grant me wisdom to see clearly, courage to choose rightly, and strength to follow through. Quiet the noise of my own desires and fears, that I may hear Your still, small voice. Through the intercession of Our Lady, Seat of Wisdom, guide me in the path You have prepared. I trust not in my own understanding, but in You alone. Amen.",
    instructions: "Pray daily, and spend time in silence after praying, listening for the movements of the Holy Spirit.",
    duration: 3,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 1,
    patronSaint: null,
    feastDay: null,
    situationTags: [SituationCategory.DISCERNMENT, SituationCategory.CAREER],
  },

  // ─── LOCALE-ANCHORED DEVOTIONS ──────────────────────────────
  // Catholic devotions central to the four non-English locales
  // PrayerTrain supports (es, pt-BR, fil, pl). English base content
  // here; locale-native translations land via PrayerTypeTranslation
  // (Phase ε editorial work).

  {
    slug: "novena-guadalupe",
    name: "Novena to Our Lady of Guadalupe",
    category: PrayerCategory.NOVENA,
    description: "Our Lady of Guadalupe is the central Marian devotion of the Spanish-speaking Catholic world and one of the most powerful Marian apparitions in the Church's history. On December 9, 1531 — ten years after the Spanish conquest of Mexico, in a moment of profound cultural and spiritual upheaval — the Blessed Virgin Mary appeared on the hill of Tepeyac to St. Juan Diego Cuauhtlatoatzin, a recently-converted Nahua peasant. Speaking in his native Nahuatl, Mary identified herself as 'la perfecta siempre Virgen Santa María, Madre del verdaderísimo Dios' and asked that a church be built on the hill. After the local bishop, Juan de Zumárraga, requested a sign, Mary instructed Juan Diego on December 12 to gather roses from the frozen hilltop and carry them in his tilma (cloak) to the bishop. When Juan Diego opened the tilma before the bishop, the roses tumbled out and an image of Mary appeared miraculously imprinted on the cloth — a young pregnant woman in indigenous dress, wearing the maternity sash of Nahua custom, surrounded by sunburst rays and standing on a crescent moon, an angel at her feet. This is the image preserved to this day in the Basilica of Our Lady of Guadalupe in Mexico City, one of the most-visited Catholic shrines in the world. The narrative — known as the Nican Mopohua, recorded in Nahuatl shortly after the events — has been studied by historians, scientists, and pilgrims for nearly five centuries; the tilma's preservation defies natural explanation (it should have decomposed within twenty years but remains intact after 490). Pope St. John Paul II canonized Juan Diego in 2002 in the Basilica itself, becoming the first canonization of an indigenous American. Mary is honored as Empress of the Americas, Patroness of the unborn, and the Star of the New Evangelization. The devotion has profound resonance in Mexico, throughout Latin America, and in the US Hispanic Catholic community, and is particularly invoked for pregnancy, the protection of children, and the conversion of cultures.",
    prayerText: "Most Holy Virgin of Guadalupe, Patroness of the Americas, we entrust ourselves and our families to your maternal protection. You appeared to St. Juan Diego on the hill of Tepeyac and gave him a sign of your love — your image imprinted on his tilma. You said: 'Am I not here, who am your Mother? Are you not under my shadow and protection?' Grant us today the grace to trust in those words. Watch over (mention your intention). Protect mothers in their pregnancy, children in their innocence, families in their unity. Convert our hearts to your Son Jesus Christ. As you stood at the foot of His Cross, stand now at the foot of every cross we carry. We ask this through Christ our Lord. Amen.",
    instructions: "Pray once daily for nine consecutive days. The novena is traditionally prayed in the nine days leading up to the Feast of Our Lady of Guadalupe (December 12), beginning December 3. Mañanitas — the traditional pre-dawn serenade with song and prayer — are sung at parishes throughout Latin America and the US Hispanic Catholic community on the evening of December 11 into the morning of December 12. The novena structure: (1) Sign of the Cross; (2) Read the day's brief reflection from the Nican Mopohua (the original Nahuatl account of the apparition); (3) Pray the novena prayer text; (4) Pray three Hail Marys; (5) Name your specific intention. Many families gather around a household image of Our Lady of Guadalupe (often placed on a small home altar) and pray the novena together. The novena is appropriate for pregnancy and the protection of unborn children (Mary is shown pregnant in the tilma); the conversion of family members; protection of immigrants and those displaced; healing of cultural or familial wounds; and any moment of personal or communal crisis. The Pilgrimage to the Basilica de Guadalupe in Mexico City, especially on December 12 itself, draws millions of pilgrims annually. The Mañanitas singing at 4:00 AM on December 12 — broadcast nationally in Mexico and increasingly in US Hispanic communities — is one of the most touching popular-Catholic devotions in the world.",
    duration: 15,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "Our Lady of Guadalupe, Empress of the Americas",
    feastDay: "December 12",
    situationTags: [SituationCategory.PREGNANCY, SituationCategory.FAMILY, SituationCategory.CONVERSION, SituationCategory.ILLNESS, SituationCategory.GENERAL],
  },
  {
    slug: "novena-aparecida",
    name: "Novena to Our Lady of Aparecida",
    category: PrayerCategory.NOVENA,
    description: "Nossa Senhora Aparecida (Our Lady of Aparecida, or Our Lady Who Appeared) is the Principal Patroness of Brazil and the central Marian devotion of the world's largest Catholic country. The origin story belongs to October 1717 on the Paraíba do Sul River in the small fishing town of Guaratinguetá, São Paulo state. Three local fishermen — Domingos Garcia, João Alves, and Filipe Pedroso — had been ordered by the village to provide fish for a visiting dignitary, the Count of Assumar, but had caught nothing all day. After hours of fruitless work, João Alves cast his net once more and brought up the headless body of a terracotta statue of the Immaculate Conception. Casting again, he brought up the head. The men joined the pieces, prayed for the Virgin's intercession, and cast their nets a final time — pulling up a miraculous catch of fish so abundant that their canoes nearly sank. The small dark-clay statue (originally light brown, the river's iron-rich waters had darkened it) was taken home by Filipe Pedroso and venerated in his household for fifteen years; reports of healings and intercessions spread, and a small chapel was built in 1745. The devotion grew rapidly through Portuguese colonial Brazil and into the independent Brazilian Empire. Pope St. Pius X declared Nossa Senhora Aparecida the Principal Patroness of Brazil in 1930. Her feast (October 12) was elevated to a Brazilian national holiday in 1980 by President João Figueiredo at the request of Pope St. John Paul II during his first Brazilian pilgrimage. The current Basilica de Nossa Senhora Aparecida — completed in 1980 — is the world's second-largest Catholic church after St. Peter's in Rome, and one of the most-visited Marian shrines in the world. The Brazilian Catholic Bishops' Conference (CNBB) approves the standard novena text used worldwide.",
    prayerText: "Most Holy Virgin Mary, Our Lady of Aparecida, you who appeared to the humble fishermen on the waters of the Paraíba and filled their nets with a miraculous catch, look upon us with the same maternal love. We are poor fishermen too, casting our nets again and again into the waters of life, sometimes hauling them up empty. Grant us your intercession in our present need (mention your intention). Strengthen our faith in moments of doubt. Bring unity to our families. Protect Brazil, your land, and all your children throughout the world. Through Christ our Lord. Amen.",
    instructions: "Pray once daily for nine consecutive days. The novena is traditionally prayed in the nine days leading up to the Feast of Nossa Senhora Aparecida (October 12), the Brazilian national patronal holiday. In Brazil, the feast day is observed with: (a) the celebration of Holy Mass at the Basilica in Aparecida, broadcast nationally by Rede Vida and Canção Nova; (b) the singing of the traditional hymn 'A treze de maio, na cova da Iria' and 'Nossa Senhora Aparecida' across parishes nationwide; (c) family gatherings featuring the traditional Brazilian Catholic meal of fish (in remembrance of the fishermen's miraculous catch); (d) home altars displaying the dark-clay image of Aparecida often crowned with a small white veil. The novena structure at home: (1) Sign of the Cross; (2) Read a brief reflection on the apparition or on a related Brazilian saint (Frei Galvão, Padre Cícero, Mother Paulina); (3) Pray the novena prayer text; (4) Three Hail Marys; (5) Name the specific intention. Brazilian Catholics commonly pray the Aparecida novena for: healing of the sick; protection of the family; safe travel (the Basilica is a major pilgrimage destination); the conversion of distant family members; and during times of national difficulty. The devotion is also strong in the Brazilian diaspora — in the United States, the Brazilian apostolate of the Archdiocese of Newark and the Brazilian Catholic communities of Boston, Miami, and Massachusetts maintain Aparecida processions on October 12.",
    duration: 12,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "Nossa Senhora Aparecida (Our Lady of Aparecida)",
    feastDay: "October 12",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.FAMILY, SituationCategory.PREGNANCY, SituationCategory.GENERAL, SituationCategory.GRIEF],
  },
  {
    slug: "novena-santo-nino",
    name: "Novena to the Santo Niño (Holy Child of Cebu)",
    category: PrayerCategory.NOVENA,
    description: "The Santo Niño de Cebú (Holy Child of Cebu) is the central icon of Filipino Catholic identity and the oldest Christian image in the Philippines. The story belongs to the moment Christianity entered the archipelago: in 1521, the Portuguese explorer Ferdinand Magellan — sailing under the Spanish crown — landed on the island of Cebu and presented a small wooden statue of the Christ Child to Queen Juana, the consort of Rajah Humabon, on the occasion of her baptism on April 14, 1521. Juana, the first Filipino Christian queen, received the image with deep affection, and Magellan's chronicler Antonio Pigafetta records her tears at the gift. When Spanish missionaries returned to Cebu in 1565 under Miguel López de Legazpi — forty-four years after Magellan's death at the Battle of Mactan — they found the image preserved in a small house, still venerated by the local people who had kept the devotion alive across the intervening decades. The Basilica Minore del Santo Niño in Cebu City was built around the recovered image and is the oldest church in the Philippines. Today the Santo Niño is the most venerated Catholic image in the Philippines and the patronal devotion of the country. The annual Sinulog Festival — held on the third Sunday of January in Cebu City — is the largest Catholic celebration in Asia, drawing millions of pilgrims and featuring days of processions, masses, and the distinctive Sinulog dance ('one step forward, two steps back') in which dancers move with the rhythm of the river current. The devotion extends across the entire Filipino diaspora: every major Filipino-American parish maintains a Santo Niño image, and the third Sunday of January is observed with processions in Daly City, Honolulu, Las Vegas, Jersey City, and dozens of other Filipino-Catholic communities. The Catholic Bishops' Conference of the Philippines (CBCP) approves the standard novena text. The devotion is particularly invoked for: the protection of children; family healing; safe travel (the Santo Niño image of Magellan crossed oceans); and any moment in which a soul needs to recover the childlike trust that Jesus called for in the Gospel.",
    prayerText: "Most loving Santo Niño, Child Jesus of Cebu, we come before You as little children — as You said we must come to enter the kingdom of heaven. You received the love of Queen Juana on the day of her baptism and watched over the Filipino people through four centuries of trial and joy. Watch over us now in our need (mention your intention). Bless our families, protect our children, give us the joy that only You can give. Through Your tiny hands, distribute the graces of the Father. Sinulog ka, Santo Niño — we dance for You, we sing for You, we trust in You. Through Christ our Lord, Your eternal Self. Amen.",
    instructions: "Pray once daily for nine consecutive days. The novena is traditionally prayed in the nine days leading up to the Feast of the Santo Niño (the third Sunday of January, the climactic day of the Sinulog Festival in Cebu City). In Filipino tradition, the novena is often prayed in connection with: (a) a Santo Niño image displayed prominently in the home — many Filipino-Catholic households maintain a Santo Niño altar with the Child Jesus in royal robes, sometimes dressed in the colors of the season or a personal devotion; (b) attendance at parish-wide novena Masses (a nine-day Mass series, very popular in the Philippines and Filipino-American parishes); (c) the singing of traditional Cebuano and Tagalog Santo Niño hymns ('Bato Balani sa Gugma' — 'Magnet of Love' — is the most beloved); (d) for many devotees, joining the Sinulog dance during the procession on the third Sunday of January, dancing 'one step forward, two steps back' in the current of the river of grace. The Filipino devotional tradition includes both Tagalog and Cebuano forms of the novena. The novena is appropriate for: family healing; the protection of children (the Santo Niño is the patron of children); preparation for or recovery from baptism; the conversion of estranged family members; safe travel; and any difficult moment in which the soul needs to recover the childlike trust Christ asks of us (Matthew 18:3). Many Filipino-Catholic families pray a brief Santo Niño aspiration daily — 'Viva Santo Niño!' or 'Pit Señor, Sinulog ka!' — as a moment of joyful confidence threaded through ordinary life.",
    duration: 12,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "Santo Niño (Holy Infant of Cebu)",
    feastDay: "Third Sunday of January (Sinulog Festival)",
    situationTags: [SituationCategory.FAMILY, SituationCategory.ILLNESS, SituationCategory.PREGNANCY, SituationCategory.GENERAL, SituationCategory.MENTAL_HEALTH],
  },
  {
    slug: "simbang-gabi",
    name: "Simbang Gabi (Dawn Masses Before Christmas)",
    category: PrayerCategory.DEVOTION,
    description: "Simbang Gabi (Tagalog for 'Night Mass') — also called Misa de Gallo (Spanish, 'Mass of the Rooster') in older Filipino Spanish-language tradition — is a uniquely Filipino Catholic Advent devotion consisting of nine consecutive dawn Masses celebrated from December 16 through December 24, immediately preceding Christmas Day. The origin lies in the early Spanish missionary period in the Philippines (late 16th century): Spanish friars, recognizing that the agricultural rhythms of Filipino farming communities meant that workers were in the fields before dawn each day, secured Vatican permission to celebrate the Advent Mass at first light — between 3:00 and 5:00 AM — so that workers could attend before the day's labor began. Pope Sixtus V formally granted the privilege of pre-dawn Advent Mass in the Philippines in 1587. The novena pattern (nine days, paralleling the nine months of Mary's pregnancy with Christ) attached to the devotion, and the popular tradition arose that completing all nine Masses — without missing one — earns a special intention from the Christ Child whose birth is being awaited. Today Simbang Gabi remains the most beloved Filipino Catholic Christmas tradition, observed across the Philippines and in the global Filipino diaspora. In the Philippines, parish churches fill before dawn each day from December 16-24; the after-Mass tradition includes the eating of bibingka (a coconut-milk rice cake cooked in clay pots over coals) and puto bumbong (steamed purple rice in bamboo tubes), sold by vendors outside the church. In the United States, the United States Conference of Catholic Bishops (USCCB) granted formal liturgical recognition to Simbang Gabi in 1989; Masses are celebrated each evening in Filipino-American parishes from December 15-23 (anticipated Masses, accommodating American work schedules). The devotion is one of the few Filipino-Catholic devotions formally recognized by the universal Church liturgy and remains a powerful catechetical and cultural anchor for the Filipino Catholic community worldwide.",
    prayerText: "Lord Jesus Christ, we await Your coming in the silence before dawn — as Your Mother Mary awaited Your birth, as the shepherds watched their flocks by night, as the prophets longed for the Day-Spring from on high. Through these nine days of Simbang Gabi, prepare our hearts for the great feast of Your Nativity. Forgive what is past; renew us in faith; let us behold You in the manger with the joy of children. We offer these nine Masses for (mention your intention). Through Your coming as the Christ Child, save us. Through Mary, our Mother, intercede for us. We adore You, Lord Jesus, who came and who will come again. Amen.",
    instructions: "Attend Holy Mass on each of nine consecutive days, from December 16 through December 24. In the Philippines, the Masses are celebrated before dawn (traditionally 4:00 AM); in the Filipino-American diaspora, evening Masses on December 15-23 (anticipated, fulfilling the same nine-day novena) are the norm. The pattern: (1) Arrive at the parish church in time for the Mass (often this means rising at 3:00 AM in the Philippines, walking through the dark streets to the parish); (2) Receive the Sacraments — Confession during Advent is part of the preparation; (3) After Mass, share fellowship and traditional Filipino Christmas foods (bibingka, puto bumbong, salabat ginger tea) with the parish community; (4) Carry the day's intention silently through the morning. Many Filipinos commit to praying for a specific intention through all nine Masses, with the traditional belief that completing the full novena earns a special grace from the Christ Child. For Filipino-American families, Simbang Gabi is often the most important catechetical link to the homeland — children learn the rhythms, foods, and prayers of Filipino Catholic culture by attending alongside parents and grandparents. Parishes typically rotate which evening they host the Mass, allowing devotees to travel to different Filipino-American parishes across a metropolitan area through the nine evenings. The devotion is appropriate for: any sustained intention requiring nine days of preparation; the conversion of family members; healing of grief during the difficult Christmas-without-a-loved-one period; preparation of one's own heart for Christmas; and the maintenance of Filipino Catholic identity across generations in the diaspora.",
    duration: 60,
    difficulty: DifficultyLevel.INTERMEDIATE,
    daysRequired: 9,
    patronSaint: null,
    feastDay: "December 16-24 (nine days before Christmas)",
    situationTags: [SituationCategory.FAMILY, SituationCategory.CONVERSION, SituationCategory.GRIEF, SituationCategory.GENERAL, SituationCategory.DISCERNMENT],
  },
  {
    slug: "novena-czestochowa",
    name: "Novena to Our Lady of Częstochowa",
    category: PrayerCategory.NOVENA,
    description: "Matka Boża Częstochowska — Our Lady of Częstochowa, the Black Madonna — is the central Marian devotion of Polish Catholicism and the icon at the heart of Polish national identity. The image, an icon of Mary holding the Child Jesus painted on cypress wood, is enshrined at the Jasna Góra monastery in Częstochowa, Poland. Tradition attributes the icon's painting to St. Luke the Evangelist; modern art-historical analysis dates the current panel to the late Middle Ages, though it may incorporate earlier work. The icon arrived at Jasna Góra in 1382, brought from Belz by Prince Władysław Opolczyk as a gift to the newly-founded Pauline monastery. The Black Madonna received her formal title and Marian crown in 1717 by papal decree. The two parallel scratches across Mary's right cheek — the icon's most recognizable feature — date to 1430, when Hussite raiders pillaged the monastery and slashed the panel; tradition holds that the image bled, terrifying the attackers into fleeing. The icon became central to Polish national consciousness during the Swedish 'Deluge' of 1655: when virtually all of Poland fell to Swedish Protestant forces, the small monastery of Jasna Góra alone held out — a tiny band of Pauline monks and Polish soldiers defending it through a six-week siege. The Swedes withdrew, and King John II Casimir formally proclaimed Mary the Queen of Poland in Lwów Cathedral in 1656, entrusting the nation to her protection. Pope Pius XI granted the icon a canonical coronation as Queen of Poland in 1717 and 1923. Through centuries of Polish partition, occupation, communist suppression, and renewal, the Black Madonna has been the spiritual heart of Polish Catholic identity. Pope St. John Paul II, born Karol Wojtyła in 1920, made multiple pilgrimages to Jasna Góra both before and after his election; his devotion to Our Lady of Częstochowa is the heart of his Marian theology. Jasna Góra remains the most-visited Catholic pilgrimage site in Poland and one of the most important Marian shrines in the world.",
    prayerText: "Most Holy Mother of God, Mary of Częstochowa, Queen of Poland and Mother of all Christians, we kneel before your image bearing the scars of the Hussite raiders, blackened by the smoke of nine centuries of candles, crowned by the love of the Polish people. You who defended Jasna Góra in the Swedish Deluge and the Polish people through the long centuries of partition and occupation, defend us now in our need (mention your intention). Strengthen our faith in moments of darkness, as you strengthened Poland in its darkest hours. Through the prayers of St. John Paul II, your son and Poland's son, intercede for the Universal Church, for Poland and the Polish diaspora, and for the petitioner who prays before you now. We adore your Son Jesus, whom you carry in your arms forever. Through Christ our Lord. Amen.",
    instructions: "Pray once daily for nine consecutive days. The novena is traditionally prayed in the nine days leading up to the Feast of Our Lady of Częstochowa (August 26) or the Feast of Mary, Queen of Poland (May 3). The novena structure: (1) Sign of the Cross; (2) Read a brief reflection on the icon's history or on Polish Catholic identity; (3) Pray the novena prayer text; (4) Pray three Hail Marys; (5) Name the specific intention. Many Polish Catholic families pray the novena before a household reproduction of the icon — the Black Madonna's image is among the most widely-copied Catholic icons in the world, and even small Polish-Catholic homes typically display a reproduction either as a wall icon or on a small home altar. The pilgrimage to Jasna Góra remains a powerful element of Polish devotional life: every August, hundreds of thousands of pilgrims walk on foot from Warsaw, Kraków, and other Polish cities to the monastery, arriving on or before the Solemnity of the Assumption (August 15) for the great feast. In the Polish-American diaspora — concentrated in Chicago, New York, and the parishes of New England — Częstochowa Sunday in late August is observed with processions, the singing of 'Czarna Madonno' ('Black Madonna') by Konwalia and other Polish-American Catholic hymns, and Polish-language Mass. The novena is appropriate for: any moment of national or personal crisis (in continuity with Poland's appeal to Mary during the Deluge); the conversion of family members; protection of the unborn (a strong Polish-Catholic intention); spiritual healing in the long arc of generational wounds; and as a sustained prayer for the universal Church.",
    duration: 12,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "Our Lady of Częstochowa, Queen of Poland",
    feastDay: "August 26",
    situationTags: [SituationCategory.ILLNESS, SituationCategory.FAMILY, SituationCategory.GRIEF, SituationCategory.GENERAL, SituationCategory.CONVERSION],
  },
  {
    slug: "novena-maximilian-kolbe",
    name: "Novena to St. Maximilian Kolbe",
    category: PrayerCategory.NOVENA,
    description: "St. Maximilian Maria Kolbe (1894-1941) was a Polish Conventual Franciscan friar, journalist, missionary, and martyr of Auschwitz — one of the most powerful witnesses of the twentieth century. Born Rajmund Kolbe near Łódź in partitioned Poland, he experienced a vision of the Blessed Virgin Mary in childhood: she offered him two crowns, one white (purity) and one red (martyrdom), and asked which he would choose. He chose both. He entered the Conventual Franciscans at sixteen, was ordained a priest in 1918, and founded the Militia Immaculatae ('Knights of the Immaculate') in 1917, a Marian apostolate dedicated to the conversion of sinners and the spreading of devotion to the Immaculate Conception. He established Niepokalanów ('City of the Immaculate') near Warsaw in 1927, which grew into one of the largest religious houses in the world; the friars there published a mass-circulation Catholic monthly, Rycerz Niepokalanej ('Knight of the Immaculate'), that reached a million readers by the late 1930s. In 1930-1936 he served as missionary in Japan, founding Mugenzai no Sono ('Garden of the Immaculate') in Nagasaki — a friary that, against all expectations, survived the 1945 atomic bombing intact. Returning to Poland on the eve of World War II, he sheltered some 2,000 Jewish refugees at Niepokalanów. He was arrested by the Gestapo on February 17, 1941, and transferred to Auschwitz on May 28, 1941 as prisoner number 16670. In July 1941, after a prisoner escaped from Block 14, the camp commander selected ten men to die of starvation in retaliation. One of the chosen, Franciszek Gajowniczek, cried out in anguish for his wife and children. Kolbe stepped forward and asked to take Gajowniczek's place. The exchange was permitted. Kolbe spent two weeks in the starvation bunker leading the other condemned men in prayer and song; he was the last to die, killed by lethal injection on August 14, 1941, the eve of the Assumption. Pope St. John Paul II — himself a Pole who lived through the same Nazi occupation — canonized Kolbe as 'martyr of charity' in 1982, declaring him 'the patron saint of our difficult century.' Franciszek Gajowniczek survived the war and lived until 1995, testifying for fifty-three years to the man who died in his place. St. Maximilian Kolbe is patron of prisoners, journalists, families, the pro-life movement, and those addicted (especially drug-addicted).",
    prayerText: "St. Maximilian Kolbe, you carried the white crown of purity and the red crown of martyrdom both. You loved the Immaculate Conception with your whole heart and gave your life for a stranger in the starvation bunker of Auschwitz, that a husband and father might live. By your intercession, obtain for us the courage to lay down our lives in love for those entrusted to us, in great matters and small. We bring before you the intention of (mention the name and the need). Through Mary Immaculate, whose Knight you were, intercede for us. Through Christ our Lord, who said that no greater love has any man than this, that he lay down his life for his friends. Amen.",
    instructions: "Pray once daily for nine consecutive days. The novena is traditionally prayed in the nine days leading up to the Feast of St. Maximilian Kolbe (August 14) or in connection with the August 15 Solemnity of the Assumption (Kolbe died on the eve of the Assumption, dressing the timing of his death in Marian significance). The novena structure: (1) Sign of the Cross; (2) Read a brief reflection on a moment from Kolbe's life — his vision of the two crowns, his founding of Niepokalanów, his Japanese mission, his Auschwitz sacrifice; (3) Pray the novena prayer text; (4) Three Hail Marys (in honor of his Marian devotion); (5) Name the specific intention. The novena is particularly appropriate for: anyone in prison or detention, refugees and the displaced, those struggling with addiction (Kolbe is patron of those addicted, especially to drugs), journalists and writers in difficult vocations, families under threat, and the pro-life cause (Kolbe's witness — laying down his life so that a father might return to his children — has made him a powerful intercessor for the unborn and for fathers). The Militia Immaculatae continues today as an international Marian apostolate; many lay Catholics formally enroll in the MI as part of their devotion to Kolbe and to the Immaculate Conception. The Auschwitz cell where Kolbe died (Block 11, Cell 18) is preserved as a place of pilgrimage; a stone plaque marks the spot. For Polish Catholics worldwide — and increasingly for Catholics of every nation who learn his story — Kolbe is the answer to the question of whether Christian love can survive the worst evils the twentieth century produced. He survived them by dying in them.",
    duration: 12,
    difficulty: DifficultyLevel.BEGINNER,
    daysRequired: 9,
    patronSaint: "St. Maximilian Maria Kolbe",
    feastDay: "August 14",
    situationTags: [SituationCategory.MENTAL_HEALTH, SituationCategory.FAMILY, SituationCategory.CAREER, SituationCategory.GENERAL, SituationCategory.GRIEF],
  },
];

async function main() {
  console.log("Seeding prayer types...");

  for (const prayer of prayers) {
    await prisma.prayerType.upsert({
      where: { slug: prayer.slug },
      update: prayer,
      create: prayer,
    });
    console.log(`  + ${prayer.name}`);
  }

  console.log(`\nSeeded ${prayers.length} prayers successfully!`);
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
